function run_checks
%RUN_CHECKS Verify P11 coherence, lock scope, bounds, and recovery.

modelFcn = @model;
scenarioFcn = @p11_scenario;
runFixture = @(fixture) modelFcn(fixture.writer_prepare_ms, ...
    fixture.record_words, fixture.reader_release_ms, ...
    fixture.reader_process_ms, fixture.protection, fixture.tick_ms, ...
    fixture.horizon_ms, fixture.wait_timeout_ms, ...
    fixture.timeout_action);
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);

%% Deterministic baseline, bounded blocking, and work conservation
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'Repeated baseline calls must be deterministic and state-isolated.');
expectedOwner = [1 1 1 1 2 2 2 2 0 0 0 0 0 0 0 0];
expectedMutexOwner = [0 0 1 1 2 2 0 0 0 0 0 0 0 0 0 0];
expectedStage = [1 1 2 2 3 3 4 4 0 0 0 0 0 0 0 0];
expectedWriterPriority = [1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1];
assert(isequal(clean.timeline.cpu_owner_task_id, expectedOwner), ...
    'Baseline CPU ownership must retain the exact dispatch sequence.');
assert(isequal(clean.timeline.mutex_owner_task_id, ...
    expectedMutexOwner), ...
    'Baseline mutex ownership must cover only commit and copy.');
assert(isequal(clean.timeline.stage_code, expectedStage), ...
    'Baseline prepare, commit, copy, and process stages changed.');
assert(isequal(clean.timeline.writer_effective_priority, ...
    expectedWriterPriority), ...
    'The writer must inherit priority 2 only while the reader waits.');
assert(isequal(find(clean.timeline.reader_blocked), 4), ...
    'The reader must be blocked only in the interval starting at 3 ms.');
assert(clean.timeline.cpu_owner_task_id(4) == 1 && ...
    clean.timeline.mutex_owner_task_id(4) == 1, ...
    'The inherited writer must finish its commit while the reader waits.');
assert(clean.writer.start_ms == 0 && ...
    clean.writer.completion_ms == 4 && ...
    clean.writer.service_ms == 4 && ...
    clean.writer.remaining_ms == 0 && clean.writer.completed, ...
    'Baseline writer service and completion changed.');
assert(clean.writer.mutex_request_ms == 2 && ...
    clean.writer.mutex_acquire_ms == 2 && ...
    clean.writer.mutex_release_ms == 4 && ...
    clean.writer.peak_effective_priority == 2, ...
    'Baseline writer lock boundaries or inherited priority changed.');
assert(clean.reader.start_ms == 4 && ...
    clean.reader.completion_ms == 8 && ...
    clean.reader.response_ms == 5 && ...
    clean.reader.service_ms == 4 && ...
    clean.reader.remaining_ms == 0 && clean.reader.completed, ...
    'Baseline reader service, completion, or response changed.');
assert(clean.reader.mutex_request_ms == 3 && ...
    clean.reader.mutex_acquire_ms == 4 && ...
    clean.reader.mutex_release_ms == 6 && ...
    clean.reader.block_start_ms == 3 && ...
    clean.reader.blocked_time_ms == 1, ...
    'Baseline reader request, handoff, or bounded wait changed.');
assert(clean.reader.commit_blocking_ms == 1 && ...
    clean.reader.scope_excess_blocking_ms == 0 && ...
    clean.metrics.reader_blocked_ms == 1 && ...
    clean.metrics.commit_blocking_ms == 1 && ...
    clean.metrics.scope_excess_blocking_ms == 0, ...
    'Commit blocking plus scope excess must equal the complete reader wait.');
assert(clean.reader.snapshot_complete && ...
    clean.reader.snapshot_consistent && ...
    ~clean.reader.torn_read_detected && ...
    ~clean.reader.stale_but_consistent && ...
    clean.reader.observed_version == 1, ...
    'The protected baseline must return complete generation one.');
assert(isequal(clean.reader.observed_values, [101 102]) && ...
    isequal(clean.reader.observed_version_by_word, [1 1]) && ...
    isequal(clean.record.initial_values, [1 2]) && ...
    isequal(clean.record.target_values, [101 102]) && ...
    isequal(clean.record.final_values, [101 102]), ...
    'Baseline record values or snapshot contents changed.');
assert(clean.record.published_version == 1 && ...
    clean.record.consistent_at_horizon && ...
    clean.metrics.torn_read_count == 0 && ...
    clean.metrics.consistent_snapshot_count == 1, ...
    'Published and observed generations must remain coherent.');
assert(clean.metrics.busy_time_ms == 8 && ...
    clean.metrics.idle_time_ms == 8 && ...
    clean.metrics.busy_time_ms + clean.metrics.idle_time_ms == 16, ...
    'Busy and idle time must conserve the baseline horizon.');
assert(abs(clean.metrics.busy_fraction - 0.5) < 1e-14 && ...
    abs(clean.metrics.idle_fraction - 0.5) < 1e-14, ...
    'Baseline busy and idle fractions changed.');
assert(clean.metrics.released_demand_ms == 8 && ...
    clean.metrics.served_work_ms == 8 && ...
    clean.metrics.cancelled_work_ms == 0 && ...
    clean.metrics.remaining_work_ms == 0 && ...
    clean.metrics.work_conservation_error_ms == 0, ...
    'Baseline work must be fully served and conserved.');
assert(numel(clean.timeline.cpu_owner_task_id) == ...
    numel(clean.timeline.time_ms) && ...
    numel(clean.timeline.writer_committed_word_count) == ...
    numel(clean.timeline.time_edges_ms) && ...
    numel(clean.timeline.reader_copied_word_count) == ...
    numel(clean.timeline.time_edges_ms) && ...
    numel(clean.timeline.live_record_min_version) == ...
    numel(clean.timeline.time_edges_ms) && ...
    numel(clean.timeline.live_record_max_version) == ...
    numel(clean.timeline.time_edges_ms), ...
    'Interval traces and boundary-state traces must use their declared axes.');
assert(isequal(clean.timeline.writer_committed_word_count(1:5), ...
    [0 0 0 1 2]) && ...
    isequal(clean.timeline.reader_copied_word_count(1:7), ...
    [0 0 0 0 0 1 2]), ...
    ['Commit and copy counts must change at service-completion boundaries, ' ...
    'not at dispatch starts.']);
baselineMixed = clean.timeline.live_record_min_version ~= ...
    clean.timeline.live_record_max_version;
assert(isequal(clean.timeline.time_edges_ms(baselineMixed), 3), ...
    ['Mutual exclusion keeps the protected reader from executing while ' ...
    'the live record is mixed over [3,4) ms after completion at 3 ms.']);

%% Independent baseline equations and coarse-scope occupancy
committedBeforeReader = ...
    (fixture.reader_release_ms - fixture.writer_prepare_ms) ./ ...
    fixture.tick_ms;
remainingCommitMs = (fixture.record_words - committedBeforeReader) .* ...
    fixture.tick_ms;
readerCopyMs = fixture.record_words .* fixture.tick_ms;
independentResponseMs = remainingCommitMs + readerCopyMs + ...
    fixture.reader_process_ms;
assert(committedBeforeReader == 1 && remainingCommitMs == 1, ...
    'Independent request-boundary commit arithmetic changed.');
assert(remainingCommitMs == clean.reader.blocked_time_ms && ...
    independentResponseMs == clean.reader.response_ms && ...
    independentResponseMs == 5, ...
    'W = t_acquire - t_request and R = W + copy + process changed.');

coarseBaseline = runFixture(scenarioFcn('coarse-lock'));
expectedCoarseMutex = [1 1 1 1 2 2 2 2 0 0 0 0 0 0 0 0];
assert(isequal(coarseBaseline.timeline.cpu_owner_task_id, expectedOwner) && ...
    isequal(coarseBaseline.timeline.mutex_owner_task_id, ...
    expectedCoarseMutex), ...
    'Coarse baseline must retain CPU service while extending lock occupancy.');
assert(coarseBaseline.reader.blocked_time_ms == 1 && ...
    coarseBaseline.reader.response_ms == 5 && ...
    coarseBaseline.reader.snapshot_consistent && ...
    coarseBaseline.reader.observed_version == 1, ...
    'Baseline phasing must give both protected scopes the same coherent result.');
assert((clean.writer.mutex_release_ms - ...
    clean.writer.mutex_acquire_ms) == 2 && ...
    (coarseBaseline.writer.mutex_release_ms - ...
    coarseBaseline.writer.mutex_acquire_ms) == 4 && ...
    (clean.reader.mutex_release_ms - ...
    clean.reader.mutex_acquire_ms) == 2 && ...
    (coarseBaseline.reader.mutex_release_ms - ...
    coarseBaseline.reader.mutex_acquire_ms) == 4, ...
    'Coarse scope must hold the mutex across preparation and processing.');

%% Sweep 1 - isolate private preparation from protected work
prepareSweepMs = [2 3 4 5];
shortWaitMs = zeros(size(prepareSweepMs));
shortResponseMs = zeros(size(prepareSweepMs));
shortVersion = zeros(size(prepareSweepMs));
coarseWaitMs = zeros(size(prepareSweepMs));
coarseResponseMs = zeros(size(prepareSweepMs));
coarseCommitMs = zeros(size(prepareSweepMs));
coarseExcessMs = zeros(size(prepareSweepMs));
for sweepIndex = 1:numel(prepareSweepMs)
    shortInput = scenarioFcn('baseline', prepareSweepMs(sweepIndex), ...
        2, 1, 2, 16);
    coarseInput = scenarioFcn('coarse-lock', ...
        prepareSweepMs(sweepIndex), 2, 1, 2, 16);
    shortOut = runFixture(shortInput);
    coarseOut = runFixture(coarseInput);
    shortWaitMs(sweepIndex) = shortOut.reader.blocked_time_ms;
    shortResponseMs(sweepIndex) = shortOut.reader.response_ms;
    shortVersion(sweepIndex) = shortOut.reader.observed_version;
    coarseWaitMs(sweepIndex) = coarseOut.reader.blocked_time_ms;
    coarseResponseMs(sweepIndex) = coarseOut.reader.response_ms;
    coarseCommitMs(sweepIndex) = ...
        coarseOut.reader.commit_blocking_ms;
    coarseExcessMs(sweepIndex) = ...
        coarseOut.reader.scope_excess_blocking_ms;
    assert(isequal(shortOut.input, coarseOut.input), ...
        'Preparation-sweep scope comparisons must retain numeric inputs.');
    assert(shortOut.reader.snapshot_consistent && ...
        coarseOut.reader.snapshot_consistent && ...
        shortOut.reader.observed_version == 0 && ...
        coarseOut.reader.observed_version == 1, ...
        ['The short result is stale but coherent; both scopes preserve ' ...
        'coherence, while freshness and ordering remain separate.']);
    assert(shortOut.reader.scope_excess_blocking_ms == 0 && ...
        shortOut.metrics.work_conservation_error_ms == 0 && ...
        coarseOut.metrics.work_conservation_error_ms == 0, ...
        'Each preparation-sweep call must isolate scope and conserve work.');
end
assert(isequal(shortWaitMs, [0 0 0 0]) && ...
    isequal(shortResponseMs, [4 4 4 4]) && ...
    isequal(shortVersion, [0 0 0 0]), ...
    'Private preparation must not lengthen short-mutex reader response.');
assert(isequal(coarseWaitMs, [3 4 5 6]) && ...
    isequal(coarseResponseMs, [7 8 9 10]), ...
    'Coarse preparation must extend wait and response one-for-one.');
assert(isequal(coarseCommitMs, [2 2 2 2]) && ...
    isequal(coarseExcessMs, [1 2 3 4]) && ...
    isequal(coarseWaitMs, coarseCommitMs + coarseExcessMs), ...
    'Coarse wait must separate necessary commit from excess preparation.');

%% Sweep 2 - isolate the protected record width
wordSweep = [2 3 4 5];
wordWaitMs = zeros(size(wordSweep));
wordResponseMs = zeros(size(wordSweep));
wordCompletionMs = zeros(size(wordSweep));
wordDemandMs = zeros(size(wordSweep));
for sweepIndex = 1:numel(wordSweep)
    sweptInput = scenarioFcn('baseline', 2, ...
        wordSweep(sweepIndex), 3, 2, 16);
    swept = runFixture(sweptInput);
    wordWaitMs(sweepIndex) = swept.reader.blocked_time_ms;
    wordResponseMs(sweepIndex) = swept.reader.response_ms;
    wordCompletionMs(sweepIndex) = swept.reader.completion_ms;
    wordDemandMs(sweepIndex) = swept.metrics.released_demand_ms;
    assert(swept.input.writer_prepare_ms == 2 && ...
        swept.input.reader_release_ms == 3 && ...
        swept.input.reader_process_ms == 2 && ...
        swept.input.tick_ms == 1 && ...
        swept.input.horizon_ms == 16 && ...
        strcmp(swept.policy.protection, 'short-mutex'), ...
        'Record-width sweep must isolate its one protected-work input.');
    assert(swept.reader.blocked_time_ms == ...
        swept.reader.commit_blocking_ms && ...
        swept.reader.scope_excess_blocking_ms == 0 && ...
        swept.reader.snapshot_consistent && ...
        swept.reader.observed_version == 1, ...
        'Record-width sweep must retain only necessary coherent blocking.');
    assert(swept.metrics.served_work_ms == ...
        swept.metrics.released_demand_ms && ...
        swept.metrics.work_conservation_error_ms == 0, ...
        'Every completed record-width fixture must conserve its own demand.');
end
assert(isequal(wordWaitMs, [1 2 3 4]) && ...
    isequal(wordResponseMs, [5 7 9 11]) && ...
    isequal(wordCompletionMs, [8 10 12 14]), ...
    'Record-width wait, response, and completion references changed.');
assert(isequal(wordDemandMs, [8 10 12 14]), ...
    'Each added word must add one writer and one reader service tick.');
assert(isequal(wordResponseMs, ...
    wordWaitMs + wordSweep + fixture.reader_process_ms), ...
    'Reader response must equal wait plus word copies plus private process.');

%% Deliberately torn case, rollback, and clean recovery
brokenInput = scenarioFcn('unprotected-torn');
broken = runFixture(brokenInput);
expectedBrokenOwner = [1 1 1 2 2 2 2 1 0 0 0 0 0 0 0 0];
assert(isequal(broken.timeline.cpu_owner_task_id, ...
    expectedBrokenOwner), ...
    'Unprotected broken-case dispatch sequence changed.');
assert(all(broken.timeline.mutex_owner_task_id == 0) && ...
    ~any(broken.timeline.reader_blocked) && ...
    broken.reader.blocked_time_ms == 0 && ...
    broken.reader.response_ms == 4, ...
    'The unprotected reader must avoid waiting without inventing a mutex.');
assert(isequal(broken.reader.observed_values, [101 2]) && ...
    isequal(broken.reader.observed_version_by_word, [1 0]) && ...
    broken.reader.snapshot_complete && ...
    ~broken.reader.snapshot_consistent && ...
    broken.reader.torn_read_detected, ...
    'The broken case must retain one deterministic mixed-generation read.');
assert(isnan(broken.reader.observed_version) && ...
    ~broken.reader.stale_but_consistent && ...
    broken.metrics.torn_read_count == 1 && ...
    broken.metrics.consistent_snapshot_count == 0, ...
    'A torn snapshot must not be mislabeled as one stale generation.');
brokenMixed = broken.timeline.live_record_min_version ~= ...
    broken.timeline.live_record_max_version;
assert(isequal(broken.timeline.time_edges_ms(brokenMixed), 3:7), ...
    ['The unprotected mixed record must be visible from the first commit ' ...
    'completion at 3 ms until writer recovery at 8 ms.']);
assert(broken.reader.completion_ms == 7 && ...
    broken.writer.completion_ms == 8 && ...
    broken.record.published_version == 1 && ...
    broken.record.consistent_at_horizon && ...
    isequal(broken.record.final_values, clean.record.final_values), ...
    'The torn observation must stay distinct from the final complete record.');
assert(isequal(broken.input, clean.input) && ...
    broken.metrics.released_demand_ms == ...
    clean.metrics.released_demand_ms && ...
    broken.metrics.served_work_ms == clean.metrics.served_work_ms && ...
    broken.metrics.work_conservation_error_ms == 0, ...
    'Broken protection must retain workload and numeric inputs.');
rolledBack = runFixture(fixture);
assert(isequaln(rolledBack, clean), ...
    'Restoring short locking must roll back exactly to the baseline.');
recoveredAfterTear = runFixture(scenarioFcn('baseline'));
assert(isequaln(recoveredAfterTear, clean), ...
    'A clean call after a torn case must recover without hidden state.');

%% Timeout boundary, continued wait, reader cancellation, and recovery
exactInput = fixture;
exactInput.wait_timeout_ms = 1;
exactInput.timeout_action = 'cancel-reader';
exactHandoff = runFixture(exactInput);
assert(~exactHandoff.reader.wait_timed_out && ...
    ~exactHandoff.reader.cancelled_while_waiting && ...
    exactHandoff.reader.mutex_acquire_ms == 4 && ...
    exactHandoff.reader.completion_ms == 8, ...
    'Publish, unlock, and handoff at the timeout boundary must win.');
assert(exactHandoff.reader.blocked_time_ms == 1 && ...
    exactHandoff.reader.snapshot_consistent && ...
    exactHandoff.reader.observed_version == 1 && ...
    exactHandoff.metrics.cancelled_work_ms == 0, ...
    'Exact handoff must preserve the complete reader job and snapshot.');

continueInput = scenarioFcn('timeout-continue');
continued = runFixture(continueInput);
expectedContinueOwner = [1 1 1 1 1 1 2 2 2 2 2 2 0 0 0 0];
expectedContinueMutex = [0 0 1 1 1 1 2 2 2 2 0 0 0 0 0 0];
assert(isequal(continued.timeline.cpu_owner_task_id, ...
    expectedContinueOwner) && ...
    isequal(continued.timeline.mutex_owner_task_id, ...
    expectedContinueMutex), ...
    'Continue-waiting ownership sequence changed.');
assert(continued.reader.wait_timed_out && ...
    continued.reader.wait_timeout_time_ms == 4 && ...
    ~continued.reader.cancelled_while_waiting && ...
    continued.reader.blocked_time_ms == 3 && ...
    continued.reader.commit_blocking_ms == 3 && ...
    continued.reader.scope_excess_blocking_ms == 0, ...
    'Continue-waiting must classify once and retain necessary commit wait.');
assert(continued.writer.completion_ms == 6 && ...
    continued.reader.mutex_acquire_ms == 6 && ...
    continued.reader.completion_ms == 12 && ...
    continued.reader.response_ms == 9 && ...
    continued.reader.snapshot_consistent, ...
    'Continued wait must reach one coherent four-word snapshot.');
assert(continued.metrics.released_demand_ms == 12 && ...
    continued.metrics.served_work_ms == 12 && ...
    continued.metrics.cancelled_work_ms == 0 && ...
    continued.metrics.remaining_work_ms == 0 && ...
    continued.metrics.work_conservation_error_ms == 0, ...
    'Continued waiting must conserve all twelve work ticks.');

cancelInput = scenarioFcn('timeout-cancel');
cancelled = runFixture(cancelInput);
expectedCancelledOwner = [1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0];
expectedCancelledMutex = [0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0];
assert(isequal(cancelled.timeline.cpu_owner_task_id, ...
    expectedCancelledOwner) && ...
    isequal(cancelled.timeline.mutex_owner_task_id, ...
    expectedCancelledMutex), ...
    'Canceled-reader ownership sequence changed.');
assert(cancelled.reader.wait_timed_out && ...
    cancelled.reader.wait_timeout_time_ms == 4 && ...
    cancelled.reader.cancelled_while_waiting && ...
    cancelled.reader.cancellation_time_ms == 4 && ...
    cancelled.reader.cancelled_work_ms == 6, ...
    'Cancel-reader must remove six unserved reader ticks at 4 ms.');
assert(cancelled.reader.service_ms == 0 && ...
    cancelled.reader.remaining_ms == 0 && ...
    isnan(cancelled.reader.completion_ms) && ...
    ~cancelled.reader.snapshot_complete && ...
    ~cancelled.reader.torn_read_detected, ...
    'A canceled blocked reader must not invent service, completion, or data.');
assert(cancelled.reader.blocked_time_ms == 1 && ...
    cancelled.writer.mutex_release_ms == 6 && ...
    cancelled.writer.completion_ms == 6 && ...
    cancelled.writer.completed && ...
    isequal(cancelled.record.final_values, ...
    cancelled.record.target_values), ...
    'Reader cancellation must not unlock, cancel, or roll back the writer.');
assert(cancelled.timeline.mutex_owner_task_id(5) == 1 && ...
    cancelled.timeline.writer_effective_priority(4) == 2 && ...
    all(cancelled.timeline.writer_effective_priority(5:6) == 1), ...
    'Cancellation must withdraw donation without changing mutex ownership.');
assert(cancelled.metrics.released_demand_ms == 12 && ...
    cancelled.metrics.served_work_ms == 6 && ...
    cancelled.metrics.cancelled_work_ms == 6 && ...
    cancelled.metrics.remaining_work_ms == 0 && ...
    cancelled.metrics.work_conservation_error_ms == 0, ...
    'Reader cancellation must conserve served and canceled work.');
recoveredAfterCancellation = runFixture(fixture);
assert(isequaln(recoveredAfterCancellation, clean), ...
    'A clean call after cancellation must recover exact baseline state.');

%% No-contention, early-reader, phasing, and horizon limits
noContention = modelFcn(2, 2, 4, 2, 'short-mutex', 1, 10);
assert(isequal(noContention.timeline.cpu_owner_task_id, ...
    [1 1 1 1 2 2 2 2 0 0]) && ...
    noContention.reader.blocked_time_ms == 0 && ...
    noContention.reader.mutex_request_ms == 4 && ...
    noContention.reader.mutex_acquire_ms == 4, ...
    'Reader release after publication must create no contention.');
assert(noContention.reader.response_ms == 4 && ...
    noContention.reader.snapshot_consistent && ...
    noContention.reader.observed_version == 1 && ...
    noContention.metrics.work_conservation_error_ms == 0, ...
    'No-contention reader must copy the complete new generation.');

early = runFixture(scenarioFcn('early-reader'));
expectedEarlyOwner = [1 2 2 2 2 1 1 1 0 0 0 0 0 0 0 0];
expectedEarlyMutex = [0 2 2 0 0 0 1 1 0 0 0 0 0 0 0 0];
assert(isequal(early.timeline.cpu_owner_task_id, expectedEarlyOwner) && ...
    isequal(early.timeline.mutex_owner_task_id, expectedEarlyMutex), ...
    'Early-reader schedule or ownership changed.');
assert(early.reader.blocked_time_ms == 0 && ...
    early.reader.response_ms == 4 && ...
    early.reader.snapshot_consistent && ...
    early.reader.observed_version == 0 && ...
    early.reader.stale_but_consistent, ...
    'Early short-mutex reader must return coherent generation zero.');
assert(isequal(early.reader.observed_values, [1 2]) && ...
    early.writer.mutex_acquire_ms == 6 && ...
    early.writer.completion_ms == 8 && ...
    early.record.published_version == 1, ...
    'Early read must not prevent the later complete publication.');

unprotectedBeforeCommit = modelFcn(2, 2, 2, 2, ...
    'unprotected', 1, 10);
unprotectedAfterCommit = modelFcn(2, 2, 4, 2, ...
    'unprotected', 1, 10);
assert(unprotectedBeforeCommit.reader.snapshot_consistent && ...
    unprotectedBeforeCommit.reader.observed_version == 0 && ...
    ~unprotectedBeforeCommit.reader.torn_read_detected, ...
    'An early unprotected reader may see complete old data by phasing.');
assert(unprotectedAfterCommit.reader.snapshot_consistent && ...
    unprotectedAfterCommit.reader.observed_version == 1 && ...
    ~unprotectedAfterCommit.reader.torn_read_detected, ...
    'A late unprotected reader may see complete new data by phasing.');
assert(broken.reader.torn_read_detected, ...
    'The broken symptom requires overlap; zero tears elsewhere prove no safety.');

shortInput = scenarioFcn('baseline', 2, 2, 3, 2, 4);
shortHorizon = runFixture(shortInput);
assert(isequal(shortHorizon.timeline.cpu_owner_task_id, [1 1 1 1]) && ...
    isequal(shortHorizon.timeline.mutex_owner_task_id, [0 0 1 1]) && ...
    shortHorizon.writer.completed && ...
    shortHorizon.writer.completion_ms == 4 && ...
    shortHorizon.writer.mutex_release_ms == 4, ...
    'Final-boundary writer completion and unlock changed.');
assert(shortHorizon.reader.released && ...
    ~shortHorizon.reader.completed && ...
    isnan(shortHorizon.reader.mutex_acquire_ms) && ...
    shortHorizon.reader.blocked_time_ms == 1 && ...
    shortHorizon.reader.remaining_ms == 4, ...
    'Short horizon must retain the blocked reader remainder.');
assert(shortHorizon.record.published_version == 1 && ...
    shortHorizon.record.consistent_at_horizon && ...
    shortHorizon.metrics.released_demand_ms == 8 && ...
    shortHorizon.metrics.served_work_ms == 4 && ...
    shortHorizon.metrics.remaining_work_ms == 4 && ...
    shortHorizon.metrics.work_conservation_error_ms == 0, ...
    'Short-horizon publication and work accounting changed.');

releaseAtHorizon = modelFcn(2, 2, 4, 2, ...
    'short-mutex', 1, 4);
assert(~releaseAtHorizon.reader.released && ...
    isnan(releaseAtHorizon.reader.mutex_request_ms) && ...
    releaseAtHorizon.writer.completed && ...
    releaseAtHorizon.metrics.released_demand_ms == 4 && ...
    releaseAtHorizon.metrics.served_work_ms == 4 && ...
    releaseAtHorizon.metrics.remaining_work_ms == 0, ...
    'A reader release exactly at the half-open horizon must be excluded.');

zeroShort = modelFcn(0, 2, 1, 0, 'short-mutex', 1, 8);
zeroCoarse = modelFcn(0, 2, 1, 0, 'coarse-mutex', 1, 8);
assert(isequal(zeroShort.timeline.cpu_owner_task_id, ...
    [1 1 2 2 0 0 0 0]) && ...
    isequal(zeroShort.timeline.mutex_owner_task_id, ...
    [1 1 2 2 0 0 0 0]), ...
    'Zero preparation and processing schedule changed.');
assert(zeroShort.reader.blocked_time_ms == 1 && ...
    zeroShort.reader.response_ms == 3 && ...
    zeroShort.reader.snapshot_consistent && ...
    zeroShort.metrics.released_demand_ms == 4 && ...
    zeroShort.metrics.served_work_ms == 4, ...
    'Zero private work must leave only commit, wait, and copy.');
assert(isequaln(zeroShort.timeline, zeroCoarse.timeline) && ...
    isequaln(zeroShort.writer, zeroCoarse.writer) && ...
    isequaln(zeroShort.reader, zeroCoarse.reader) && ...
    isequaln(zeroShort.metrics, zeroCoarse.metrics), ...
    'Short and coarse scopes must coincide when private work is zero.');

%% Numeric compatibility and callback lifetime after path cleanup
integerCompatible = modelFcn(uint16(fixture.writer_prepare_ms), ...
    uint8(fixture.record_words), uint16(fixture.reader_release_ms), ...
    uint16(fixture.reader_process_ms), string(fixture.protection), ...
    uint8(fixture.tick_ms), uint16(fixture.horizon_ms), ...
    fixture.wait_timeout_ms, string(fixture.timeout_action));
assert(isequaln(integerCompatible, clean), ...
    'Integer-class scalars and scalar strings must normalize compatibly.');
stringScenario = scenarioFcn(string('baseline'), uint16(2), ...
    uint8(2), uint16(3), uint16(2), uint16(16));
assert(isequaln(stringScenario, fixture), ...
    'Scenario scalar strings and integer-class controls must be compatible.');
omittedDefaults = modelFcn(2, 2, 3, 2, ...
    'short-mutex', 1, 16);
emptyDefaults = modelFcn(2, 2, 3, 2, [], 1, 16, [], []);
assert(isequaln(omittedDefaults, clean) && ...
    isequaln(emptyDefaults, clean), ...
    'Omitted and empty protection/timeout defaults must match baseline.');

callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.writer_prepare_ms, ...
    callbackInput.record_words, callbackInput.reader_release_ms, ...
    callbackInput.reader_process_ms, callbackInput.protection, ...
    callbackInput.tick_ms, callbackInput.horizon_ms, ...
    callbackInput.wait_timeout_ms, callbackInput.timeout_action);
assert(isequal(callbackOut.timeline.cpu_owner_task_id, expectedOwner), ...
    ['Callback-bound P11 dependencies must survive module path cleanup ' ...
    'and a conflicting P01 model path.']);
clear searchPathCleanup;

%% Malformed input, accepted limits, and resource-bound rejection
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1), ...
    'P11:model:Arity');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, ...
    Inf, 'continue-waiting', 0), 'P11:model:Arity');
assertReject(@() modelFcn('2', 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:WriterPrepare');
assertReject(@() modelFcn(true, 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:WriterPrepare');
assertReject(@() modelFcn(NaN, 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:WriterPrepare');
assertReject(@() modelFcn(1i, 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:WriterPrepare');
assertReject(@() modelFcn(-1, 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:WriterPrepare');
assertReject(@() modelFcn([1 2], 2, 3, 2, ...
    'short-mutex', 1, 16), 'P11:model:WriterPrepare');
assertReject(@() modelFcn(2, 1, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:RecordWords');
assertReject(@() modelFcn(2, 2.5, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:RecordWords');
assertReject(@() modelFcn(2, 65, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:RecordResourceBound');
assertReject(@() modelFcn(2, 2, -1, 2, 'short-mutex', 1, 16), ...
    'P11:model:ReaderRelease');
assertReject(@() modelFcn(2, 2, 3, -1, 'short-mutex', 1, 16), ...
    'P11:model:ReaderProcess');
assertReject(@() modelFcn(2, 2, 3, 2, {'short-mutex'}, 1, 16), ...
    'P11:model:Protection');
assertReject(@() modelFcn(2, 2, 3, 2, 'seqlock', 1, 16), ...
    'P11:model:Protection');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 0, 16), ...
    'P11:model:Tick');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 0), ...
    'P11:model:Horizon');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, 0), ...
    'P11:model:WaitTimeout');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, NaN), ...
    'P11:model:WaitTimeout');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, -Inf), ...
    'P11:model:WaitTimeout');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, ...
    [1 2]), 'P11:model:WaitTimeout');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, ...
    Inf, {'continue-waiting'}), 'P11:model:TimeoutAction');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, ...
    Inf, 'delete-owner'), 'P11:model:TimeoutAction');
assertReject(@() modelFcn(0.5, 2, 3, 2, 'short-mutex', 1, 16), ...
    'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3.5, 2, 'short-mutex', 1, 16), ...
    'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2.5, 'short-mutex', 1, 16), ...
    'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16.5), ...
    'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2, 'short-mutex', 1, 16, 0.5), ...
    'P11:model:GridAlignment');
assertReject(@() modelFcn(eps(1), 2, 3, 2, ...
    'short-mutex', 1, 16), 'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, eps(1), 2, ...
    'short-mutex', 1, 16), 'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, eps(1), ...
    'short-mutex', 1, 16), 'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2, ...
    'short-mutex', 1, eps(1)), 'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2, ...
    'short-mutex', 1, 16, eps(1)), 'P11:model:GridAlignment');
assertReject(@() modelFcn(2, 2, 3, 2, ...
    'short-mutex', 1, 100001), 'P11:model:TimingResourceBound');
assertReject(@() modelFcn(1e9 + 1, 2, 3, 2, ...
    'short-mutex', 1, 16), 'P11:model:TimingResourceBound');
assertReject(@() modelFcn(2, 2, 1e9 + 1, 2, ...
    'short-mutex', 1, 16), 'P11:model:TimingResourceBound');
assertReject(@() modelFcn(2, 2, 3, 1e9 + 1, ...
    'short-mutex', 1, 16), 'P11:model:TimingResourceBound');
assertReject(@() modelFcn(2, 2, 3, 2, ...
    'short-mutex', 1, 16, 1e9 + 1), ...
    'P11:model:TimingResourceBound');

largestAccepted = runFixture(scenarioFcn('baseline', ...
    2, 64, 3, 2, 100000));
assert(numel(largestAccepted.record.target_values) == 64 && ...
    numel(largestAccepted.timeline.time_ms) == 100000 && ...
    largestAccepted.writer.committed_words == 64 && ...
    largestAccepted.reader.snapshot_consistent, ...
    ['The accepted horizon resource bound and accepted record resource ' ...
    'bound must execute coherently.']);
assert(largestAccepted.metrics.released_demand_ms == 132 && ...
    largestAccepted.metrics.served_work_ms == 132 && ...
    largestAccepted.metrics.idle_time_ms == 99868 && ...
    largestAccepted.metrics.work_conservation_error_ms == 0, ...
    'Largest accepted fixture must remain bounded and conserve work.');

largestFiniteTime = modelFcn(1e9, 2, 1e9, 0, ...
    'short-mutex', 1, 1, 1e9, 'continue-waiting');
assert(~largestFiniteTime.reader.released && ...
    largestFiniteTime.writer.service_ms == 1 && ...
    largestFiniteTime.writer.remaining_ms == 1e9 + 1 && ...
    largestFiniteTime.input.wait_timeout_ms == 1e9, ...
    'Accepted finite-time bounds may remain outside a short horizon.');

largestScenarioTimes = scenarioFcn('baseline', ...
    1000, 64, 1000, 1000, 100000);
assert(largestScenarioTimes.writer_prepare_ms == 1000 && ...
    largestScenarioTimes.record_words == 64 && ...
    largestScenarioTimes.reader_release_ms == 1000 && ...
    largestScenarioTimes.reader_process_ms == 1000 && ...
    largestScenarioTimes.horizon_ms == 100000, ...
    'Scenario controls must accept every declared upper bound.');
assertReject(@() scenarioFcn({'baseline'}), 'P11:scenario:Kind');
assertReject(@() scenarioFcn('unknown'), 'P11:scenario:Kind');
assertReject(@() scenarioFcn('baseline', -1), ...
    'P11:scenario:WriterPrepare');
assertReject(@() scenarioFcn('baseline', 1001), ...
    'P11:scenario:WriterPrepare');
assertReject(@() scenarioFcn('baseline', 2, 1), ...
    'P11:scenario:RecordWords');
assertReject(@() scenarioFcn('baseline', 2, 65), ...
    'P11:scenario:RecordWords');
assertReject(@() scenarioFcn('baseline', 2, 2, -1), ...
    'P11:scenario:ReaderRelease');
assertReject(@() scenarioFcn('baseline', 2, 2, 1001), ...
    'P11:scenario:ReaderRelease');
assertReject(@() scenarioFcn('baseline', 2, 2, 3, -1), ...
    'P11:scenario:ReaderProcess');
assertReject(@() scenarioFcn('baseline', 2, 2, 3, 1001), ...
    'P11:scenario:ReaderProcess');
assertReject(@() scenarioFcn('baseline', 2, 2, 3, 2, 0), ...
    'P11:scenario:Horizon');
assertReject(@() scenarioFcn('baseline', 2, 2, 3, 2, 100001), ...
    'P11:scenario:Horizon');

afterRejection = runFixture(fixture);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('Cancel-reader is synchronous modeled work removal, not an asynchronous RTOS cancellation API, owner unlock, or data rollback.');
disp(['Generation tags are diagnostics, not a seqlock or a substitute ' ...
    'for cache and memory-ordering analysis.']);
disp('P11 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
