function out = model(sourceSamples, samplePeriodUs, bytesPerSample, ...
    busRateBytesPerUs, arbitrationUs, blockSamples, dmaSetupCpuUs, ...
    completionIsrCpuUs, processorCopyCpuUsPerSample, ...
    descriptorTimeoutUs, timeoutAction, destinationMode)
%MODEL Move a finite sample vector through a transparent serial DMA model.
%   Sample request i arrives at a_i=(i-1)*T_s. One DMA engine serves one
%   beat at a time with q=A+b/r microseconds per beat:
%       s_i = max(a_i, f_(i-1))
%       f_i = s_i + q.
%   Every complete block produces one completion interrupt. A final partial
%   block is also a completion block. The model has an unbounded source
%   request queue for this finite fixture; backlog is visible but is not
%   mislabeled as ring-buffer loss.
%
%   The timeout observes full-descriptor completion. Equality passes.
%   continue-waiting records a timeout and retains all writes. abort-transfer
%   commits only beats completed by the timeout boundary. It does not roll
%   back a partial peripheral transaction or repair external state.

if nargin ~= 12
    error('P13:model:Arity', [ ...
        'Expected sourceSamples, samplePeriodUs, bytesPerSample, ' ...
        'busRateBytesPerUs, arbitrationUs, blockSamples, ' ...
        'dmaSetupCpuUs, completionIsrCpuUs, ' ...
        'processorCopyCpuUsPerSample, descriptorTimeoutUs, ' ...
        'timeoutAction, and destinationMode.']);
end

maxSamples = 10000;
maxBlockSamples = 1e6;
maxTimelineUs = 1e12;

sourceSamples = validateFiniteVector(sourceSamples, ...
    'P13:model:SourceSamples', 'sourceSamples', maxSamples);
sampleCount = numel(sourceSamples);
samplePeriodUs = validateFiniteScalar(samplePeriodUs, ...
    'P13:model:SamplePeriod', 'samplePeriodUs');
bytesPerSample = validateFiniteScalar(bytesPerSample, ...
    'P13:model:BytesPerSample', 'bytesPerSample');
busRateBytesPerUs = validateFiniteScalar(busRateBytesPerUs, ...
    'P13:model:BusRate', 'busRateBytesPerUs');
arbitrationUs = validateFiniteScalar(arbitrationUs, ...
    'P13:model:Arbitration', 'arbitrationUs');
blockSamples = validateFiniteScalar(blockSamples, ...
    'P13:model:BlockSamples', 'blockSamples');
dmaSetupCpuUs = validateFiniteScalar(dmaSetupCpuUs, ...
    'P13:model:DmaSetupCpu', 'dmaSetupCpuUs');
completionIsrCpuUs = validateFiniteScalar(completionIsrCpuUs, ...
    'P13:model:CompletionIsrCpu', 'completionIsrCpuUs');
processorCopyCpuUsPerSample = validateFiniteScalar( ...
    processorCopyCpuUsPerSample, 'P13:model:ProcessorCopyCpu', ...
    'processorCopyCpuUsPerSample');

if samplePeriodUs <= 0
    error('P13:model:SamplePeriod', ...
        'samplePeriodUs must be strictly positive.');
end
if bytesPerSample < 1 || bytesPerSample > 16 || ...
        bytesPerSample ~= floor(bytesPerSample)
    error('P13:model:BytesPerSample', ...
        'bytesPerSample must be an integer from 1 through 16.');
end
if busRateBytesPerUs <= 0
    error('P13:model:BusRate', ...
        'busRateBytesPerUs must be strictly positive.');
end
if arbitrationUs < 0
    error('P13:model:Arbitration', ...
        'arbitrationUs must be nonnegative.');
end
if blockSamples < 1 || blockSamples ~= floor(blockSamples)
    error('P13:model:BlockSamples', ...
        'blockSamples must be a positive integer.');
end
if blockSamples > maxBlockSamples
    error('P13:model:BlockResourceBound', ...
        'At most 1,000,000 samples may be requested per completion block.');
end
if dmaSetupCpuUs < 0
    error('P13:model:DmaSetupCpu', ...
        'dmaSetupCpuUs must be nonnegative.');
end
if completionIsrCpuUs < 0
    error('P13:model:CompletionIsrCpu', ...
        'completionIsrCpuUs must be nonnegative.');
end
if processorCopyCpuUsPerSample < 0
    error('P13:model:ProcessorCopyCpu', ...
        'processorCopyCpuUsPerSample must be nonnegative.');
end

descriptorTimeoutUs = validateTimeout(descriptorTimeoutUs);
if isempty(timeoutAction)
    timeoutAction = 'continue-waiting';
else
    timeoutAction = normalizeText(timeoutAction, ...
        'P13:model:TimeoutAction', 'timeoutAction');
end
if ~any(strcmp(timeoutAction, ...
        {'continue-waiting', 'abort-transfer'}))
    error('P13:model:TimeoutAction', ...
        ['timeoutAction must be continue-waiting or ' ...
        'abort-transfer.']);
end
if isempty(destinationMode)
    destinationMode = 'increment';
else
    destinationMode = normalizeText(destinationMode, ...
        'P13:model:DestinationMode', 'destinationMode');
end
if ~any(strcmp(destinationMode, {'increment', 'fixed'}))
    error('P13:model:DestinationMode', ...
        'destinationMode must be increment or fixed.');
end

payloadServiceUs = bytesPerSample ./ busRateBytesPerUs;
beatServiceUs = arbitrationUs + payloadServiceUs;
if ~isfinite(payloadServiceUs) || ~isfinite(beatServiceUs) || ...
        beatServiceUs > maxTimelineUs
    error('P13:model:TimingResourceBound', ...
        'A DMA beat exceeds the finite 1e12-us model horizon.');
end
if payloadServiceUs <= 0 || beatServiceUs <= 0 || ...
        (arbitrationUs > 0 && beatServiceUs <= arbitrationUs)
    error('P13:model:TimingPrecision', ...
        'Floating-point precision erased positive payload service time.');
end

lastRequestUs = (sampleCount - 1) .* samplePeriodUs;
if ~isfinite(lastRequestUs) || lastRequestUs > maxTimelineUs
    error('P13:model:TimingResourceBound', ...
        'Sample requests exceed the finite 1e12-us model horizon.');
end
sampleIndex = 1:sampleCount;
requestUs = (sampleIndex - 1) .* samplePeriodUs;
if sampleCount > 1 && any(diff(requestUs) <= 0)
    error('P13:model:TimingPrecision', ...
        'Floating-point precision collapsed distinct sample requests.');
end

startUs = zeros(1, sampleCount);
completionUs = zeros(1, sampleCount);
previousCompletionUs = 0;
for sampleIndexValue = 1:sampleCount
    startUs(sampleIndexValue) = max( ...
        requestUs(sampleIndexValue), previousCompletionUs);
    completionUs(sampleIndexValue) = ...
        startUs(sampleIndexValue) + beatServiceUs;
    if ~isfinite(completionUs(sampleIndexValue)) || ...
            completionUs(sampleIndexValue) > maxTimelineUs
        error('P13:model:TimingResourceBound', ...
            'DMA completion exceeds the finite 1e12-us model horizon.');
    end
    if completionUs(sampleIndexValue) <= startUs(sampleIndexValue)
        error('P13:model:TimingPrecision', ...
            'Floating-point precision erased positive DMA service time.');
    end
    previousCompletionUs = completionUs(sampleIndexValue);
end

queueWaitUs = startUs - requestUs;
requestLatencyUs = completionUs - requestUs;
requestBudgetUs = requestUs + samplePeriodUs;
requestBudgetExceeded = completionUs > requestBudgetUs;
pendingAtArrival = zeros(1, sampleCount);
completedByArrival = zeros(1, sampleCount);
completedBeforeArrival = 0;
for sampleIndexValue = 1:sampleCount
    while completedBeforeArrival < sampleIndexValue - 1 && ...
            completionUs(completedBeforeArrival + 1) <= ...
            requestUs(sampleIndexValue)
        completedBeforeArrival = completedBeforeArrival + 1;
    end
    pendingAtArrival(sampleIndexValue) = ...
        sampleIndexValue - completedBeforeArrival;
    completedByArrival(sampleIndexValue) = completedBeforeArrival;
end

blockCount = ceil(sampleCount ./ blockSamples);
blockId = 1:blockCount;
blockEndSampleIndex = min(blockId .* blockSamples, sampleCount);
blockStartSampleIndex = [1 blockEndSampleIndex(1:end - 1) + 1];
blockSampleCount = blockEndSampleIndex - blockStartSampleIndex + 1;
blockCompletionUs = completionUs(blockEndSampleIndex);
blockIdPerSample = zeros(1, sampleCount);
blockReadyLatencyUs = zeros(1, sampleCount);
for blockIndex = 1:blockCount
    memberIndices = blockStartSampleIndex(blockIndex): ...
        blockEndSampleIndex(blockIndex);
    blockIdPerSample(memberIndices) = blockIndex;
    blockReadyLatencyUs(memberIndices) = ...
        blockCompletionUs(blockIndex) - requestUs(memberIndices);
end

descriptorCompletionUs = completionUs(end);
waitTimedOut = isfinite(descriptorTimeoutUs) && ...
    descriptorCompletionUs > descriptorTimeoutUs;
abortIssued = waitTimedOut && strcmp(timeoutAction, 'abort-transfer');
if abortIssued
    committed = completionUs <= descriptorTimeoutUs;
else
    committed = true(1, sampleCount);
end
committedCount = sum(committed);
cancelled = ~committed;
cancelledCount = sum(cancelled);
descriptorComplete = committedCount == sampleCount;
if descriptorComplete
    observedDescriptorCompletionUs = descriptorCompletionUs;
else
    observedDescriptorCompletionUs = NaN;
end

completedBlock = blockEndSampleIndex <= committedCount;
completedBlockCount = sum(completedBlock);
observedBlockCompletionUs = blockCompletionUs;
observedBlockCompletionUs(~completedBlock) = NaN;
observedBlockReadyLatencyUs = NaN(1, sampleCount);
for blockIndex = 1:blockCount
    if completedBlock(blockIndex)
        memberIndices = blockStartSampleIndex(blockIndex): ...
            blockEndSampleIndex(blockIndex);
        observedBlockReadyLatencyUs(memberIndices) = ...
            blockReadyLatencyUs(memberIndices);
    end
end

if strcmp(destinationMode, 'increment')
    plannedDestinationSlot = sampleIndex;
else
    plannedDestinationSlot = ones(1, sampleCount);
end
committedDestinationSlot = NaN(1, sampleCount);
committedDestinationSlot(committed) = ...
    plannedDestinationSlot(committed);
destinationSamples = NaN(1, sampleCount);
overwrittenBeat = false(1, sampleCount);
overwriteCount = 0;
for sampleIndexValue = 1:sampleCount
    if committed(sampleIndexValue)
        destinationIndex = plannedDestinationSlot(sampleIndexValue);
        if ~isnan(destinationSamples(destinationIndex))
            overwrittenBeat(sampleIndexValue) = true;
            overwriteCount = overwriteCount + 1;
        end
        destinationSamples(destinationIndex) = ...
            sourceSamples(sampleIndexValue);
    end
end
writtenSlot = ~isnan(destinationSamples);
writtenSlotCount = sum(writtenSlot);
unwrittenSlotCount = sampleCount - writtenSlotCount;
dataIntegrity = descriptorComplete && ...
    isequal(destinationSamples, sourceSamples);

referenceBlockCountBySample = zeros(1, sampleCount);
completedBlockCursor = 0;
for sampleIndexValue = 1:sampleCount
    if completedBlockCursor < blockCount && ...
            blockEndSampleIndex(completedBlockCursor + 1) == ...
            sampleIndexValue
        completedBlockCursor = completedBlockCursor + 1;
    end
    referenceBlockCountBySample(sampleIndexValue) = completedBlockCursor;
end
observedBlockCountBySample = min(referenceBlockCountBySample, ...
    completedBlockCount);
processorCopyCumulativeCpuUs = ...
    sampleIndex .* processorCopyCpuUsPerSample;
referenceDmaCumulativeCpuUs = dmaSetupCpuUs + ...
    referenceBlockCountBySample .* completionIsrCpuUs;
observedDmaCumulativeCpuUs = dmaSetupCpuUs + ...
    observedBlockCountBySample .* completionIsrCpuUs;
processorCopyCpuDemandUs = ...
    sampleCount .* processorCopyCpuUsPerSample;
committedProcessorCopyCpuDemandUs = ...
    committedCount .* processorCopyCpuUsPerSample;
referenceDmaCpuDemandUs = dmaSetupCpuUs + ...
    blockCount .* completionIsrCpuUs;
observedDmaCpuDemandUs = dmaSetupCpuUs + ...
    completedBlockCount .* completionIsrCpuUs;
cpuDiagnostics = [processorCopyCumulativeCpuUs ...
    referenceDmaCumulativeCpuUs observedDmaCumulativeCpuUs ...
    processorCopyCpuDemandUs committedProcessorCopyCpuDemandUs ...
    referenceDmaCpuDemandUs ...
    observedDmaCpuDemandUs ...
    processorCopyCpuDemandUs - referenceDmaCpuDemandUs ...
    committedProcessorCopyCpuDemandUs - observedDmaCpuDemandUs];
if any(~isfinite(cpuDiagnostics))
    error('P13:model:CpuResourceBound', ...
        'A derived processor-service demand exceeded finite numeric range.');
end

referenceBusBusyUs = sampleCount .* beatServiceUs;
if abortIssued
    activeBeforeAbortUs = min(completionUs, descriptorTimeoutUs) - ...
        startUs;
    activeBeforeAbortUs = max(activeBeforeAbortUs, 0);
    observedBusActiveUs = sum(activeBeforeAbortUs);
    partialBeatInFlight = any(startUs < descriptorTimeoutUs & ...
        completionUs > descriptorTimeoutUs);
else
    observedBusActiveUs = referenceBusBusyUs;
    partialBeatInFlight = false;
end
completedBusServiceUs = committedCount .* beatServiceUs;
if ~isfinite(referenceBusBusyUs) || ...
        ~isfinite(observedBusActiveUs) || ...
        ~isfinite(completedBusServiceUs)
    error('P13:model:TimingResourceBound', ...
        'A derived bus-service aggregate exceeded finite numeric range.');
end

queueConservationError = sampleIndex - completedByArrival - ...
    pendingAtArrival;
offeredBusLoadPct = 100 .* beatServiceUs ./ samplePeriodUs;
if ~isfinite(offeredBusLoadPct)
    error('P13:model:TimingResourceBound', ...
        'Offered bus load exceeded finite numeric range.');
end

out = struct();
out.input = struct( ...
    'source_samples', sourceSamples, ...
    'sample_count', sampleCount, ...
    'sample_period_us', samplePeriodUs, ...
    'bytes_per_sample', bytesPerSample, ...
    'bus_rate_bytes_per_us', busRateBytesPerUs, ...
    'arbitration_us', arbitrationUs, ...
    'block_samples', blockSamples, ...
    'dma_setup_cpu_us', dmaSetupCpuUs, ...
    'completion_isr_cpu_us', completionIsrCpuUs, ...
    'processor_copy_cpu_us_per_sample', ...
        processorCopyCpuUsPerSample, ...
    'descriptor_timeout_us', descriptorTimeoutUs, ...
    'timeout_action', timeoutAction, ...
    'destination_mode', destinationMode);
out.timeline = struct( ...
    'sample_index', sampleIndex, ...
    'request_us', requestUs, ...
    'start_us', startUs, ...
    'completion_us', completionUs, ...
    'queue_wait_us', queueWaitUs, ...
    'request_latency_us', requestLatencyUs, ...
    'request_budget_us', requestBudgetUs, ...
    'request_budget_exceeded', requestBudgetExceeded, ...
    'pending_at_arrival', pendingAtArrival, ...
    'completed_by_arrival', completedByArrival, ...
    'queue_conservation_error', queueConservationError);
out.block = struct( ...
    'block_id', blockId, ...
    'block_id_per_sample', blockIdPerSample, ...
    'start_sample_index', blockStartSampleIndex, ...
    'end_sample_index', blockEndSampleIndex, ...
    'sample_count', blockSampleCount, ...
    'completion_us', blockCompletionUs, ...
    'ready_latency_us', blockReadyLatencyUs, ...
    'completed', completedBlock, ...
    'observed_completion_us', observedBlockCompletionUs, ...
    'observed_ready_latency_us', observedBlockReadyLatencyUs);
out.cpu = struct( ...
    'processor_copy_cumulative_us', processorCopyCumulativeCpuUs, ...
    'reference_dma_cumulative_us', referenceDmaCumulativeCpuUs, ...
    'observed_dma_cumulative_us', observedDmaCumulativeCpuUs, ...
    'processor_copy_demand_us', processorCopyCpuDemandUs, ...
    'committed_processor_copy_demand_us', ...
        committedProcessorCopyCpuDemandUs, ...
    'reference_dma_demand_us', referenceDmaCpuDemandUs, ...
    'observed_dma_demand_us', observedDmaCpuDemandUs, ...
    'reference_cpu_service_saved_us', ...
        processorCopyCpuDemandUs - referenceDmaCpuDemandUs, ...
    'observed_cpu_service_saved_us', ...
        committedProcessorCopyCpuDemandUs - observedDmaCpuDemandUs);
out.memory = struct( ...
    'source_samples', sourceSamples, ...
    'planned_destination_slot', plannedDestinationSlot, ...
    'committed_destination_slot', committedDestinationSlot, ...
    'destination_samples', destinationSamples, ...
    'committed', committed, ...
    'cancelled', cancelled, ...
    'overwritten_beat', overwrittenBeat, ...
    'written_slot', writtenSlot, ...
    'written_slot_count', writtenSlotCount, ...
    'unwritten_slot_count', unwrittenSlotCount, ...
    'overwrite_count', overwriteCount, ...
    'data_integrity', dataIntegrity);
out.observation = struct( ...
    'wait_timed_out', waitTimedOut, ...
    'abort_issued', abortIssued, ...
    'descriptor_complete', descriptorComplete, ...
    'descriptor_completion_us', observedDescriptorCompletionUs, ...
    'committed_sample_count', committedCount, ...
    'cancelled_sample_count', cancelledCount, ...
    'completed_block_count', completedBlockCount, ...
    'partial_beat_in_flight_at_abort', partialBeatInFlight, ...
    'observed_bus_active_us', observedBusActiveUs, ...
    'completed_bus_service_us', completedBusServiceUs);
out.metrics = struct( ...
    'sample_count', sampleCount, ...
    'requested_bytes', sampleCount .* bytesPerSample, ...
    'committed_bytes', committedCount .* bytesPerSample, ...
    'cancelled_bytes', cancelledCount .* bytesPerSample, ...
    'byte_conservation_error', sampleCount .* bytesPerSample - ...
        committedCount .* bytesPerSample - ...
        cancelledCount .* bytesPerSample, ...
    'beat_service_us', beatServiceUs, ...
    'payload_service_us', payloadServiceUs, ...
    'request_slack_us', samplePeriodUs - beatServiceUs, ...
    'offered_bus_load_pct', offeredBusLoadPct, ...
    'sustainable_without_queue_growth', beatServiceUs <= samplePeriodUs, ...
    'reference_bus_busy_us', referenceBusBusyUs, ...
    'descriptor_completion_us', descriptorCompletionUs, ...
    'max_queue_wait_us', max(queueWaitUs), ...
    'max_request_latency_us', max(requestLatencyUs), ...
    'peak_pending_requests', max(pendingAtArrival), ...
    'request_budget_exceed_count', sum(requestBudgetExceeded), ...
    'block_count', blockCount, ...
    'completion_interrupt_count', blockCount, ...
    'observed_completion_interrupt_count', completedBlockCount, ...
    'mean_block_ready_latency_us', finiteMean(blockReadyLatencyUs), ...
    'max_block_ready_latency_us', max(blockReadyLatencyUs), ...
    'written_slot_count', writtenSlotCount, ...
    'unwritten_slot_count', unwrittenSlotCount, ...
    'overwrite_count', overwriteCount, ...
    'data_integrity', dataIntegrity, ...
    'source_queue_loss_count', 0, ...
    'ring_buffer_overrun_modeled', false, ...
    'queue_conservation_max_error', max(abs(queueConservationError)));
out.claim_boundary = [ ...
    'Finite deterministic DMA-beat arithmetic only; not MATLAB-runtime, ' ...
    'UI, numerical-fidelity, DMA-controller, bus-arbitration, cache or ' ...
    'coherence, processor-timing, hardware, bench, HIL, field, or ' ...
    'production evidence.'];
end

function values = validateFiniteVector(values, identifier, label, maxCount)
validType = isnumeric(values) && ~islogical(values) && isreal(values) && ...
    isvector(values);
if ~validType
    error(identifier, '%s must be a real numeric vector.', label);
end
if isempty(values)
    error(identifier, '%s must be nonempty.', label);
end
if numel(values) > maxCount
    error('P13:model:SampleResourceBound', ...
        'At most 10,000 source samples are allowed.');
end
integerOutsideExactDoubleRange = ...
    (isa(values, 'uint64') && ...
        any(values(:) > uint64(flintmax))) || ...
    (isa(values, 'int64') && ...
        any(values(:) > int64(flintmax) | ...
            values(:) < -int64(flintmax)));
if integerOutsideExactDoubleRange
    error('P13:model:SourcePrecision', ...
        'Integer source samples must stay within +/-flintmax.');
end
values = reshape(double(values), 1, []);
if any(~isfinite(values))
    error(identifier, '%s values must be finite.', label);
end
end

function value = validateFiniteScalar(value, identifier, label)
validValue = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && isfinite(value);
if ~validValue
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function timeoutUs = validateTimeout(timeoutUs)
if isempty(timeoutUs)
    timeoutUs = Inf;
    return;
end
validValue = isnumeric(timeoutUs) && ~islogical(timeoutUs) && ...
    isreal(timeoutUs) && isscalar(timeoutUs) && ...
    (isfinite(timeoutUs) || isinf(timeoutUs));
if ~validValue || isnan(timeoutUs) || timeoutUs <= 0
    error('P13:model:DescriptorTimeout', ...
        'descriptorTimeoutUs must be positive, Inf, or empty.');
end
timeoutUs = double(timeoutUs);
end

function value = normalizeText(value, identifier, label)
validCharacter = ischar(value) && isrow(value);
validString = isstring(value) && isscalar(value) && ~ismissing(value);
if ~validCharacter && ~validString
    error(identifier, '%s must be a character vector or scalar string.', ...
        label);
end
value = char(value);
end

function value = finiteMean(values)
if isempty(values) || any(~isfinite(values))
    error('P13:model:TimingResourceBound', ...
        'Mean input must contain finite values.');
end
scale = max(abs(values));
if scale == 0
    value = 0;
else
    value = scale .* (sum(values ./ scale) ./ numel(values));
end
if ~isfinite(value)
    error('P13:model:TimingResourceBound', ...
        'A derived mean exceeded finite numeric range.');
end
end
