function run_checks
%RUN_CHECKS Verify P13 DMA timing, movement, and failure invariants.

% Bind dependencies before public launchers remove this module path. The
% callback-lifetime regression below exercises these retained handles.
modelFcn = @model;
scenarioFcn = @p13_scenario;
runFixture = @(fixture) modelFcn(fixture.source_samples, ...
    fixture.sample_period_us, fixture.bytes_per_sample, ...
    fixture.bus_rate_bytes_per_us, fixture.arbitration_us, ...
    fixture.block_samples, fixture.dma_setup_cpu_us, ...
    fixture.completion_isr_cpu_us, ...
    fixture.processor_copy_cpu_us_per_sample, ...
    fixture.descriptor_timeout_us, fixture.timeout_action, ...
    fixture.destination_mode);

%% Deterministic baseline and independent recurrence checks
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'The baseline must repeat exactly without persistent state.');
assert(isequal(fixture.source_samples, ...
    mod(37 .* (0:31) + 11, 4096)) && ...
    fixture.source_samples(end) == 1158, ...
    'The deterministic source-code fixture changed.');
assert(clean.metrics.sample_count == 32 && ...
    clean.metrics.requested_bytes == 64 && ...
    clean.metrics.beat_service_us == 11 && ...
    clean.metrics.payload_service_us == 10 && ...
    clean.metrics.request_slack_us == 39 && ...
    clean.metrics.offered_bus_load_pct == 22 && ...
    clean.metrics.sustainable_without_queue_growth, ...
    'Baseline byte, service, slack, or load references changed.');
assert(isequal(clean.timeline.request_us, 0:50:1550) && ...
    isequal(clean.timeline.start_us, 0:50:1550) && ...
    isequal(clean.timeline.completion_us, 11:50:1561), ...
    'Baseline request/start/completion vectors changed.');

previousCompletionUs = [0 clean.timeline.completion_us(1:end - 1)];
independentStartUs = max(clean.timeline.request_us, ...
    previousCompletionUs);
assert(isequal(clean.timeline.start_us, independentStartUs) && ...
    all(clean.timeline.completion_us - ...
    clean.timeline.start_us == 11), ...
    's_i=max(a_i,f_(i-1)) and f_i=s_i+q must close exactly.');
assert(all(clean.timeline.request_us <= clean.timeline.start_us) && ...
    all(clean.timeline.start_us < clean.timeline.completion_us) && ...
    all(clean.timeline.start_us(2:end) >= ...
    clean.timeline.completion_us(1:end - 1)), ...
    'DMA beats must remain causal, positive, and serial.');
assert(all(clean.timeline.queue_wait_us == 0) && ...
    clean.metrics.max_queue_wait_us == 0 && ...
    clean.metrics.max_request_latency_us == 11 && ...
    clean.metrics.peak_pending_requests == 1 && ...
    clean.metrics.request_budget_exceed_count == 0 && ...
    clean.metrics.queue_conservation_max_error == 0, ...
    'Baseline request waiting or queue conservation changed.');
assert(clean.metrics.reference_bus_busy_us == 352 && ...
    clean.metrics.descriptor_completion_us == 1561, ...
    'Total service and descriptor-completion references changed.');

expectedReadyLatencyUs = repmat(361:-50:11, 1, 4);
assert(isequal(clean.block.start_sample_index, [1 9 17 25]) && ...
    isequal(clean.block.end_sample_index, [8 16 24 32]) && ...
    isequal(clean.block.sample_count, [8 8 8 8]) && ...
    isequal(clean.block.completion_us, [361 761 1161 1561]) && ...
    isequal(clean.block.ready_latency_us, expectedReadyLatencyUs), ...
    'Baseline block partition or readiness references changed.');
assert(clean.metrics.block_count == 4 && ...
    clean.metrics.completion_interrupt_count == 4 && ...
    clean.metrics.mean_block_ready_latency_us == 186 && ...
    clean.metrics.max_block_ready_latency_us == 361, ...
    'Baseline completion or ready-latency metrics changed.');
assert(clean.cpu.processor_copy_demand_us == 128 && ...
    clean.cpu.reference_dma_demand_us == 20 && ...
    clean.cpu.reference_cpu_service_saved_us == 108 && ...
    clean.cpu.processor_copy_cumulative_us(end) == 128 && ...
    clean.cpu.reference_dma_cumulative_us(end) == 20, ...
    'Baseline processor-service accounting changed.');
assert(clean.metrics.data_integrity && ...
    isequal(clean.memory.destination_samples, ...
    clean.memory.source_samples) && ...
    all(clean.memory.committed) && ...
    ~any(clean.memory.cancelled) && ...
    clean.metrics.written_slot_count == 32 && ...
    clean.metrics.unwritten_slot_count == 0 && ...
    clean.metrics.overwrite_count == 0 && ...
    clean.metrics.byte_conservation_error == 0, ...
    'Incrementing DMA writes must preserve data and byte conservation.');
assert(clean.metrics.payload_service_us == ...
    clean.input.bytes_per_sample ./ clean.input.bus_rate_bytes_per_us, ...
    'Payload service must equal b/r.');
assert(clean.metrics.beat_service_us == ...
    clean.input.arbitration_us + clean.metrics.payload_service_us, ...
    'Beat equation A+b/r must equal arbitration plus payload service.');
assert(clean.metrics.request_slack_us == ...
    clean.input.sample_period_us - clean.metrics.beat_service_us, ...
    'Request slack must equal T_s-q.');
assert(clean.metrics.offered_bus_load_pct == ...
    100 .* clean.metrics.beat_service_us ./ ...
    clean.input.sample_period_us, ...
    'Offered load must equal 100q/T_s.');
assert(numel(clean.timeline.sample_index) == ...
    clean.metrics.sample_count, ...
    'Every accepted sample must own one timeline identity.');
assert(clean.metrics.requested_bytes == ...
    clean.metrics.sample_count .* clean.input.bytes_per_sample, ...
    'Requested bytes must conserve sample count times sample width.');
assert(isequal(clean.timeline.queue_wait_us, ...
    clean.timeline.start_us - clean.timeline.request_us), ...
    'Queue wait must equal serialized start minus request.');
assert(isequal(clean.timeline.request_latency_us, ...
    clean.timeline.completion_us - clean.timeline.request_us), ...
    'Request latency must equal completion minus request.');
assert(isequal(clean.timeline.request_budget_us, ...
    clean.timeline.request_us + clean.input.sample_period_us), ...
    'Per-request budget boundaries must be explicit.');
assert(isequal(clean.timeline.request_budget_exceeded, ...
    clean.timeline.completion_us > clean.timeline.request_budget_us), ...
    'Strict request-budget excess must preserve equality.');
assert(all(clean.timeline.pending_at_arrival >= 1), ...
    'The arriving sample itself must be pending at its arrival instant.');
assert(all(clean.timeline.queue_conservation_error == 0), ...
    'Arrived, completed, and pending requests must satisfy work conservation.');
assert(sum(clean.block.sample_count) == clean.metrics.sample_count, ...
    'Completion blocks must partition every sample exactly once.');
assert(clean.block.end_sample_index(end) == clean.metrics.sample_count, ...
    'The final block completion must own the descriptor tail.');
assert(isequal(clean.block.completion_us, ...
    clean.timeline.completion_us(clean.block.end_sample_index)), ...
    'Block completion must reference its final serialized beat.');
assert(all(clean.block.ready_latency_us >= ...
    clean.metrics.beat_service_us), ...
    'Block-ready ownership cannot precede the owning beat completion.');
assert(clean.cpu.processor_copy_demand_us == ...
    clean.metrics.sample_count .* ...
    clean.input.processor_copy_cpu_us_per_sample, ...
    'Processor-copy CPU demand must equal N*C_copy.');
assert(clean.cpu.reference_dma_demand_us == ...
    clean.input.dma_setup_cpu_us + ...
    clean.metrics.block_count .* clean.input.completion_isr_cpu_us, ...
    'DMA CPU demand must equal setup plus block completion handlers.');
assert(clean.cpu.reference_cpu_service_saved_us == ...
    clean.cpu.processor_copy_demand_us - ...
    clean.cpu.reference_dma_demand_us, ...
    'CPU service savings must preserve their signed accounting identity.');
assert(isequal(clean.memory.planned_destination_slot, 1:32), ...
    'Increment mode must advance one destination slot per sample.');
assert(isequal(clean.memory.committed_destination_slot, 1:32), ...
    'Every baseline destination address must commit.');
assert(~any(clean.memory.overwritten_beat), ...
    'Incrementing baseline writes must never overwrite a prior slot.');
assert(clean.observation.descriptor_complete, ...
    'The baseline descriptor must expose full completion.');
assert(~clean.observation.wait_timed_out, ...
    'An infinite baseline wait must not report timeout.');
assert(~clean.observation.abort_issued, ...
    'The baseline must not issue an abort-transfer action.');
assert(clean.observation.observed_bus_active_us == ...
    clean.metrics.reference_bus_busy_us, ...
    'Unaborted observed bus service must equal reference busy time.');
assert(clean.observation.completed_bus_service_us == ...
    clean.metrics.reference_bus_busy_us, ...
    'Every baseline beat must contribute completed bus service.');
assert(clean.metrics.source_queue_loss_count == 0 && ...
    ~clean.metrics.ring_buffer_overrun_modeled, ...
    ['The finite serialized fixture must not invent FIFO loss or the ' ...
    'P14 ring-buffer policy.']);
assert(isequaln(runFixture(fixture), clean), ...
    'The clean fixture must remain deterministic and state-isolated.');

%% Sweep 1 isolates block notification from bus timing
blockSizeSweep = [1 2 4 8 16 32];
interruptCount = zeros(size(blockSizeSweep));
dmaCpuDemandUs = zeros(size(blockSizeSweep));
meanReadyLatencyUs = zeros(size(blockSizeSweep));
maxReadyLatencyUs = zeros(size(blockSizeSweep));
for sweepIndex = 1:numel(blockSizeSweep)
    sweptInput = scenarioFcn('baseline', blockSizeSweep(sweepIndex), ...
        0.2, 50, 1, 3, 4);
    swept = runFixture(sweptInput);
    interruptCount(sweepIndex) = ...
        swept.metrics.completion_interrupt_count;
    dmaCpuDemandUs(sweepIndex) = ...
        swept.cpu.reference_dma_demand_us;
    meanReadyLatencyUs(sweepIndex) = ...
        swept.metrics.mean_block_ready_latency_us;
    maxReadyLatencyUs(sweepIndex) = ...
        swept.metrics.max_block_ready_latency_us;
    assert(isequal(swept.timeline.request_us, ...
        clean.timeline.request_us) && ...
        isequal(swept.timeline.start_us, clean.timeline.start_us) && ...
        isequal(swept.timeline.completion_us, ...
        clean.timeline.completion_us) && ...
        swept.metrics.reference_bus_busy_us == ...
        clean.metrics.reference_bus_busy_us && ...
        swept.metrics.offered_bus_load_pct == ...
        clean.metrics.offered_bus_load_pct && ...
        isequal(swept.memory.destination_samples, ...
        clean.memory.destination_samples), ...
        ['Block-size sweep must isolate notification while retaining ' ...
        'timing, bus work, and destination data.']);
end
assert(isequal(interruptCount, [32 16 8 4 2 1]) && ...
    isequal(dmaCpuDemandUs, [104 56 32 20 14 11]) && ...
    isequal(meanReadyLatencyUs, [11 36 86 186 386 786]) && ...
    isequal(maxReadyLatencyUs, [11 61 161 361 761 1561]), ...
    'Block-size sweep references changed.');

%% Sweep 2 isolates bus service from notification CPU demand
busRateSweepBytesPerUs = [0.025 0.04 0.05 0.1 0.2];
beatServiceSweepUs = zeros(size(busRateSweepBytesPerUs));
offeredLoadPct = zeros(size(busRateSweepBytesPerUs));
maxRequestLatencyUs = zeros(size(busRateSweepBytesPerUs));
peakPendingRequests = zeros(size(busRateSweepBytesPerUs));
descriptorCompletionSweepUs = zeros(size(busRateSweepBytesPerUs));
requestBudgetExceedCount = zeros(size(busRateSweepBytesPerUs));
for sweepIndex = 1:numel(busRateSweepBytesPerUs)
    sweptInput = scenarioFcn('baseline', 8, ...
        busRateSweepBytesPerUs(sweepIndex), 50, 1, 3, 4);
    swept = runFixture(sweptInput);
    beatServiceSweepUs(sweepIndex) = swept.metrics.beat_service_us;
    offeredLoadPct(sweepIndex) = swept.metrics.offered_bus_load_pct;
    maxRequestLatencyUs(sweepIndex) = ...
        swept.metrics.max_request_latency_us;
    peakPendingRequests(sweepIndex) = ...
        swept.metrics.peak_pending_requests;
    descriptorCompletionSweepUs(sweepIndex) = ...
        swept.metrics.descriptor_completion_us;
    requestBudgetExceedCount(sweepIndex) = ...
        swept.metrics.request_budget_exceed_count;
    assert(swept.metrics.completion_interrupt_count == 4 && ...
        swept.cpu.reference_dma_demand_us == 20 && ...
        swept.input.block_samples == clean.input.block_samples && ...
        swept.input.sample_period_us == clean.input.sample_period_us && ...
        swept.input.bytes_per_sample == clean.input.bytes_per_sample && ...
        swept.input.arbitration_us == clean.input.arbitration_us && ...
        isequal(swept.input.source_samples, ...
        clean.input.source_samples), ...
        'Bus-rate sweep must retain block, CPU, request, and source inputs.');
end
assert(isequal(beatServiceSweepUs, [81 51 41 21 11]) && ...
    isequal(offeredLoadPct, [162 102 82 42 22]) && ...
    isequal(maxRequestLatencyUs, [1042 82 41 21 11]) && ...
    isequal(peakPendingRequests, [13 2 1 1 1]) && ...
    isequal(descriptorCompletionSweepUs, ...
    [2592 1632 1591 1571 1561]) && ...
    isequal(requestBudgetExceedCount, [32 32 0 0 0]), ...
    'Bus-rate sweep references changed.');
overloaded = runFixture(scenarioFcn('overloaded-bus'));
assert(~overloaded.metrics.sustainable_without_queue_growth && ...
    overloaded.metrics.source_queue_loss_count == 0 && ...
    ~overloaded.metrics.ring_buffer_overrun_modeled, ...
    'Overload must expose backlog without fabricating FIFO or ring loss.');

%% Broken destination increment, exact rollback, and isolation
broken = runFixture(scenarioFcn('fixed-destination'));
assert(isequal(broken.timeline.request_us, clean.timeline.request_us) && ...
    isequal(broken.timeline.start_us, clean.timeline.start_us) && ...
    isequal(broken.timeline.completion_us, ...
    clean.timeline.completion_us) && ...
    broken.metrics.completion_interrupt_count == 4 && ...
    broken.cpu.reference_dma_demand_us == 20 && ...
    broken.observation.descriptor_complete, ...
    'The fixed-address fault must retain healthy-looking timing.');
assert(all(broken.memory.planned_destination_slot == 1) && ...
    broken.memory.destination_samples(1) == 1158 && ...
    all(isnan(broken.memory.destination_samples(2:end))) && ...
    broken.metrics.written_slot_count == 1 && ...
    broken.metrics.unwritten_slot_count == 31 && ...
    broken.metrics.overwrite_count == 31 && ...
    sum(broken.memory.overwritten_beat) == 31 && ...
    ~broken.metrics.data_integrity, ...
    'Fixed addressing must leave one final value and 31 holes.');
brokenRepeat = runFixture(scenarioFcn('fixed-destination'));
assert(isequaln(brokenRepeat, broken), ...
    'The deliberately broken case must itself be deterministic.');
rollback = runFixture(fixture);
assert(isequaln(rollback, clean), ...
    'Restoring incrementing baseline input must roll back exactly.');

%% Timeout equality, continued wait, abort, and clean recovery
boundaryInput = fixture;
boundaryInput.descriptor_timeout_us = 1561;
boundaryInput.timeout_action = 'abort-transfer';
boundary = runFixture(boundaryInput);
assert(~boundary.observation.wait_timed_out && ...
    ~boundary.observation.abort_issued && ...
    boundary.observation.descriptor_complete && ...
    boundary.observation.committed_sample_count == 32 && ...
    boundary.metrics.data_integrity, ...
    'Descriptor timeout equality must retain completion at the boundary.');

continued = runFixture(scenarioFcn('timeout-continue'));
assert(continued.observation.wait_timed_out && ...
    ~continued.observation.abort_issued && ...
    continued.observation.descriptor_complete && ...
    continued.observation.committed_sample_count == 32 && ...
    continued.observation.completed_block_count == 4 && ...
    continued.metrics.data_integrity && ...
    isequal(continued.memory.destination_samples, ...
    clean.memory.destination_samples), ...
    'Continue-waiting must retain every eventual write after timeout.');

aborted = runFixture(scenarioFcn('timeout-abort'));
assert(aborted.observation.wait_timed_out && ...
    aborted.observation.abort_issued && ...
    ~aborted.observation.descriptor_complete && ...
    isnan(aborted.observation.descriptor_completion_us) && ...
    aborted.observation.committed_sample_count == 24 && ...
    aborted.observation.cancelled_sample_count == 8 && ...
    aborted.observation.completed_block_count == 3 && ...
    aborted.metrics.observed_completion_interrupt_count == 3 && ...
    ~aborted.observation.partial_beat_in_flight_at_abort, ...
    'Abort at 1161 us must retain exactly 24 beats and three blocks.');
assert(isequal(aborted.memory.destination_samples(1:24), ...
    clean.memory.source_samples(1:24)) && ...
    all(isnan(aborted.memory.destination_samples(25:end))) && ...
    aborted.metrics.committed_bytes == 48 && ...
    aborted.metrics.cancelled_bytes == 16 && ...
    aborted.metrics.byte_conservation_error == 0 && ...
    ~aborted.metrics.data_integrity, ...
    'Abort must expose the committed prefix without fabricating a tail.');
assert(aborted.cpu.committed_processor_copy_demand_us == 96 && ...
    aborted.cpu.observed_dma_demand_us == 17 && ...
    aborted.cpu.observed_cpu_service_saved_us == 79, ...
    ['Observed CPU savings after abort must compare equal committed ' ...
    '24-sample work, not a full 32-sample processor-copy transfer.']);

partialInput = fixture;
partialInput.descriptor_timeout_us = 1160;
partialInput.timeout_action = 'abort-transfer';
partialAbort = runFixture(partialInput);
assert(partialAbort.observation.committed_sample_count == 23 && ...
    partialAbort.observation.completed_block_count == 2 && ...
    partialAbort.metrics.observed_completion_interrupt_count == 2 && ...
    partialAbort.observation.partial_beat_in_flight_at_abort && ...
    partialAbort.observation.completed_bus_service_us == 253 && ...
    partialAbort.observation.observed_bus_active_us == 263 && ...
    all(isnan(partialAbort.block.observed_ready_latency_us(17:end))), ...
    'An incomplete third block must not become processor-owned.');
afterCancellation = runFixture(fixture);
assert(isequaln(afterCancellation, clean), ...
    'A clean call after cancellation must recover exact baseline state.');

%% Limiting cases, final partial blocks, and compatibility
single = modelFcn(7, 50, 2, 0.2, 1, 8, 0, 0, 0, ...
    [], [], []);
assert(single.metrics.sample_count == 1 && ...
    single.metrics.block_count == 1 && ...
    single.block.sample_count == 1 && ...
    single.metrics.completion_interrupt_count == 1 && ...
    single.metrics.max_request_latency_us == 11 && ...
    single.metrics.max_block_ready_latency_us == 11 && ...
    single.cpu.reference_dma_demand_us == 0 && ...
    single.metrics.data_integrity, ...
    'One sample must form one final partial block with one-beat latency.');

exactCapacity = modelFcn([1 2 3], 3, 2, 1, 1, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(exactCapacity.metrics.beat_service_us == 3 && ...
    exactCapacity.metrics.request_slack_us == 0 && ...
    exactCapacity.metrics.offered_bus_load_pct == 100 && ...
    exactCapacity.metrics.sustainable_without_queue_growth && ...
    isequal(exactCapacity.timeline.request_us, [0 3 6]) && ...
    isequal(exactCapacity.timeline.completion_us, [3 6 9]) && ...
    isequal(exactCapacity.timeline.pending_at_arrival, [1 1 1]) && ...
    exactCapacity.metrics.request_budget_exceed_count == 0, ...
    'q=T_s must pass with completion before equal-boundary arrival.');
slower = modelFcn([1 2 3], 3, 2, 1, 2, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(slower.metrics.beat_service_us == 4 && ...
    ~slower.metrics.sustainable_without_queue_growth && ...
    slower.metrics.max_queue_wait_us == 2 && ...
    slower.metrics.request_budget_exceed_count == 3, ...
    'The smallest declared slower case must accumulate serial wait.');

partialTail = modelFcn([1 2 3 4 5], 10, 2, 1, 1, 3, ...
    0, 1, 1, Inf, 'continue-waiting', 'increment');
assert(isequal(partialTail.block.start_sample_index, [1 4]) && ...
    isequal(partialTail.block.end_sample_index, [3 5]) && ...
    isequal(partialTail.block.sample_count, [3 2]) && ...
    isequal(partialTail.block.completion_us, [23 43]) && ...
    isequal(partialTail.block.ready_latency_us, [23 13 3 13 3]) && ...
    partialTail.metrics.mean_block_ready_latency_us == 11 && ...
    partialTail.metrics.max_block_ready_latency_us == 23 && ...
    partialTail.metrics.completion_interrupt_count == 2 && ...
    partialTail.cpu.reference_dma_demand_us == 2 && ...
    partialTail.metrics.data_integrity && ...
    partialTail.block.end_sample_index(end) == 5, ...
    ['A final short block must retain its true sample count, final-beat ' ...
    'handoff, readiness, interrupt demand, and destination integrity.']);
largerThanTrace = modelFcn([1 2 3 4 5], 10, 2, 1, 1, 8, ...
    0, 1, 1, Inf, 'continue-waiting', 'increment');
assert(largerThanTrace.metrics.block_count == 1 && ...
    largerThanTrace.block.sample_count == 5 && ...
    largerThanTrace.block.end_sample_index == 5, ...
    'Block size above trace length must create one declared short block.');

negativeSaving = modelFcn(1:4, 10, 1, 1, 0, 1, ...
    10, 10, 1, Inf, 'continue-waiting', 'increment');
assert(negativeSaving.cpu.processor_copy_demand_us == 4 && ...
    negativeSaving.cpu.reference_dma_demand_us == 50 && ...
    negativeSaving.cpu.reference_cpu_service_saved_us == -46, ...
    'CPU service savings must remain signed, not clamp at zero.');

integerColumn = modelFcn(uint16(fixture.source_samples'), ...
    uint16(50), uint8(2), 0.2, uint8(1), uint8(8), ...
    uint8(8), uint8(3), uint8(4), [], ...
    string('continue-waiting'), string('increment'));
assert(isequaln(integerColumn, clean), ...
    ['Integer numeric classes, a column source, scalar strings, and ' ...
    'an empty timeout must normalize exactly.']);
safeInteger = modelFcn(uint64([0 flintmax]), 50, 2, 0.2, 1, 2, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(isequal(safeInteger.memory.source_samples, [0 flintmax]) && ...
    safeInteger.metrics.data_integrity, ...
    'Integer source values through flintmax must retain exact identity.');
safeSignedInteger = modelFcn( ...
    [-int64(flintmax) int64(flintmax)], 50, 2, 0.2, 1, 2, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(isequal(safeSignedInteger.memory.source_samples, ...
        [-flintmax flintmax]) && ...
    safeSignedInteger.metrics.data_integrity, ...
    'Signed integer source values at +/-flintmax must remain exact.');
emptyDefaults = modelFcn(fixture.source_samples, 50, 2, 0.2, 1, 8, ...
    8, 3, 4, [], [], []);
assert(isequaln(emptyDefaults, clean), ...
    'Empty timeout/action/address defaults must recover baseline policy.');
stringScenario = scenarioFcn(string('baseline'));
assert(isequaln(stringScenario, fixture), ...
    'A scalar-string scenario name must match the character-vector name.');

%% Callback-bound dependencies survive public path cleanup
callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
clear model;
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.source_samples, ...
    callbackInput.sample_period_us, callbackInput.bytes_per_sample, ...
    callbackInput.bus_rate_bytes_per_us, ...
    callbackInput.arbitration_us, callbackInput.block_samples, ...
    callbackInput.dma_setup_cpu_us, ...
    callbackInput.completion_isr_cpu_us, ...
    callbackInput.processor_copy_cpu_us_per_sample, ...
    callbackInput.descriptor_timeout_us, ...
    callbackInput.timeout_action, callbackInput.destination_mode);
assert(isequaln(callbackOut, clean), ...
    ['Callback-bound P13 dependencies must survive module path cleanup ' ...
    'plus a generic-model clear and conflicting P01 model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn(fixture.source_samples, 50, 2, 0.2, 1, 8, ...
    8, 3, 4, Inf, 'continue-waiting'), 'P13:model:Arity');
assertReject(@() modelFcn([], 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn('samples', 50, 2, 0.2, 1, 8, 8, 3, 4, ...
    Inf, 'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(true, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(1 + 1i, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(NaN, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(Inf, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(ones(2), 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourceSamples');
assertReject(@() modelFcn(uint64(flintmax) + uint64(1), ...
    50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourcePrecision');
assertReject(@() modelFcn(-int64(flintmax) - int64(1), ...
    50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SourcePrecision');

assertReject(@() modelFcn(1, '50', 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SamplePeriod');
assertReject(@() modelFcn(1, true, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SamplePeriod');
assertReject(@() modelFcn(1, 0, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SamplePeriod');
assertReject(@() modelFcn(1, [50 50], 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:SamplePeriod');
assertReject(@() modelFcn(1, 50, 0, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BytesPerSample');
assertReject(@() modelFcn(1, 50, 1.5, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BytesPerSample');
assertReject(@() modelFcn(1, 50, 17, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BytesPerSample');
assertReject(@() modelFcn(1, 50, 2, 0, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BusRate');
assertReject(@() modelFcn(1, 50, 2, 0.2, -1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:Arbitration');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 0, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BlockSamples');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 1.5, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:BlockSamples');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 1000001, 8, 3, 4, Inf, ...
    'continue-waiting', 'increment'), ...
    'P13:model:BlockResourceBound');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, -1, 3, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:DmaSetupCpu');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, -1, 4, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:CompletionIsrCpu');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, -1, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:ProcessorCopyCpu');

assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, 0, ...
    'continue-waiting', 'increment'), 'P13:model:DescriptorTimeout');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, NaN, ...
    'continue-waiting', 'increment'), 'P13:model:DescriptorTimeout');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, [1 2], ...
    'continue-waiting', 'increment'), 'P13:model:DescriptorTimeout');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'drop-tail', 'increment'), 'P13:model:TimeoutAction');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    {'continue-waiting'}, 'increment'), 'P13:model:TimeoutAction');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', 'scatter'), 'P13:model:DestinationMode');
assertReject(@() modelFcn(1, 50, 2, 0.2, 1, 8, 8, 3, 4, Inf, ...
    'continue-waiting', {'increment'}), 'P13:model:DestinationMode');

largestSource = 1:10000;
largest = modelFcn(largestSource, 1, 1, 1, 0, 10000, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(largest.metrics.sample_count == 10000 && ...
    largest.timeline.completion_us(end) == 10000 && ...
    largest.metrics.block_count == 1 && ...
    largest.metrics.data_integrity, ...
    'The accepted 10,000-sample resource boundary must execute.');
assertReject(@() modelFcn(zeros(1, 10001), 1, 1, 1, 0, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:SampleResourceBound');
largestBlock = modelFcn(1, 1, 1, 1, 0, 1000000, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(largestBlock.metrics.block_count == 1 && ...
    largestBlock.block.sample_count == 1, ...
    'The block-size bound must not allocate a million-sample trace.');

timelineBoundary = modelFcn([1 2], 1e12 - 1, 1, 1, 0, 2, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment');
assert(timelineBoundary.timeline.completion_us(end) == 1e12, ...
    'The exact 1e12-us derived timeline boundary must pass.');
assertReject(@() modelFcn([1 2], 1e12, 1, 1, 0, 2, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:TimingResourceBound');
assertReject(@() modelFcn(1, 1, 1, realmin, 0, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:TimingResourceBound');
assertReject(@() modelFcn(1, realmin, 1, 1, 0, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:TimingResourceBound');
assertReject(@() modelFcn([1 2], 1e12, 1, 1e6, 0, 2, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:TimingPrecision');
assertReject(@() modelFcn(1, 1, 1, 1e6, 1e12, 1, ...
    0, 0, 0, Inf, 'continue-waiting', 'increment'), ...
    'P13:model:TimingPrecision');
assertReject(@() modelFcn([1 2], 1, 1, 1, 0, 1, ...
    realmax, realmax, realmax, Inf, ...
    'continue-waiting', 'increment'), 'P13:model:CpuResourceBound');

assertReject(@() scenarioFcn({'baseline'}), 'P13:scenario:Name');
assertReject(@() scenarioFcn('unknown'), 'P13:scenario:Name');
assertReject(@() scenarioFcn('baseline', 0), ...
    'P13:scenario:BlockSamples');
assertReject(@() scenarioFcn('baseline', 1.5), ...
    'P13:scenario:BlockSamples');
assertReject(@() scenarioFcn('baseline', 8, 0.0001), ...
    'P13:scenario:BusRate');
assertReject(@() scenarioFcn('baseline', 8, 0.2, 0), ...
    'P13:scenario:SamplePeriod');
assertReject(@() scenarioFcn('baseline', 8, 0.2, 50, -1), ...
    'P13:scenario:Arbitration');
assertReject(@() scenarioFcn('baseline', 8, 0.2, 50, 1, -1), ...
    'P13:scenario:CompletionIsrCpu');
assertReject(@() scenarioFcn('baseline', 8, 0.2, 50, 1, 3, -1), ...
    'P13:scenario:ProcessorCopyCpu');
assertReject(@() scenarioFcn('baseline', 8, 0.2, 50, 1, 3, 4, 99), ...
    'P13:scenario:Arity');

afterMalformed = runFixture(fixture);
assert(isequaln(afterMalformed, clean), ...
    'A malformed call must not contaminate clean recovery.');

disp(['DMA CPU values are declared service demand, not measured ' ...
    'processor utilization or a P12 response-time guarantee.']);
disp(['Resource bound and resource ceiling rejection occur before ' ...
    'unbounded trace allocation.']);
disp(['Abort-transfer is not an asynchronous DMA cancellation API and ' ...
    'does not provide transactional rollback.']);
disp(['Backlog is not proved loss; completion is not integrity; abort ' ...
    'is not peripheral, memory, driver, cache, or plant rollback.']);
disp('P13 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
