function out = model(signalFrequencyHz, sampleRateHz, sampleCount, ...
    amplitudeV, offsetV, phaseRad, antiAliasCutoffHz, adcBits, ...
    referenceVoltageV, fault, acquisitionDeadlineS)
%MODEL Sample one conditioned sinusoid with an ideal bounded ADC fixture.
%   The source is offsetV + amplitudeV*cos(2*pi*f*t + phaseRad). A
%   transparent first-order analog low-pass has H(f)=1/(1+j*f/fc), unless
%   the deliberately broken anti-alias-bypass fault is selected. This is
%   the steady-state component response; filter startup and initial state
%   are not modeled. Samples occur at t_n=n/sampleRateHz. Signed frequency
%   folding is explicit:
%
%     f_fold = mod(f + sampleRateHz/2, sampleRateHz) - sampleRateHz/2
%     f_alias = abs(f_fold).
%
%   ADC codes use L=2^adcBits levels over [0, referenceVoltageV],
%   LSB=referenceVoltageV/L, floor quantization, saturation to [0,L-1],
%   and code-center voltage estimates. A finite acquisition deadline only
%   classifies this pure analytical result; it does not wait for or cancel
%   a hardware conversion.

if nargin < 9 || nargin > 11
    error('P07:model:Arity', ...
        ['Expected frequency, sample rate/count, amplitude, offset, phase, ' ...
        'anti-alias cutoff, ADC bits/reference, and optional fault/deadline.']);
end
if nargin < 10 || isempty(fault)
    fault = defaultFault();
end
if nargin < 11 || isempty(acquisitionDeadlineS)
    acquisitionDeadlineS = Inf;
end

maxSamples = 10000;
maxReferencePoints = 200000;
if isnumeric(sampleCount) && isreal(sampleCount) && isscalar(sampleCount) && ...
        isfinite(sampleCount) && sampleCount > maxSamples
    error('P07:model:ResourceBound', ...
        'At most ten thousand ADC samples are allowed.');
end

signalFrequencyHz = validateFiniteScalar(signalFrequencyHz, ...
    'P07:model:SignalFrequency', 'signalFrequencyHz');
if signalFrequencyHz < 0 || signalFrequencyHz > 1e6
    error('P07:model:SignalFrequency', ...
        'signalFrequencyHz must lie in [0, 1e6] Hz.');
end
sampleRateHz = validateFiniteScalar(sampleRateHz, ...
    'P07:model:SampleRate', 'sampleRateHz');
if sampleRateHz < 1e-3 || sampleRateHz > 1e6
    error('P07:model:SampleRate', ...
        'sampleRateHz must lie in [1e-3, 1e6] Hz.');
end
sampleCount = validateIntegerScalar(sampleCount, 2, maxSamples, ...
    'P07:model:SampleCount', 'sampleCount');
referenceVoltageV = validateFiniteScalar(referenceVoltageV, ...
    'P07:model:ReferenceVoltage', 'referenceVoltageV');
if referenceVoltageV <= 0 || referenceVoltageV > 1000
    error('P07:model:ReferenceVoltage', ...
        'referenceVoltageV must lie in (0, 1000] V.');
end
amplitudeV = validateFiniteScalar(amplitudeV, ...
    'P07:model:Amplitude', 'amplitudeV');
if amplitudeV < 0 || amplitudeV > 2 .* referenceVoltageV
    error('P07:model:Amplitude', ...
        'amplitudeV must lie in [0, 2*referenceVoltageV].');
end
offsetV = validateFiniteScalar(offsetV, ...
    'P07:model:Offset', 'offsetV');
if offsetV < -referenceVoltageV || offsetV > 2 .* referenceVoltageV
    error('P07:model:Offset', ...
        'offsetV must lie in [-referenceVoltageV, 2*referenceVoltageV].');
end
phaseRad = validateFiniteScalar(phaseRad, ...
    'P07:model:Phase', 'phaseRad');
if abs(phaseRad) > 2 .* pi .* 1e6
    error('P07:model:Phase', ...
        'abs(phaseRad) must not exceed 2*pi*1e6 radians.');
end
antiAliasCutoffHz = validateFiniteScalar(antiAliasCutoffHz, ...
    'P07:model:AntiAliasCutoff', 'antiAliasCutoffHz');
if antiAliasCutoffHz <= 0 || antiAliasCutoffHz > 1e6
    error('P07:model:AntiAliasCutoff', ...
        'antiAliasCutoffHz must lie in (0, 1e6] Hz.');
end
adcBits = validateIntegerScalar(adcBits, 2, 24, ...
    'P07:model:ADCBits', 'adcBits');
fault = validateFault(fault);
acquisitionDeadlineS = validateDeadline(acquisitionDeadlineS);

modeledAcquisitionTimeS = sampleCount ./ sampleRateHz;
if ~isfinite(modeledAcquisitionTimeS) || modeledAcquisitionTimeS > 1e6
    error('P07:model:TimingResourceBound', ...
        'The sample count and rate must keep acquisition time at or below 1e6 s.');
end
lastSampleTimeS = (sampleCount - 1) ./ sampleRateHz;
% Retain at least sixteen reference points per sample interval and twenty-
% four per physical input cycle. Every accepted P07 fixture, including its
% ten-thousand-sample upper bound, then remains below the explicit cap.
frequencyDrivenPoints = ceil(24 .* signalFrequencyHz .* ...
    max(lastSampleTimeS, 1 ./ sampleRateHz)) + 1;
referencePointCount = max([512, 16 .* sampleCount, frequencyDrivenPoints]);
if ~isfinite(referencePointCount) || ...
        referencePointCount > maxReferencePoints
    error('P07:model:ResourceBound', ...
        'The dense reference trace must remain at or below 200000 points.');
end

filterBypassed = strcmp(fault.mode, 'anti-alias-bypass');
if filterBypassed || signalFrequencyHz == 0
    filterGain = 1;
    filterPhaseRad = 0;
else
    normalizedFrequency = signalFrequencyHz ./ antiAliasCutoffHz;
    filterGain = 1 ./ sqrt(1 + normalizedFrequency .^ 2);
    filterPhaseRad = -atan(normalizedFrequency);
end
filteredAmplitudeV = amplitudeV .* filterGain;
effectivePhaseRad = phaseRad + filterPhaseRad;

nyquistHz = sampleRateHz ./ 2;
signedFoldHz = mod(signalFrequencyHz + nyquistHz, sampleRateHz) - ...
    nyquistHz;
aliasFrequencyHz = abs(signedFoldHz);
if signedFoldHz < 0
    aliasPhaseRad = -effectivePhaseRad;
else
    aliasPhaseRad = effectivePhaseRad;
end
strictNyquistSafe = signalFrequencyHz < nyquistHz;
aliasingPresent = amplitudeV > 0 && ~strictNyquistSafe;
nyquistMarginHz = nyquistHz - signalFrequencyHz;
if signalFrequencyHz == 0
    samplesPerInputCycle = Inf;
else
    samplesPerInputCycle = sampleRateHz ./ signalFrequencyHz;
end

sampleTimeS = (0:(sampleCount - 1)) ./ sampleRateHz;
referenceTimeS = linspace(0, lastSampleTimeS, referencePointCount);
sourceSampleV = offsetV + amplitudeV .* cos( ...
    2 .* pi .* signalFrequencyHz .* sampleTimeS + phaseRad);
directFilteredSampleV = offsetV + filteredAmplitudeV .* cos( ...
    2 .* pi .* signalFrequencyHz .* sampleTimeS + effectivePhaseRad);
apparentSampleV = offsetV + filteredAmplitudeV .* cos( ...
    2 .* pi .* aliasFrequencyHz .* sampleTimeS + aliasPhaseRad);
% The signed-fold form is mathematically the same sequence and avoids
% large-angle trigonometric roundoff making equivalent aliases quantize to
% different codes at a transition.
filteredSampleV = apparentSampleV;
sourceReferenceV = offsetV + amplitudeV .* cos( ...
    2 .* pi .* signalFrequencyHz .* referenceTimeS + phaseRad);
filteredReferenceV = offsetV + filteredAmplitudeV .* cos( ...
    2 .* pi .* signalFrequencyHz .* referenceTimeS + effectivePhaseRad);
apparentReferenceV = offsetV + filteredAmplitudeV .* cos( ...
    2 .* pi .* aliasFrequencyHz .* referenceTimeS + aliasPhaseRad);
aliasIdentityErrorV = apparentSampleV - directFilteredSampleV;

levelCount = 2 .^ adcBits;
maxCode = levelCount - 1;
lsbV = referenceVoltageV ./ levelCount;
clippedLow = filteredSampleV < 0;
clippedHigh = filteredSampleV > referenceVoltageV;
clippedSampleV = min(max(filteredSampleV, 0), referenceVoltageV);
codes = min(floor(clippedSampleV ./ lsbV), maxCode);
codeCenterV = (codes + 0.5) .* lsbV;
quantizationErrorV = codeCenterV - clippedSampleV;
totalConversionErrorV = codeCenterV - filteredSampleV;

timedOut = modeledAcquisitionTimeS > acquisitionDeadlineS;
captureComplete = ~timedOut;
if captureComplete
    committedCodes = codes;
    committedVoltageV = codeCenterV;
else
    committedCodes = zeros(1, 0);
    committedVoltageV = zeros(1, 0);
end

out = struct();
out.input = struct( ...
    'signal_frequency_hz', signalFrequencyHz, ...
    'sample_rate_hz', sampleRateHz, ...
    'sample_count', sampleCount, ...
    'amplitude_v', amplitudeV, ...
    'offset_v', offsetV, ...
    'phase_rad', phaseRad, ...
    'anti_alias_cutoff_hz', antiAliasCutoffHz, ...
    'adc_bits', adcBits, ...
    'reference_voltage_v', referenceVoltageV);
out.config = struct( ...
    'fault', fault, ...
    'acquisition_deadline_s', acquisitionDeadlineS);
out.filter = struct( ...
    'kind', 'first-order analog low-pass', ...
    'enabled', ~filterBypassed, ...
    'gain', filterGain, ...
    'phase_rad', filterPhaseRad, ...
    'filtered_amplitude_v', filteredAmplitudeV, ...
    'rejection_db', -20 .* log10(filterGain));
out.frequency = struct( ...
    'nyquist_hz', nyquistHz, ...
    'nyquist_margin_hz', nyquistMarginHz, ...
    'signed_fold_hz', signedFoldHz, ...
    'alias_frequency_hz', aliasFrequencyHz, ...
    'alias_phase_rad', aliasPhaseRad, ...
    'strict_nyquist_safe', strictNyquistSafe, ...
    'aliasing_present', aliasingPresent, ...
    'samples_per_input_cycle', samplesPerInputCycle, ...
    'max_alias_identity_error_v', max(abs(aliasIdentityErrorV)));
out.analog = struct( ...
    'reference_time_s', referenceTimeS, ...
    'source_v', sourceReferenceV, ...
    'filtered_v', filteredReferenceV, ...
    'apparent_alias_v', apparentReferenceV);
out.samples = struct( ...
    'time_s', sampleTimeS, ...
    'source_v', sourceSampleV, ...
    'direct_filtered_v', directFilteredSampleV, ...
    'filtered_v', filteredSampleV, ...
    'apparent_alias_v', apparentSampleV);
out.adc = struct( ...
    'level_count', levelCount, ...
    'max_code', maxCode, ...
    'lsb_v', lsbV, ...
    'clipped_sample_v', clippedSampleV, ...
    'codes', codes, ...
    'code_center_v', codeCenterV, ...
    'quantization_error_v', quantizationErrorV, ...
    'total_conversion_error_v', totalConversionErrorV, ...
    'clipped_low', clippedLow, ...
    'clipped_high', clippedHigh, ...
    'clipped_count', sum(clippedLow | clippedHigh), ...
    'committed_codes', committedCodes, ...
    'committed_voltage_v', committedVoltageV);
out.capture = struct( ...
    'observation_span_s', lastSampleTimeS, ...
    'modeled_acquisition_time_s', modeledAcquisitionTimeS, ...
    'timed_out', timedOut, ...
    'complete', captureComplete, ...
    'raw_payload_rate_bps', sampleRateHz .* adcBits);
out.claim_boundary = [ ...
    'Deterministic synthetic sampling, first-order conditioning, and ideal ' ...
    'ADC quantization; not a hardware measurement or converter-fidelity result.'];
end

function value = validateFiniteScalar(value, identifier, label)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
if ~valid
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function value = validateIntegerScalar(value, lowerBound, upperBound, ...
    identifier, label)
value = validateFiniteScalar(value, identifier, label);
if value ~= round(value) || value < lowerBound || value > upperBound
    error(identifier, '%s must be an integer in [%d, %d].', ...
        label, lowerBound, upperBound);
end
end

function deadlineS = validateDeadline(deadlineS)
validType = isnumeric(deadlineS) && isreal(deadlineS) && ...
    isscalar(deadlineS);
validValue = validType && ...
    ((isfinite(deadlineS) && deadlineS >= 0) || ...
    (isinf(deadlineS) && deadlineS > 0));
if ~validValue
    error('P07:model:AcquisitionDeadline', ...
        ['acquisitionDeadlineS must be nonnegative and finite, or ' ...
        'positive Inf.']);
end
deadlineS = double(deadlineS);
end

function fault = defaultFault()
fault = struct('mode', 'none');
end

function fault = validateFault(candidate)
if ~isstruct(candidate) || ~isscalar(candidate) || ...
        ~isfield(candidate, 'mode')
    error('P07:model:Fault', ...
        'fault must be a scalar struct with a mode field.');
end
if any(~ismember(fieldnames(candidate), {'mode'}))
    error('P07:model:Fault', 'fault contains an unsupported field.');
end
mode = candidate.mode;
if ~(ischar(mode) || (isstring(mode) && isscalar(mode)))
    error('P07:model:FaultMode', 'fault.mode must be scalar text.');
end
mode = lower(strtrim(char(mode)));
if ~any(strcmp(mode, {'none', 'anti-alias-bypass'}))
    error('P07:model:FaultMode', ...
        'fault.mode must be none or anti-alias-bypass.');
end
fault = struct('mode', mode);
end
