function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P07.

%% Exact baseline timing, filter, fold, ADC, and transport identities
fixture = p07_scenario('baseline');
clean = model(fixture.signal_frequency_hz, fixture.sample_rate_hz, ...
    fixture.sample_count, fixture.amplitude_v, fixture.offset_v, ...
    fixture.phase_rad, fixture.anti_alias_cutoff_hz, ...
    fixture.adc_bits, fixture.reference_voltage_v, fixture.fault, ...
    fixture.acquisition_deadline_s);
assert(isequal(clean.samples.time_s, (0:50) ./ 1000), ...
    'Baseline sample instants must be n/f_s from 0 through 50 ms.');
assert(clean.capture.observation_span_s == 0.05 && ...
    clean.capture.modeled_acquisition_time_s == 0.051, ...
    'Fifty-one samples span 50 ms and consume 51 modeled conversion periods.');
assert(clean.frequency.nyquist_hz == 500 && ...
    clean.frequency.nyquist_margin_hz == 320, ...
    'The baseline Nyquist boundary and strict margin must be 500 and 320 Hz.');
assert(clean.frequency.signed_fold_hz == 180 && ...
    clean.frequency.alias_frequency_hz == 180 && ...
    clean.frequency.strict_nyquist_safe && ...
    ~clean.frequency.aliasing_present, ...
    'A 180 Hz baseline at 1 ksample/s must retain its frequency safely.');
expectedGain = 1 ./ sqrt(1 + (180 ./ 400) .^ 2);
expectedPhase = -atan(180 ./ 400);
assert(abs(clean.filter.gain - expectedGain) < 1e-14 && ...
    abs(clean.filter.phase_rad - expectedPhase) < 1e-14, ...
    'First-order analog gain and phase must match H(f)=1/(1+jf/f_c).');
assert(clean.filter.enabled && ...
    abs(clean.filter.filtered_amplitude_v - expectedGain) < 1e-14, ...
    'The enabled baseline front end must scale the one-volt peak explicitly.');
assert(clean.frequency.max_alias_identity_error_v < 1e-10, ...
    'The signed folded sinusoid must reproduce the physical sample sequence.');

expectedLsbV = 3.3 ./ 4096;
assert(clean.adc.level_count == 4096 && clean.adc.max_code == 4095 && ...
    abs(clean.adc.lsb_v - expectedLsbV) < 1e-15, ...
    'Twelve ADC bits must define 4096 levels and V_ref/4096 volts per code.');
assert(all(clean.adc.codes >= 0) && all(clean.adc.codes <= 4095) && ...
    clean.adc.clipped_count == 0, ...
    'Baseline codes must stay inside the rails without clipping.');
assert(max(abs(clean.adc.quantization_error_v)) <= ...
    clean.adc.lsb_v ./ 2 + 8 .* eps(clean.input.reference_voltage_v), ...
    'Unclipped code-center quantization error must remain within half an LSB.');
assert(isequal(clean.adc.codes, clean.adc.committed_codes) && ...
    clean.capture.complete && ~clean.capture.timed_out, ...
    'An infinite deadline must commit every offered baseline code.');
assert(clean.capture.raw_payload_rate_bps == 12000, ...
    'Raw ADC payload rate must equal f_s times ADC bits.');

%% DC, filter-corner, zero-amplitude, and strict Nyquist limiting cases
dc = model(0, 1000, 8, 1, 1.65, 0, 400, 12, 3.3);
assert(dc.filter.gain == 1 && dc.filter.phase_rad == 0 && ...
    dc.frequency.alias_frequency_hz == 0, ...
    'DC must pass the first-order front end with unity gain and zero phase.');
assert(all(dc.samples.filtered_v == 2.65) && ...
    dc.frequency.strict_nyquist_safe && ...
    isinf(dc.frequency.samples_per_input_cycle), ...
    'The DC limiting case must be constant and need no finite cycle count.');

atCorner = model(400, 2000, 16, 1, 1.65, 0, 400, 12, 3.3);
assert(abs(atCorner.filter.gain - 1 ./ sqrt(2)) < 1e-14 && ...
    abs(atCorner.filter.phase_rad + pi ./ 4) < 1e-14, ...
    'At f=f_c the first-order front end must be -3 dB and -pi/4 rad.');

zeroAmplitude = model(820, 1000, 16, 0, 1.65, 0, 400, 12, 3.3);
assert(~zeroAmplitude.frequency.strict_nyquist_safe && ...
    ~zeroAmplitude.frequency.aliasing_present, ...
    'An absent zero-amplitude component cannot contribute alias energy.');

justBelow = model(500 - eps(500), 1000, 16, 1, 1.65, 0, ...
    400, 12, 3.3);
atNyquist = model(500, 1000, 16, 1, 1.65, 0, 400, 12, 3.3);
justAbove = model(500 + eps(500), 1000, 16, 1, 1.65, 0, ...
    400, 12, 3.3);
assert(justBelow.frequency.strict_nyquist_safe && ...
    justBelow.frequency.nyquist_margin_hz > 0, ...
    'A representably sub-Nyquist tone must retain a positive strict margin.');
assert(~atNyquist.frequency.strict_nyquist_safe && ...
    atNyquist.frequency.signed_fold_hz == -500 && ...
    atNyquist.frequency.alias_frequency_hz == 500, ...
    'Exact Nyquist equality is degenerate and must not be called safe.');
assert(~justAbove.frequency.strict_nyquist_safe && ...
    justAbove.frequency.nyquist_margin_hz < 0, ...
    'A representably super-Nyquist tone must retain a negative margin.');

nyquistFixture = p07_scenario('nyquist-boundary');
phaseLost = model(nyquistFixture.signal_frequency_hz, ...
    nyquistFixture.sample_rate_hz, nyquistFixture.sample_count, ...
    nyquistFixture.amplitude_v, nyquistFixture.offset_v, ...
    nyquistFixture.phase_rad, nyquistFixture.anti_alias_cutoff_hz, ...
    nyquistFixture.adc_bits, nyquistFixture.reference_voltage_v, ...
    nyquistFixture.fault, Inf);
assert(max(abs(phaseLost.samples.filtered_v - ...
    nyquistFixture.offset_v)) < 1e-10, ...
    'A pi/2-phase cosine at exact Nyquist must collapse to the offset samples.');
assert(all(phaseLost.adc.codes == phaseLost.adc.codes(1)), ...
    ['The phase-loss diagnostic offset must stay inside one ADC bin despite ' ...
    'floating-point trigonometric residue.']);

%% Fold periodicity, signed orientation, and input-frequency cases
foldToDc = model(1000, 1000, 16, 1, 1.65, 0, 400, 12, 3.3);
positiveFold = model(1180, 1000, 16, 1, 1.65, 0.3, ...
    400, 12, 3.3);
negativeFold = model(820, 1000, 16, 1, 1.65, 0.3, ...
    400, 12, 3.3);
assert(foldToDc.frequency.signed_fold_hz == 0 && ...
    foldToDc.frequency.alias_frequency_hz == 0, ...
    'A tone one whole sample rate above DC must fold to DC.');
assert(positiveFold.frequency.signed_fold_hz == 180 && ...
    negativeFold.frequency.signed_fold_hz == -180, ...
    'Fold periodicity must preserve positive and negative signed orientation.');
assert(positiveFold.frequency.max_alias_identity_error_v < 1e-9 && ...
    negativeFold.frequency.max_alias_identity_error_v < 1e-9, ...
    'Signed phase handling must reproduce arbitrary-phase physical samples.');

%% Sample-rate sweep changes folding but not the analog front end
sampleRateSweepHz = [1000 600 400 300 250];
expectedSignedFoldHz = [180 180 180 -120 -70];
expectedAliasHz = [180 180 180 120 70];
expectedMarginHz = [320 120 20 -30 -55];
expectedSafe = [true true true false false];
for sweepIndex = 1:numel(sampleRateSweepHz)
    swept = model(180, sampleRateSweepHz(sweepIndex), 51, ...
        1, 1.65, 0, 400, 12, 3.3);
    assert(swept.frequency.signed_fold_hz == ...
        expectedSignedFoldHz(sweepIndex) && ...
        swept.frequency.alias_frequency_hz == ...
        expectedAliasHz(sweepIndex), ...
        'Sample-rate sweep fold must match independent modular arithmetic.');
    assert(swept.frequency.nyquist_margin_hz == ...
        expectedMarginHz(sweepIndex) && ...
        swept.frequency.strict_nyquist_safe == expectedSafe(sweepIndex), ...
        'Sample-rate sweep margin and safety must retain the strict boundary.');
    assert(swept.filter.gain == clean.filter.gain && ...
        swept.filter.phase_rad == clean.filter.phase_rad, ...
        'Changing sample rate must not mutate the physical analog front end.');
    assert(swept.capture.raw_payload_rate_bps == ...
        sampleRateSweepHz(sweepIndex) .* 12, ...
        'Sample-rate sweep payload rate must remain f_s times B.');
end

%% Input-frequency sweep resets sampling and retains the exact fold map
frequencySweepHz = [50 180 350 500 650 820 1150];
expectedAliasHz = [50 180 350 500 350 180 150];
expectedSafe = [true true true false false false false];
previousGain = Inf;
for sweepIndex = 1:numel(frequencySweepHz)
    swept = model(frequencySweepHz(sweepIndex), 1000, 51, ...
        1, 1.65, 0, 400, 12, 3.3);
    assert(swept.frequency.alias_frequency_hz == ...
        expectedAliasHz(sweepIndex) && ...
        swept.frequency.strict_nyquist_safe == expectedSafe(sweepIndex), ...
        'Input-frequency sweep must match the independent fold table.');
    assert(swept.input.sample_rate_hz == 1000 && ...
        swept.input.adc_bits == 12 && ...
        swept.capture.raw_payload_rate_bps == 12000, ...
        'Input-frequency sweep must isolate frequency from ADC sampling settings.');
    assert(swept.filter.gain < previousGain, ...
        'First-order analog gain must decrease as physical frequency rises.');
    previousGain = swept.filter.gain;
end

%% Exact alias ambiguity, bit-depth isolation, and analog-filter boundary
bypassFault = struct('mode', 'anti-alias-bypass');
lowPhysical = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, bypassFault, Inf);
highPhysical = model(820, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, bypassFault, Inf);
sharedTraceTimeS = linspace(0, min( ...
    lowPhysical.capture.observation_span_s, ...
    highPhysical.capture.observation_span_s), 2001);
lowPhysicalOnSharedGridV = lowPhysical.input.offset_v + ...
    lowPhysical.input.amplitude_v .* cos(2 .* pi .* ...
    lowPhysical.input.signal_frequency_hz .* sharedTraceTimeS + ...
    lowPhysical.input.phase_rad);
highPhysicalOnSharedGridV = highPhysical.input.offset_v + ...
    highPhysical.input.amplitude_v .* cos(2 .* pi .* ...
    highPhysical.input.signal_frequency_hz .* sharedTraceTimeS + ...
    highPhysical.input.phase_rad);
assert(isequal(lowPhysical.samples.filtered_v, ...
    highPhysical.samples.filtered_v), ...
    'Canonical signed-fold samples for 180 Hz and 820 Hz must match exactly.');
assert(isequal(lowPhysical.adc.codes, highPhysical.adc.codes), ...
    'The bypassed alias pair must produce identical twelve-bit codes.');
assert(max(abs(lowPhysicalOnSharedGridV - ...
    highPhysicalOnSharedGridV)) > 0.5, ...
    'Dense physical traces must remain visibly different before sampling.');
assert(lowPhysical.frequency.strict_nyquist_safe && ...
    ~highPhysical.frequency.strict_nyquist_safe && ...
    highPhysical.frequency.aliasing_present, ...
    'Only the 820 Hz member must violate the strict 1 ksample/s boundary.');
assert(~lowPhysical.filter.enabled && lowPhysical.filter.gain == 1 && ...
    lowPhysical.filter.phase_rad == 0, ...
    'The broken fault must explicitly bypass, not digitally emulate, the filter.');
for bitDepth = [4 6 8 12 16]
    lowBits = model(180, 1000, 51, 1, 1.65, 0, ...
        400, bitDepth, 3.3, bypassFault, Inf);
    highBits = model(820, 1000, 51, 1, 1.65, 0, ...
        400, bitDepth, 3.3, bypassFault, Inf);
    assert(isequal(lowBits.adc.codes, highBits.adc.codes), ...
        'Changing ADC resolution must not disambiguate the alias pair.');
    assert(isequal(lowBits.samples.time_s, highBits.samples.time_s), ...
        'Bit depth must not alter the shared sample instants.');
end
conditionedHigh = model(820, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3);
assert(conditionedHigh.filter.gain < clean.filter.gain && ...
    conditionedHigh.frequency.aliasing_present, ...
    'The analog filter attenuates high input but cannot make it Nyquist-safe.');

%% ADC rail, code-center, clipping, and quantization boundaries
lowRail = model(0, 1000, 2, 0, 0, 0, 400, 12, 3.3);
highRail = model(0, 1000, 2, 0, 3.3, 0, 400, 12, 3.3);
assert(all(lowRail.adc.codes == 0) && ...
    all(abs(lowRail.adc.code_center_v - lowRail.adc.lsb_v ./ 2) < 1e-15), ...
    'Zero volts must map to code zero and its center estimate.');
assert(all(highRail.adc.codes == 4095) && ...
    all(abs(highRail.adc.code_center_v - ...
    (3.3 - highRail.adc.lsb_v ./ 2)) < 1e-14), ...
    'Reference voltage must saturate to the highest code center.');
assert(lowRail.adc.clipped_count == 0 && highRail.adc.clipped_count == 0, ...
    'Values exactly on declared ADC rails must not be called overrange.');

clippingFixture = p07_scenario('clipping');
clipped = model(clippingFixture.signal_frequency_hz, ...
    clippingFixture.sample_rate_hz, clippingFixture.sample_count, ...
    clippingFixture.amplitude_v, clippingFixture.offset_v, ...
    clippingFixture.phase_rad, clippingFixture.anti_alias_cutoff_hz, ...
    clippingFixture.adc_bits, clippingFixture.reference_voltage_v, ...
    clippingFixture.fault, Inf);
assert(any(clipped.adc.clipped_low) && any(clipped.adc.clipped_high), ...
    'The overrange fixture must cross both ADC rails.');
assert(any(clipped.adc.codes == 0) && ...
    any(clipped.adc.codes == clipped.adc.max_code), ...
    'Both clipped rails must map to bounded endpoint codes.');
assert(clipped.frequency.strict_nyquist_safe, ...
    'Rail clipping must remain distinct from frequency aliasing.');

lowerResolution = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 6, 3.3);
assert(lowerResolution.adc.lsb_v == 3.3 ./ 64 && ...
    lowerResolution.frequency.alias_frequency_hz == ...
    clean.frequency.alias_frequency_hz && ...
    isequal(lowerResolution.samples.time_s, clean.samples.time_s), ...
    'ADC bits change voltage resolution but not sample time or fold frequency.');

%% Analytical deadline, rollback, clean retry, and cancellation boundary
atBoundary = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], clean.capture.modeled_acquisition_time_s);
assert(atBoundary.capture.complete && ~atBoundary.capture.timed_out && ...
    numel(atBoundary.adc.committed_codes) == 51, ...
    'A deadline exactly at N/f_s must accept the analytical acquisition.');
oneUlpBefore = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], clean.capture.modeled_acquisition_time_s - ...
    eps(clean.capture.modeled_acquisition_time_s));
assert(oneUlpBefore.capture.timed_out && ...
    ~oneUlpBefore.capture.complete && ...
    isempty(oneUlpBefore.adc.committed_codes), ...
    'A representably earlier deadline must expose no committed codes.');
zeroDeadline = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], 0);
assert(zeroDeadline.capture.timed_out && ...
    isempty(zeroDeadline.adc.committed_voltage_v), ...
    'A zero deadline must reject a positive-duration acquisition result.');
rolledBack = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], []);
assert(isequaln(rolledBack, clean), ...
    'Removing fault and deadline inputs must roll back exactly to baseline.');
retryAfterDeadline = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], Inf);
assert(isequaln(retryAfterDeadline, clean), ...
    'A clean retry after a rejected deadline must recover the exact baseline.');
% This finite pure calculation has no asynchronous wait or cancellation API.

%% Determinism, numeric/text compatibility, state isolation, and callbacks
first = model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3);
second = model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3);
assert(isequaln(first, second), ...
    'Repeated calls must be deterministic and state-isolated.');
compatible = model(uint16(180), uint16(1000), uint8(51), ...
    uint8(1), uint8(2), uint8(0), uint16(400), uint8(12), ...
    uint8(4), struct('mode', string('none')), []);
compatibleExpected = model(180, 1000, 51, 1, 2, 0, ...
    400, 12, 4);
assert(isequaln(compatible, compatibleExpected), ...
    'Supported numeric classes and scalar-string mode must normalize compatibly.');
explicitDefaults = model(180, 1000, 51, 1, 1.65, 0, ...
    400, 12, 3.3, [], []);
assert(isequaln(first, explicitDefaults), ...
    'Omitted and empty optional fault/deadline inputs must be compatible.');

callbackModel = @model;
callbackScenario = @p07_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.signal_frequency_hz, ...
    callbackInput.sample_rate_hz, callbackInput.sample_count, ...
    callbackInput.amplitude_v, callbackInput.offset_v, ...
    callbackInput.phase_rad, callbackInput.anti_alias_cutoff_hz, ...
    callbackInput.adc_bits, callbackInput.reference_voltage_v);
assert(callbackOut.frequency.alias_frequency_hz == 180 && ...
    callbackOut.capture.raw_payload_rate_bps == 12000, ...
    ['Callback-bound P07 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed input, fault schema, timing, and resource-bound rejection
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12), ...
    'P07:model:Arity');
assertReject(@() model('180', 1000, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SignalFrequency');
assertReject(@() model(-1, 1000, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SignalFrequency');
assertReject(@() model(NaN, 1000, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SignalFrequency');
assertReject(@() model(1i, 1000, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SignalFrequency');
assertReject(@() model(180, 0, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SampleRate');
assertReject(@() model(180, Inf, 51, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SampleRate');
assertReject(@() model(180, 1000, 1, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SampleCount');
assertReject(@() model(180, 1000, 2.5, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:SampleCount');
assertReject(@() model(180, 1000, 10001, 1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:ResourceBound');
assertReject(@() model(180, 1000, 51, -1, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:Amplitude');
assertReject(@() model(180, 1000, 51, 7, 1.65, 0, 400, 12, 3.3), ...
    'P07:model:Amplitude');
assertReject(@() model(180, 1000, 51, 1, -4, 0, 400, 12, 3.3), ...
    'P07:model:Offset');
assertReject(@() model(180, 1000, 51, 1, 7, 0, 400, 12, 3.3), ...
    'P07:model:Offset');
assertReject(@() model(180, 1000, 51, 1, 1.65, NaN, 400, 12, 3.3), ...
    'P07:model:Phase');
assertReject(@() model(180, 1000, 51, 1, 1.65, ...
    2 .* pi .* 1e6 + 1, 400, 12, 3.3), 'P07:model:Phase');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 0, 12, 3.3), ...
    'P07:model:AntiAliasCutoff');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, Inf, 12, 3.3), ...
    'P07:model:AntiAliasCutoff');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 1, 3.3), ...
    'P07:model:ADCBits');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12.5, 3.3), ...
    'P07:model:ADCBits');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 25, 3.3), ...
    'P07:model:ADCBits');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 0), ...
    'P07:model:ReferenceVoltage');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 1001), ...
    'P07:model:ReferenceVoltage');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    {'none'}, Inf), 'P07:model:Fault');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    struct(), Inf), 'P07:model:Fault');
extraFault = struct('mode', 'none', 'extra', 1);
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    extraFault, Inf), 'P07:model:Fault');
badMode = struct('mode', 'digital-filter');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    badMode, Inf), 'P07:model:FaultMode');
badModeType = struct('mode', {'none', 'anti-alias-bypass'});
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    badModeType, Inf), 'P07:model:Fault');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    [], -1), 'P07:model:AcquisitionDeadline');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    [], NaN), 'P07:model:AcquisitionDeadline');
assertReject(@() model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3, ...
    [], -Inf), 'P07:model:AcquisitionDeadline');
assertReject(@() model(0, 1e-3, 10000, 0, 1, 0, 400, 12, 3.3), ...
    'P07:model:TimingResourceBound');
assertReject(@() model(1e6, 1e6, 10000, 0, 1, 0, 400, 12, 3.3), ...
    'P07:model:ResourceBound');
largestFixture = p07_scenario('alias-trap', 10000);
largestAccepted = model(largestFixture.signal_frequency_hz, ...
    largestFixture.sample_rate_hz, largestFixture.sample_count, ...
    largestFixture.amplitude_v, largestFixture.offset_v, ...
    largestFixture.phase_rad, largestFixture.anti_alias_cutoff_hz, ...
    largestFixture.adc_bits, largestFixture.reference_voltage_v, ...
    largestFixture.fault, largestFixture.acquisition_deadline_s);
assert(numel(largestAccepted.samples.time_s) == 10000 && ...
    numel(largestAccepted.analog.reference_time_s) <= 200000, ...
    ['Every advertised scenario count through the accepted upper bound ' ...
    'must produce a resource-bounded fixture.']);
assertReject(@() p07_scenario({'baseline'}), 'P07:scenario:Kind');
assertReject(@() p07_scenario('baseline', 1), ...
    'P07:scenario:SampleCount');
assertReject(@() p07_scenario('baseline', 10001), ...
    'P07:scenario:SampleCount');
assertReject(@() p07_scenario('unknown'), 'P07:scenario:Kind');

afterRejection = model(180, 1000, 51, 1, 1.65, 0, 400, 12, 3.3);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('P07 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
