function out = model(eventReferenceUs, ppsSequenceId, ppsPeriodUs, ...
    clockOffsetUs, clockSkewPpm, timestampTickUs, ppsWaitTimeoutUs, ...
    timeoutAction, associationMode)
%MODEL Align quantized local timestamps to PPS reference coordinates.
%   The pure calculation owns no figures, UI, timers, hardware APIs, or
%   persistent state. PPS sequence identity determines the reference epoch.

if nargin ~= 9
    error('P15:model:Arity', 'model requires exactly nine inputs.');
end

maxEventCount = 10000;
maxPpsCount = 10000;
maxTimestampUs = 1e12;
maxTimestampTickIndex = 1e12;
eventReferenceUs = validateTimeVector(eventReferenceUs, ...
    'EventReference', maxEventCount, maxTimestampUs, false);
ppsSequenceId = validateSequenceIds(ppsSequenceId, maxPpsCount);
ppsPeriodUs = validatePositiveScalar(ppsPeriodUs, 'PpsPeriod');
clockOffsetUs = validateNonnegativeScalar(clockOffsetUs, 'ClockOffset');
clockSkewPpm = validateSkew(clockSkewPpm);
timestampTickUs = validatePositiveScalar(timestampTickUs, ...
    'TimestampTick');
ppsWaitTimeoutUs = validateTimeout(ppsWaitTimeoutUs);
timeoutAction = validateChoice(timeoutAction, 'TimeoutAction', ...
    {'continue-waiting', 'cancel-alignment'}, 'continue-waiting');
associationMode = validateChoice(associationMode, 'AssociationMode', ...
    {'sequence-id', 'arrival-index'}, 'sequence-id');
if ppsPeriodUs > maxTimestampUs || timestampTickUs > maxTimestampUs
    error('P15:model:TimelineResourceBound', ...
        'PPS period and timestamp tick must not exceed 1e12 us.');
end

clockRateRatio = 1 + clockSkewPpm .* 1e-6;
if ~isfinite(clockRateRatio) || clockRateRatio <= 0
    error('P15:model:ClockSkew', ...
        'clockSkewPpm must leave a positive finite local-clock rate.');
end

ppsTrueReferenceUs = ppsSequenceId .* ppsPeriodUs;
if any(~isfinite(ppsTrueReferenceUs)) || ...
        any(ppsTrueReferenceUs > maxTimestampUs)
    error('P15:model:TimelineResourceBound', ...
        'The PPS reference timeline exceeds the 1e12-us bound.');
end
if numel(ppsTrueReferenceUs) > 1 && ...
        any(diff(ppsTrueReferenceUs) <= 0)
    error('P15:model:PpsTimelinePrecision', ...
        'PPS sequence times collapse at double timestamp precision.');
end
if strcmp(associationMode, 'sequence-id')
    ppsAssumedReferenceUs = ppsTrueReferenceUs;
else
    ppsAssumedReferenceUs = ...
        (ppsSequenceId(1) + (0:numel(ppsSequenceId)-1)) .* ppsPeriodUs;
end
if any(~isfinite(ppsAssumedReferenceUs)) || ...
        any(ppsAssumedReferenceUs > maxTimestampUs)
    error('P15:model:TimelineResourceBound', ...
        'The assumed PPS timeline exceeds the 1e12-us bound.');
end

eventLocalIdealUs = clockOffsetUs + clockRateRatio .* eventReferenceUs;
ppsLocalIdealUs = clockOffsetUs + ...
    clockRateRatio .* ppsTrueReferenceUs;
validateDerivedClock(eventLocalIdealUs, ppsLocalIdealUs, maxTimestampUs);
eventLocalTimestampUs = quantizeDown(eventLocalIdealUs, timestampTickUs, ...
    maxTimestampTickIndex);
ppsLocalTimestampUs = quantizeDown(ppsLocalIdealUs, timestampTickUs, ...
    maxTimestampTickIndex);

% Derive elapsed gaps from identity deltas instead of subtracting absolute
% epoch coordinates, which can amplify cancellation away from epoch zero.
ppsGapUs = diff(ppsSequenceId) .* ppsPeriodUs;
lateGap = false(size(ppsGapUs));
if isfinite(ppsWaitTimeoutUs)
    gapForTimeoutComparisonUs = ppsGapUs;
    if ppsWaitTimeoutUs > 0
        timeoutBoundaryToleranceUs = eps(max( ...
            abs(ppsGapUs), abs(ppsWaitTimeoutUs)));
        nearTimeoutBoundary = abs(ppsGapUs - ppsWaitTimeoutUs) <= ...
            timeoutBoundaryToleranceUs;
        gapForTimeoutComparisonUs(nearTimeoutBoundary) = ppsWaitTimeoutUs;
    end
    lateGap = gapForTimeoutComparisonUs > ppsWaitTimeoutUs;
end
firstLateGap = find(lateGap, 1, 'first');
waitTimedOut = ~isempty(firstLateGap);
alignmentCancelled = waitTimedOut && ...
    strcmp(timeoutAction, 'cancel-alignment');
if alignmentCancelled
    retainedCount = firstLateGap;
else
    retainedCount = numel(ppsSequenceId);
end
retainedMask = false(size(ppsSequenceId));
retainedMask(1:retainedCount) = true;
censoredMask = ~retainedMask;

if waitTimedOut
    timeoutDeadlineUs = addBoundedTime( ...
        ppsTrueReferenceUs(firstLateGap), ppsWaitTimeoutUs, ...
        maxTimestampUs);
else
    timeoutDeadlineUs = Inf;
end

offsetOnlyEstimateUs = ppsLocalTimestampUs(1) - ...
    ppsAssumedReferenceUs(1);
eventOffsetOnlyUs = eventLocalTimestampUs - offsetOnlyEstimateUs;
offsetOnlyErrorUs = eventOffsetOnlyUs - eventReferenceUs;

alignmentAvailable = retainedCount >= 2;
estimatedRateRatio = NaN;
estimatedSkewPpm = NaN;
estimatedOffsetUs = NaN;
eventAlignedUs = nan(size(eventReferenceUs));
correctedErrorUs = nan(size(eventReferenceUs));
ppsFitResidualUs = nan(size(ppsSequenceId));
if alignmentAvailable
    retainedIndices = find(retainedMask);
    firstIndex = retainedIndices(1);
    lastIndex = retainedIndices(end);
    referenceSpanUs = ppsAssumedReferenceUs(lastIndex) - ...
        ppsAssumedReferenceUs(firstIndex);
    localSpanUs = ppsLocalTimestampUs(lastIndex) - ...
        ppsLocalTimestampUs(firstIndex);
    if ~(isfinite(referenceSpanUs) && referenceSpanUs > 0 && ...
            isfinite(localSpanUs) && localSpanUs > 0)
        error('P15:model:FitResolution', ...
            'Retained PPS anchors must span distinct reference and local ticks.');
    end
    estimatedRateRatio = localSpanUs ./ referenceSpanUs;
    estimatedOffsetUs = ppsLocalTimestampUs(firstIndex) - ...
        estimatedRateRatio .* ppsAssumedReferenceUs(firstIndex);
    estimatedSkewPpm = (estimatedRateRatio - 1) .* 1e6;
    if any(~isfinite([estimatedRateRatio, estimatedOffsetUs, ...
            estimatedSkewPpm])) || estimatedRateRatio <= 0
        error('P15:model:FitPrecision', ...
            'The affine PPS estimate is not positive and finite.');
    end
    eventAlignedUs = ...
        (eventLocalTimestampUs - estimatedOffsetUs) ./ estimatedRateRatio;
    correctedErrorUs = eventAlignedUs - eventReferenceUs;
    ppsFitResidualUs(retainedMask) = ppsLocalTimestampUs(retainedMask) - ...
        (estimatedOffsetUs + estimatedRateRatio .* ...
        ppsAssumedReferenceUs(retainedMask));
    if any(~isfinite(eventAlignedUs)) || ...
            any(~isfinite(ppsFitResidualUs(retainedMask)))
        error('P15:model:FitPrecision', ...
            'Aligned timestamps or PPS residuals are not finite.');
    end
end

rawErrorUs = eventLocalTimestampUs - eventReferenceUs;
associationConsistent = ...
    isequal(ppsAssumedReferenceUs, ppsTrueReferenceUs);
missingPpsCount = sum(diff(ppsSequenceId) - 1);
if isempty(ppsGapUs)
    maximumObservedGapUs = NaN;
else
    maximumObservedGapUs = max(ppsGapUs);
end

out.input = struct( ...
    'event_reference_us', eventReferenceUs, ...
    'pps_sequence_id', ppsSequenceId, ...
    'pps_period_us', ppsPeriodUs, ...
    'clock_offset_us', clockOffsetUs, ...
    'clock_skew_ppm', clockSkewPpm, ...
    'timestamp_tick_us', timestampTickUs, ...
    'pps_wait_timeout_us', ppsWaitTimeoutUs, ...
    'timeout_action', timeoutAction, ...
    'association_mode', associationMode);
out.clock = struct( ...
    'rate_ratio', clockRateRatio, ...
    'event_local_ideal_us', eventLocalIdealUs, ...
    'event_local_timestamp_us', eventLocalTimestampUs, ...
    'raw_error_us', rawErrorUs);
out.pps = struct( ...
    'true_reference_us', ppsTrueReferenceUs, ...
    'assumed_reference_us', ppsAssumedReferenceUs, ...
    'local_ideal_us', ppsLocalIdealUs, ...
    'local_timestamp_us', ppsLocalTimestampUs, ...
    'gap_us', ppsGapUs, ...
    'late_gap', lateGap, ...
    'retained', retainedMask, ...
    'censored', censoredMask, ...
    'fit_residual_us', ppsFitResidualUs);
out.alignment = struct( ...
    'available', alignmentAvailable, ...
    'estimated_rate_ratio', estimatedRateRatio, ...
    'estimated_skew_ppm', estimatedSkewPpm, ...
    'estimated_offset_us', estimatedOffsetUs, ...
    'event_aligned_us', eventAlignedUs, ...
    'corrected_error_us', correctedErrorUs, ...
    'offset_only_estimate_us', offsetOnlyEstimateUs, ...
    'event_offset_only_us', eventOffsetOnlyUs, ...
    'offset_only_error_us', offsetOnlyErrorUs);
out.observation = struct( ...
    'wait_timed_out', waitTimedOut, ...
    'alignment_cancelled', alignmentCancelled, ...
    'timeout_deadline_us', timeoutDeadlineUs, ...
    'retained_pps_count', retainedCount, ...
    'censored_pps_count', sum(censoredMask), ...
    'reference_last_pps_us', ppsTrueReferenceUs(end), ...
    'observed_last_pps_us', ppsTrueReferenceUs(retainedCount), ...
    'timeout_boundary_order', ...
    'a PPS capture at equality precedes timeout evaluation');
out.metrics = struct( ...
    'event_count', numel(eventReferenceUs), ...
    'received_pps_count', numel(ppsSequenceId), ...
    'missing_pps_count', missingPpsCount, ...
    'maximum_observed_gap_us', maximumObservedGapUs, ...
    'raw_start_error_us', rawErrorUs(1), ...
    'raw_end_error_us', rawErrorUs(end), ...
    'raw_maximum_absolute_error_us', max(abs(rawErrorUs)), ...
    'offset_only_maximum_absolute_error_us', ...
    max(abs(offsetOnlyErrorUs)), ...
    'corrected_maximum_absolute_error_us', ...
    maximumAbsoluteOrNaN(correctedErrorUs), ...
    'pps_fit_maximum_absolute_residual_us', ...
    maximumAbsoluteOrNaN(ppsFitResidualUs(retainedMask)), ...
    'association_consistent_with_sequence_identity', ...
    associationConsistent, ...
    'alignment_available', alignmentAvailable);
out.semantics = struct( ...
    'local_clock_equation', ...
    'C(t) = offset + (1 + skew_ppm * 1e-6) * t', ...
    'timestamp_rule', 'timestamp = tick * floor(C(t) / tick)', ...
    'pps_epoch_rule', 'reference PPS time = sequence ID * PPS period', ...
    'affine_inverse_rule', ...
    'aligned event = (local timestamp - estimated offset) / estimated rate', ...
    'association_rule', ...
    'sequence identity, not received array position, names the PPS epoch', ...
    'timeout_rule', ...
    'a gap strictly greater than timeout is late; equality captures first', ...
    'floating_boundary_rule', ...
    ['tick boundaries use eight quotient ULPs for the affine operation ' ...
    'chain only through a 1e12 absolute tick index; positive timeout ' ...
    'boundaries use one gap-scale ULP'], ...
    'cancellation_rule', ...
    'cancel alignment retains the prefix and censors later PPS captures');
out.claim_boundary = [ ...
    'Deterministic simulated affine-clock arithmetic only; not ' ...
    'MATLAB-runtime, rendered-UI, PPS receiver, GNSS epoch, oscillator, ' ...
    'interrupt-latency, timestamp-register, PTP, NTP, bench, HIL, field, ' ...
    'or production evidence.'];
end

function values = validateTimeVector(values, label, maximumCount, ...
    maximumTimeUs, allowEmpty)
valid = isnumeric(values) && ~islogical(values) && isreal(values) && ...
    isvector(values) && (allowEmpty || ~isempty(values)) && ...
    all(isfinite(values(:)));
if ~valid
    error(['P15:model:' label], ...
        '%s must be a nonempty finite real numeric vector.', label);
end
if numel(values) > maximumCount
    error(['P15:model:' label 'ResourceBound'], ...
        '%s exceeds the 10,000-value resource bound.', label);
end
if isa(values, 'uint64') && any(values(:) > uint64(flintmax))
    error(['P15:model:' label 'Precision'], ...
        '%s contains uint64 values above flintmax.', label);
end
if isa(values, 'int64') && ...
        (any(values(:) > int64(flintmax)) || ...
        any(values(:) < -int64(flintmax)))
    error(['P15:model:' label 'Precision'], ...
        '%s contains int64 values outside +/-flintmax.', label);
end
values = double(values(:)');
if any(values < 0) || any(values > maximumTimeUs)
    error(['P15:model:' label 'ResourceBound'], ...
        '%s must lie from 0 through 1e12 us.', label);
end
if numel(values) > 1 && any(diff(values) <= 0)
    error(['P15:model:' label 'Order'], ...
        '%s must be strictly increasing.', label);
end
end

function ids = validateSequenceIds(ids, maximumCount)
valid = isnumeric(ids) && ~islogical(ids) && isreal(ids) && ...
    isvector(ids) && ~isempty(ids) && all(isfinite(ids(:)));
if ~valid
    error('P15:model:PpsSequenceId', ...
        'ppsSequenceId must be a nonempty finite real numeric vector.');
end
if numel(ids) > maximumCount
    error('P15:model:PpsResourceBound', ...
        'ppsSequenceId exceeds the 10,000-PPS resource bound.');
end
if isa(ids, 'uint64') && any(ids(:) > uint64(flintmax))
    error('P15:model:PpsSequencePrecision', ...
        'uint64 PPS sequence IDs above flintmax cannot normalize exactly.');
end
if isa(ids, 'int64') && ...
        (any(ids(:) > int64(flintmax)) || ...
        any(ids(:) < 0))
    error('P15:model:PpsSequencePrecision', ...
        'int64 PPS sequence IDs must lie from 0 through flintmax.');
end
ids = double(ids(:)');
if any(ids < 0) || any(ids > flintmax) || any(ids ~= fix(ids))
    error('P15:model:PpsSequenceId', ...
        'PPS sequence IDs must be exact nonnegative integers.');
end
if numel(ids) > 1 && any(diff(ids) <= 0)
    error('P15:model:PpsSequenceOrder', ...
        'PPS sequence IDs must be unique and strictly increasing.');
end
end

function value = validatePositiveScalar(value, label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value > 0)
    error(['P15:model:' label], ...
        '%s must be a positive finite real numeric scalar.', label);
end
value = double(value);
end

function value = validateNonnegativeScalar(value, label)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && value >= 0)
    error(['P15:model:' label], ...
        '%s must be a nonnegative finite real numeric scalar.', label);
end
value = double(value);
end

function value = validateSkew(value)
if ~(isnumeric(value) && ~islogical(value) && isreal(value) && ...
        isscalar(value) && isfinite(value))
    error('P15:model:ClockSkew', ...
        'clockSkewPpm must be a finite real numeric scalar.');
end
value = double(value);
end

function timeoutUs = validateTimeout(timeoutUs)
if isempty(timeoutUs)
    timeoutUs = Inf;
end
valid = isnumeric(timeoutUs) && ~islogical(timeoutUs) && ...
    isreal(timeoutUs) && isscalar(timeoutUs) && ~isnan(timeoutUs) && ...
    timeoutUs >= 0;
if ~valid
    error('P15:model:PpsWaitTimeout', ...
        'ppsWaitTimeoutUs must be nonnegative; Inf disables timeout.');
end
timeoutUs = double(timeoutUs);
if isfinite(timeoutUs) && timeoutUs > 1e12
    error('P15:model:TimelineResourceBound', ...
        'ppsWaitTimeoutUs exceeds the 1e12-us bound.');
end
end

function choice = validateChoice(choice, label, choices, defaultChoice)
if isempty(choice)
    choice = defaultChoice;
end
if ~(ischar(choice) || (isstring(choice) && isscalar(choice)))
    error(['P15:model:' label], ...
        '%s must be a character vector or scalar string.', label);
end
choice = lower(strtrim(char(choice)));
if ~any(strcmp(choice, choices))
    error(['P15:model:' label], ...
        '%s is not a supported value.', label);
end
end

function validateDerivedClock(eventLocalUs, ppsLocalUs, maximumTimeUs)
allLocalUs = [eventLocalUs, ppsLocalUs];
if any(~isfinite(allLocalUs)) || any(allLocalUs < 0) || ...
        any(allLocalUs > maximumTimeUs)
    error('P15:model:TimestampResourceBound', ...
        'Derived local timestamps must lie from 0 through 1e12 us.');
end
end

function quantizedUs = quantizeDown(valueUs, tickUs, maximumTickIndex)
scaled = valueUs ./ tickUs;
if any(~isfinite(scaled))
    error('P15:model:TimestampPrecision', ...
        'Timestamp tick scaling is not finite.');
end
if any(scaled > maximumTickIndex)
    error('P15:model:TimestampPrecision', ...
        ['Timestamp tick indices above 1e12 exceed the transparent ' ...
        'floor-quantization precision bound.']);
end
% An exact decimal tick can accumulate a few representation ULPs across the
% affine multiply/add and division. Match P04's bounded eight-ULP operation-
% chain guard before flooring; this is not general round-to-nearest.
nearestInteger = round(scaled);
boundaryTolerance = 8 .* eps(max(abs(scaled), 1));
nearInteger = abs(scaled - nearestInteger) <= boundaryTolerance;
scaled(nearInteger) = nearestInteger(nearInteger);
quantizedUs = tickUs .* floor(scaled);
if any(~isfinite(quantizedUs))
    error('P15:model:TimestampPrecision', ...
        'Quantized timestamps are not finite.');
end
end

function deadlineUs = addBoundedTime(currentUs, deltaUs, maximumTimeUs)
deadlineUs = currentUs + deltaUs;
if ~isfinite(deadlineUs) || deadlineUs > maximumTimeUs
    error('P15:model:TimelineResourceBound', ...
        'The PPS timeout deadline exceeds the 1e12-us bound.');
end
if deltaUs > 0 && deadlineUs == currentUs
    error('P15:model:TimestampPrecision', ...
        'The positive PPS timeout collapses at timestamp precision.');
end
end

function value = maximumAbsoluteOrNaN(values)
if isempty(values) || all(isnan(values))
    value = NaN;
else
    value = max(abs(values(~isnan(values))));
end
end
