function run_checks()
%RUN_CHECKS Independent invariants for PPS and timestamp alignment.
%   Source checks remain distinct from MATLAB-runtime and physical evidence.

modelFcn = @model;
scenarioFcn = @p15_scenario;
runFixture = @(input) modelFcn(input.event_reference_us, ...
    input.pps_sequence_id, input.pps_period_us, ...
    input.clock_offset_us, input.clock_skew_ppm, ...
    input.timestamp_tick_us, input.pps_wait_timeout_us, ...
    input.timeout_action, input.association_mode);

%% Deterministic baseline and independent affine equations
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'The seedless P15 baseline must repeat exactly.');

referenceEventUs = 250000:500000:3750000;
referencePpsUs = (0:4) .* 1e6;
referenceRate = 1 + 40 .* 1e-6;
referenceEventLocalUs = floor((2500 + ...
    referenceRate .* referenceEventUs) ./ 1) .* 1;
referencePpsLocalUs = floor((2500 + ...
    referenceRate .* referencePpsUs) ./ 1) .* 1;
referenceRateEstimate = ...
    (referencePpsLocalUs(end) - referencePpsLocalUs(1)) ./ ...
    (referencePpsUs(end) - referencePpsUs(1));
referenceOffsetEstimateUs = referencePpsLocalUs(1) - ...
    referenceRateEstimate .* referencePpsUs(1);
referenceAlignedUs = ...
    (referenceEventLocalUs - referenceOffsetEstimateUs) ./ ...
    referenceRateEstimate;

assert(isequal(referencePpsLocalUs, ...
    [2500 1002540 2002580 3002620 4002660]) && ...
    isequal(clean.pps.local_timestamp_us, referencePpsLocalUs), ...
    'Baseline PPS timestamps changed.');
assert(isequal(referenceEventLocalUs, ...
    [252510 752530 1252550 1752570 2252590 2752610 3252630 3752650]) && ...
    isequal(clean.clock.event_local_timestamp_us, ...
    referenceEventLocalUs), ...
    'Baseline event timestamps changed.');
assert(isequal(clean.clock.raw_error_us, 2510:20:2650) && ...
    isequal(clean.alignment.offset_only_error_us, 10:20:150) && ...
    max(abs(referenceAlignedUs - referenceEventUs)) < 1e-9 && ...
    max(abs(clean.alignment.corrected_error_us)) < 1e-9 && ...
    max(abs(clean.pps.fit_residual_us)) < 1e-9, ...
    'Baseline raw, offset-only, aligned, or fit-residual values changed.');
assert(abs(referenceOffsetEstimateUs - 2500) < 1e-9 && ...
    abs((referenceRateEstimate - 1) .* 1e6 - 40) < 1e-9 && ...
    abs(clean.alignment.estimated_offset_us - 2500) < 1e-9 && ...
    abs(clean.alignment.estimated_skew_ppm - 40) < 1e-9 && ...
    clean.metrics.association_consistent_with_sequence_identity && ...
    clean.metrics.missing_pps_count == 0, ...
    'Independent baseline offset, skew, or association arithmetic changed.');

%% Sweep 1: initial clock offset only
offsetSweepUs = [0 1000 2500 5000 10000];
offsetFirstErrorUs = zeros(size(offsetSweepUs));
offsetFinalErrorUs = zeros(size(offsetSweepUs));
offsetEstimateUs = zeros(size(offsetSweepUs));
offsetCorrectedMaxUs = zeros(size(offsetSweepUs));
for sweepIndex = 1:numel(offsetSweepUs)
    input = fixture;
    input.clock_offset_us = offsetSweepUs(sweepIndex);
    swept = runFixture(input);
    offsetFirstErrorUs(sweepIndex) = swept.clock.raw_error_us(1);
    offsetFinalErrorUs(sweepIndex) = swept.clock.raw_error_us(end);
    offsetEstimateUs(sweepIndex) = swept.alignment.estimated_offset_us;
    offsetCorrectedMaxUs(sweepIndex) = ...
        swept.metrics.corrected_maximum_absolute_error_us;
    assert(swept.input.clock_skew_ppm == clean.input.clock_skew_ppm && ...
        swept.input.timestamp_tick_us == clean.input.timestamp_tick_us && ...
        isequal(swept.input.pps_sequence_id, ...
        clean.input.pps_sequence_id), ...
        'Offset sweep must isolate the additive clock translation.');
end
assert(isequal(offsetFirstErrorUs, ...
    [10 1010 2510 5010 10010]) && ...
    isequal(offsetFinalErrorUs, ...
    [150 1150 2650 5150 10150]) && ...
    isequal(offsetEstimateUs, offsetSweepUs) && ...
    max(offsetCorrectedMaxUs) < 1e-9, ...
    'Clock-offset sweep reference vectors changed.');

%% Sweep 2: reset, then oscillator skew only
skewSweepPpm = [-80 -40 0 40 80];
skewDriftUs = zeros(size(skewSweepPpm));
skewFinalErrorUs = zeros(size(skewSweepPpm));
skewOffsetOnlyMaxUs = zeros(size(skewSweepPpm));
skewEstimatePpm = zeros(size(skewSweepPpm));
skewCorrectedMaxUs = zeros(size(skewSweepPpm));
for sweepIndex = 1:numel(skewSweepPpm)
    input = fixture;
    input.clock_skew_ppm = skewSweepPpm(sweepIndex);
    swept = runFixture(input);
    skewDriftUs(sweepIndex) = ...
        (swept.pps.local_timestamp_us(end) - ...
        swept.pps.local_timestamp_us(1)) - 4e6;
    skewFinalErrorUs(sweepIndex) = swept.clock.raw_error_us(end);
    skewOffsetOnlyMaxUs(sweepIndex) = ...
        swept.metrics.offset_only_maximum_absolute_error_us;
    skewEstimatePpm(sweepIndex) = swept.alignment.estimated_skew_ppm;
    skewCorrectedMaxUs(sweepIndex) = ...
        swept.metrics.corrected_maximum_absolute_error_us;
    assert(swept.input.clock_offset_us == ...
        clean.input.clock_offset_us && ...
        swept.input.timestamp_tick_us == ...
        clean.input.timestamp_tick_us && ...
        isequal(swept.input.pps_sequence_id, ...
        clean.input.pps_sequence_id), ...
        'Skew sweep must reset and isolate oscillator rate.');
end
assert(isequal(skewDriftUs, [-320 -160 0 160 320]) && ...
    isequal(skewFinalErrorUs, [2200 2350 2500 2650 2800]) && ...
    isequal(skewOffsetOnlyMaxUs, [300 150 0 150 300]) && ...
    max(abs(skewEstimatePpm - skewSweepPpm)) < 1e-9 && ...
    max(skewCorrectedMaxUs) < 1e-9, ...
    'Oscillator-skew sweep reference vectors changed.');

%% Broken missing-PPS association and correct sequence identity
correctMissing = runFixture(scenarioFcn('missing-id-correct'));
broken = runFixture(scenarioFcn('broken-arrival-index'));
expectedBrokenErrorUs = ...
    [-62500 -187500 -312500 -437500 -562500 -687500 -812500 -937500];
expectedBrokenResidualUs = ...
    [0 666693.333333333 333346.666666667 0];
assert(correctMissing.metrics.missing_pps_count == 1 && ...
    correctMissing.metrics.association_consistent_with_sequence_identity && ...
    abs(correctMissing.alignment.estimated_offset_us - 2500) < 1e-9 && ...
    abs(correctMissing.alignment.estimated_skew_ppm - 40) < 1e-9 && ...
    max(abs(correctMissing.alignment.corrected_error_us)) < 1e-9, ...
    'Sequence identity must survive a missing PPS without rate bias.');
assert(broken.metrics.missing_pps_count == 1 && ...
    ~broken.metrics.association_consistent_with_sequence_identity && ...
    abs(broken.alignment.estimated_skew_ppm - ...
    333386.666666667) < 1e-6 && ...
    max(abs(broken.alignment.corrected_error_us - ...
    expectedBrokenErrorUs)) < 1e-6 && ...
    max(abs(broken.pps.fit_residual_us - ...
    expectedBrokenResidualUs)) < 1e-6, ...
    'Arrival-index association must expose the missing-epoch failure.');

%% PPS timeout equality, continuation, cancellation, rollback, recovery
equalityInput = scenarioFcn('missing-id-correct');
equalityInput.pps_wait_timeout_us = 2e6;
equalityInput.timeout_action = 'cancel-alignment';
equality = runFixture(equalityInput);
continued = runFixture(scenarioFcn('timeout-continue'));
cancelled = runFixture(scenarioFcn('timeout-cancel'));
assert(~equality.observation.wait_timed_out && ...
    ~equality.observation.alignment_cancelled && ...
    equality.observation.retained_pps_count == 4 && ...
    equality.alignment.available, ...
    'A PPS capture exactly at the wait deadline must pass.');
assert(continued.observation.wait_timed_out && ...
    ~continued.observation.alignment_cancelled && ...
    continued.observation.timeout_deadline_us == 1.5e6 && ...
    continued.observation.retained_pps_count == 4 && ...
    continued.observation.censored_pps_count == 0 && ...
    continued.alignment.available && ...
    max(abs(continued.alignment.corrected_error_us)) < 1e-9, ...
    'Continue-waiting must retain the late sequence-aware alignment.');
assert(cancelled.observation.wait_timed_out && ...
    cancelled.observation.alignment_cancelled && ...
    cancelled.observation.retained_pps_count == 1 && ...
    cancelled.observation.censored_pps_count == 3 && ...
    ~cancelled.alignment.available && ...
    isnan(cancelled.alignment.estimated_skew_ppm) && ...
    all(isnan(cancelled.alignment.corrected_error_us)) && ...
    isequal(cancelled.clock.event_local_timestamp_us, ...
    correctMissing.clock.event_local_timestamp_us), ...
    'Cancellation must censor anchors without changing raw timestamps.');

rollback = runFixture(fixture);
afterCancellation = runFixture(fixture);
assert(isequaln(rollback, clean) && isequaln(afterCancellation, clean), ...
    'Pure clean input must provide exact computational rollback and recovery.');

%% Limiting cases, quantization, and compatibility
zero = modelFcn([0 250000 500000], 0:2, 1e6, 0, 0, 1, ...
    Inf, 'continue-waiting', 'sequence-id');
assert(isequal(zero.clock.event_local_timestamp_us, [0 250000 500000]) && ...
    all(zero.clock.raw_error_us == 0) && ...
    zero.alignment.estimated_offset_us == 0 && ...
    zero.alignment.estimated_skew_ppm == 0 && ...
    all(zero.alignment.corrected_error_us == 0), ...
    'Zero offset and skew must reduce to the identity map.');

constantOffset = modelFcn([100 200 300], 0:2, 1000, 123, 0, 1, ...
    Inf, 'continue-waiting', 'sequence-id');
assert(isequal(constantOffset.clock.raw_error_us, [123 123 123]) && ...
    all(constantOffset.alignment.corrected_error_us == 0), ...
    'Zero skew must make raw error a constant offset.');

decimalBoundary = modelFcn([0.1 0.2 0.3], [0 3], 0.1, 0, 0, 0.1, ...
    Inf, 'continue-waiting', 'sequence-id');
decimalEventTicksUs = 0.1 .* (1:3);
decimalPpsTicksUs = 0.1 .* [0 3];
assert(isequal(decimalBoundary.clock.event_local_timestamp_us, ...
    decimalEventTicksUs) && ...
    isequal(decimalBoundary.pps.local_timestamp_us, decimalPpsTicksUs) && ...
    decimalBoundary.alignment.estimated_rate_ratio == 1 && ...
    decimalBoundary.alignment.estimated_skew_ppm == 0 && ...
    max(abs(decimalBoundary.alignment.corrected_error_us)) < eps(1), ...
    ['A decimal tick boundary must normalize bounded operation-chain ' ...
    'roundoff without losing a full timestamp tick.']);

affineOperationBoundary = modelFcn(3.5, [0 1], 3.5, ...
    0, 800000, 0.1, Inf, 'continue-waiting', 'sequence-id');
distinguishablyBelowTick = modelFcn(6.3 - 1e-10, [0 1], 1, ...
    0, 0, 0.1, Inf, 'continue-waiting', 'sequence-id');
assert(affineOperationBoundary.clock.event_local_timestamp_us == ...
    0.1 .* 63 && ...
    affineOperationBoundary.pps.local_timestamp_us(end) == 0.1 .* 63 && ...
    distinguishablyBelowTick.clock.event_local_timestamp_us == 0.1 .* 62, ...
    ['The eight-ULP affine operation-chain guard must retain an exact ' ...
    'tick but must not snap a distinguishably below-tick value upward.']);

largestTickIndex = modelFcn([0 1e12], [0 1], 1e12, ...
    0, 0, 1, Inf, 'continue-waiting', 'sequence-id');
ambiguousTickUs = (2^48 + 0.75) .* 1e-3;
ambiguousScaledTick = ambiguousTickUs ./ 1e-3;
unboundedToleranceTicks = 8 .* eps(max(abs(ambiguousScaledTick), 1));
unboundedRoundedUs = 1e-3 .* floor(round(ambiguousScaledTick));
assert(largestTickIndex.clock.event_local_timestamp_us(end) == 1e12 && ...
    largestTickIndex.alignment.estimated_rate_ratio == 1 && ...
    unboundedToleranceTicks >= 0.5 && ...
    unboundedRoundedUs > ambiguousTickUs, ...
    ['The accepted 1e12 tick-index boundary must execute, and the ' ...
    'unbounded eight-ULP policy must expose its upward-rounding hazard.']);
assertReject(@() modelFcn(ambiguousTickUs, [0 1], 1, ...
    0, 0, 1e-3, Inf, 'continue-waiting', 'sequence-id'), ...
    'P15:model:TimestampPrecision');

decimalTimeoutEquality = modelFcn([0.1 0.2 0.3], [0 3], 0.1, ...
    0, 0, 0.1, 0.3, 'cancel-alignment', 'sequence-id');
decimalTimeoutLate = modelFcn([0.1 0.2 0.3], [0 3], 0.1, ...
    0, 0, 0.1, 0.29, 'cancel-alignment', 'sequence-id');
strictPositiveSubnormalGap = modelFcn(realmin, [0 1], realmin, ...
    0, 0, realmin, 0, 'cancel-alignment', 'sequence-id');
higherEpochTimeoutEquality = modelFcn(4.05, [40 41], 0.1, ...
    0, 0, 0.1, 0.1, 'cancel-alignment', 'sequence-id');
adjacentTimeoutBoundary = modelFcn(0.1, [0 1], ...
    0.3 + eps(0.3), 0, 0, 0.1, 0.3, ...
    'cancel-alignment', 'sequence-id');
distinctTimeoutLate = modelFcn(0.1, [0 1], ...
    0.3 + 4 .* eps(0.3), 0, 0, 0.1, 0.3, ...
    'cancel-alignment', 'sequence-id');
assert(~decimalTimeoutEquality.observation.wait_timed_out && ...
    ~decimalTimeoutEquality.observation.alignment_cancelled && ...
    decimalTimeoutEquality.observation.retained_pps_count == 2 && ...
    decimalTimeoutLate.observation.wait_timed_out && ...
    decimalTimeoutLate.observation.alignment_cancelled && ...
    decimalTimeoutLate.observation.retained_pps_count == 1 && ...
    strictPositiveSubnormalGap.observation.wait_timed_out && ...
    strictPositiveSubnormalGap.observation.alignment_cancelled && ...
    ~higherEpochTimeoutEquality.observation.wait_timed_out && ...
    ~adjacentTimeoutBoundary.observation.wait_timed_out && ...
    distinctTimeoutLate.observation.wait_timed_out, ...
    ['Timeout gaps must use sequence deltas, normalize one local ULP at ' ...
    'a positive boundary, keep a strict positive subnormal gap at zero, ' ...
    'and keep distinguishable gaps late.']);

oneAnchor = modelFcn(fixture.event_reference_us, 0, 1e6, ...
    fixture.clock_offset_us, fixture.clock_skew_ppm, 1, Inf, ...
    'continue-waiting', 'sequence-id');
assert(~oneAnchor.alignment.available && ...
    isnan(oneAnchor.alignment.estimated_rate_ratio) && ...
    all(isnan(oneAnchor.alignment.corrected_error_us)) && ...
    isequal(oneAnchor.alignment.offset_only_error_us, 10:20:150), ...
    'One PPS anchor must expose offset-only correction but no rate estimate.');

twoAnchors = modelFcn(fixture.event_reference_us, [0 4], 1e6, ...
    2500, 40, 1, Inf, 'continue-waiting', 'sequence-id');
assert(twoAnchors.alignment.available && ...
    abs(twoAnchors.alignment.estimated_offset_us - 2500) < 1e-9 && ...
    abs(twoAnchors.alignment.estimated_skew_ppm - 40) < 1e-9 && ...
    max(abs(twoAnchors.alignment.corrected_error_us)) < 1e-9, ...
    'Two distinct ideal anchors must identify an affine clock.');

compatible = modelFcn(uint32(fixture.event_reference_us'), ...
    uint8(fixture.pps_sequence_id'), uint32(1e6), uint16(2500), ...
    int16(40), uint8(1), [], string('continue-waiting'), ...
    string('sequence-id'));
assert(isequaln(compatible, clean), ...
    'Column/integer/string/empty compatibility must normalize exactly.');
emptyDefaults = modelFcn(fixture.event_reference_us, ...
    fixture.pps_sequence_id, fixture.pps_period_us, ...
    fixture.clock_offset_us, fixture.clock_skew_ppm, ...
    fixture.timestamp_tick_us, [], [], []);
assert(isequaln(emptyDefaults, clean), ...
    'Empty timeout, action, and association must recover baseline defaults.');
stringScenario = scenarioFcn(string('baseline'));
assert(isequaln(stringScenario, fixture), ...
    'Scalar-string and character scenario names must agree.');
fixedOverride = scenarioFcn('broken-arrival-index', ...
    9999, -200, 100, 10, 'cancel-alignment', 'sequence-id');
assert(isequaln(fixedOverride, scenarioFcn('broken-arrival-index')), ...
    'Named diagnostics must replace every editable override.');

%% Callback lifetime and module isolation
callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
clear model;
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.event_reference_us, ...
    callbackInput.pps_sequence_id, callbackInput.pps_period_us, ...
    callbackInput.clock_offset_us, callbackInput.clock_skew_ppm, ...
    callbackInput.timestamp_tick_us, ...
    callbackInput.pps_wait_timeout_us, callbackInput.timeout_action, ...
    callbackInput.association_mode);
assert(isequaln(callbackOut, clean), ...
    ['Callback-bound P15 dependencies must survive module path cleanup ' ...
    'and a conflicting generic model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn(1, 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting'), 'P15:model:Arity');
assertReject(@() modelFcn([], 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:EventReference');
assertReject(@() modelFcn(true, 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:EventReference');
assertReject(@() modelFcn(1 + 1i, 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:EventReference');
assertReject(@() modelFcn(NaN, 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:EventReference');
assertReject(@() modelFcn(ones(2), 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:EventReference');
assertReject(@() modelFcn([0 0], 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:EventReferenceOrder');
assertReject(@() modelFcn(-1, 0, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:EventReferenceResourceBound');
assertReject(@() modelFcn(uint64(flintmax) + uint64(1), ...
    0, 1, 0, 0, 1, Inf, 'continue-waiting', 'sequence-id'), ...
    'P15:model:EventReferencePrecision');

assertReject(@() modelFcn(1, [], 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:PpsSequenceId');
assertReject(@() modelFcn(1, [0 0], 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:PpsSequenceOrder');
assertReject(@() modelFcn(1, [0 1.5], 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:PpsSequenceId');
assertReject(@() modelFcn(1, uint64(flintmax) + uint64(1), ...
    1, 0, 0, 1, Inf, 'continue-waiting', 'sequence-id'), ...
    'P15:model:PpsSequencePrecision');
assertReject(@() modelFcn(1, 0:1, 0, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:PpsPeriod');
assertReject(@() modelFcn(1, 0:1, 1, -1, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:ClockOffset');
assertReject(@() modelFcn(1, 0:1, 1, 0, -1e6, 1, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:ClockSkew');
assertReject(@() modelFcn(1, 0:1, 1, 0, 0, 0, Inf, ...
    'continue-waiting', 'sequence-id'), 'P15:model:TimestampTick');
assertReject(@() modelFcn(1, 0:1, 1, 0, 0, 1, -1, ...
    'continue-waiting', 'sequence-id'), 'P15:model:PpsWaitTimeout');
assertReject(@() modelFcn(1, 0:1, 1, 0, 0, 1, Inf, ...
    'flush', 'sequence-id'), 'P15:model:TimeoutAction');
assertReject(@() modelFcn(1, 0:1, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'zip-arrays'), 'P15:model:AssociationMode');

largestEvents = modelFcn(0:9999, 0:1, 1e6, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id');
assert(largestEvents.metrics.event_count == 10000 && ...
    largestEvents.alignment.available, ...
    'The accepted 10,000-event boundary must execute.');
assertReject(@() modelFcn(0:10000, 0:1, 1e6, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:EventReferenceResourceBound');
largestPps = modelFcn([0 1], 0:9999, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id');
assert(largestPps.metrics.received_pps_count == 10000 && ...
    largestPps.alignment.available, ...
    'The accepted 10,000-PPS boundary must execute.');
assertReject(@() modelFcn([0 1], 0:10000, 1, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:PpsResourceBound');
assertReject(@() modelFcn(1, [0 2], 1e12, 0, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:TimelineResourceBound');
assertReject(@() modelFcn(1e12, 0:1, 1, 1, 0, 1, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:TimestampResourceBound');
assertReject(@() modelFcn(1, [500000 500002], 1e6, 0, 0, 1, ...
    realmin, 'continue-waiting', 'sequence-id'), ...
    'P15:model:TimestampPrecision');
assertReject(@() modelFcn([0 1], 0:1, 1, 0, 0, 2, Inf, ...
    'continue-waiting', 'sequence-id'), ...
    'P15:model:FitResolution');

assertReject(@() scenarioFcn({'baseline'}), 'P15:scenario:Name');
assertReject(@() scenarioFcn('unknown'), 'P15:scenario:Name');
assertReject(@() scenarioFcn('baseline', -1), ...
    'P15:scenario:ClockOffset');
assertReject(@() scenarioFcn('baseline', 2500, 600000), ...
    'P15:scenario:ClockSkew');
assertReject(@() scenarioFcn('baseline', 2500, 40, 0), ...
    'P15:scenario:TimestampTick');
assertReject(@() scenarioFcn('baseline', 2500, 40, 1, -1), ...
    'P15:scenario:PpsWaitTimeout');
assertReject(@() scenarioFcn('baseline', 2500, 40, 1, Inf, ...
    'flush'), 'P15:scenario:TimeoutAction');
assertReject(@() scenarioFcn('baseline', 2500, 40, 1, Inf, ...
    'continue-waiting', 'zip-arrays'), ...
    'P15:scenario:AssociationMode');
assertReject(@() scenarioFcn('baseline', 2500, 40, 1, Inf, ...
    'continue-waiting', 'sequence-id', 1), 'P15:scenario:Arity');

afterMalformed = runFixture(fixture);
assert(isequaln(afterMalformed, clean), ...
    'Malformed or rejected calls must not contaminate clean recovery.');

disp(['P15 checks preserve PPS sequence identity, affine offset/rate ' ...
    'arithmetic, bounded tick-index precision, quantized timestamps, ' ...
    'and strict timeout equality.']);
disp(['Cancellation censors future anchors but cannot modify true or raw ' ...
    'event timestamps; recovery is a stateless model rerun.']);
disp(['Checks are deterministic calculations, not MATLAB-runtime, ' ...
    'rendered-UI, PPS/GNSS hardware, oscillator, bench, HIL, field, ' ...
    'or production evidence unless executed and retained on named systems.']);
disp('P15 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
