function interactive
%INTERACTIVE Explore P12 release jitter, response components, and censoring.

% launch_lesson removes this folder after the function returns. Bind P12's
% generic model and unique fixture helper now so retained callbacks cannot
% resolve another module's model.m after a later module switch.
modelFcn = @model;
scenarioFcn = @p12_scenario;

fig = uifigure('Name', ...
    'P12 Measure Jitter and Worst-Case Response Time', ...
    'Position', [10 25 1810 880]);
gridLayout = uigridlayout(fig, [5 9]);
gridLayout.RowHeight = {'1x', '1x', 135, 22, 42};
gridLayout.ColumnWidth = {'1x', '1x', '1x', '1x', ...
    '1x', '1x', '1.25x', '1.35x', '1.8x'};

releaseAxes = uiaxes(gridLayout);
releaseAxes.Layout.Row = 1;
releaseAxes.Layout.Column = [1 9];
responseAxes = uiaxes(gridLayout);
responseAxes.Layout.Row = 2;
responseAxes.Layout.Column = [1 9];
summary = uilabel(gridLayout, 'WordWrap', 'on');
summary.Layout.Row = 3;
summary.Layout.Column = [1 9];

makeLabel(gridLayout, 'Release-offset amplitude (ms)', 1);
makeLabel(gridLayout, 'P11 blocking bound (ms)', 2);
makeLabel(gridLayout, 'Nominal period (ms)', 3);
makeLabel(gridLayout, 'Own execution C (ms)', 4);
makeLabel(gridLayout, 'Relative deadline D (ms)', 5);
makeLabel(gridLayout, 'Timestamp tick (ms)', 6);
makeLabel(gridLayout, 'Response timeout (ms; 0=off)', 7);
makeLabel(gridLayout, 'Timeout action', 8);
makeLabel(gridLayout, 'Scenario', 9);

releaseAmplitudeControl = integerSpinner(gridLayout, [0 4], 1, 1);
blockingBudgetControl = integerSpinner(gridLayout, [0 5], 1, 2);
periodControl = integerSpinner(gridLayout, [10 100], 20, 3);
executionControl = integerSpinner(gridLayout, [0 10], 2, 4);
deadlineControl = integerSpinner(gridLayout, [1 50], 7, 5);
timestampTickControl = integerSpinner(gridLayout, [1 8], 1, 6);
responseTimeoutControl = integerSpinner(gridLayout, [0 50], 0, 7);
timeoutActionControl = uidropdown(gridLayout, ...
    'Items', {'Continue observing', 'Cancel observation'}, ...
    'Value', 'Continue observing');
timeoutActionControl.Layout.Row = 5;
timeoutActionControl.Layout.Column = 8;
scenarioControl = uidropdown(gridLayout, ...
    'Items', {'Editable baseline', ...
    'Completion spacing trap (fixed)', ...
    'Coarse timestamp clock (fixed)', ...
    'Response timeout continues (fixed)', ...
    'Cancel rare observation (fixed)', ...
    'Exact deadline boundary (fixed)'}, ...
    'Value', 'Editable baseline');
scenarioControl.Layout.Row = 5;
scenarioControl.Layout.Column = 9;

controls = {releaseAmplitudeControl, blockingBudgetControl, ...
    periodControl, executionControl, deadlineControl, ...
    timestampTickControl, responseTimeoutControl, ...
    timeoutActionControl};
for controlIndex = 1:numel(controls)
    controls{controlIndex}.ValueChangedFcn = @(~, ~) updateViews();
end
scenarioControl.ValueChangedFcn = @(~, ~) selectScenario();
selectScenario();

    function selectScenario
        for controlIndex = 1:numel(controls)
            controls{controlIndex}.Enable = 'on';
        end
        scenarioName = mapScenarioName(scenarioControl.Value);
        fixedInput = scenarioFcn(scenarioName, 1, 1, 20, 2, 7, 1);
        releaseAmplitudeControl.Value = ...
            max(abs(fixedInput.release_offset_ms));
        blockingBudgetControl.Value = max(fixedInput.blocking_ms);
        periodControl.Value = fixedInput.period_ms;
        executionControl.Value = fixedInput.execution_ms(1);
        deadlineControl.Value = fixedInput.deadline_ms;
        timestampTickControl.Value = fixedInput.timestamp_tick_ms;
        responseTimeoutControl.Value = ...
            timeoutControlValue(fixedInput.response_timeout_ms);
        timeoutActionControl.Value = ...
            timeoutActionLabel(fixedInput.timeout_action);
        if ~strcmp(scenarioControl.Value, 'Editable baseline')
            for controlIndex = 1:numel(controls)
                controls{controlIndex}.Enable = 'off';
            end
        end
        updateViews();
    end

    function updateViews
        scenarioName = mapScenarioName(scenarioControl.Value);
        input = scenarioFcn(scenarioName, ...
            releaseAmplitudeControl.Value, ...
            blockingBudgetControl.Value, periodControl.Value, ...
            executionControl.Value, deadlineControl.Value, ...
            timestampTickControl.Value);
        if strcmp(scenarioName, 'baseline')
            input.response_timeout_ms = ...
                timeoutFromControl(responseTimeoutControl.Value);
            input.timeout_action = ...
                timeoutActionFromLabel(timeoutActionControl.Value);
        end
        out = modelFcn(input.period_ms, input.job_count, ...
            input.release_offset_ms, input.execution_ms, ...
            input.blocking_ms, input.interference_ms, ...
            input.deadline_ms, input.timestamp_tick_ms, ...
            input.response_timeout_ms, input.timeout_action);

        cla(releaseAxes);
        stem(releaseAxes, out.timeline.job_id, ...
            out.reference.release_offset_ms, 'filled', ...
            'LineWidth', 1.3);
        hold(releaseAxes, 'on');
        plot(releaseAxes, out.timeline.job_id, ...
            out.measurement.release_offset_ms, 's--', ...
            'LineWidth', 1.3);
        hold(releaseAxes, 'off');
        grid(releaseAxes, 'on');
        xlabel(releaseAxes, 'Job (index)');
        ylabel(releaseAxes, 'Actual - nominal release (ms)');
        legend(releaseAxes, {'Reference release offset', ...
            'Timestamped release offset'}, 'Location', 'eastoutside');
        title(releaseAxes, sprintf([ ...
            'Release jitter p-p: reference %.1f ms, timestamped %.1f ms'], ...
            out.metrics.reference_release_jitter_pp_ms, ...
            out.metrics.measured_release_jitter_pp_ms));

        cla(responseAxes);
        bar(responseAxes, out.timeline.job_id, ...
            [out.input.blocking_ms(:) ...
            out.input.interference_ms(:) ...
            out.input.execution_ms(:)], 'stacked');
        hold(responseAxes, 'on');
        plot(responseAxes, out.timeline.job_id, ...
            out.measurement.response_ms, 'ko--', ...
            'LineWidth', 1.3, 'MarkerFaceColor', 'w');
        plot(responseAxes, out.timeline.job_id, ...
            out.deadline.deadline_ms .* ...
            ones(size(out.timeline.job_id)), 'r:', 'LineWidth', 1.5);
        hold(responseAxes, 'off');
        grid(responseAxes, 'on');
        xlabel(responseAxes, 'Job (index)');
        ylabel(responseAxes, 'Response time or component (ms)');
        legend(responseAxes, {'Blocking B', 'Interference I', ...
            'Execution C', 'Timestamped response', 'Deadline D'}, ...
            'Location', 'eastoutside');
        title(responseAxes, ...
            'R = f-a = B+I+C; NaN marks a censored observation');

        summary.Text = sprintf([ ...
            'Period %.0f ms; release amplitude %.0f ms; blocking bound ' ...
            '%.0f ms; execution %.0f ms; deadline %.0f ms; timestamp ' ...
            'tick %.0f ms. Reference release jitter p-p %.1f ms, ' ...
            'response jitter p-p %.1f ms, finite-fixture observed worst ' ...
            'response %.1f ms, component envelope %.1f ms, misses %.0f. ' ...
            'Timestamped observed max %.1f ms; retained %.0f/%.0f, ' ...
            'timeouts %.0f, censored %.0f, complete trace=%d. ' ...
            'Incomplete observed-worst lower bound %.1f ms. ' ...
            'A finite trace is not a WCRT guarantee; cancellation is ' ...
            'observation censoring, not task actuation. ' ...
            'Synthetic only: not MATLAB-runtime, RTOS, processor, ' ...
            'hardware, bench, HIL, ' ...
            'field, or production evidence.'], ...
            out.input.period_ms, ...
            max(abs(out.input.release_offset_ms)), ...
            max(out.input.blocking_ms), out.input.execution_ms(1), ...
            out.input.deadline_ms, out.input.timestamp_tick_ms, ...
            out.metrics.reference_release_jitter_pp_ms, ...
            out.metrics.reference_response_jitter_pp_ms, ...
            out.metrics.fixture_observed_worst_response_ms, ...
            out.metrics.component_response_envelope_ms, ...
            out.metrics.reference_deadline_miss_count, ...
            out.metrics.measured_observed_worst_response_ms, ...
            out.metrics.retained_count, out.metrics.job_count, ...
            out.metrics.timeout_count, out.metrics.censored_count, ...
            out.metrics.measured_observed_worst_is_complete_trace, ...
            out.metrics.incomplete_observed_worst_lower_bound_ms);
    end
end

function control = integerSpinner(gridLayout, limits, value, column)
control = uispinner(gridLayout, 'Limits', limits, 'Step', 1, ...
    'Value', value, 'RoundFractionalValues', 'on');
control.Layout.Row = 5;
control.Layout.Column = column;
end

function makeLabel(gridLayout, labelText, column)
label = uilabel(gridLayout, 'Text', labelText, ...
    'HorizontalAlignment', 'center');
label.Layout.Row = 4;
label.Layout.Column = column;
end

function name = mapScenarioName(displayName)
switch displayName
    case 'Editable baseline'
        name = 'baseline';
    case 'Completion spacing trap (fixed)'
        name = 'completion-jitter-trap';
    case 'Coarse timestamp clock (fixed)'
        name = 'coarse-clock';
    case 'Response timeout continues (fixed)'
        name = 'timeout-continue';
    case 'Cancel rare observation (fixed)'
        name = 'timeout-cancel';
    case 'Exact deadline boundary (fixed)'
        name = 'deadline-boundary';
    otherwise
        error('P12:interactive:Scenario', ...
            'Unknown interactive scenario.');
end
end

function timeoutMs = timeoutFromControl(value)
if value == 0
    timeoutMs = Inf;
else
    timeoutMs = value;
end
end

function value = timeoutControlValue(timeoutMs)
if isinf(timeoutMs)
    value = 0;
else
    value = timeoutMs;
end
end

function action = timeoutActionFromLabel(label)
if strcmp(label, 'Continue observing')
    action = 'continue-observing';
elseif strcmp(label, 'Cancel observation')
    action = 'cancel-observation';
else
    error('P12:interactive:TimeoutAction', ...
        'Unknown timeout action.');
end
end

function label = timeoutActionLabel(action)
if strcmp(action, 'continue-observing')
    label = 'Continue observing';
elseif strcmp(action, 'cancel-observation')
    label = 'Cancel observation';
else
    error('P12:interactive:TimeoutAction', ...
        'Scenario timeout action has no UI label.');
end
end
