function out = model(periodMs, jobCount, releaseOffsetMs, executionMs, ...
    blockingMs, interferenceMs, deadlineMs, timestampTickMs, ...
    responseTimeoutMs, timeoutAction)
%MODEL Measure release jitter and response time on a finite synthetic trace.
%   For job k, nominal release n_k, actual release a_k, first start s_k,
%   and completion f_k obey
%       j_k = a_k - n_k
%       R_k = f_k - a_k = B_k + I_k + C_k
%       L_k = f_k - n_k = j_k + R_k.
%   Peak-to-peak jitter is max(x)-min(x). The maximum response in this
%   finite fixture is an observed worst response, not a target WCRT proof.
%
%   Time-valued inputs and outputs use milliseconds. Each component vector
%   may be scalar or contain one entry per job. A finite response timeout
%   classifies R_k > timeout; equality completes at the boundary. The
%   cancel-observation action censors only the retained measurement. It
%   does not cancel a task or change any synthetic job timestamp.

if nargin ~= 10
    error('P12:model:Arity', [ ...
        'Expected periodMs, jobCount, releaseOffsetMs, executionMs, ' ...
        'blockingMs, interferenceMs, deadlineMs, timestampTickMs, ' ...
        'responseTimeoutMs, and timeoutAction.']);
end

maxJobs = 10000;
maxTimestampTicks = 1e12;

periodMs = validateFiniteScalar(periodMs, 'P12:model:Period', ...
    'periodMs');
jobCount = validateFiniteScalar(jobCount, 'P12:model:JobCount', ...
    'jobCount');
if periodMs <= 0
    error('P12:model:Period', 'periodMs must be strictly positive.');
end
if jobCount < 1 || jobCount ~= floor(jobCount)
    error('P12:model:JobCount', ...
        'jobCount must be a positive integer.');
end
if jobCount > maxJobs
    error('P12:model:JobResourceBound', ...
        'At most 10,000 jobs are allowed.');
end

releaseOffsetMs = validateFiniteVector(releaseOffsetMs, ...
    'P12:model:ReleaseOffset', 'releaseOffsetMs', maxJobs);
executionMs = validateFiniteVector(executionMs, ...
    'P12:model:Execution', 'executionMs', maxJobs);
blockingMs = validateFiniteVector(blockingMs, ...
    'P12:model:Blocking', 'blockingMs', maxJobs);
interferenceMs = validateFiniteVector(interferenceMs, ...
    'P12:model:Interference', 'interferenceMs', maxJobs);

releaseOffsetMs = expandPerJob(releaseOffsetMs, jobCount, ...
    'P12:model:ReleaseOffsetLength', 'releaseOffsetMs');
executionMs = expandPerJob(executionMs, jobCount, ...
    'P12:model:ExecutionLength', 'executionMs');
blockingMs = expandPerJob(blockingMs, jobCount, ...
    'P12:model:BlockingLength', 'blockingMs');
interferenceMs = expandPerJob(interferenceMs, jobCount, ...
    'P12:model:InterferenceLength', 'interferenceMs');

if any(executionMs < 0)
    error('P12:model:Execution', ...
        'executionMs values must be nonnegative.');
end
if any(blockingMs < 0)
    error('P12:model:Blocking', ...
        'blockingMs values must be nonnegative.');
end
if any(interferenceMs < 0)
    error('P12:model:Interference', ...
        'interferenceMs values must be nonnegative.');
end

deadlineMs = validateFiniteScalar(deadlineMs, ...
    'P12:model:Deadline', 'deadlineMs');
timestampTickMs = validateFiniteScalar(timestampTickMs, ...
    'P12:model:TimestampTick', 'timestampTickMs');
if deadlineMs <= 0
    error('P12:model:Deadline', ...
        'deadlineMs must be strictly positive.');
end
if timestampTickMs <= 0
    error('P12:model:TimestampTick', ...
        'timestampTickMs must be strictly positive.');
end

if isempty(responseTimeoutMs)
    responseTimeoutMs = Inf;
else
    responseTimeoutMs = validateTimeout(responseTimeoutMs);
end
if isempty(timeoutAction)
    timeoutAction = 'continue-observing';
else
    timeoutAction = normalizeText(timeoutAction, ...
        'P12:model:TimeoutAction', 'timeoutAction');
end
if ~any(strcmp(timeoutAction, ...
        {'continue-observing', 'cancel-observation'}))
    error('P12:model:TimeoutAction', ...
        ['timeoutAction must be continue-observing or ' ...
        'cancel-observation.']);
end

jobId = 1:jobCount;
nominalReleaseMs = (jobId - 1) .* periodMs;
actualReleaseMs = nominalReleaseMs + releaseOffsetMs;
if any(actualReleaseMs < 0)
    error('P12:model:ReleaseOrder', ...
        'Every actual release must be nonnegative.');
end
releaseOffsetCollapsed = ...
    (releaseOffsetMs > 0 & actualReleaseMs <= nominalReleaseMs) | ...
    (releaseOffsetMs < 0 & actualReleaseMs >= nominalReleaseMs);
if any(releaseOffsetCollapsed)
    error('P12:model:TimingPrecision', ...
        ['Absolute-time precision erased a nonzero release offset; ' ...
        'rescale the time origin or reject the record.']);
end
if jobCount > 1 && any(diff(actualReleaseMs) <= 0)
    error('P12:model:ReleaseOrder', ...
        'Actual releases must be strictly increasing by job ID.');
end

dispatchDelayMs = blockingMs + interferenceMs;
responseMs = dispatchDelayMs + executionMs;
startMs = actualReleaseMs + dispatchDelayMs;
completionMs = startMs + executionMs;
derivedTimes = [nominalReleaseMs actualReleaseMs startMs completionMs];
scaledTimes = derivedTimes ./ timestampTickMs;
componentResponseEnvelopeMs = max(blockingMs) + ...
    max(interferenceMs) + max(executionMs);
if any(~isfinite(dispatchDelayMs)) || any(~isfinite(responseMs)) || ...
        ~isfinite(componentResponseEnvelopeMs) || ...
        any(~isfinite(derivedTimes(:))) || any(~isfinite(scaledTimes(:))) || ...
        any(abs(scaledTimes(:)) > maxTimestampTicks)
    error('P12:model:TimingResourceBound', ...
        'Derived timestamps exceed the finite 1e12-tick model bound.');
end
relativeComponentCollapsed = ...
    (blockingMs > 0 & dispatchDelayMs <= interferenceMs) | ...
    (interferenceMs > 0 & dispatchDelayMs <= blockingMs) | ...
    (dispatchDelayMs > 0 & responseMs <= executionMs) | ...
    (executionMs > 0 & responseMs <= dispatchDelayMs);
absoluteAdvanceCollapsed = ...
    (dispatchDelayMs > 0 & startMs <= actualReleaseMs) | ...
    (executionMs > 0 & completionMs <= startMs) | ...
    (responseMs > 0 & completionMs <= actualReleaseMs);
if any(relativeComponentCollapsed) || any(absoluteAdvanceCollapsed)
    error('P12:model:TimingPrecision', ...
        ['Floating-point precision erased a positive timing component ' ...
        'or absolute-time advance; rescale the time origin.']);
end

nominalCompletionLatencyMs = releaseOffsetMs + responseMs;
releaseIdentityErrorMs = actualReleaseMs - nominalReleaseMs - ...
    releaseOffsetMs;
dispatchIdentityErrorMs = startMs - actualReleaseMs - dispatchDelayMs;
endToEndIdentityErrorMs = completionMs - nominalReleaseMs - ...
    nominalCompletionLatencyMs;
componentIdentityErrorMs = completionMs - actualReleaseMs - responseMs;

releaseScaledTick = actualReleaseMs ./ timestampTickMs;
startScaledTick = startMs ./ timestampTickMs;
completionScaledTick = completionMs ./ timestampTickMs;
captureScaledMagnitude = max(ones(1, jobCount), ...
    max(abs(releaseScaledTick), ...
    max(abs(startScaledTick), abs(completionScaledTick))));
captureComparisonToleranceTicks = 8 .* eps(captureScaledMagnitude);
[releaseTimestampMs, releaseQuantizationErrorMs, releaseTick] = ...
    captureTimestamp(actualReleaseMs, timestampTickMs, ...
    captureComparisonToleranceTicks);
[startTimestampMs, startQuantizationErrorMs, startTick] = ...
    captureTimestamp(startMs, timestampTickMs, ...
    captureComparisonToleranceTicks);
[completionTimestampRawMs, completionQuantizationErrorRawMs, ...
    completionTickRaw] = captureTimestamp(completionMs, timestampTickMs, ...
    captureComparisonToleranceTicks);
rawCaptureValues = [captureComparisonToleranceTicks releaseTick ...
    startTick completionTickRaw releaseTimestampMs startTimestampMs ...
    completionTimestampRawMs releaseQuantizationErrorMs ...
    startQuantizationErrorMs completionQuantizationErrorRawMs];
if any(~isfinite(rawCaptureValues(:)))
    error('P12:model:TimingResourceBound', ...
        'Timestamp capture produced a nonfinite derived value.');
end

waitTimedOut = false(1, jobCount);
if isfinite(responseTimeoutMs)
    waitTimedOut = responseMs > responseTimeoutMs;
end
censored = waitTimedOut & strcmp(timeoutAction, ...
    'cancel-observation');
retained = ~censored;

completionTimestampMs = completionTimestampRawMs;
completionTimestampMs(censored) = NaN;
completionTick = completionTickRaw;
completionTick(censored) = NaN;
completionQuantizationErrorMs = completionQuantizationErrorRawMs;
completionQuantizationErrorMs(censored) = NaN;
measuredReleaseOffsetMs = releaseTimestampMs - nominalReleaseMs;
measuredDispatchDelayMs = startTimestampMs - releaseTimestampMs;
measuredResponseMs = completionTimestampMs - releaseTimestampMs;
measuredNominalLatencyMs = completionTimestampMs - nominalReleaseMs;
responseMeasurementErrorMs = measuredResponseMs - responseMs;

if jobCount > 1
    referenceCompletionIntervalDeviationMs = ...
        diff(completionMs) - periodMs;
    completionIntervalDeviationMs = ...
        diff(completionTimestampMs) - periodMs;
    referenceCompletionIdentityErrorMs = ...
        referenceCompletionIntervalDeviationMs - ...
        (diff(releaseOffsetMs) + diff(responseMs));
else
    referenceCompletionIntervalDeviationMs = zeros(1, 0);
    completionIntervalDeviationMs = zeros(1, 0);
    referenceCompletionIdentityErrorMs = zeros(1, 0);
end
referenceDiagnostics = [nominalCompletionLatencyMs ...
    releaseIdentityErrorMs dispatchIdentityErrorMs ...
    endToEndIdentityErrorMs componentIdentityErrorMs ...
    referenceCompletionIntervalDeviationMs ...
    referenceCompletionIdentityErrorMs];
measurementDiagnostics = [measuredReleaseOffsetMs ...
    measuredDispatchDelayMs measuredResponseMs ...
    measuredNominalLatencyMs responseMeasurementErrorMs ...
    completionIntervalDeviationMs];
if any(~isfinite(referenceDiagnostics(:))) || ...
        any(isinf(measurementDiagnostics(:)))
    error('P12:model:TimingResourceBound', ...
        'A derived timing diagnostic exceeded finite numeric range.');
end

referenceDeadlineMarginMs = deadlineMs - responseMs;
referenceDeadlineMiss = responseMs > deadlineMs;
measuredDeadlineMarginMs = deadlineMs - measuredResponseMs;
measuredDeadlineEvaluable = retained;
measuredDeadlineMiss = retained & measuredResponseMs > deadlineMs;

prefixObservedWorstResponseMs = zeros(1, jobCount);
prefixObservedWorstResponseMs(1) = responseMs(1);
for prefixIndex = 2:jobCount
    prefixObservedWorstResponseMs(prefixIndex) = max( ...
        prefixObservedWorstResponseMs(prefixIndex - 1), ...
        responseMs(prefixIndex));
end

fixtureWorstResponseMs = max(responseMs);
retainedObservedWorstResponseMs = finiteMaximum(measuredResponseMs);
if any(censored)
    incompleteWorstLowerBoundMs = responseTimeoutMs;
    if isfinite(retainedObservedWorstResponseMs)
        incompleteWorstLowerBoundMs = max( ...
            incompleteWorstLowerBoundMs, ...
            max(0, retainedObservedWorstResponseMs - ...
            timestampTickMs));
    end
else
    incompleteWorstLowerBoundMs = NaN;
end

out = struct();
out.input = struct( ...
    'period_ms', periodMs, ...
    'job_count', jobCount, ...
    'release_offset_ms', releaseOffsetMs, ...
    'execution_ms', executionMs, ...
    'blocking_ms', blockingMs, ...
    'interference_ms', interferenceMs, ...
    'deadline_ms', deadlineMs, ...
    'timestamp_tick_ms', timestampTickMs, ...
    'response_timeout_ms', responseTimeoutMs, ...
    'timeout_action', timeoutAction);
out.timeline = struct( ...
    'job_id', jobId, ...
    'nominal_release_ms', nominalReleaseMs, ...
    'actual_release_ms', actualReleaseMs, ...
    'start_ms', startMs, ...
    'completion_ms', completionMs);
out.reference = struct( ...
    'release_offset_ms', releaseOffsetMs, ...
    'dispatch_delay_ms', dispatchDelayMs, ...
    'response_ms', responseMs, ...
    'nominal_completion_latency_ms', nominalCompletionLatencyMs, ...
    'completion_interval_deviation_ms', ...
        referenceCompletionIntervalDeviationMs, ...
    'deadline_margin_ms', referenceDeadlineMarginMs, ...
    'deadline_miss', referenceDeadlineMiss, ...
    'prefix_observed_worst_response_ms', ...
        prefixObservedWorstResponseMs, ...
    'release_identity_error_ms', releaseIdentityErrorMs, ...
    'dispatch_identity_error_ms', dispatchIdentityErrorMs, ...
    'end_to_end_identity_error_ms', endToEndIdentityErrorMs, ...
    'component_identity_error_ms', componentIdentityErrorMs, ...
    'completion_identity_error_ms', ...
        referenceCompletionIdentityErrorMs);
out.capture = struct( ...
    'normalization_tolerance_ticks', ...
        captureComparisonToleranceTicks, ...
    'normalization_tolerance_ms', ...
        captureComparisonToleranceTicks .* timestampTickMs, ...
    'release_tick', releaseTick, ...
    'start_tick', startTick, ...
    'completion_tick', completionTick, ...
    'release_timestamp_ms', releaseTimestampMs, ...
    'start_timestamp_ms', startTimestampMs, ...
    'completion_timestamp_ms', completionTimestampMs, ...
    'release_quantization_error_ms', releaseQuantizationErrorMs, ...
    'start_quantization_error_ms', startQuantizationErrorMs, ...
    'completion_quantization_error_ms', ...
        completionQuantizationErrorMs);
out.measurement = struct( ...
    'release_offset_ms', measuredReleaseOffsetMs, ...
    'dispatch_delay_ms', measuredDispatchDelayMs, ...
    'response_ms', measuredResponseMs, ...
    'nominal_completion_latency_ms', measuredNominalLatencyMs, ...
    'completion_interval_deviation_ms', ...
        completionIntervalDeviationMs, ...
    'response_error_ms', responseMeasurementErrorMs, ...
    'retained', retained, ...
    'wait_timed_out', waitTimedOut, ...
    'censored', censored);
out.deadline = struct( ...
    'deadline_ms', deadlineMs, ...
    'reference_margin_ms', referenceDeadlineMarginMs, ...
    'reference_miss', referenceDeadlineMiss, ...
    'measured_margin_ms', measuredDeadlineMarginMs, ...
    'measured_evaluable', measuredDeadlineEvaluable, ...
    'measured_miss', measuredDeadlineMiss);
out.metrics = struct( ...
    'job_count', jobCount, ...
    'reference_release_jitter_pp_ms', finiteRange(releaseOffsetMs), ...
    'reference_release_jitter_max_abs_ms', ...
        max(abs(releaseOffsetMs)), ...
    'reference_response_jitter_pp_ms', finiteRange(responseMs), ...
    'fixture_observed_worst_response_ms', fixtureWorstResponseMs, ...
    'component_response_envelope_ms', componentResponseEnvelopeMs, ...
    'reference_deadline_miss_count', sum(referenceDeadlineMiss), ...
    'measured_release_jitter_pp_ms', ...
        finiteRange(measuredReleaseOffsetMs), ...
    'measured_response_jitter_pp_ms', finiteRange(measuredResponseMs), ...
    'measured_observed_worst_response_ms', ...
        retainedObservedWorstResponseMs, ...
    'measured_response_mean_ms', finiteMean(measuredResponseMs), ...
    'retained_count', sum(retained), ...
    'timeout_count', sum(waitTimedOut), ...
    'censored_count', sum(censored), ...
    'measured_observed_worst_is_complete_trace', ~any(censored), ...
    'incomplete_observed_worst_lower_bound_ms', ...
        incompleteWorstLowerBoundMs, ...
    'finite_trace_is_wcrt_guarantee', false, ...
    'max_abs_response_measurement_error_ms', ...
        finiteMaximum(abs(responseMeasurementErrorMs)), ...
    'timestamp_interval_error_bound_ms', timestampTickMs, ...
    'release_identity_max_error_ms', ...
        finiteMaximum(abs(releaseIdentityErrorMs)), ...
    'dispatch_identity_max_error_ms', ...
        finiteMaximum(abs(dispatchIdentityErrorMs)), ...
    'end_to_end_identity_max_error_ms', ...
        finiteMaximum(abs(endToEndIdentityErrorMs)), ...
    'component_identity_max_error_ms', ...
        finiteMaximum(abs(componentIdentityErrorMs)), ...
    'completion_identity_max_error_ms', ...
        finiteMaximum(abs(referenceCompletionIdentityErrorMs)));
out.claim_boundary = [ ...
    'Finite deterministic timestamp arithmetic; not MATLAB-runtime, ' ...
    'RTOS, processor, hardware, bench, HIL, field, or production evidence.'];
end

function values = validateFiniteVector(values, identifier, label, maxCount)
validType = isnumeric(values) && ~islogical(values) && isreal(values) && ...
    (isvector(values) || isempty(values));
if ~validType
    error(identifier, '%s must be a real numeric vector.', label);
end
if numel(values) > maxCount
    error('P12:model:JobResourceBound', ...
        'Per-job inputs may contain at most 10,000 values.');
end
values = reshape(double(values), 1, []);
if isempty(values) || any(~isfinite(values))
    error(identifier, '%s values must be finite and nonempty.', label);
end
end

function value = validateFiniteScalar(value, identifier, label)
validValue = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && isfinite(value);
if ~validValue
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function timeoutMs = validateTimeout(timeoutMs)
validValue = isnumeric(timeoutMs) && ~islogical(timeoutMs) && ...
    isreal(timeoutMs) && isscalar(timeoutMs) && ...
    (isfinite(timeoutMs) || isinf(timeoutMs));
if ~validValue || isnan(timeoutMs) || timeoutMs <= 0
    error('P12:model:ResponseTimeout', ...
        'responseTimeoutMs must be positive, Inf, or empty.');
end
timeoutMs = double(timeoutMs);
end

function values = expandPerJob(values, jobCount, identifier, label)
if isscalar(values)
    values = repmat(values, 1, jobCount);
elseif numel(values) ~= jobCount
    error(identifier, ...
        '%s must be scalar or have one value per job.', label);
end
end

function value = normalizeText(value, identifier, label)
validCharacter = ischar(value) && isrow(value);
validString = isstring(value) && isscalar(value) && ~ismissing(value);
if ~validCharacter && ~validString
    error(identifier, '%s must be a character vector or scalar string.', ...
        label);
end
value = char(value);
end

function [timestampMs, errorMs, tick] = captureTimestamp(timeMs, tickMs, ...
    comparisonToleranceTicks)
% Share one tolerance across each job's release/start/completion captures.
scaledTick = timeMs ./ tickMs;
nearestTick = round(scaledTick);
snapToBoundary = abs(scaledTick - nearestTick) <= ...
    comparisonToleranceTicks;
scaledTick(snapToBoundary) = nearestTick(snapToBoundary);
tick = floor(scaledTick);
timestampMs = tick .* tickMs;
errorMs = timestampMs - timeMs;
end

function value = finiteMaximum(values)
values = values(~isnan(values));
if isempty(values)
    value = NaN;
elseif any(isinf(values))
    error('P12:model:TimingResourceBound', ...
        'An aggregate input exceeded finite numeric range.');
else
    value = max(values);
end
end

function value = finiteRange(values)
values = values(~isnan(values));
if isempty(values)
    value = NaN;
elseif any(isinf(values))
    error('P12:model:TimingResourceBound', ...
        'An aggregate input exceeded finite numeric range.');
else
    value = max(values) - min(values);
    if ~isfinite(value)
        error('P12:model:TimingResourceBound', ...
            'An aggregate range exceeded finite numeric range.');
    end
end
end

function value = finiteMean(values)
values = values(~isnan(values));
if isempty(values)
    value = NaN;
elseif any(isinf(values))
    error('P12:model:TimingResourceBound', ...
        'An aggregate input exceeded finite numeric range.');
else
    scale = max(abs(values));
    if scale == 0
        value = 0;
    else
        value = scale .* (sum(values ./ scale) ./ numel(values));
    end
    if ~isfinite(value)
        error('P12:model:TimingResourceBound', ...
            'An aggregate mean exceeded finite numeric range.');
    end
end
end
