function run_checks
%RUN_CHECKS Verify P12 timestamp identities, jitter, censoring, and bounds.

modelFcn = @model;
scenarioFcn = @p12_scenario;
runFixture = @(fixture) modelFcn(fixture.period_ms, ...
    fixture.job_count, fixture.release_offset_ms, ...
    fixture.execution_ms, fixture.blocking_ms, ...
    fixture.interference_ms, fixture.deadline_ms, ...
    fixture.timestamp_tick_ms, fixture.response_timeout_ms, ...
    fixture.timeout_action);
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);

%% Deterministic baseline and independent timing identities
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'Repeated baseline calls must be deterministic and state-isolated.');
assert(isequal(clean.timeline.job_id, 1:8), ...
    'Baseline job IDs changed.');
assert(isequal(clean.timeline.nominal_release_ms, ...
    [0 20 40 60 80 100 120 140]), ...
    'Nominal release grid changed.');
assert(isequal(clean.timeline.actual_release_ms, ...
    [0 21 39 60 81 99 120 141]), ...
    'Actual release timestamps changed.');
assert(isequal(clean.timeline.start_ms, ...
    [0 22 40 61 83 100 121 145]), ...
    'First-start timestamps changed.');
assert(isequal(clean.timeline.completion_ms, ...
    [2 24 42 63 85 102 123 147]), ...
    'Completion timestamps changed.');
assert(all(clean.timeline.start_ms >= ...
    clean.timeline.actual_release_ms) && ...
    all(clean.timeline.completion_ms >= clean.timeline.start_ms), ...
    'Every job must start after release and complete after start.');
assert(isequal(clean.reference.release_offset_ms, ...
    clean.timeline.actual_release_ms - ...
    clean.timeline.nominal_release_ms), ...
    'Release offset must equal a-n.');
assert(isequal(clean.reference.response_ms, ...
    clean.timeline.completion_ms - ...
    clean.timeline.actual_release_ms), ...
    'Response must equal f-a.');
assert(isequal(clean.reference.response_ms, ...
    clean.input.blocking_ms + clean.input.interference_ms + ...
    clean.input.execution_ms), ...
    'Response must decompose independently as B+I+C.');
assert(isequal(clean.reference.nominal_completion_latency_ms, ...
    clean.reference.release_offset_ms + clean.reference.response_ms), ...
    'Nominal completion latency must equal j+R.');
assert(all(clean.reference.release_identity_error_ms == 0) && ...
    all(clean.reference.dispatch_identity_error_ms == 0) && ...
    all(clean.reference.end_to_end_identity_error_ms == 0) && ...
    all(clean.reference.component_identity_error_ms == 0) && ...
    all(clean.reference.completion_identity_error_ms == 0), ...
    'All independent baseline identities must close exactly.');
assert(isequal(clean.reference.response_ms, [2 3 3 3 4 3 3 6]), ...
    'Baseline response vector changed.');
assert(isequal(clean.reference.nominal_completion_latency_ms, ...
    [2 4 2 3 5 2 3 7]), ...
    'Baseline nominal-latency vector changed.');
assert(clean.metrics.reference_release_jitter_pp_ms == 2 && ...
    clean.metrics.reference_release_jitter_max_abs_ms == 1, ...
    'Baseline release-jitter statistics changed.');
assert(clean.metrics.reference_response_jitter_pp_ms == 4 && ...
    clean.metrics.fixture_observed_worst_response_ms == 6, ...
    'Baseline response-jitter or observed maximum changed.');
assert(clean.metrics.component_response_envelope_ms == 6 && ...
    clean.metrics.fixture_observed_worst_response_ms <= ...
    clean.metrics.component_response_envelope_ms, ...
    'Finite-fixture responses must remain inside the component envelope.');
assert(isequal(clean.reference.prefix_observed_worst_response_ms, ...
    [2 3 3 3 4 4 4 6]) && ...
    all(diff(clean.reference.prefix_observed_worst_response_ms) >= 0), ...
    'A longer prefix must never lower its observed maximum.');
assert(clean.metrics.reference_deadline_miss_count == 0 && ...
    ~any(clean.deadline.reference_miss) && ...
    min(clean.deadline.reference_margin_ms) == 1, ...
    'Baseline deadline classification changed.');
assert(clean.metrics.retained_count == 8 && ...
    clean.metrics.timeout_count == 0 && ...
    clean.metrics.censored_count == 0 && ...
    clean.metrics.measured_observed_worst_is_complete_trace, ...
    'The baseline must retain a complete uncensored trace.');
assert(~clean.metrics.finite_trace_is_wcrt_guarantee, ...
    'A finite trace must never advertise a WCRT guarantee.');
assert(isequal(clean.capture.release_timestamp_ms, ...
    clean.timeline.actual_release_ms) && ...
    isequal(clean.capture.start_timestamp_ms, ...
    clean.timeline.start_ms) && ...
    isequal(clean.capture.completion_timestamp_ms, ...
    clean.timeline.completion_ms), ...
    'One-millisecond aligned baseline captures must be exact.');
assert(clean.metrics.max_abs_response_measurement_error_ms == 0 && ...
    clean.metrics.timestamp_interval_error_bound_ms == 1, ...
    'Aligned baseline timestamp error changed.');

%% Sweep 1 isolates release offset from response
releaseAmplitudeSweepMs = [0 1 2 3];
releaseJitterPpMs = zeros(size(releaseAmplitudeSweepMs));
releaseSweepWorstResponseMs = zeros(size(releaseAmplitudeSweepMs));
releaseSweepResponseJitterMs = zeros(size(releaseAmplitudeSweepMs));
releaseSweepNominalLatencyMs = zeros(size(releaseAmplitudeSweepMs));
for sweepIndex = 1:numel(releaseAmplitudeSweepMs)
    sweptInput = scenarioFcn('baseline', ...
        releaseAmplitudeSweepMs(sweepIndex), 1, 20, 2, 7, 1);
    swept = runFixture(sweptInput);
    releaseJitterPpMs(sweepIndex) = ...
        swept.metrics.reference_release_jitter_pp_ms;
    releaseSweepWorstResponseMs(sweepIndex) = ...
        swept.metrics.fixture_observed_worst_response_ms;
    releaseSweepResponseJitterMs(sweepIndex) = ...
        swept.metrics.reference_response_jitter_pp_ms;
    releaseSweepNominalLatencyMs(sweepIndex) = ...
        max(swept.reference.nominal_completion_latency_ms);
    assert(isequal(swept.input.blocking_ms, clean.input.blocking_ms) && ...
        isequal(swept.input.interference_ms, ...
        clean.input.interference_ms) && ...
        isequal(swept.input.execution_ms, clean.input.execution_ms) && ...
        swept.input.period_ms == clean.input.period_ms && ...
        swept.input.deadline_ms == clean.input.deadline_ms && ...
        swept.input.timestamp_tick_ms == ...
        clean.input.timestamp_tick_ms && ...
        swept.input.response_timeout_ms == ...
        clean.input.response_timeout_ms && ...
        strcmp(swept.input.timeout_action, clean.input.timeout_action), ...
        'Release sweep must isolate its one input.');
end
assert(isequal(releaseJitterPpMs, [0 2 4 6]), ...
    'Release-jitter sweep reference changed.');
assert(isequal(releaseSweepWorstResponseMs, [6 6 6 6]) && ...
    isequal(releaseSweepResponseJitterMs, [4 4 4 4]), ...
    'Own release offset must not enter R=f-a.');
assert(isequal(releaseSweepNominalLatencyMs, [6 7 8 9]), ...
    'Own release offset must enter L=f-n.');

%% Sweep 2 isolates P11 bounded blocking
blockingBudgetSweepMs = [0 1 2 3];
blockingWorstResponseMs = zeros(size(blockingBudgetSweepMs));
blockingResponseJitterMs = zeros(size(blockingBudgetSweepMs));
blockingReleaseJitterMs = zeros(size(blockingBudgetSweepMs));
blockingDeadlineMissCount = zeros(size(blockingBudgetSweepMs));
for sweepIndex = 1:numel(blockingBudgetSweepMs)
    sweptInput = scenarioFcn('baseline', 1, ...
        blockingBudgetSweepMs(sweepIndex), 20, 2, 7, 1);
    swept = runFixture(sweptInput);
    blockingWorstResponseMs(sweepIndex) = ...
        swept.metrics.fixture_observed_worst_response_ms;
    blockingResponseJitterMs(sweepIndex) = ...
        swept.metrics.reference_response_jitter_pp_ms;
    blockingReleaseJitterMs(sweepIndex) = ...
        swept.metrics.reference_release_jitter_pp_ms;
    blockingDeadlineMissCount(sweepIndex) = ...
        swept.metrics.reference_deadline_miss_count;
    assert(isequal(swept.input.release_offset_ms, ...
        clean.input.release_offset_ms) && ...
        isequal(swept.input.interference_ms, ...
        clean.input.interference_ms) && ...
        isequal(swept.input.execution_ms, clean.input.execution_ms) && ...
        swept.input.period_ms == clean.input.period_ms && ...
        swept.input.deadline_ms == clean.input.deadline_ms && ...
        swept.input.timestamp_tick_ms == ...
        clean.input.timestamp_tick_ms && ...
        swept.input.response_timeout_ms == ...
        clean.input.response_timeout_ms && ...
        strcmp(swept.input.timeout_action, clean.input.timeout_action), ...
        'Blocking sweep must isolate its P11-derived input.');
end
assert(isequal(blockingWorstResponseMs, [5 6 7 8]), ...
    'Blocking sweep observed-worst references changed.');
assert(isequal(blockingResponseJitterMs, [3 4 5 6]) && ...
    isequal(blockingReleaseJitterMs, [2 2 2 2]), ...
    'Blocking must change response jitter, not release jitter.');
assert(isequal(blockingDeadlineMissCount, [0 0 0 1]), ...
    'Deadline equality and strict miss classification changed.');

%% Broken completion-spacing proxy and exact rollback
broken = runFixture(scenarioFcn('completion-jitter-trap'));
assert(all(broken.reference.release_offset_ms == 0) && ...
    broken.metrics.reference_release_jitter_pp_ms == 0, ...
    'Broken diagnostic must have exactly zero release jitter.');
assert(isequal(broken.reference.completion_interval_deviation_ms, ...
    [1 0 0 1 -1 0 3]), ...
    'Completion-interval diagnostic vector changed.');
assert(max(broken.reference.completion_interval_deviation_ms) - ...
    min(broken.reference.completion_interval_deviation_ms) == 4, ...
    'Completion spacing must show a false four-millisecond jitter proxy.');
assert(all(broken.reference.completion_identity_error_ms == 0), ...
    'Completion variation must equal delta-j plus delta-R.');
assert(isequal(broken.input.blocking_ms, clean.input.blocking_ms) && ...
    isequal(broken.input.interference_ms, clean.input.interference_ms) && ...
    isequal(broken.input.execution_ms, clean.input.execution_ms), ...
    'Broken analysis must retain the response workload.');
rollback = runFixture(fixture);
assert(isequaln(rollback, clean), ...
    'Broken analysis must roll back exactly to baseline.');

%% Coarse timestamps retain an explicit quantization error bound
coarse = runFixture(scenarioFcn('coarse-clock'));
assert(isequal(coarse.reference.response_ms, [2 3 3 3 4 3 3 6]), ...
    'Coarse-clock reference responses changed.');
assert(isequal(coarse.measurement.response_ms, [0 4 0 4 4 4 0 8]), ...
    'Coarse-clock timestamped responses changed.');
assert(coarse.metrics.fixture_observed_worst_response_ms == 6 && ...
    coarse.metrics.measured_observed_worst_response_ms == 8, ...
    'Coarse ticks must visibly change the retained maximum.');
assert(all(abs(coarse.measurement.response_error_ms) < ...
    coarse.input.timestamp_tick_ms), ...
    'Every paired timestamp response error must be strictly below one tick.');
assert(any(coarse.measurement.response_ms == 0) && ...
    all(coarse.reference.response_ms > 0), ...
    'Coarse ticks must expose collapsed positive intervals.');

exponentBoundary = 2 ^ 20;
lowerBoundaryUlp = eps(exponentBoundary - 1);
boundaryReleaseMs = exponentBoundary - 9 .* lowerBoundaryUlp;
boundaryCompletionMs = exponentBoundary + 1 - ...
    14 .* lowerBoundaryUlp;
boundaryResponseMs = boundaryCompletionMs - boundaryReleaseMs;
pairedBoundary = modelFcn(20, 1, boundaryReleaseMs, ...
    boundaryResponseMs, 0, 0, 2, 1, Inf, 'continue-observing');
assert(pairedBoundary.capture.release_tick == exponentBoundary && ...
    pairedBoundary.capture.start_tick == exponentBoundary && ...
    pairedBoundary.capture.completion_tick == exponentBoundary + 1 && ...
    pairedBoundary.measurement.response_ms == 1 && ...
    abs(pairedBoundary.measurement.response_error_ms) < 1, ...
    ['Release/start/completion captures across an exponent boundary ' ...
    'must share one per-job tolerance and retain the strict one-tick bound.']);

distinguishablyBelowMs = exponentBoundary - 20 .* lowerBoundaryUlp;
isolatedSingle = modelFcn(20, 1, distinguishablyBelowMs, ...
    0, 0, 0, 2, 1, Inf, 'continue-observing');
isolatedFarFuture = modelFcn(1e10, 2, ...
    [distinguishablyBelowMs 0], [0 0], 0, 0, 2, 1, Inf, ...
    'continue-observing');
assert(isolatedSingle.capture.release_tick == exponentBoundary - 1 && ...
    isolatedFarFuture.capture.release_tick(1) == ...
        isolatedSingle.capture.release_tick && ...
    isolatedFarFuture.capture.completion_tick(1) == ...
        isolatedSingle.capture.completion_tick, ...
    ['An unrelated far-future job must not change another job''s ' ...
    'timestamp-boundary normalization.']);

%% Deadline, timeout, cancellation, and unavailable-statistic limits
deadlineBoundaryInput = fixture;
deadlineBoundaryInput.deadline_ms = 6;
deadlineBoundary = runFixture(deadlineBoundaryInput);
assert(~any(deadlineBoundary.deadline.reference_miss) && ...
    deadlineBoundary.deadline.reference_margin_ms(8) == 0, ...
    'Response exactly equal to deadline must pass.');
deadlineMissInput = deadlineBoundaryInput;
deadlineMissInput.deadline_ms = 5.5;
deadlineMiss = runFixture(deadlineMissInput);
assert(deadlineMiss.deadline.reference_miss(8) && ...
    deadlineMiss.metrics.reference_deadline_miss_count == 1, ...
    'A positive response-over-deadline excess must miss once.');

timeoutBoundaryInput = fixture;
timeoutBoundaryInput.response_timeout_ms = 6;
timeoutBoundaryInput.timeout_action = 'cancel-observation';
timeoutBoundary = runFixture(timeoutBoundaryInput);
assert(timeoutBoundary.metrics.timeout_count == 0 && ...
    timeoutBoundary.metrics.censored_count == 0 && ...
    timeoutBoundary.metrics.retained_count == 8, ...
    'Response exactly equal to timeout must remain retained.');

continued = runFixture(scenarioFcn('timeout-continue'));
assert(continued.metrics.timeout_count == 1 && ...
    continued.metrics.censored_count == 0 && ...
    continued.metrics.retained_count == 8, ...
    'Continue-observing must record timeout without censoring.');
assert(continued.measurement.wait_timed_out(8) && ...
    continued.measurement.retained(8) && ...
    continued.measurement.response_ms(8) == 6, ...
    'Continue-observing must retain the rare tail response.');

cancelled = runFixture(scenarioFcn('timeout-cancel'));
assert(cancelled.metrics.timeout_count == 1 && ...
    cancelled.metrics.censored_count == 1 && ...
    cancelled.metrics.retained_count == 7, ...
    'Cancel-observation must expose one censored sample.');
assert(cancelled.measurement.censored(8) && ...
    ~cancelled.measurement.retained(8) && ...
    isnan(cancelled.measurement.response_ms(8)) && ...
    isnan(cancelled.capture.completion_tick(8)) && ...
    isnan(cancelled.capture.completion_timestamp_ms(8)), ...
    'Censoring must create no fake response or completion capture.');
assert(cancelled.timeline.completion_ms(8) == ...
    clean.timeline.completion_ms(8) && ...
    isequal(cancelled.timeline.start_ms, clean.timeline.start_ms), ...
    'Observation cancellation must leave every synthetic job unchanged.');
assert(cancelled.metrics.measured_observed_worst_response_ms == 4 && ...
    cancelled.metrics.incomplete_observed_worst_lower_bound_ms == 5 && ...
    ~cancelled.metrics.measured_observed_worst_is_complete_trace, ...
    'Censored maximum must stay visibly incomplete with a lower bound.');

coarseCancel = modelFcn(10, 2, [3 0], [1 2], 0, 0, ...
    10, 4, 1.5, 'cancel-observation');
assert(isequal(coarseCancel.reference.response_ms, [1 2]) && ...
    isequaln(coarseCancel.measurement.response_ms, [4 NaN]) && ...
    coarseCancel.metrics.measured_observed_worst_response_ms == 4 && ...
    coarseCancel.metrics.incomplete_observed_worst_lower_bound_ms == 1.5 && ...
    coarseCancel.metrics.incomplete_observed_worst_lower_bound_ms <= ...
        coarseCancel.metrics.fixture_observed_worst_response_ms, ...
    ['An upward-quantized retained sample must be reduced by one tick ' ...
    'before it contributes to an incomplete observed-worst lower bound.']);

allCensoredInput = fixture;
allCensoredInput.response_timeout_ms = 1;
allCensoredInput.timeout_action = 'cancel-observation';
allCensored = runFixture(allCensoredInput);
assert(all(allCensored.measurement.censored) && ...
    all(isnan(allCensored.capture.completion_tick)) && ...
    allCensored.metrics.retained_count == 0 && ...
    allCensored.metrics.censored_count == 8, ...
    'A one-millisecond cutoff must censor every baseline response.');
assert(isnan(allCensored.metrics.measured_observed_worst_response_ms) && ...
    isnan(allCensored.metrics.measured_response_mean_ms) && ...
    isnan(allCensored.metrics.measured_response_jitter_pp_ms), ...
    'Zero retained completions must produce unavailable, not zero, statistics.');
afterCancellation = runFixture(fixture);
assert(isequaln(afterCancellation, clean), ...
    'A clean call after cancellation must recover exact baseline state.');

%% Limiting cases, normalization, and compatibility
single = modelFcn(20, 1, 0, 2, 1, 3, 6, 1, [], []);
assert(single.metrics.reference_release_jitter_pp_ms == 0 && ...
    single.metrics.reference_response_jitter_pp_ms == 0 && ...
    single.metrics.fixture_observed_worst_response_ms == 6, ...
    'One retained job must have zero p-p jitter and a six-ms response.');
assert(isempty(single.reference.completion_interval_deviation_ms) && ...
    isempty(single.measurement.completion_interval_deviation_ms), ...
    'One job has no completion interval to compare.');

zeroResponse = modelFcn(20, 2, [0 0], 0, 0, 0, 1, 1, ...
    Inf, 'continue-observing');
assert(isequal(zeroResponse.reference.response_ms, [0 0]) && ...
    zeroResponse.metrics.fixture_observed_worst_response_ms == 0 && ...
    zeroResponse.metrics.reference_response_jitter_pp_ms == 0 && ...
    zeroResponse.metrics.reference_deadline_miss_count == 0, ...
    'Zero work must produce zero response and no miss.');

constantLate = modelFcn(20, 3, [0 0 0], 9, 0, 0, 8, 1, ...
    Inf, 'continue-observing');
assert(constantLate.metrics.reference_response_jitter_pp_ms == 0 && ...
    constantLate.metrics.reference_deadline_miss_count == 3, ...
    'Zero response jitter does not imply deadline safety.');

integerColumn = modelFcn(uint16(20), uint8(8), ...
    int8([0 1 -1 0 1 -1 0 1])', uint8(2), ...
    uint8([0 1 0 1 0 1 0 1])', ...
    uint8([0 0 1 0 2 0 1 3])', uint8(7), uint8(1), ...
    [], string('continue-observing'));
assert(isequaln(integerColumn, clean), ...
    ['Integer-class scalars and columns plus a scalar string must ' ...
    'normalize exactly.']);

emptyDefaults = modelFcn(fixture.period_ms, fixture.job_count, ...
    fixture.release_offset_ms, fixture.execution_ms, ...
    fixture.blocking_ms, fixture.interference_ms, ...
    fixture.deadline_ms, fixture.timestamp_tick_ms, [], []);
assert(isequaln(emptyDefaults, clean), ...
    'Empty timeout and action defaults must recover the baseline policy.');

scalarExpansion = modelFcn(20, 3, 0, 2, 1, 0, 4, 1, ...
    Inf, 'continue-observing');
assert(isequal(scalarExpansion.input.release_offset_ms, [0 0 0]) && ...
    isequal(scalarExpansion.input.execution_ms, [2 2 2]) && ...
    isequal(scalarExpansion.input.blocking_ms, [1 1 1]) && ...
    isequal(scalarExpansion.reference.response_ms, [3 3 3]), ...
    'Scalar component inputs must expand once per job.');

%% Callback-bound dependencies survive public path cleanup
callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
clear model;
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.period_ms, ...
    callbackInput.job_count, callbackInput.release_offset_ms, ...
    callbackInput.execution_ms, callbackInput.blocking_ms, ...
    callbackInput.interference_ms, callbackInput.deadline_ms, ...
    callbackInput.timestamp_tick_ms, ...
    callbackInput.response_timeout_ms, callbackInput.timeout_action);
assert(isequaln(callbackOut, clean), ...
    ['Callback-bound P12 dependencies must survive module path cleanup ' ...
    'plus a generic-model clear and conflicting P01 model path.']);
clear searchPathCleanup;

%% Malformed-input and resource-bound rejection
assertReject(@() modelFcn(20, 8, fixture.release_offset_ms, ...
    fixture.execution_ms, fixture.blocking_ms, ...
    fixture.interference_ms, 7, 1, Inf), 'P12:model:Arity');
assertReject(@() modelFcn('20', 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(true, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(20 + 1i, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(NaN, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(Inf, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn([20 20], 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(0, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Period');
assertReject(@() modelFcn(20, 0, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:JobCount');
assertReject(@() modelFcn(20, 1.5, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:JobCount');
assertReject(@() modelFcn(20, 10001, 0, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:JobResourceBound');

assertReject(@() modelFcn(20, 8, [], 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffset');
assertReject(@() modelFcn(20, 8, true, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffset');
assertReject(@() modelFcn(20, 8, 1i, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffset');
assertReject(@() modelFcn(20, 8, NaN, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffset');
assertReject(@() modelFcn(20, 8, Inf, 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffset');
assertReject(@() modelFcn(20, 8, [0 1], 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOffsetLength');
assertReject(@() modelFcn(20, 8, 0, [2 2], 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ExecutionLength');
assertReject(@() modelFcn(20, 8, 0, 2, [1 1], 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:BlockingLength');
assertReject(@() modelFcn(20, 8, 0, 2, 1, [0 1], 7, 1, Inf, ...
    'continue-observing'), 'P12:model:InterferenceLength');
assertReject(@() modelFcn(20, 8, 0, -1, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Execution');
assertReject(@() modelFcn(20, 8, 0, 2, -1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Blocking');
assertReject(@() modelFcn(20, 8, 0, 2, 1, -1, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:Interference');
assertReject(@() modelFcn(20, 2, [-1 0], 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOrder');
assertReject(@() modelFcn(20, 2, [0 -20], 2, 1, 0, 7, 1, Inf, ...
    'continue-observing'), 'P12:model:ReleaseOrder');

assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 0, 1, Inf, ...
    'continue-observing'), 'P12:model:Deadline');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 0, Inf, ...
    'continue-observing'), 'P12:model:TimestampTick');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 1, 0, ...
    'continue-observing'), 'P12:model:ResponseTimeout');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 1, -1, ...
    'continue-observing'), 'P12:model:ResponseTimeout');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 1, NaN, ...
    'continue-observing'), 'P12:model:ResponseTimeout');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    'drop-slowest'), 'P12:model:TimeoutAction');
assertReject(@() modelFcn(20, 8, 0, 2, 1, 0, 7, 1, Inf, ...
    {'continue-observing'}), 'P12:model:TimeoutAction');

largestJobs = modelFcn(1, 10000, 0, 0, 0, 0, 1, 1, Inf, ...
    'continue-observing');
assert(largestJobs.metrics.job_count == 10000 && ...
    numel(largestJobs.timeline.job_id) == 10000 && ...
    largestJobs.timeline.nominal_release_ms(end) == 9999, ...
    'The accepted 10,000-job resource bound must execute deterministically.');
assertReject(@() modelFcn(20, 1, zeros(1, 10001), 2, 1, 0, ...
    7, 1, Inf, 'continue-observing'), ...
    'P12:model:JobResourceBound');

largestTimestamp = modelFcn(1e12, 2, [0 0], 0, 0, 0, 1, 1, ...
    Inf, 'continue-observing');
assert(largestTimestamp.timeline.nominal_release_ms(2) == 1e12, ...
    'The exact 1e12-tick timestamp boundary must be accepted.');
assertReject(@() modelFcn(1e12 + 1, 2, [0 0], 0, 0, 0, ...
    1, 1, Inf, 'continue-observing'), ...
    'P12:model:TimingResourceBound');
assertReject(@() modelFcn(1e12, 2, [0 0], [0 1e-6], 0, 0, ...
    1, 1, Inf, 'continue-observing'), ...
    'P12:model:TimingPrecision');
assertReject(@() modelFcn(1e12, 2, [0 1e-6], 0, 0, 0, ...
    1, 1, Inf, 'continue-observing'), ...
    'P12:model:TimingPrecision');
assertReject(@() modelFcn(20, 1, 0, 0, 1e12, 1e-6, ...
    1, 1, Inf, 'continue-observing'), ...
    'P12:model:TimingPrecision');
assertReject(@() modelFcn(20, 2, [0 0], 0, ...
    [realmax 0], [0 realmax], 1, realmax, Inf, ...
    'continue-observing'), 'P12:model:TimingResourceBound');

largeFiniteMean = modelFcn(1e307, 2, [0 0], 1e308, ...
    0, 0, realmax, 1e308, Inf, 'continue-observing');
assert(isfinite(largeFiniteMean.metrics.measured_response_mean_ms) && ...
    largeFiniteMean.metrics.measured_response_mean_ms == 1e308, ...
    ['A finite large-response mean must not overflow through an ' ...
    'intermediate sum.']);
nearNegativeOffset = -1e308 + 1e293;
assertReject(@() modelFcn(1e308, 2, [0 nearNegativeOffset], ...
    [1e308 0], 0, 0, 1, 1e308, Inf, ...
    'continue-observing'), 'P12:model:TimingResourceBound');

assertReject(@() scenarioFcn({'baseline'}), 'P12:scenario:Name');
assertReject(@() scenarioFcn('unknown'), 'P12:scenario:Name');
assertReject(@() scenarioFcn('baseline', -1), ...
    'P12:scenario:ReleaseAmplitude');
assertReject(@() scenarioFcn('baseline', 5), ...
    'P12:scenario:ReleaseAmplitude');
assertReject(@() scenarioFcn('baseline', 1, -1), ...
    'P12:scenario:BlockingBudget');
assertReject(@() scenarioFcn('baseline', 1, 6), ...
    'P12:scenario:BlockingBudget');
assertReject(@() scenarioFcn('baseline', 1, 1, 9), ...
    'P12:scenario:Period');
assertReject(@() scenarioFcn('baseline', 1, 1, 101), ...
    'P12:scenario:Period');
assertReject(@() scenarioFcn('baseline', 1, 1, 20, 11), ...
    'P12:scenario:Execution');
assertReject(@() scenarioFcn('baseline', 1, 1, 20, 2, 0), ...
    'P12:scenario:Deadline');
assertReject(@() scenarioFcn('baseline', 1, 1, 20, 2, 7, 0.2), ...
    'P12:scenario:TimestampTick');
assertReject(@() scenarioFcn('baseline', 1, 1, 20, 2, 7, 1, 9), ...
    'P12:scenario:Arity');

afterMalformed = runFixture(fixture);
assert(isequaln(afterMalformed, clean), ...
    'A malformed call must not contaminate later recovery.');

disp(['Observation cancellation censors a retained measurement only; ' ...
    'it is not an asynchronous RTOS cancellation API or rollback action.']);
disp(['Observed worst response names a finite campaign maximum; it is ' ...
    'not a measured-WCET/WCRT or target timing guarantee.']);
disp('P12 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
