function out = model(releaseMs, preCriticalMs, criticalMs, postCriticalMs, ...
    relativeDeadlineMs, basePriority, protocol, tickMs, horizonMs, ...
    waitTimeoutMs, timeoutAction)
%MODEL Simulate one-shot fixed-priority jobs sharing one owned mutex.
%   Each task executes pre-critical, mutex-held critical, and post-critical
%   CPU work. A task with zero critical work never requests the mutex. A
%   blocked task is not ready. With priority inheritance, the mutex owner
%   temporarily receives the largest base priority of its current waiters.
%   The calculation is bounded, single-core, and discrete-time.

if nargin < 9 || nargin > 11
    error('P10:model:Arity', ...
        ['Expected release, pre-critical, critical, post-critical, ' ...
        'relative deadline, base priority, protocol, tick, horizon, ' ...
        'and optional wait-timeout and timeout-action inputs.']);
end
if isempty(protocol)
    protocol = 'priority-inheritance';
end
if nargin < 10 || isempty(waitTimeoutMs)
    waitTimeoutMs = Inf;
end
if nargin < 11 || isempty(timeoutAction)
    timeoutAction = 'continue-waiting';
end

maxTasks = 16;
maxTicks = 100000;
maxInputTicks = 1e9;

releaseMs = validateNumericVector(releaseMs, ...
    'P10:model:Release', 'releaseMs');
taskCount = numel(releaseMs);
if taskCount > maxTasks
    error('P10:model:ResourceBound', ...
        'At most sixteen one-shot tasks are allowed.');
end
preCriticalMs = validateNumericVector(preCriticalMs, ...
    'P10:model:PreCritical', 'preCriticalMs');
criticalMs = validateNumericVector(criticalMs, ...
    'P10:model:Critical', 'criticalMs');
postCriticalMs = validateNumericVector(postCriticalMs, ...
    'P10:model:PostCritical', 'postCriticalMs');
relativeDeadlineMs = validateNumericVector(relativeDeadlineMs, ...
    'P10:model:Deadline', 'relativeDeadlineMs');
basePriority = validateNumericVector(basePriority, ...
    'P10:model:Priority', 'basePriority');
if any([numel(preCriticalMs), numel(criticalMs), ...
        numel(postCriticalMs), numel(relativeDeadlineMs), ...
        numel(basePriority)] ~= taskCount)
    error('P10:model:VectorLength', ...
        'Every task vector must contain the same number of elements.');
end
if any(releaseMs < 0)
    error('P10:model:Release', ...
        'Every release time must be nonnegative.');
end
if any(preCriticalMs < 0)
    error('P10:model:PreCritical', ...
        'Every pre-critical execution time must be nonnegative.');
end
if any(criticalMs < 0)
    error('P10:model:Critical', ...
        'Every critical-section execution time must be nonnegative.');
end
if any(postCriticalMs < 0)
    error('P10:model:PostCritical', ...
        'Every post-critical execution time must be nonnegative.');
end
if any(relativeDeadlineMs <= 0)
    error('P10:model:Deadline', ...
        'Every relative deadline must be positive.');
end
if any(basePriority ~= round(basePriority)) || ...
        any(abs(basePriority) > 1e6)
    error('P10:model:Priority', ...
        'Base priorities must be integers with magnitude at most 1e6.');
end

protocol = validateProtocol(protocol);
timeoutAction = validateTimeoutAction(timeoutAction);
tickMs = validatePositiveScalar(tickMs, ...
    'P10:model:Tick', 'tickMs');
horizonMs = validatePositiveScalar(horizonMs, ...
    'P10:model:Horizon', 'horizonMs');
waitTimeoutMs = validateWaitTimeout(waitTimeoutMs, taskCount);

scaledHorizon = horizonMs ./ tickMs;
if ~isfinite(scaledHorizon) || scaledHorizon > maxTicks
    error('P10:model:TimingResourceBound', ...
        'The observation horizon may contain at most 100000 ticks.');
end
allScaledTimes = [releaseMs, preCriticalMs, criticalMs, ...
    postCriticalMs, relativeDeadlineMs, horizonMs] ./ tickMs;
nearestTicks = round(allScaledTimes);
alignmentTolerance = 32 .* eps(max(abs(allScaledTimes), 1));
positiveCollapsedToZero = allScaledTimes > 0 & nearestTicks == 0;
if any(~isfinite(allScaledTimes)) || ...
        any(abs(allScaledTimes - nearestTicks) > alignmentTolerance) || ...
        any(positiveCollapsedToZero)
    error('P10:model:GridAlignment', ...
        ['Every finite time and the horizon must align to tickMs; a ' ...
        'positive time cannot collapse to zero ticks.']);
end
finiteTimeout = isfinite(waitTimeoutMs);
scaledTimeout = waitTimeoutMs(finiteTimeout) ./ tickMs;
timeoutTicksRounded = zeros(size(scaledTimeout));
if any(finiteTimeout)
    timeoutTicksRounded = round(scaledTimeout);
    timeoutTolerance = 32 .* eps(max(abs(scaledTimeout), 1));
    if any(abs(scaledTimeout - timeoutTicksRounded) > ...
            timeoutTolerance) || ...
            any(scaledTimeout > 0 & timeoutTicksRounded == 0)
        error('P10:model:GridAlignment', ...
            'Every finite wait timeout must align to tickMs.');
    end
end
if any(allScaledTimes > maxInputTicks) || ...
        any(scaledTimeout > maxInputTicks)
    error('P10:model:TimingResourceBound', ...
        'Each declared finite time may span at most 1e9 ticks.');
end

releaseTicks = round(releaseMs ./ tickMs);
preCriticalTicks = round(preCriticalMs ./ tickMs);
criticalTicks = round(criticalMs ./ tickMs);
postCriticalTicks = round(postCriticalMs ./ tickMs);
deadlineTicks = round(relativeDeadlineMs ./ tickMs);
horizonTicks = round(scaledHorizon);
if horizonTicks < 1
    error('P10:model:Horizon', ...
        'The horizon must contain at least one scheduler tick.');
end
totalExecutionTicks = preCriticalTicks + criticalTicks + ...
    postCriticalTicks;
if any(totalExecutionTicks > maxInputTicks)
    error('P10:model:TimingResourceBound', ...
        'Total execution for one task may span at most 1e9 ticks.');
end
waitTimeoutTicks = Inf(1, taskCount);
waitTimeoutTicks(finiteTimeout) = timeoutTicksRounded;

ownerTask = zeros(1, horizonTicks);
resourceOwnerTimeline = zeros(1, horizonTicks);
readyCount = zeros(1, horizonTicks);
blockedCount = zeros(1, horizonTicks);
selectedEffectivePriority = NaN(1, horizonTicks);
stateCode = zeros(taskCount, horizonTicks);
blockedTimeline = false(taskCount, horizonTicks);
effectivePriorityTimeline = repmat(basePriority(:), 1, horizonTicks);

released = false(1, taskCount);
completed = false(1, taskCount);
cancelled = false(1, taskCount);
blocked = false(1, taskCount);
acquiredResource = false(1, taskCount);
remainingTicks = totalExecutionTicks;
serviceTicks = zeros(1, taskCount);
criticalServiceTicks = zeros(1, taskCount);
blockedTicks = zeros(1, taskCount);
directBlockingTicks = zeros(1, taskCount);
thirdPartyInterferenceTicks = zeros(1, taskCount);
cancelledWorkTicks = zeros(1, taskCount);
startTick = NaN(1, taskCount);
completionTick = NaN(1, taskCount);
resourceRequestTick = NaN(1, taskCount);
resourceAcquireTick = NaN(1, taskCount);
resourceReleaseTick = NaN(1, taskCount);
blockStartTick = NaN(1, taskCount);
deadlineMissTick = NaN(1, taskCount);
waitTimeoutTick = NaN(1, taskCount);
cancellationTick = NaN(1, taskCount);
deadlineMissed = false(1, taskCount);
waitTimedOut = false(1, taskCount);
dispatchCount = zeros(1, taskCount);
preemptionCount = zeros(1, taskCount);
resourceOwner = 0;
lastOwner = 0;

% Prior-slot completion and mutex release are applied during that slot's
% service update. At each boundary, deadline expiry precedes waiter timeout;
% release into the half-open horizon precedes a bounded select/block/reselect
% transition loop, then one tick of CPU service is executed.
for boundaryTick = 0:horizonTicks
    dueDeadline = released & ~completed & ~cancelled & ...
        (releaseTicks + deadlineTicks == boundaryTick);
    newlyMissed = dueDeadline & ~deadlineMissed;
    deadlineMissed(newlyMissed) = true;
    deadlineMissTick(newlyMissed) = boundaryTick;

    timeoutNow = blocked & ~waitTimedOut & ...
        (blockedTicks >= waitTimeoutTicks);
    waitTimedOut(timeoutNow) = true;
    waitTimeoutTick(timeoutNow) = boundaryTick;
    if strcmp(timeoutAction, 'cancel-waiter')
        cancelIds = find(timeoutNow);
        for cancelIndex = 1:numel(cancelIds)
            taskId = cancelIds(cancelIndex);
            if resourceOwner == taskId
                error('P10:model:InternalMutex', ...
                    'A blocked waiter cannot own the mutex it waits for.');
            end
            cancelled(taskId) = true;
            blocked(taskId) = false;
            cancellationTick(taskId) = boundaryTick;
            cancelledWorkTicks(taskId) = remainingTicks(taskId);
            remainingTicks(taskId) = 0;
        end
    end

    if boundaryTick == horizonTicks
        break;
    end

    releaseNow = ~released & releaseTicks == boundaryTick;
    released(releaseNow) = true;
    zeroWorkNow = releaseNow & totalExecutionTicks == 0;
    startTick(zeroWorkNow) = boundaryTick;
    completionTick(zeroWorkNow) = boundaryTick;
    completed(zeroWorkNow) = true;

    selectedTask = 0;
    effectivePriority = basePriority;
    dispatchResolved = false;
    for boundedTransition = 1:(taskCount + 1)
        effectivePriority = basePriority;
        if strcmp(protocol, 'priority-inheritance') && ...
                resourceOwner > 0 && any(blocked)
            effectivePriority(resourceOwner) = max( ...
                effectivePriority(resourceOwner), ...
                max(basePriority(blocked)));
        end
        candidate = released & ~completed & ~cancelled & ...
            ~blocked & remainingTicks > 0;
        selectedTask = chooseTask(candidate, effectivePriority, ...
            releaseTicks);
        if selectedTask == 0
            dispatchResolved = true;
            break;
        end

        needsResource = criticalTicks(selectedTask) > 0 && ...
            ~acquiredResource(selectedTask) && ...
            serviceTicks(selectedTask) == preCriticalTicks(selectedTask);
        if needsResource
            if isnan(resourceRequestTick(selectedTask))
                resourceRequestTick(selectedTask) = boundaryTick;
            end
            if resourceOwner == 0
                resourceOwner = selectedTask;
                acquiredResource(selectedTask) = true;
                resourceAcquireTick(selectedTask) = boundaryTick;
            elseif resourceOwner ~= selectedTask
                blocked(selectedTask) = true;
                if isnan(blockStartTick(selectedTask))
                    blockStartTick(selectedTask) = boundaryTick;
                end
                selectedTask = 0;
                continue;
            end
        end
        dispatchResolved = true;
        break;
    end
    if ~dispatchResolved
        error('P10:model:InternalTransition', ...
            'Mutex request transitions exceeded the task-count bound.');
    end

    % Recompute after the final request/block decision so the trace captures
    % donation in the same interval in which the high-priority task blocks.
    effectivePriority = basePriority;
    if strcmp(protocol, 'priority-inheritance') && ...
            resourceOwner > 0 && any(blocked)
        effectivePriority(resourceOwner) = max( ...
            effectivePriority(resourceOwner), max(basePriority(blocked)));
    end

    slotIndex = boundaryTick + 1;
    ownerTask(slotIndex) = selectedTask;
    resourceOwnerTimeline(slotIndex) = resourceOwner;
    readyMask = released & ~completed & ~cancelled & ...
        ~blocked & remainingTicks > 0;
    readyCount(slotIndex) = sum(readyMask);
    blockedCount(slotIndex) = sum(blocked);
    blockedTimeline(:, slotIndex) = blocked(:);
    effectivePriorityTimeline(:, slotIndex) = effectivePriority(:);
    if selectedTask > 0
        selectedEffectivePriority(slotIndex) = ...
            effectivePriority(selectedTask);
    end

    state = zeros(taskCount, 1);
    state(released & ~completed & ~cancelled) = 1;
    state(blocked) = 3;
    if selectedTask > 0
        state(selectedTask) = 2;
    end
    state(completed) = 4;
    state(cancelled) = 5;
    stateCode(:, slotIndex) = state;

    blockedIds = find(blocked);
    for blockedIndex = 1:numel(blockedIds)
        waiterId = blockedIds(blockedIndex);
        blockedTicks(waiterId) = blockedTicks(waiterId) + 1;
        if selectedTask == resourceOwner && resourceOwner > 0
            directBlockingTicks(waiterId) = ...
                directBlockingTicks(waiterId) + 1;
        elseif selectedTask > 0
            thirdPartyInterferenceTicks(waiterId) = ...
                thirdPartyInterferenceTicks(waiterId) + 1;
        end
    end

    if lastOwner > 0 && selectedTask ~= lastOwner && ...
            released(lastOwner) && ~completed(lastOwner) && ...
            ~cancelled(lastOwner) && ~blocked(lastOwner) && ...
            remainingTicks(lastOwner) > 0
        preemptionCount(lastOwner) = preemptionCount(lastOwner) + 1;
    end

    if selectedTask > 0
        if selectedTask ~= lastOwner
            dispatchCount(selectedTask) = dispatchCount(selectedTask) + 1;
        end
        if isnan(startTick(selectedTask))
            startTick(selectedTask) = boundaryTick;
        end
        remainingTicks(selectedTask) = remainingTicks(selectedTask) - 1;
        serviceTicks(selectedTask) = serviceTicks(selectedTask) + 1;

        if resourceOwner == selectedTask
            criticalServiceTicks(selectedTask) = ...
                criticalServiceTicks(selectedTask) + 1;
            if criticalServiceTicks(selectedTask) == ...
                    criticalTicks(selectedTask)
                resourceOwner = 0;
                resourceReleaseTick(selectedTask) = boundaryTick + 1;
                blocked(:) = false;
            end
        end

        if remainingTicks(selectedTask) == 0
            if resourceOwner == selectedTask
                error('P10:model:InternalMutex', ...
                    'A task completed while still owning the mutex.');
            end
            completed(selectedTask) = true;
            completionTick(selectedTask) = boundaryTick + 1;
        end
    end
    lastOwner = selectedTask;
end

responseTicks = NaN(1, taskCount);
responseTicks(completed) = completionTick(completed) - ...
    releaseTicks(completed);
unfinished = released & ~completed & ~cancelled;
busyTicks = sum(ownerTask > 0);
idleTicks = horizonTicks - busyTicks;
releasedDemandTicks = sum(totalExecutionTicks(released));
servedTicks = sum(serviceTicks);
cancelledTicks = sum(cancelledWorkTicks);
remainingReleasedTicks = sum(remainingTicks(released));
boostTicksByTask = sum(effectivePriorityTimeline > ...
    repmat(basePriority(:), 1, horizonTicks), 2).';

if resourceOwner < 0 || resourceOwner > taskCount || ...
        releasedDemandTicks ~= servedTicks + cancelledTicks + ...
        remainingReleasedTicks
    error('P10:model:InternalAccounting', ...
        'Bounded scheduler accounting did not conserve work or ownership.');
end

out = struct();
out.input = struct( ...
    'release_ms', releaseTicks .* tickMs, ...
    'pre_critical_ms', preCriticalTicks .* tickMs, ...
    'critical_ms', criticalTicks .* tickMs, ...
    'post_critical_ms', postCriticalTicks .* tickMs, ...
    'total_execution_ms', totalExecutionTicks .* tickMs, ...
    'relative_deadline_ms', deadlineTicks .* tickMs, ...
    'base_priority', basePriority, ...
    'tick_ms', tickMs, ...
    'horizon_ms', horizonTicks .* tickMs, ...
    'wait_timeout_ms', waitTimeoutTicks .* tickMs);
out.policy = struct( ...
    'scheduler', 'fixed-priority-preemptive-single-core', ...
    'resource_count', 1, ...
    'mutex_protocol', protocol, ...
    'timeout_action', timeoutAction, ...
    'larger_priority_runs_first', true, ...
    'tie_break', 'earliest release, then task ID', ...
    'unlock_before_timeout_at_same_boundary', true, ...
    'deadline_before_wait_timeout_at_same_boundary', true, ...
    'dispatch_overhead_ms', 0, ...
    'context_switch_overhead_ms', 0, ...
    'release_at_horizon_included', false);
out.timeline = struct( ...
    'time_ms', (0:(horizonTicks - 1)) .* tickMs, ...
    'time_edges_ms', (0:horizonTicks) .* tickMs, ...
    'cpu_owner_task_id', ownerTask, ...
    'mutex_owner_task_id', resourceOwnerTimeline, ...
    'ready_task_count', readyCount, ...
    'blocked_task_count', blockedCount, ...
    'selected_effective_priority', selectedEffectivePriority, ...
    'effective_priority_by_task', effectivePriorityTimeline, ...
    'blocked_by_task', blockedTimeline, ...
    'state_code_by_task', stateCode, ...
    'state_labels', {{'not released', 'ready', 'running', ...
    'blocked', 'completed', 'cancelled'}});
out.tasks = struct( ...
    'id', 1:taskCount, ...
    'released', released, ...
    'absolute_deadline_ms', (releaseTicks + deadlineTicks) .* tickMs, ...
    'start_ms', startTick .* tickMs, ...
    'completion_ms', completionTick .* tickMs, ...
    'response_ms', responseTicks .* tickMs, ...
    'service_ms', serviceTicks .* tickMs, ...
    'remaining_ms', remainingTicks .* tickMs, ...
    'cancelled_work_ms', cancelledWorkTicks .* tickMs, ...
    'resource_request_ms', resourceRequestTick .* tickMs, ...
    'resource_acquire_ms', resourceAcquireTick .* tickMs, ...
    'resource_release_ms', resourceReleaseTick .* tickMs, ...
    'block_start_ms', blockStartTick .* tickMs, ...
    'blocked_time_ms', blockedTicks .* tickMs, ...
    'direct_blocking_ms', directBlockingTicks .* tickMs, ...
    'third_party_interference_ms', ...
    thirdPartyInterferenceTicks .* tickMs, ...
    'peak_effective_priority', ...
    max(effectivePriorityTimeline, [], 2).', ...
    'boost_time_ms', boostTicksByTask .* tickMs, ...
    'deadline_missed', deadlineMissed, ...
    'deadline_miss_time_ms', deadlineMissTick .* tickMs, ...
    'wait_timed_out', waitTimedOut, ...
    'wait_timeout_time_ms', waitTimeoutTick .* tickMs, ...
    'cancelled_while_waiting', cancelled, ...
    'cancellation_time_ms', cancellationTick .* tickMs, ...
    'completed', completed, ...
    'unfinished_at_horizon', unfinished, ...
    'dispatch_count', dispatchCount, ...
    'preemption_count', preemptionCount);
out.metrics = struct( ...
    'released_count', sum(released), ...
    'completion_count', sum(completed), ...
    'deadline_miss_count', sum(deadlineMissed), ...
    'wait_timeout_count', sum(waitTimedOut), ...
    'wait_cancel_count', sum(cancelled), ...
    'unfinished_count', sum(unfinished), ...
    'service_time_ms_by_task', serviceTicks .* tickMs, ...
    'blocked_time_ms_by_task', blockedTicks .* tickMs, ...
    'direct_blocking_ms_by_task', directBlockingTicks .* tickMs, ...
    'third_party_interference_ms_by_task', ...
    thirdPartyInterferenceTicks .* tickMs, ...
    'boost_time_ms_by_task', boostTicksByTask .* tickMs, ...
    'busy_time_ms', busyTicks .* tickMs, ...
    'idle_time_ms', idleTicks .* tickMs, ...
    'busy_fraction', busyTicks ./ horizonTicks, ...
    'idle_fraction', idleTicks ./ horizonTicks, ...
    'max_blocked_tasks', max([0 blockedCount]), ...
    'released_demand_ms', releasedDemandTicks .* tickMs, ...
    'served_work_ms', servedTicks .* tickMs, ...
    'cancelled_work_ms', cancelledTicks .* tickMs, ...
    'remaining_work_ms', remainingReleasedTicks .* tickMs, ...
    'work_conservation_error_ms', ...
    (releasedDemandTicks - servedTicks - cancelledTicks - ...
    remainingReleasedTicks) .* tickMs);
out.claim_boundary = [ ...
    'Deterministic one-mutex discrete-time scheduler calculation; not a ' ...
    'MATLAB-runtime, RTOS, processor, mutex implementation, or hardware ' ...
    'timing measurement.'];
end

function selectedTask = chooseTask(candidate, effectivePriority, releaseTicks)
selectedTask = 0;
for taskId = 1:numel(candidate)
    if ~candidate(taskId)
        continue;
    end
    choose = selectedTask == 0;
    if ~choose
        choose = effectivePriority(taskId) > ...
            effectivePriority(selectedTask) || ...
            (effectivePriority(taskId) == ...
            effectivePriority(selectedTask) && ...
            (releaseTicks(taskId) < releaseTicks(selectedTask) || ...
            (releaseTicks(taskId) == releaseTicks(selectedTask) && ...
            taskId < selectedTask)));
    end
    if choose
        selectedTask = taskId;
    end
end
end

function value = validateNumericVector(value, identifier, label)
valid = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isvector(value) && ~isempty(value) && all(isfinite(value(:)));
if ~valid
    error(identifier, ...
        '%s must be a nonempty finite real numeric vector.', label);
end
value = double(value(:).');
end

function value = validatePositiveScalar(value, identifier, label)
valid = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && isfinite(value) && value > 0;
if ~valid
    error(identifier, ...
        '%s must be a positive finite real numeric scalar.', label);
end
value = double(value);
end

function protocol = validateProtocol(protocol)
if ~(ischar(protocol) || (isstring(protocol) && isscalar(protocol)))
    error('P10:model:Protocol', ...
        'protocol must be a character vector or scalar string.');
end
protocol = lower(strtrim(char(protocol)));
if ~any(strcmp(protocol, {'none', 'priority-inheritance'}))
    error('P10:model:Protocol', ...
        'protocol must be none or priority-inheritance.');
end
end

function timeoutAction = validateTimeoutAction(timeoutAction)
if ~(ischar(timeoutAction) || ...
        (isstring(timeoutAction) && isscalar(timeoutAction)))
    error('P10:model:TimeoutAction', ...
        'timeoutAction must be a character vector or scalar string.');
end
timeoutAction = lower(strtrim(char(timeoutAction)));
if ~any(strcmp(timeoutAction, ...
        {'continue-waiting', 'cancel-waiter'}))
    error('P10:model:TimeoutAction', ...
        'timeoutAction must be continue-waiting or cancel-waiter.');
end
end

function waitTimeoutMs = validateWaitTimeout(waitTimeoutMs, taskCount)
valid = isnumeric(waitTimeoutMs) && ~islogical(waitTimeoutMs) && ...
    isreal(waitTimeoutMs) && isvector(waitTimeoutMs) && ...
    ~isempty(waitTimeoutMs) && ...
    all(~isnan(waitTimeoutMs(:))) && all(waitTimeoutMs(:) > 0);
if ~valid
    error('P10:model:WaitTimeout', ...
        ['waitTimeoutMs must be a positive real numeric scalar or task ' ...
        'vector; Inf disables timeout.']);
end
waitTimeoutMs = double(waitTimeoutMs(:).');
if isscalar(waitTimeoutMs)
    waitTimeoutMs = repmat(waitTimeoutMs, 1, taskCount);
elseif numel(waitTimeoutMs) ~= taskCount
    error('P10:model:VectorLength', ...
        'A wait-timeout vector must contain one value per task.');
end
end
