function run_checks
%RUN_CHECKS Verify P10 inversion, inheritance, boundaries, and recovery.

modelFcn = @model;
scenarioFcn = @p10_scenario;
runFixture = @(fixture) modelFcn(fixture.release_ms, ...
    fixture.pre_critical_ms, fixture.critical_ms, ...
    fixture.post_critical_ms, fixture.relative_deadline_ms, ...
    fixture.base_priority, fixture.protocol, fixture.tick_ms, ...
    fixture.horizon_ms, fixture.wait_timeout_ms, ...
    fixture.timeout_action);
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);

%% Deterministic baseline, ownership, donation, and conservation
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'Repeated baseline calls must be deterministic and state-isolated.');
expectedOwner = [1 2 1 1 1 3 3 2 2 2 2 1 1 0 0 0];
expectedMutexOwner = [1 1 1 1 1 3 0 0 0 0 0 0 0 0 0 0];
expectedLowEffective = [1 1 3 3 3 1 1 1 1 1 1 1 1 1 1 1];
assert(isequal(clean.timeline.cpu_owner_task_id, expectedOwner), ...
    'Baseline CPU ownership must retain the exact dispatch sequence.');
assert(isequal(clean.timeline.mutex_owner_task_id, ...
    expectedMutexOwner), ...
    'Baseline mutex ownership must retain Low then High acquisition.');
assert(isequal(clean.timeline.effective_priority_by_task(1, :), ...
    expectedLowEffective), ...
    'Low must inherit priority 3 for exactly three intervals.');
assert(isequal(clean.timeline.effective_priority_by_task(2:3, :), ...
    repmat([2; 3], 1, 16)), ...
    'Inheritance must not mutate Medium or blocked High priority.');
assert(isequal(find(clean.timeline.blocked_by_task(3, :)), 3:5), ...
    'High must be blocked in intervals starting at 2, 3, and 4 ms.');
assert(~any(any(clean.timeline.blocked_by_task(1:2, :))), ...
    'Only High waits in the baseline fixture.');
assert(all(clean.timeline.cpu_owner_task_id(3:5) == 1) && ...
    all(clean.timeline.mutex_owner_task_id(3:5) == 1), ...
    'Donated Low must both own the CPU and retain the mutex while High waits.');
assert(~any(clean.timeline.cpu_owner_task_id(3:5) == 3), ...
    'A mutex-blocked High task must never execute.');
assert(isequaln(clean.tasks.resource_request_ms, [0 NaN 2]) && ...
    isequaln(clean.tasks.resource_acquire_ms, [0 NaN 5]) && ...
    isequaln(clean.tasks.resource_release_ms, [5 NaN 6]), ...
    'Resource request, acquisition, and release boundaries changed.');
assert(isequal(clean.tasks.completion_ms, [13 11 7]) && ...
    isequal(clean.tasks.response_ms, [13 10 5]), ...
    'Baseline completion and response times changed.');
assert(isequal(clean.tasks.service_ms, [6 5 2]) && ...
    isequal(clean.metrics.service_time_ms_by_task, [6 5 2]), ...
    'Every baseline task must receive its declared CPU service.');
assert(clean.tasks.blocked_time_ms(3) == 3 && ...
    clean.tasks.direct_blocking_ms(3) == 3 && ...
    clean.tasks.third_party_interference_ms(3) == 0, ...
    'Inherited High wait must contain three direct and zero third-party ticks.');
assert(clean.tasks.boost_time_ms(1) == 3 && ...
    isequal(clean.tasks.peak_effective_priority, [3 2 3]) && ...
    isequal(clean.input.base_priority, [1 2 3]), ...
    'Donation must be temporary and base priorities must remain immutable.');
assert(~any(clean.tasks.deadline_missed) && ...
    clean.metrics.deadline_miss_count == 0, ...
    'The inherited baseline must meet every observed deadline.');
assert(clean.metrics.released_count == 3 && ...
    clean.metrics.completion_count == 3 && ...
    clean.metrics.unfinished_count == 0, ...
    'Every baseline job must release and complete exactly once.');
assert(clean.metrics.busy_time_ms == 13 && ...
    clean.metrics.idle_time_ms == 3 && ...
    clean.metrics.busy_time_ms + clean.metrics.idle_time_ms == 16, ...
    'Busy and idle time must conserve the 16 ms horizon.');
assert(abs(clean.metrics.busy_fraction - 13 / 16) < 1e-14 && ...
    abs(clean.metrics.idle_fraction - 3 / 16) < 1e-14, ...
    'Busy and idle fractions must match retained service.');
assert(clean.metrics.released_demand_ms == 13 && ...
    clean.metrics.served_work_ms == 13 && ...
    clean.metrics.cancelled_work_ms == 0 && ...
    clean.metrics.remaining_work_ms == 0 && ...
    clean.metrics.work_conservation_error_ms == 0, ...
    'Released demand must equal served plus canceled plus remaining work.');
assert(all(ismember(unique(clean.timeline.cpu_owner_task_id), 0:3)) && ...
    all(ismember(unique(clean.timeline.mutex_owner_task_id), 0:3)) && ...
    clean.metrics.max_blocked_tasks == 1, ...
    'CPU owner, mutex owner, and blocked depth must stay bounded.');

%% Independent wait and response calculations
remainingLowCriticalMs = fixture.critical_ms(1) - 1;
remainingMediumMs = fixture.pre_critical_ms(2) - 1;
independentInheritedWaitMs = remainingLowCriticalMs;
independentPlainWaitMs = remainingLowCriticalMs + remainingMediumMs;
highExecutionMs = fixture.critical_ms(3) + ...
    fixture.post_critical_ms(3);
assert(remainingLowCriticalMs == 3 && remainingMediumMs == 4, ...
    'Independent request-boundary work must be three Low plus four Medium ms.');
assert(independentInheritedWaitMs == clean.tasks.blocked_time_ms(3) && ...
    independentInheritedWaitMs + highExecutionMs == ...
    clean.tasks.response_ms(3), ...
    'Inherited wait and response must match independent arithmetic.');
assert(independentPlainWaitMs == 7 && ...
    independentPlainWaitMs + highExecutionMs == 9, ...
    'Plain-mutex independent wait and response references changed.');

%% Plain mutex inversion, deadline failure, rollback, and recovery
plainFixture = scenarioFcn('plain-mutex');
plain = runFixture(plainFixture);
expectedPlainOwner = [1 2 2 2 2 2 1 1 1 3 3 1 1 0 0 0];
expectedPlainMutex = [1 1 1 1 1 1 1 1 1 3 0 0 0 0 0 0];
assert(isequal(plain.timeline.cpu_owner_task_id, ...
    expectedPlainOwner) && ...
    isequal(plain.timeline.mutex_owner_task_id, ...
    expectedPlainMutex), ...
    'Plain-mutex ownership timelines changed.');
assert(isequal(plain.timeline.effective_priority_by_task, ...
    repmat([1; 2; 3], 1, 16)), ...
    'Plain mutex must never alter effective priority.');
assert(isequal(plain.tasks.completion_ms, [13 6 11]) && ...
    isequal(plain.tasks.response_ms, [13 5 9]), ...
    'Plain-mutex completion and response references changed.');
assert(plain.tasks.blocked_time_ms(3) == 7 && ...
    plain.tasks.direct_blocking_ms(3) == 3 && ...
    plain.tasks.third_party_interference_ms(3) == 4 && ...
    plain.tasks.blocked_time_ms(3) == ...
    plain.tasks.direct_blocking_ms(3) + ...
    plain.tasks.third_party_interference_ms(3), ...
    'Plain High wait must decompose into three direct and four inversion ticks.');
assert(plain.tasks.deadline_missed(3) && ...
    plain.tasks.deadline_miss_time_ms(3) == 8 && ...
    plain.metrics.deadline_miss_count == 1, ...
    'High must miss once at its 8 ms absolute deadline.');
assert(isequal(plain.input, clean.input) && ...
    isequal(plain.tasks.service_ms, clean.tasks.service_ms) && ...
    plain.metrics.released_demand_ms == ...
    clean.metrics.released_demand_ms && ...
    plain.metrics.busy_time_ms == clean.metrics.busy_time_ms, ...
    'Protocol comparison must retain every numeric input and unit of work.');
rolledBack = runFixture(fixture);
assert(isequaln(rolledBack, clean), ...
    'Restoring priority inheritance must roll back exactly to baseline.');

%% Sweep 1 isolates Medium work under both protocols
mediumWorkSweepMs = [1 3 5 7];
expectedPlainWaitMs = [3 5 7 9];
expectedPlainResponseMs = [5 7 9 11];
expectedPlainThirdPartyMs = [0 2 4 6];
expectedPlainMiss = [false true true true];
for sweepIndex = 1:numel(mediumWorkSweepMs)
    protectedInput = scenarioFcn('baseline', ...
        mediumWorkSweepMs(sweepIndex), 4, 16);
    plainInput = scenarioFcn('plain-mutex', ...
        mediumWorkSweepMs(sweepIndex), 4, 16);
    protected = runFixture(protectedInput);
    unprotected = runFixture(plainInput);
    assert(unprotected.tasks.blocked_time_ms(3) == ...
        expectedPlainWaitMs(sweepIndex) && ...
        unprotected.tasks.response_ms(3) == ...
        expectedPlainResponseMs(sweepIndex) && ...
        unprotected.tasks.third_party_interference_ms(3) == ...
        expectedPlainThirdPartyMs(sweepIndex) && ...
        unprotected.tasks.deadline_missed(3) == ...
        expectedPlainMiss(sweepIndex), ...
        'Plain Medium-work sweep reference changed.');
    assert(protected.tasks.blocked_time_ms(3) == 3 && ...
        protected.tasks.direct_blocking_ms(3) == 3 && ...
        protected.tasks.third_party_interference_ms(3) == 0 && ...
        protected.tasks.response_ms(3) == 5 && ...
        ~protected.tasks.deadline_missed(3), ...
        'Inheritance must isolate High from swept Medium work.');
    assert(isequal(protected.input.release_ms, clean.input.release_ms) && ...
        isequal(protected.input.critical_ms, clean.input.critical_ms) && ...
        isequal(protected.input.post_critical_ms, ...
        clean.input.post_critical_ms) && ...
        isequal(protected.input.relative_deadline_ms, ...
        clean.input.relative_deadline_ms) && ...
        isequal(protected.input.base_priority, ...
        clean.input.base_priority) && ...
        isequal(protected.input.wait_timeout_ms, ...
        clean.input.wait_timeout_ms), ...
        'Medium-work sweep must isolate its one work input.');
    assert(isequal(unprotected.input, protected.input), ...
        'Protocol comparison must preserve all numeric inputs.');
end

%% Sweep 2 isolates Low critical share while total Low work stays fixed
lowCriticalSweepMs = [1 2 3 4 5];
expectedCriticalWaitMs = [0 1 2 3 4];
expectedCriticalResponseMs = [2 3 4 5 6];
for sweepIndex = 1:numel(lowCriticalSweepMs)
    sweptFixture = scenarioFcn('baseline', 5, ...
        lowCriticalSweepMs(sweepIndex), 16);
    swept = runFixture(sweptFixture);
    assert(swept.input.total_execution_ms(1) == 6 && ...
        swept.input.critical_ms(1) == lowCriticalSweepMs(sweepIndex) && ...
        swept.input.post_critical_ms(1) == ...
        6 - lowCriticalSweepMs(sweepIndex), ...
        'Low critical-share sweep must retain six total Low work ticks.');
    assert(swept.tasks.blocked_time_ms(3) == ...
        expectedCriticalWaitMs(sweepIndex) && ...
        swept.tasks.direct_blocking_ms(3) == ...
        expectedCriticalWaitMs(sweepIndex) && ...
        swept.tasks.third_party_interference_ms(3) == 0 && ...
        swept.tasks.response_ms(3) == ...
        expectedCriticalResponseMs(sweepIndex) && ...
        ~swept.tasks.deadline_missed(3), ...
        'Low critical-share sweep response reference changed.');
    assert(swept.input.pre_critical_ms(2) == 5 && ...
        isequal(swept.input.release_ms, clean.input.release_ms) && ...
        isequal(swept.input.relative_deadline_ms, ...
        clean.input.relative_deadline_ms) && ...
        isequal(swept.input.base_priority, clean.input.base_priority) && ...
        strcmp(swept.policy.mutex_protocol, ...
        'priority-inheritance'), ...
        'Low critical-share sweep must isolate held share from other inputs.');
end

%% Limiting trigger, contention, exact-deadline, and horizon cases
directOnlyInput = scenarioFcn('direct-block-only');
directOnlyPlain = runFixture(directOnlyInput);
directOnlyInput.protocol = 'priority-inheritance';
directOnlyInherited = runFixture(directOnlyInput);
assert(directOnlyPlain.tasks.blocked_time_ms(3) == 2 && ...
    directOnlyPlain.tasks.direct_blocking_ms(3) == 2 && ...
    directOnlyPlain.tasks.third_party_interference_ms(3) == 0 && ...
    directOnlyPlain.tasks.response_ms(3) == 4, ...
    'Zero Medium work must leave two direct blocking ticks in this phasing.');
assert(isequal(directOnlyPlain.timeline.cpu_owner_task_id, ...
    directOnlyInherited.timeline.cpu_owner_task_id) && ...
    isequal(directOnlyPlain.tasks.response_ms, ...
    directOnlyInherited.tasks.response_ms), ...
    'Plain and inherited protocols must agree without third-party work.');

oneCritical = runFixture(scenarioFcn('baseline', 5, 1, 16));
assert(oneCritical.tasks.blocked_time_ms(3) == 0 && ...
    oneCritical.tasks.response_ms(3) == 2 && ...
    oneCritical.tasks.resource_release_ms(1) == 1, ...
    'One Low critical tick must unlock before High releases.');

highFirst = runFixture(scenarioFcn('high-first'));
expectedHighFirstOwner = [3 3 2 2 2 2 2 1 1 1 1 1 1 0 0 0];
assert(isequal(highFirst.timeline.cpu_owner_task_id, ...
    expectedHighFirstOwner) && ...
    highFirst.tasks.resource_acquire_ms(3) == 0 && ...
    highFirst.tasks.blocked_time_ms(3) == 0 && ...
    highFirst.tasks.response_ms(3) == 2, ...
    'High acquiring first must remove the owner-before-waiter trigger.');

exactDeadline = runFixture(scenarioFcn('baseline', 5, 5, 16));
assert(exactDeadline.tasks.completion_ms(3) == 8 && ...
    exactDeadline.tasks.absolute_deadline_ms(3) == 8 && ...
    ~exactDeadline.tasks.deadline_missed(3), ...
    'Completion exactly at the absolute deadline must pass.');
shortDeadlineInput = scenarioFcn('baseline', 5, 5, 16);
shortDeadlineInput.relative_deadline_ms(3) = 5;
shortDeadline = runFixture(shortDeadlineInput);
assert(shortDeadline.tasks.deadline_missed(3) && ...
    shortDeadline.tasks.deadline_miss_time_ms(3) == 7 && ...
    shortDeadline.tasks.completion_ms(3) == 8, ...
    'One unfinished post-critical tick at the deadline must miss once.');

zeroWork = modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2);
assert(zeroWork.tasks.completed && zeroWork.tasks.completion_ms == 0 && ...
    all(zeroWork.timeline.cpu_owner_task_id == 0) && ...
    zeroWork.metrics.busy_time_ms == 0 && ...
    zeroWork.metrics.idle_time_ms == 2, ...
    'A zero-work job must complete at release without consuming CPU.');

equalPriority = modelFcn([0 0], [1 1], [0 0], [0 0], ...
    [2 2], [1 1], 'none', 1, 2);
assert(isequal(equalPriority.timeline.cpu_owner_task_id, [1 2]) && ...
    isequal(equalPriority.tasks.response_ms, [1 2]), ...
    'Equal-priority simultaneous jobs must use task ID deterministically.');

releaseAtHorizon = modelFcn([0 4], [1 1], [0 0], [0 0], ...
    [4 4], [2 1], 'none', 1, 4);
assert(isequal(releaseAtHorizon.tasks.released, [true false]) && ...
    releaseAtHorizon.metrics.released_count == 1 && ...
    releaseAtHorizon.metrics.released_demand_ms == 1, ...
    'A release exactly at the half-open horizon must be excluded.');

shortHorizon = runFixture(scenarioFcn('baseline', 5, 4, 4));
assert(isequal(shortHorizon.timeline.cpu_owner_task_id, [1 2 1 1]) && ...
    isequal(shortHorizon.tasks.service_ms, [3 1 0]) && ...
    isequal(shortHorizon.tasks.remaining_ms, [3 4 2]) && ...
    shortHorizon.tasks.blocked_time_ms(3) == 2 && ...
    shortHorizon.timeline.mutex_owner_task_id(end) == 1, ...
    'Short horizon must retain service, remainder, blocking, and mutex owner.');
assert(shortHorizon.metrics.released_demand_ms == 13 && ...
    shortHorizon.metrics.served_work_ms == 4 && ...
    shortHorizon.metrics.remaining_work_ms == 9 && ...
    shortHorizon.metrics.work_conservation_error_ms == 0, ...
    'Short-horizon work must conserve served plus remaining demand.');

%% Wait timeout, continued waiting, cancellation, and exact handoff
continueInput = scenarioFcn('wait-continue');
continueWait = runFixture(continueInput);
assert(continueWait.tasks.wait_timed_out(3) && ...
    continueWait.tasks.wait_timeout_time_ms(3) == 4 && ...
    ~continueWait.tasks.cancelled_while_waiting(3) && ...
    continueWait.tasks.completion_ms(3) == 7, ...
    'Continue-waiting must retain one timeout and eventual completion.');
assert(isequal(continueWait.timeline.cpu_owner_task_id, expectedOwner) && ...
    continueWait.tasks.boost_time_ms(1) == 3, ...
    'Continued waiting must retain donation and the clean schedule.');

exactHandoffInput = fixture;
exactHandoffInput.wait_timeout_ms(3) = 3;
exactHandoffInput.timeout_action = 'cancel-waiter';
exactHandoff = runFixture(exactHandoffInput);
assert(~exactHandoff.tasks.wait_timed_out(3) && ...
    ~exactHandoff.tasks.cancelled_while_waiting(3) && ...
    exactHandoff.tasks.resource_acquire_ms(3) == 5 && ...
    exactHandoff.tasks.completion_ms(3) == 7, ...
    'Unlock and handoff at the timeout boundary must win before timeout.');

cancelInput = scenarioFcn('wait-cancel');
cancelledWait = runFixture(cancelInput);
expectedCancelledOwner = [1 2 1 1 2 2 2 2 1 1 1 0 0 0 0 0];
assert(isequal(cancelledWait.timeline.cpu_owner_task_id, ...
    expectedCancelledOwner), ...
    'Waiter cancellation schedule changed.');
assert(cancelledWait.tasks.wait_timed_out(3) && ...
    cancelledWait.tasks.wait_timeout_time_ms(3) == 4 && ...
    cancelledWait.tasks.cancelled_while_waiting(3) && ...
    cancelledWait.tasks.cancellation_time_ms(3) == 4 && ...
    cancelledWait.tasks.cancelled_work_ms(3) == 2 && ...
    cancelledWait.tasks.service_ms(3) == 0 && ...
    isnan(cancelledWait.tasks.completion_ms(3)), ...
    'Cancel-waiter must remove exactly two unserved High ticks at 4 ms.');
assert(cancelledWait.tasks.resource_release_ms(1) == 9 && ...
    cancelledWait.timeline.mutex_owner_task_id(5) == 1 && ...
    cancelledWait.tasks.boost_time_ms(1) == 2, ...
    'Waiter cancellation must withdraw donation without unlocking Low.');
assert(cancelledWait.metrics.released_demand_ms == 13 && ...
    cancelledWait.metrics.served_work_ms == 11 && ...
    cancelledWait.metrics.cancelled_work_ms == 2 && ...
    cancelledWait.metrics.remaining_work_ms == 0 && ...
    cancelledWait.metrics.work_conservation_error_ms == 0, ...
    'Waiter cancellation must conserve served and canceled work.');

sameBoundaryInput = cancelInput;
sameBoundaryInput.relative_deadline_ms(3) = 2;
sameBoundary = runFixture(sameBoundaryInput);
assert(sameBoundary.tasks.deadline_missed(3) && ...
    sameBoundary.tasks.deadline_miss_time_ms(3) == 4 && ...
    sameBoundary.tasks.wait_timed_out(3) && ...
    sameBoundary.tasks.wait_timeout_time_ms(3) == 4, ...
    'Deadline expiry must be retained before waiter timeout at one boundary.');

recoveredAfterCancellation = runFixture(fixture);
assert(isequaln(recoveredAfterCancellation, clean), ...
    'A clean retry after waiter cancellation must recover exactly.');

%% Numeric compatibility and callback lifetime after path cleanup
columnCompatible = modelFcn(uint8(fixture.release_ms.'), ...
    uint8(fixture.pre_critical_ms.'), ...
    uint8(fixture.critical_ms.'), ...
    uint8(fixture.post_critical_ms.'), ...
    uint8(fixture.relative_deadline_ms.'), ...
    int8(fixture.base_priority.'), ...
    string(fixture.protocol), uint8(fixture.tick_ms), ...
    uint8(fixture.horizon_ms), fixture.wait_timeout_ms.', ...
    string(fixture.timeout_action));
assert(isequaln(columnCompatible, clean), ...
    'Integer-class columns and scalar strings must normalize compatibly.');
omittedDefaults = modelFcn(fixture.release_ms, ...
    fixture.pre_critical_ms, fixture.critical_ms, ...
    fixture.post_critical_ms, fixture.relative_deadline_ms, ...
    fixture.base_priority, fixture.protocol, fixture.tick_ms, ...
    fixture.horizon_ms);
emptyDefaults = modelFcn(fixture.release_ms, ...
    fixture.pre_critical_ms, fixture.critical_ms, ...
    fixture.post_critical_ms, fixture.relative_deadline_ms, ...
    fixture.base_priority, [], fixture.tick_ms, fixture.horizon_ms, ...
    [], []);
assert(isequaln(omittedDefaults, clean) && ...
    isequaln(emptyDefaults, clean), ...
    'Omitted and empty protocol/timeout defaults must match the baseline.');

callbackModel = @model;
callbackScenario = @p10_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.release_ms, ...
    callbackInput.pre_critical_ms, callbackInput.critical_ms, ...
    callbackInput.post_critical_ms, ...
    callbackInput.relative_deadline_ms, callbackInput.base_priority, ...
    callbackInput.protocol, callbackInput.tick_ms, ...
    callbackInput.horizon_ms, callbackInput.wait_timeout_ms, ...
    callbackInput.timeout_action);
assert(isequal(callbackOut.timeline.cpu_owner_task_id, expectedOwner), ...
    ['Callback-bound P10 dependencies must survive module path cleanup ' ...
    'and a conflicting P01 model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1), ...
    'P10:model:Arity');
assertReject(@() modelFcn('0', 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Release');
assertReject(@() modelFcn(true, 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Release');
assertReject(@() modelFcn(NaN, 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Release');
assertReject(@() modelFcn(1i, 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Release');
assertReject(@() modelFcn(-1, 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Release');
assertReject(@() modelFcn([0 1; 2 3], [0 0], [0 0], [0 0], ...
    [1 1], [2 1], 'none', 1, 2), 'P10:model:Release');
assertReject(@() modelFcn([0 1], 0, [0 0], [0 0], ...
    [1 1], [2 1], 'none', 1, 2), 'P10:model:VectorLength');
assertReject(@() modelFcn(0, -1, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:PreCritical');
assertReject(@() modelFcn(0, 0, -1, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:Critical');
assertReject(@() modelFcn(0, 0, 0, -1, 1, 1, 'none', 1, 2), ...
    'P10:model:PostCritical');
assertReject(@() modelFcn(0, 0, 0, 0, 0, 1, 'none', 1, 2), ...
    'P10:model:Deadline');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1.5, 'none', 1, 2), ...
    'P10:model:Priority');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, {'none'}, 1, 2), ...
    'P10:model:Protocol');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'ceiling', 1, 2), ...
    'P10:model:Protocol');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 0, 2), ...
    'P10:model:Tick');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 0), ...
    'P10:model:Horizon');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, 0), ...
    'P10:model:WaitTimeout');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, NaN), ...
    'P10:model:WaitTimeout');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, -Inf), ...
    'P10:model:WaitTimeout');
assertReject(@() modelFcn([0 0], [0 0], [0 0], [0 0], ...
    [1 1], [2 1], 'none', 1, 2, [Inf Inf Inf]), ...
    'P10:model:VectorLength');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, ...
    Inf, {'continue-waiting'}), 'P10:model:TimeoutAction');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, ...
    Inf, 'delete-owner'), 'P10:model:TimeoutAction');
assertReject(@() modelFcn(0.5, 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(eps(1), 0, 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, eps(1), 0, 0, 1, 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, 0, eps(1), 0, 1, 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, 0, 0, eps(1), 1, 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, 0, 0, 0, eps(1), 1, 'none', 1, 2), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, eps(1)), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 2, eps(1)), ...
    'P10:model:GridAlignment');
assertReject(@() modelFcn(zeros(1, 17), zeros(1, 17), ...
    zeros(1, 17), zeros(1, 17), ones(1, 17), 1:17, ...
    'none', 1, 2), 'P10:model:ResourceBound');
assertReject(@() modelFcn(0, 0, 0, 0, 1, 1, 'none', 1, 100001), ...
    'P10:model:TimingResourceBound');
assertReject(@() modelFcn(1e9 + 1, 0, 0, 0, 1, 1, ...
    'none', 1, 2), 'P10:model:TimingResourceBound');

largestTaskSet = modelFcn(zeros(1, 16), zeros(1, 16), ...
    zeros(1, 16), zeros(1, 16), ones(1, 16), 1:16, ...
    'none', 1, 1);
assert(largestTaskSet.metrics.released_count == 16 && ...
    largestTaskSet.metrics.completion_count == 16 && ...
    largestTaskSet.metrics.busy_time_ms == 0, ...
    'The accepted task resource bound must retain sixteen zero-work jobs.');
largestHorizon = modelFcn(0, 0, 0, 0, 1, 1, ...
    'none', 1, 100000);
assert(numel(largestHorizon.timeline.time_ms) == 100000 && ...
    largestHorizon.metrics.idle_time_ms == 100000, ...
    'The accepted horizon resource bound must retain 100000 ticks.');
largestFiniteTime = modelFcn(1e9, 0, 0, 0, 1, 1, ...
    'none', 1, 1);
assert(~largestFiniteTime.tasks.released && ...
    largestFiniteTime.metrics.released_count == 0, ...
    'The accepted finite-time bound may remain outside a short horizon.');

largestScenario = scenarioFcn('baseline', 5, 4, 100000);
largestScenarioOut = runFixture(largestScenario);
assert(numel(largestScenarioOut.timeline.time_ms) == 100000 && ...
    largestScenarioOut.metrics.released_count == 3 && ...
    largestScenarioOut.metrics.served_work_ms == 13, ...
    'The largest accepted scenario horizon must remain model-compatible.');
assertReject(@() scenarioFcn({'baseline'}), 'P10:scenario:Kind');
assertReject(@() scenarioFcn('baseline', -1), ...
    'P10:scenario:MediumWork');
assertReject(@() scenarioFcn('baseline', 1001), ...
    'P10:scenario:MediumWork');
assertReject(@() scenarioFcn('baseline', 5, 0), ...
    'P10:scenario:LowCritical');
assertReject(@() scenarioFcn('baseline', 5, 7), ...
    'P10:scenario:LowCritical');
assertReject(@() scenarioFcn('baseline', 5, 4, 0), ...
    'P10:scenario:Horizon');
assertReject(@() scenarioFcn('baseline', 5, 4, 100001), ...
    'P10:scenario:Horizon');
assertReject(@() scenarioFcn('unknown'), 'P10:scenario:Kind');

afterRejection = runFixture(fixture);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('Waiter cancellation is synchronous modeled work removal, not an asynchronous RTOS cancellation API, owner unlock, or physical rollback.');
disp('P10 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
