function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P05.

%% Empty input and exact 8-N-1 frame identities
quiet = model([], 115200, 0, 'none', 1, 0);
assert(quiet.input.frame_count == 0 && ...
    quiet.metrics.correct_count == 0 && quiet.tx.line_time_us == 0, ...
    'Empty input must retain zero frames, correct bytes, and line time.');
assert(isnan(quiet.metrics.minimum_sampling_margin_bits) && ...
    isnan(quiet.metrics.payload_efficiency) && ...
    ~quiet.metrics.pattern_independent_timing_safe, ...
    'Empty input must report observed margin and efficiency as N/A.');
assert(isequal(size(quiet.tx.actual_frame_bits), [0 10]) && ...
    isequal(size(quiet.rx.sample_level), [0 10]), ...
    'Empty 8-N-1 input must preserve bounded zero-row output shapes.');

knownBytes = [0 85 163 255];
known = model(knownBytes, 9600, 0, 'none', 1, 0);
expectedFrames = [ ...
    0 0 0 0 0 0 0 0 0 1; ...
    0 1 0 1 0 1 0 1 0 1; ...
    0 1 1 0 0 0 1 0 1 1; ...
    0 1 1 1 1 1 1 1 1 1];
assert(isequal(known.tx.nominal_frame_bits, expectedFrames), ...
    'Known bytes must encode start-low, eight LSB-first bits, and stop-high.');
assert(isequal(known.tx.actual_frame_bits, expectedFrames) && ...
    isequal(known.rx.sample_level, expectedFrames), ...
    'A clean matched receiver must sample the exact transmitter frame rows.');
assert(isequal(known.rx.decoded_bytes, knownBytes) && ...
    all(known.rx.byte_correct), ...
    'Known 8-N-1 frames must decode to the offered bytes.');
assert(known.config.bits_per_frame == 10 && ...
    known.tx.line_bit_cells == 40, ...
    'Four continuous 8-N-1 bytes must occupy forty line-bit cells.');
assert(abs(known.config.tx_bit_period_us - 1e6 / 9600) < 1e-12 && ...
    abs(known.tx.line_time_us - 40 * 1e6 / 9600) < 1e-10, ...
    'Bit and line time must equal independent inverse-baud calculations.');
assert(abs(known.metrics.nominal_frame_efficiency - 0.8) < 1e-14 && ...
    abs(known.metrics.payload_efficiency - 0.8) < 1e-14, ...
    'Continuous 8-N-1 framing efficiency must equal eight tenths.');
assert(abs(known.metrics.payload_goodput_bps - 0.8 * 9600) < 1e-10, ...
    'Matched continuous 8-N-1 goodput must be eighty percent of bit rate.');
assert(known.metrics.minimum_sampling_margin_bits == 0.5 && ...
    known.metrics.pattern_independent_timing_safe, ...
    'Matched center samples must retain one-half transmitter-bit margin.');

%% Format, parity, stop-bit, and gap limiting cases
evenFormat = model(knownBytes, 9600, 0, 'even', 1, 0);
assert(evenFormat.config.bits_per_frame == 11 && ...
    all(evenFormat.tx.nominal_frame_bits(:, 10) == 0), ...
    'These even-one-count fixtures must append zero even-parity bits.');
assert(all(evenFormat.rx.byte_correct) && ...
    evenFormat.metrics.parity_error_count == 0, ...
    'Matched even-parity frames must pass their parity checks.');
oddFormat = model(knownBytes, 9600, 0, 'odd', 1, 0);
assert(all(oddFormat.tx.nominal_frame_bits(:, 10) == 1) && ...
    all(oddFormat.rx.byte_correct), ...
    'Odd parity must complement the retained even-parity bits.');
twoStops = model(knownBytes, 9600, 0, 'none', 2, 0);
assert(twoStops.config.bits_per_frame == 11 && ...
    all(all(twoStops.tx.actual_frame_bits(:, 10:11) == 1)), ...
    'Two-stop-bit format must append two high slots.');
assert(abs(twoStops.metrics.nominal_frame_efficiency - 8 / 11) < 1e-14, ...
    'A second stop bit must reduce nominal payload efficiency to 8/11.');
withGap = model(knownBytes, 9600, 0, 'none', 1, 2);
assert(withGap.tx.line_bit_cells == 46 && ...
    abs(withGap.tx.line_time_us - 46 * 1e6 / 9600) < 1e-10, ...
    'Three two-bit inter-frame gaps must add six high line-bit cells.');
assert(isequal(withGap.tx.actual_frame_bits, known.tx.actual_frame_bits) && ...
    all(withGap.rx.byte_correct), ...
    'Idle gap must change spacing without changing the framed byte bits.');

%% Independent receiver-clock sweep and exact boundary behavior
errorSweepPct = [-6 -4 -2 0 2 4 6];
expectedMargins = [-5/47 5/48 15/49 1/2 16/51 7/52 -2/53];
expectedDecoded = [213 85 85 85 85 85 85];
observedMargins = zeros(size(errorSweepPct));
observedDecoded = zeros(size(errorSweepPct));
observedFraming = false(size(errorSweepPct));
for sweepIndex = 1:numel(errorSweepPct)
    swept = model(85, 9600, errorSweepPct(sweepIndex), ...
        'none', 1, 0);
    observedMargins(sweepIndex) = ...
        swept.metrics.minimum_sampling_margin_bits;
    observedDecoded(sweepIndex) = swept.rx.decoded_bytes;
    observedFraming(sweepIndex) = swept.rx.framing_error;
end
assert(all(abs(observedMargins - expectedMargins) < 1e-12), ...
    'Receiver-error sweep margins must match independent slot arithmetic.');
assert(isequal(observedDecoded, expectedDecoded), ...
    'Receiver-error sweep decoded bytes must match independent bit lookup.');
assert(isequal(observedFraming, ...
    [false false false false false false true]), ...
    'Only the fast endpoint must sample byte 85 data-low as its stop.');
assert(all(observedMargins(2:6) > 0) && ...
    observedMargins(1) < 0 && observedMargins(end) < 0, ...
    'Retained inner errors must stay inside every slot; endpoints must not.');

boundaryErrorPct = 100 .* (9.5 / 9 - 1);
exactBoundary = model(85, 9600, boundaryErrorPct, 'none', 1, 0);
assert(abs(exactBoundary.metrics.minimum_sampling_margin_bits) < 1e-12 && ...
    ~exactBoundary.metrics.pattern_independent_timing_safe, ...
    'A sample exactly on a slot transition must classify as timing-unsafe.');
assert(exactBoundary.rx.byte_correct, ...
    ['Half-open arithmetic may choose the stop-high side at an exact ' ...
    'boundary without turning that fixture result into a safety guarantee.']);

nearBoundaryErrorPct = 100 .* (9.5 ./ (10 - 1e-11) - 1);
isolatedNearBoundary = model(0, 9600, nearBoundaryErrorPct, ...
    'none', 1, 0);
largeBatchNearBoundary = model(zeros(1, 10001), 9600, ...
    nearBoundaryErrorPct, 'none', 1, 0);
assert(isolatedNearBoundary.metrics.pattern_independent_timing_safe && ...
    largeBatchNearBoundary.metrics.pattern_independent_timing_safe, ...
    'The small positive stop margin must remain timing-safe in both calls.');
assert(largeBatchNearBoundary.rx.byte_correct(10000) && ...
    isequal(largeBatchNearBoundary.rx.sample_level(10000, :), ...
    isolatedNearBoundary.rx.sample_level), ...
    ['Large-index batched-versus-isolated sampling must use the same ' ...
    'frame-local lookup and retain the positive-margin stop sample.']);

continuousSlow = model([85 163 60 126], 115200, -6, ...
    'none', 1, 0);
assert(isequal(continuousSlow.rx.receiver_busy, ...
    [false true false true]), ...
    'A slow receiver must still be sampling when alternating starts arrive.');
assert(continuousSlow.metrics.receiver_busy_count == 2 && ...
    continuousSlow.metrics.correct_count < 4, ...
    'Receiver overrun must remain distinct from decoded-byte correctness.');

nearReadyErrorPct = 100 .* (9.5 ./ (10 + 1e-10) - 1);
isolatedNearReady = model([0 0], 1, nearReadyErrorPct, ...
    'none', 1, 0);
largeBatchNearReady = model(zeros(1, 10001), 1, ...
    nearReadyErrorPct, 'none', 1, 0);
assert(isolatedNearReady.rx.receiver_busy(2) && ...
    largeBatchNearReady.rx.receiver_busy(10000), ...
    ['A receiver still busy by 1e-10 transmitter-bit times must reject ' ...
    'the next start both early and at a late frame index.']);
assert(~isolatedNearReady.rx.attempted(2) && ...
    ~largeBatchNearReady.rx.attempted(10000), ...
    ['Late absolute timestamps must not change the frame-local receiver ' ...
    'readiness decision.']);

%% Transmitter-baud sweep isolates time scaling
baudSweepBps = [9600 19200 57600 115200];
for sweepIndex = 1:numel(baudSweepBps)
    swept = model(knownBytes, baudSweepBps(sweepIndex), 0, ...
        'none', 1, 0);
    expectedTimeUs = 40 .* 1e6 ./ baudSweepBps(sweepIndex);
    assert(abs(swept.tx.line_time_us - expectedTimeUs) < ...
        1e-10 .* max(1, expectedTimeUs), ...
        'Baud sweep line time must retain the forty-bit identity.');
    assert(isequal(swept.tx.actual_frame_bits, expectedFrames) && ...
        all(swept.rx.byte_correct), ...
        'Matched baud sweep must not mutate frame bits or decoded bytes.');
end

%% Single-bit detection, even-bit limitation, and recovery
singleBitFault = struct('mode', 'flip-data', 'frame_index', 2, ...
    'data_bit_indices', 0);
singleWithParity = model([85 163 60], 115200, 0, ...
    'even', 1, 0, singleBitFault, Inf);
assert(singleWithParity.rx.decoded_bytes(2) == 162 && ...
    singleWithParity.rx.parity_error(2), ...
    'One post-parity data-bit flip must alter 163 to 162 and fail even parity.');
assert(~singleWithParity.rx.byte_valid(2) && ...
    singleWithParity.metrics.recovery_frame_index == 3, ...
    'Parity-rejected frame must be followed by an independently valid recovery.');
singleWithoutParity = model([85 163 60], 115200, 0, ...
    'none', 1, 0, singleBitFault, Inf);
assert(singleWithoutParity.rx.byte_valid(2) && ...
    singleWithoutParity.rx.undetected_corruption(2), ...
    'The same one-bit fault under 8-N-1 must remain UART-valid corruption.');
assert(singleWithoutParity.metrics.parity_error_count == 0 && ...
    singleWithoutParity.metrics.undetected_corruption_count == 1, ...
    'No-parity mode must not claim a parity detection it cannot perform.');

twoBitFault = struct('mode', 'flip-data', 'frame_index', 2, ...
    'data_bit_indices', [0 1]);
twoWithParity = model([85 163 60], 115200, 0, ...
    'even', 1, 0, twoBitFault, Inf);
assert(twoWithParity.rx.decoded_bytes(2) == 160 && ...
    ~twoWithParity.rx.parity_error(2), ...
    'Two flipped one-bits must change 163 to 160 while preserving even parity.');
assert(twoWithParity.rx.undetected_corruption(2), ...
    'Even parity must not be presented as detection of every corruption.');

%% Broken stop, lost edge, later recovery, and exact rollback
fixture = p05_scenario('baseline');
clean = model(fixture.payload_bytes, fixture.tx_baud_bps, ...
    fixture.receiver_error_pct, fixture.parity_mode, fixture.stop_bits, ...
    fixture.inter_frame_gap_bits, fixture.fault, ...
    fixture.receive_timeout_us);
brokenFixture = p05_scenario('stop-fault-recovery');
broken = model(brokenFixture.payload_bytes, brokenFixture.tx_baud_bps, ...
    brokenFixture.receiver_error_pct, brokenFixture.parity_mode, ...
    brokenFixture.stop_bits, brokenFixture.inter_frame_gap_bits, ...
    brokenFixture.fault, brokenFixture.receive_timeout_us);
assert(isequal(broken.rx.attempted, [true true false true]), ...
    'Forced-low stop fixture must attempt, fail, miss one edge, then recover.');
assert(isequal(broken.rx.framing_error, [false true false false]) && ...
    broken.metrics.framing_error_count == 1, ...
    'A low stop sample must be classified as one framing error.');
assert(isequal(broken.rx.no_start_edge, [false false true false]) && ...
    broken.metrics.no_start_edge_count == 1, ...
    'Low stop followed by low start must remove exactly one falling edge.');
assert(isequal(broken.rx.byte_correct, [true false false true]) && ...
    broken.metrics.recovery_frame_index == 4, ...
    'Frame four must prove later recovery without restoring lost frames.');
rolledBack = model(fixture.payload_bytes, fixture.tx_baud_bps, ...
    fixture.receiver_error_pct, fixture.parity_mode, fixture.stop_bits, ...
    fixture.inter_frame_gap_bits, [], []);
assert(isequaln(rolledBack, clean), ...
    'Resetting fault and deadline inputs must roll back to the exact baseline.');

%% Deterministic absolute timeout boundaries and recovery by re-invocation
secondCompletionUs = clean.rx.scheduled_sample_time_us(2, end);
atBoundary = model(fixture.payload_bytes, fixture.tx_baud_bps, 0, ...
    'none', 1, 0, [], secondCompletionUs);
assert(isequal(atBoundary.rx.timed_out, [false false true true]) && ...
    atBoundary.metrics.correct_count == 2, ...
    'A deadline exactly at frame two final sample must accept two attempts.');
justBefore = model(fixture.payload_bytes, fixture.tx_baud_bps, 0, ...
    'none', 1, 0, [], secondCompletionUs - 1e-6);
assert(isequal(justBefore.rx.timed_out, [false true true true]) && ...
    justBefore.metrics.correct_count == 1, ...
    'A deadline just before frame two final sample must cut it off.');
deadlineFixture = p05_scenario('deadline');
deadline = model(deadlineFixture.payload_bytes, ...
    deadlineFixture.tx_baud_bps, deadlineFixture.receiver_error_pct, ...
    deadlineFixture.parity_mode, deadlineFixture.stop_bits, ...
    deadlineFixture.inter_frame_gap_bits, deadlineFixture.fault, ...
    deadlineFixture.receive_timeout_us);
assert(deadline.metrics.correct_count == 2 && ...
    deadline.metrics.timed_out_count == 2, ...
    'The fixed 170 us deadline must retain two receive attempts and cut two off.');
timeoutRecovery = model(fixture.payload_bytes, fixture.tx_baud_bps, ...
    0, 'none', 1, 0, [], Inf);
assert(isequaln(timeoutRecovery, clean), ...
    'An infinite-deadline re-invocation must recover the isolated clean result.');
% This finite pure calculation has no asynchronous wait or cancellation API.

%% Determinism, state isolation, shape, numeric, and optional-input compatibility
first = model(fixture.payload_bytes, 115200, 0, 'none', 1, 0);
second = model(fixture.payload_bytes, 115200, 0, 'none', 1, 0);
assert(isequaln(first, second), ...
    'Repeated calls must be deterministic and state-isolated.');
columnInput = model(uint8([85; 163]), uint32(115200), int8(0), ...
    string('none'), uint8(1), uint8(0));
assert(isrow(columnInput.input.payload_bytes) && ...
    isa(columnInput.input.payload_bytes, 'double'), ...
    'Column and integer byte inputs must normalize to a double row vector.');
assert(isequal(columnInput.rx.decoded_bytes, [85 163]) && ...
    all(columnInput.rx.byte_correct), ...
    'Supported shape and numeric classes must retain byte compatibility.');
explicitDefaults = model(fixture.payload_bytes, 115200, 0, ...
    'none', 1, 0, [], []);
assert(isequaln(first, explicitDefaults), ...
    'Omitted and empty optional fault/deadline inputs must be compatible.');

%% Callback dependency lifetime across launcher cleanup and module switches
callbackModel = @model;
callbackScenario = @p05_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackFixture = callbackScenario('baseline');
callbackOut = callbackModel(callbackFixture.payload_bytes, ...
    callbackFixture.tx_baud_bps, 0, 'none', 1, 0);
assert(callbackOut.metrics.correct_count == 4 && ...
    callbackOut.config.bits_per_frame == 10, ...
    ['Callback-bound P05 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed input, fault, timing, and resource-bound rejection
assertReject(@() model(85, 9600, 0, 'none', 1), 'P05:model:Arity');
assertReject(@() model({85}, 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model([1 2; 3 4], 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model([85 NaN], 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model([85 1i], 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model(1.5, 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model(-1, 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model(256, 9600, 0, 'none', 1, 0), ...
    'P05:model:PayloadBytes');
assertReject(@() model(85, 0, 0, 'none', 1, 0), ...
    'P05:model:BaudRate');
assertReject(@() model(85, Inf, 0, 'none', 1, 0), ...
    'P05:model:BaudRate');
assertReject(@() model(85, 1e9 + 1, 0, 'none', 1, 0), ...
    'P05:model:BaudRate');
assertReject(@() model(85, 9600, -40, 'none', 1, 0), ...
    'P05:model:ReceiverError');
assertReject(@() model(85, 9600, 40, 'none', 1, 0), ...
    'P05:model:ReceiverError');
assertReject(@() model(85, 9600, NaN, 'none', 1, 0), ...
    'P05:model:ReceiverError');
assertReject(@() model(85, 9600, 0, {'none'}, 1, 0), ...
    'P05:model:ParityMode');
assertReject(@() model(85, 9600, 0, 'mark', 1, 0), ...
    'P05:model:ParityMode');
assertReject(@() model(85, 9600, 0, 'none', 0, 0), ...
    'P05:model:StopBits');
assertReject(@() model(85, 9600, 0, 'none', 1.5, 0), ...
    'P05:model:StopBits');
assertReject(@() model(85, 9600, 0, 'none', 3, 0), ...
    'P05:model:StopBits');
assertReject(@() model(85, 9600, 0, 'none', 1, -1), ...
    'P05:model:InterFrameGap');
assertReject(@() model(85, 9600, 0, 'none', 1, 1001), ...
    'P05:model:InterFrameGap');
assertReject(@() model(85, 9600, 0, 'none', 1, NaN), ...
    'P05:model:InterFrameGap');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, [], -1), ...
    'P05:model:ReceiveTimeout');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, [], NaN), ...
    'P05:model:ReceiveTimeout');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, [], -Inf), ...
    'P05:model:ReceiveTimeout');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, {'none'}, Inf), ...
    'P05:model:Fault');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, struct(), Inf), ...
    'P05:model:Fault');
extraFault = struct('mode', 'none', 'extra', 1);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, extraFault, Inf), ...
    'P05:model:Fault');
badMode = struct('mode', 'invert-line');
assertReject(@() model(85, 9600, 0, 'none', 1, 0, badMode, Inf), ...
    'P05:model:Fault');
missingFrame = struct('mode', 'flip-data', 'data_bit_indices', 0);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, missingFrame, Inf), ...
    'P05:model:FaultFrame');
badFrame = struct('mode', 'force-stop-low', 'frame_index', 2);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, badFrame, Inf), ...
    'P05:model:FaultFrame');
missingBit = struct('mode', 'flip-data', 'frame_index', 1);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, missingBit, Inf), ...
    'P05:model:FaultBit');
duplicateBits = struct('mode', 'flip-data', 'frame_index', 1, ...
    'data_bit_indices', [0 0]);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, ...
    duplicateBits, Inf), 'P05:model:FaultBit');
badBit = struct('mode', 'flip-data', 'frame_index', 1, ...
    'data_bit_indices', 8);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, badBit, Inf), ...
    'P05:model:FaultBit');
tooManyFaultBits = struct('mode', 'flip-data', 'frame_index', 1, ...
    'data_bit_indices', zeros(1, 9));
assertReject(@() model(85, 9600, 0, 'none', 1, 0, ...
    tooManyFaultBits, Inf), 'P05:model:ResourceBound');
stopWithDataBit = struct('mode', 'force-stop-low', 'frame_index', 1, ...
    'data_bit_indices', 0);
assertReject(@() model(85, 9600, 0, 'none', 1, 0, ...
    stopWithDataBit, Inf), 'P05:model:FaultBit');

tooManyFrames = zeros(1, 100001);
assertReject(@() model(tooManyFrames, 9600, 0, 'none', 1, 0), ...
    'P05:model:ResourceBound');
clear tooManyFrames;
tooManySamples = zeros(1, 83334);
assertReject(@() model(tooManySamples, 9600, 0, 'even', 2, 0), ...
    'P05:model:ResourceBound');
clear tooManySamples;
tooManyLineCells = zeros(1, 1000);
assertReject(@() model(tooManyLineCells, 9600, 0, 'none', 1, 1000), ...
    'P05:model:ResourceBound');
clear tooManyLineCells;
assertReject(@() p05_scenario({'baseline'}), 'P05:scenario:Kind');
assertReject(@() p05_scenario('unknown'), 'P05:scenario:Kind');

afterRejection = model(fixture.payload_bytes, 115200, 0, 'none', 1, 0);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('P05 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
