function out = model(payloadBytes, spiClockHz, i2cClockHz, ...
    i2cAddress7, registerAddress, fault, transactionTimeoutUs)
%MODEL Compare explicit SPI and I2C register-read transactions.
%   The same expected payload is read from one device register by two
%   transparent deterministic fixtures:
%
%   * SPI uses mode 0, MSB-first cells, one device-specific read-command
%     byte, N dummy MOSI bytes, and one continuous active-low chip select.
%   * I2C uses a 7-bit address, write direction, register byte, repeated
%     START, read direction, N data bytes, and one ninth-clock response per
%     byte. N is at least one because the controller must NACK a final read
%     byte before STOP.
%
%   START, repeated START, and STOP are boundary conditions and add no SCL
%   pulses in this clock-count abstraction. A finite transactionTimeoutUs
%   is a deterministic result deadline, not an asynchronous device wait.

if nargin < 5 || nargin > 7
    error('P06:model:Arity', ...
        ['Expected payloadBytes, spiClockHz, i2cClockHz, i2cAddress7, ' ...
        'registerAddress, and optional fault and transactionTimeoutUs.']);
end
if nargin < 6 || isempty(fault)
    fault = defaultFault();
end
if nargin < 7 || isempty(transactionTimeoutUs)
    transactionTimeoutUs = Inf;
end

maxPayloadBytes = 100000;
maxClockedCells = 850000;
payloadCount = numel(payloadBytes);
if payloadCount > maxPayloadBytes
    error('P06:model:ResourceBound', ...
        'At most one hundred thousand payload bytes are allowed.');
end
payloadBytes = validatePayload(payloadBytes);
spiClockHz = validateClock(spiClockHz, 'P06:model:SPIClock', ...
    'spiClockHz');
i2cClockHz = validateClock(i2cClockHz, 'P06:model:I2CClock', ...
    'i2cClockHz');
i2cAddress7 = validateIntegerScalar(i2cAddress7, 8, 119, ...
    'P06:model:I2CAddress', 'i2cAddress7');
registerAddress = validateIntegerScalar(registerAddress, 0, 127, ...
    'P06:model:RegisterAddress', 'registerAddress');
transactionTimeoutUs = validateTimeout(transactionTimeoutUs);
fault = validateFault(fault, payloadCount);

spiClockedBitCount = 8 .* (payloadCount + 1);
i2cNominalClockedBitCount = 9 .* (payloadCount + 3);
if spiClockedBitCount > maxClockedCells || ...
        i2cNominalClockedBitCount > maxClockedCells
    error('P06:model:ResourceBound', ...
        'Each protocol must remain at or below 850000 clocked cells.');
end

%% SPI: command and dummy MOSI bytes shift with dummy and payload MISO bytes
spiCommandByte = 128 + registerAddress;
spiMosiBytes = [spiCommandByte zeros(1, payloadCount)];
spiMisoNominalBytes = [0 payloadBytes];
spiMosiBitMatrix = byteBitMatrixMsb(spiMosiBytes);
spiMisoNominalBitMatrix = byteBitMatrixMsb(spiMisoNominalBytes);
spiMosiBits = reshape(spiMosiBitMatrix.', 1, []);
spiMisoNominalBits = reshape(spiMisoNominalBitMatrix.', 1, []);
spiChipSelectLevels = zeros(1, spiClockedBitCount);
spiMisoActualBits = spiMisoNominalBits;
if strcmp(fault.mode, 'spi-bit-flip')
    bytePosition = fault.spi_payload_index + 1;
    bitColumnMsbFirst = 8 - fault.spi_bit_index;
    wireBitIndex = (bytePosition - 1) .* 8 + bitColumnMsbFirst;
    spiMisoActualBits(wireBitIndex) = 1 - ...
        spiMisoActualBits(wireBitIndex);
end
spiReceivedBytes = bitsToBytesMsb(spiMisoActualBits);
spiReceivedPayload = spiReceivedBytes(2:end);
spiWireByteCorrect = spiReceivedPayload == payloadBytes;
spiClockedTimeUs = spiClockedBitCount .* 1e6 ./ spiClockHz;
if ~isfinite(spiClockedTimeUs)
    error('P06:model:TimingResourceBound', ...
        'The SPI clock and payload must produce a finite duration.');
end
spiTimedOut = deadlineExceeded(spiClockedTimeUs, transactionTimeoutUs);
spiTransactionComplete = ~spiTimedOut;
spiPayloadByteCorrect = spiWireByteCorrect & spiTransactionComplete;
spiPayloadCorrect = spiTransactionComplete && all(spiWireByteCorrect);
spiUndetectedCorruption = spiTransactionComplete & ~spiWireByteCorrect;
if spiTransactionComplete
    spiCommittedPayload = spiReceivedPayload;
else
    spiCommittedPayload = zeros(1, 0);
end

%% I2C: address-write, register, repeated START, address-read, then data
i2cHeaderBytes = [2 .* i2cAddress7 registerAddress ...
    2 .* i2cAddress7 + 1];
i2cHeaderBitMatrix = byteBitMatrixMsb(i2cHeaderBytes);
i2cDataBitMatrix = byteBitMatrixMsb(payloadBytes);
i2cTargetAckBits = zeros(1, 3);
if strcmp(fault.mode, 'i2c-target-nack')
    i2cTargetAckBits(fault.i2c_ack_index) = 1;
end
i2cTargetNackIndex = find(i2cTargetAckBits == 1, 1, 'first');
i2cTargetNackDetected = ~isempty(i2cTargetNackIndex);
if i2cTargetNackDetected
    attemptedHeaderCount = i2cTargetNackIndex;
    i2cActualClockedBitCount = 9 .* attemptedHeaderCount;
else
    attemptedHeaderCount = 3;
    i2cActualClockedBitCount = i2cNominalClockedBitCount;
end

i2cClockedSdaBits = zeros(1, i2cActualClockedBitCount);
i2cResponseBits = zeros(1, attemptedHeaderCount);
i2cResponseOwners = cell(1, attemptedHeaderCount);
cursor = 0;
for headerIndex = 1:attemptedHeaderCount
    i2cClockedSdaBits(cursor + (1:8)) = ...
        i2cHeaderBitMatrix(headerIndex, :);
    i2cClockedSdaBits(cursor + 9) = i2cTargetAckBits(headerIndex);
    i2cResponseBits(headerIndex) = i2cTargetAckBits(headerIndex);
    i2cResponseOwners{headerIndex} = 'target';
    cursor = cursor + 9;
end

i2cControllerResponseBits = zeros(1, 0);
if ~i2cTargetNackDetected
    i2cControllerResponseBits = zeros(1, payloadCount);
    if payloadCount > 0
        i2cControllerResponseBits(end) = 1;
    end
    i2cResponseBits = [i2cResponseBits i2cControllerResponseBits];
    i2cResponseOwners = [i2cResponseOwners ...
        repmat({'controller'}, 1, payloadCount)];
    for payloadIndex = 1:payloadCount
        i2cClockedSdaBits(cursor + (1:8)) = ...
            i2cDataBitMatrix(payloadIndex, :);
        i2cClockedSdaBits(cursor + 9) = ...
            i2cControllerResponseBits(payloadIndex);
        cursor = cursor + 9;
    end
end

i2cStretchUs = fault.i2c_stretch_us;
i2cClockedTimeUs = i2cActualClockedBitCount .* 1e6 ./ i2cClockHz;
i2cModeledElapsedTimeUs = i2cClockedTimeUs + i2cStretchUs;
if ~isfinite(i2cModeledElapsedTimeUs)
    error('P06:model:TimingResourceBound', ...
        'The I2C clock, stretch, and payload must produce a finite duration.');
end
i2cTimedOut = deadlineExceeded(i2cModeledElapsedTimeUs, ...
    transactionTimeoutUs);
i2cTransactionComplete = ~i2cTargetNackDetected && ~i2cTimedOut;
i2cPayloadByteCorrect = repmat(i2cTransactionComplete, 1, payloadCount);
i2cPayloadCorrect = i2cTransactionComplete;
if i2cTargetNackDetected
    i2cWirePayload = zeros(1, 0);
else
    i2cWirePayload = payloadBytes;
end
if i2cTransactionComplete
    i2cCommittedPayload = payloadBytes;
else
    i2cCommittedPayload = zeros(1, 0);
end
i2cIntentionalFinalNack = ~i2cTargetNackDetected && ...
    payloadCount > 0 && i2cControllerResponseBits(end) == 1;
i2cRepeatedStartPresent = attemptedHeaderCount >= 3;
i2cResponseClockIndices = 9:9:i2cActualClockedBitCount;

%% Comparable metrics
spiNominalPayloadEfficiency = payloadCount .* 8 ./ spiClockedBitCount;
i2cNominalPayloadEfficiency = payloadCount .* 8 ./ ...
    i2cNominalClockedBitCount;
spiCorrectPayloadGoodputBps = sum(spiPayloadByteCorrect) .* 8 ./ ...
    (spiClockedTimeUs .* 1e-6);
i2cCorrectPayloadGoodputBps = sum(i2cPayloadByteCorrect) .* 8 ./ ...
    (i2cModeledElapsedTimeUs .* 1e-6);

out = struct();
out.input = struct( ...
    'payload_bytes', payloadBytes, ...
    'payload_count', payloadCount, ...
    'i2c_address_7bit', i2cAddress7, ...
    'register_address', registerAddress);
out.config = struct( ...
    'spi_clock_hz', spiClockHz, ...
    'i2c_clock_hz', i2cClockHz, ...
    'transaction_timeout_us', transactionTimeoutUs, ...
    'fault', fault);
out.spi = struct( ...
    'mode', 0, ...
    'bit_order', 'MSB-first', ...
    'chip_select_active_level', 0, ...
    'chip_select_idle_level', 1, ...
    'chip_select_assert_clock_index', 0, ...
    'chip_select_deassert_clock_index', spiClockedBitCount, ...
    'chip_select_level_during_clocked_cells', spiChipSelectLevels, ...
    'command_byte', spiCommandByte, ...
    'mosi_bytes', spiMosiBytes, ...
    'miso_nominal_bytes', spiMisoNominalBytes, ...
    'mosi_bits', spiMosiBits, ...
    'miso_nominal_bits', spiMisoNominalBits, ...
    'miso_actual_bits', spiMisoActualBits, ...
    'received_payload_bytes', spiReceivedPayload, ...
    'committed_payload_bytes', spiCommittedPayload, ...
    'wire_payload_byte_correct', spiWireByteCorrect, ...
    'payload_byte_correct', spiPayloadByteCorrect, ...
    'clocked_bit_count', spiClockedBitCount, ...
    'clocked_time_us', spiClockedTimeUs, ...
    'modeled_elapsed_time_us', spiClockedTimeUs, ...
    'timed_out', spiTimedOut, ...
    'transaction_complete', spiTransactionComplete, ...
    'payload_correct', spiPayloadCorrect, ...
    'error_detected', spiTimedOut, ...
    'undetected_corruption', spiUndetectedCorruption);
out.i2c = struct( ...
    'header_bytes', i2cHeaderBytes, ...
    'target_ack_bits', i2cTargetAckBits, ...
    'controller_response_bits', i2cControllerResponseBits, ...
    'response_bits', i2cResponseBits, ...
    'response_owners', {i2cResponseOwners}, ...
    'response_clock_indices', i2cResponseClockIndices, ...
    'clocked_sda_bits', i2cClockedSdaBits, ...
    'wire_payload_bytes', i2cWirePayload, ...
    'committed_payload_bytes', i2cCommittedPayload, ...
    'nominal_clocked_bit_count', i2cNominalClockedBitCount, ...
    'actual_clocked_bit_count', i2cActualClockedBitCount, ...
    'start_clock_index', 0, ...
    'repeated_start_clock_index', 18, ...
    'stop_clock_index', i2cActualClockedBitCount, ...
    'repeated_start_present', i2cRepeatedStartPresent, ...
    'clock_stretch_us', i2cStretchUs, ...
    'stretch_after_clock_index', 18, ...
    'clocked_time_us', i2cClockedTimeUs, ...
    'modeled_elapsed_time_us', i2cModeledElapsedTimeUs, ...
    'target_nack_detected', i2cTargetNackDetected, ...
    'target_nack_index', scalarOrNaN(i2cTargetNackIndex), ...
    'intentional_final_nack', i2cIntentionalFinalNack, ...
    'timed_out', i2cTimedOut, ...
    'transaction_complete', i2cTransactionComplete, ...
    'payload_byte_correct', i2cPayloadByteCorrect, ...
    'payload_correct', i2cPayloadCorrect, ...
    'error_detected', i2cTargetNackDetected || i2cTimedOut);
out.metrics = struct( ...
    'spi_nominal_payload_efficiency', spiNominalPayloadEfficiency, ...
    'i2c_nominal_payload_efficiency', i2cNominalPayloadEfficiency, ...
    'spi_correct_payload_count', sum(spiPayloadByteCorrect), ...
    'i2c_correct_payload_count', sum(i2cPayloadByteCorrect), ...
    'spi_correct_payload_goodput_bps', spiCorrectPayloadGoodputBps, ...
    'i2c_correct_payload_goodput_bps', i2cCorrectPayloadGoodputBps, ...
    'spi_undetected_corruption_count', sum(spiUndetectedCorruption), ...
    'i2c_target_nack_count', double(i2cTargetNackDetected), ...
    'elapsed_ratio_i2c_to_spi', ...
    i2cModeledElapsedTimeUs ./ spiClockedTimeUs);
out.claim_boundary = [ ...
    'Deterministic synthetic clock-cell accounting for one device-specific ' ...
    'register-read fixture; not a hardware measurement or standards ' ...
    'conformance result.'];
end

function payloadBytes = validatePayload(payloadBytes)
validType = isnumeric(payloadBytes) && isreal(payloadBytes) && ...
    isvector(payloadBytes) && ~isempty(payloadBytes);
if ~validType
    error('P06:model:PayloadBytes', ...
        ['payloadBytes must be a nonempty real numeric vector; the I2C ' ...
        'read requires a final byte for the controller to NACK.']);
end
payloadBytes = reshape(double(payloadBytes), 1, []);
if any(~isfinite(payloadBytes)) || any(payloadBytes ~= round(payloadBytes)) || ...
        any(payloadBytes < 0) || any(payloadBytes > 255)
    error('P06:model:PayloadBytes', ...
        'payloadBytes values must be finite integers in [0, 255].');
end
end

function value = validateClock(value, identifier, label)
value = validateFiniteScalar(value, identifier, label);
if value < 1 || value > 1e8
    error(identifier, '%s must lie in [1, 1e8] Hz.', label);
end
end

function value = validateIntegerScalar(value, lowerBound, upperBound, ...
    identifier, label)
value = validateFiniteScalar(value, identifier, label);
if value ~= round(value) || value < lowerBound || value > upperBound
    error(identifier, '%s must be an integer in [%d, %d].', ...
        label, lowerBound, upperBound);
end
end

function value = validateFiniteScalar(value, identifier, label)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
if ~valid
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function timeoutUs = validateTimeout(timeoutUs)
validType = isnumeric(timeoutUs) && isreal(timeoutUs) && ...
    isscalar(timeoutUs);
validValue = validType && ...
    ((isfinite(timeoutUs) && timeoutUs >= 0) || ...
    (isinf(timeoutUs) && timeoutUs > 0));
if ~validValue
    error('P06:model:TransactionTimeout', ...
        ['transactionTimeoutUs must be nonnegative and finite, or ' ...
        'positive Inf.']);
end
timeoutUs = double(timeoutUs);
end

function fault = defaultFault()
fault = struct( ...
    'mode', 'none', ...
    'i2c_ack_index', 0, ...
    'spi_payload_index', 0, ...
    'spi_bit_index', 0, ...
    'i2c_stretch_us', 0);
end

function fault = validateFault(candidate, payloadCount)
if ~isstruct(candidate) || ~isscalar(candidate) || ...
        ~isfield(candidate, 'mode')
    error('P06:model:Fault', ...
        'fault must be a scalar struct with a mode field.');
end
allowedFields = {'mode', 'i2c_ack_index', 'spi_payload_index', ...
    'spi_bit_index', 'i2c_stretch_us'};
if any(~ismember(fieldnames(candidate), allowedFields))
    error('P06:model:Fault', 'fault contains an unsupported field.');
end
mode = candidate.mode;
if ~(ischar(mode) || (isstring(mode) && isscalar(mode)))
    error('P06:model:FaultMode', 'fault.mode must be scalar text.');
end
mode = lower(strtrim(char(mode)));
if ~any(strcmp(mode, {'none', 'i2c-target-nack', ...
        'spi-bit-flip', 'i2c-clock-stretch'}))
    error('P06:model:FaultMode', ...
        ['fault.mode must be none, i2c-target-nack, spi-bit-flip, ' ...
        'or i2c-clock-stretch.']);
end

fault = defaultFault();
fault.mode = mode;
switch mode
    case 'none'
        rejectActiveFields(candidate, allowedFields(2:end));
    case 'i2c-target-nack'
        requireField(candidate, 'i2c_ack_index');
        fault.i2c_ack_index = validateIntegerScalar( ...
            candidate.i2c_ack_index, 1, 3, ...
            'P06:model:I2CAckIndex', 'fault.i2c_ack_index');
        rejectActiveFields(candidate, ...
            {'spi_payload_index', 'spi_bit_index', 'i2c_stretch_us'});
    case 'spi-bit-flip'
        requireField(candidate, 'spi_payload_index');
        requireField(candidate, 'spi_bit_index');
        fault.spi_payload_index = validateIntegerScalar( ...
            candidate.spi_payload_index, 1, max(1, payloadCount), ...
            'P06:model:SPIPayloadIndex', 'fault.spi_payload_index');
        if payloadCount == 0
            error('P06:model:SPIPayloadIndex', ...
                'A SPI bit flip requires at least one payload byte.');
        end
        fault.spi_bit_index = validateIntegerScalar( ...
            candidate.spi_bit_index, 0, 7, ...
            'P06:model:SPIBitIndex', 'fault.spi_bit_index');
        rejectActiveFields(candidate, ...
            {'i2c_ack_index', 'i2c_stretch_us'});
    case 'i2c-clock-stretch'
        requireField(candidate, 'i2c_stretch_us');
        fault.i2c_stretch_us = validateFiniteScalar( ...
            candidate.i2c_stretch_us, ...
            'P06:model:ClockStretch', 'fault.i2c_stretch_us');
        if fault.i2c_stretch_us <= 0 || fault.i2c_stretch_us > 1e6
            error('P06:model:ClockStretch', ...
                'fault.i2c_stretch_us must lie in (0, 1e6] us.');
        end
        rejectActiveFields(candidate, ...
            {'i2c_ack_index', 'spi_payload_index', 'spi_bit_index'});
end
end

function requireField(candidate, fieldName)
if ~isfield(candidate, fieldName)
    error('P06:model:FaultField', ...
        'Fault mode requires field %s.', fieldName);
end
end

function rejectActiveFields(candidate, fieldNames)
for fieldIndex = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIndex};
    if ~isfield(candidate, fieldName)
        continue;
    end
    value = candidate.(fieldName);
    inactive = isempty(value) || ...
        (isnumeric(value) && isreal(value) && isscalar(value) && value == 0);
    if ~inactive
        error('P06:model:FaultField', ...
            'Field %s is not active for this fault mode.', fieldName);
    end
end
end

function bitMatrix = byteBitMatrixMsb(bytes)
byteCount = numel(bytes);
bitMatrix = zeros(byteCount, 8);
for column = 1:8
    bitWeight = 2 .^ (8 - column);
    bitMatrix(:, column) = mod(floor(bytes(:) ./ bitWeight), 2);
end
end

function bytes = bitsToBytesMsb(bits)
byteCount = numel(bits) ./ 8;
bitMatrix = reshape(bits, 8, byteCount).';
bytes = zeros(1, byteCount);
for column = 1:8
    bytes = bytes + bitMatrix(:, column).' .* 2 .^ (8 - column);
end
end

function exceeded = deadlineExceeded(durationUs, timeoutUs)
if isinf(timeoutUs)
    exceeded = false;
    return;
end
exceeded = durationUs > timeoutUs;
end

function value = scalarOrNaN(candidate)
if isempty(candidate)
    value = NaN;
else
    value = candidate;
end
end
