function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P06.

%% Zero-length rejection and one-byte limiting case
assertReject(@() model([], 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() p06_scenario('baseline', 0), ...
    'P06:scenario:PayloadCount');

oneByte = model(163, 400000, 400000, 72, 45);
assert(oneByte.spi.clocked_bit_count == 16 && ...
    oneByte.i2c.nominal_clocked_bit_count == 36, ...
    'One returned byte must require 16 SPI and 36 I2C pulses.');
assert(abs(oneByte.metrics.spi_nominal_payload_efficiency - 0.5) < 1e-14 && ...
    abs(oneByte.metrics.i2c_nominal_payload_efficiency - 8 / 36) < 1e-14, ...
    'One-byte efficiencies must match independent pulse accounting.');
assert(isequal(oneByte.i2c.response_bits, [0 0 0 1]) && ...
    oneByte.i2c.intentional_final_nack && ...
    oneByte.i2c.transaction_complete, ...
    'A one-byte clean read must end successfully with controller NACK.');

%% Exact baseline bytes, MSB-first cells, ownership, time, and efficiency
fixture = p06_scenario('baseline');
clean = model(fixture.payload_bytes, fixture.spi_clock_hz, ...
    fixture.i2c_clock_hz, fixture.i2c_address_7bit, ...
    fixture.register_address, fixture.fault, ...
    fixture.transaction_timeout_us);
assert(isequal(fixture.payload_bytes, [163 86 201 30]) && ...
    clean.spi.command_byte == 173, ...
    'The baseline must retain payload A3 56 C9 1E and command AD.');
assert(isequal(clean.spi.mosi_bits(1:8), [1 0 1 0 1 1 0 1]) && ...
    all(clean.spi.mosi_bits(9:end) == 0), ...
    'SPI MOSI must send command AD MSB-first, then four dummy bytes.');
expectedPayloadBits = [ ...
    1 0 1 0 0 0 1 1; ...
    0 1 0 1 0 1 1 0; ...
    1 1 0 0 1 0 0 1; ...
    0 0 0 1 1 1 1 0];
assert(all(clean.spi.miso_actual_bits(1:8) == 0) && ...
    isequal(reshape(clean.spi.miso_actual_bits(9:end), 8, 4).', ...
    expectedPayloadBits), ...
    'SPI MISO must retain one dummy byte then exact MSB-first payload cells.');
assert(isequal(clean.spi.received_payload_bytes, [163 86 201 30]) && ...
    clean.spi.payload_correct, ...
    'Clean SPI cells must reconstruct the expected returned bytes.');
assert(clean.spi.chip_select_active_level == 0 && ...
    clean.spi.chip_select_idle_level == 1 && ...
    clean.spi.chip_select_assert_clock_index == 0 && ...
    clean.spi.chip_select_deassert_clock_index == 40 && ...
    isequal(clean.spi.chip_select_level_during_clocked_cells, ...
        zeros(1, 40)), ...
    'One active-low chip select must span every command and payload clock.');

assert(isequal(clean.i2c.header_bytes, [144 45 145]), ...
    'I2C headers must be address-write 90, register 2D, address-read 91.');
expectedHeaderBits = [ ...
    1 0 0 1 0 0 0 0; ...
    0 0 1 0 1 1 0 1; ...
    1 0 0 1 0 0 0 1];
for headerIndex = 1:3
    startIndex = (headerIndex - 1) .* 9 + 1;
    assert(isequal(clean.i2c.clocked_sda_bits( ...
        startIndex:(startIndex + 7)), expectedHeaderBits(headerIndex, :)), ...
        'Each I2C header byte must be flattened MSB-first.');
end
assert(isequal(clean.i2c.response_bits, [0 0 0 0 0 0 1]), ...
    'Clean response bits must be six ACKs then controller final NACK.');
assert(isequal(clean.i2c.response_owners, ...
    {'target', 'target', 'target', 'controller', 'controller', ...
    'controller', 'controller'}), ...
    'The first three responses are target-owned; data responses are controller-owned.');
assert(clean.i2c.repeated_start_clock_index == 18 && ...
    clean.i2c.stop_clock_index == 63 && ...
    clean.i2c.repeated_start_present, ...
    'Repeated START and STOP must retain clock-boundary positions 18 and 63.');
assert(clean.i2c.intentional_final_nack && ...
    ~clean.i2c.target_nack_detected && ~clean.i2c.error_detected && ...
    clean.i2c.payload_correct, ...
    'Final controller NACK must remain successful termination, not failure.');

assert(clean.spi.clocked_bit_count == 40 && ...
    clean.i2c.nominal_clocked_bit_count == 63, ...
    'Four bytes must use 40 simultaneous SPI and 63 I2C clock pulses.');
assert(abs(clean.spi.clocked_time_us - 100) < 1e-12 && ...
    abs(clean.i2c.clocked_time_us - 157.5) < 1e-12, ...
    'Equal 400 kHz clocks must yield 100 and 157.5 us clocked times.');
assert(abs(clean.metrics.spi_nominal_payload_efficiency - 0.8) < 1e-14 && ...
    abs(clean.metrics.i2c_nominal_payload_efficiency - 32 / 63) < 1e-14, ...
    'Baseline payload efficiencies must be 32/40 and 32/63.');
assert(abs(clean.metrics.elapsed_ratio_i2c_to_spi - 63 / 40) < 1e-14, ...
    'At equal clocks and no stretch, elapsed-time ratio must equal 63/40.');

%% Payload-length sweep and asymptotic overhead limits
payloadCountSweep = [1 2 4 8 16];
expectedSpiPulses = [16 24 40 72 136];
expectedI2cPulses = [36 45 63 99 171];
spiEfficiencies = zeros(size(payloadCountSweep));
i2cEfficiencies = zeros(size(payloadCountSweep));
for sweepIndex = 1:numel(payloadCountSweep)
    sweptFixture = p06_scenario('baseline', payloadCountSweep(sweepIndex));
    swept = model(sweptFixture.payload_bytes, 400000, 400000, 72, 45);
    assert(swept.spi.clocked_bit_count == expectedSpiPulses(sweepIndex) && ...
        swept.i2c.nominal_clocked_bit_count == ...
        expectedI2cPulses(sweepIndex), ...
        'Payload-length sweep pulse counts must match independent formulas.');
    assert(swept.config.spi_clock_hz == clean.config.spi_clock_hz && ...
        swept.config.i2c_clock_hz == clean.config.i2c_clock_hz && ...
        swept.input.i2c_address_7bit == clean.input.i2c_address_7bit && ...
        swept.input.register_address == clean.input.register_address, ...
        'Payload-length sweep must isolate length from clocks and headers.');
    spiEfficiencies(sweepIndex) = ...
        swept.metrics.spi_nominal_payload_efficiency;
    i2cEfficiencies(sweepIndex) = ...
        swept.metrics.i2c_nominal_payload_efficiency;
end
assert(all(diff(spiEfficiencies) > 0) && ...
    all(diff(i2cEfficiencies) > 0), ...
    'Fixed-overhead amortization must raise both payload efficiencies.');
largeLimit = model(zeros(1, 1000), 400000, 400000, 72, 45);
assert(abs(largeLimit.metrics.spi_nominal_payload_efficiency - ...
    1000 / 1001) < 1e-14 && ...
    abs(largeLimit.metrics.i2c_nominal_payload_efficiency - ...
    8000 / 9027) < 1e-14, ...
    'Large reads must approach fixture limits one and eight-ninths.');

%% Clock and stretch sweeps isolate time from cell structure
clockSweepHz = [100000 200000 400000 800000];
for sweepIndex = 1:numel(clockSweepHz)
    swept = model(fixture.payload_bytes, clockSweepHz(sweepIndex), ...
        400000, 72, 45);
    assert(abs(swept.spi.clocked_time_us - ...
        40 .* 1e6 ./ clockSweepHz(sweepIndex)) < 1e-12 && ...
        swept.i2c.clocked_time_us == clean.i2c.clocked_time_us, ...
        'SPI clock sweep must scale only SPI clocked time.');
    assert(isequal(swept.spi.mosi_bits, clean.spi.mosi_bits) && ...
        isequal(swept.spi.miso_actual_bits, clean.spi.miso_actual_bits) && ...
        isequal(swept.i2c.clocked_sda_bits, clean.i2c.clocked_sda_bits), ...
        'Clock rate must not mutate any protocol cell sequence.');
end

stretchSweepUs = [0 25 100 250];
for sweepIndex = 1:numel(stretchSweepUs)
    if stretchSweepUs(sweepIndex) == 0
        stretchFault = [];
    else
        stretchFault = struct('mode', 'i2c-clock-stretch', ...
            'i2c_stretch_us', stretchSweepUs(sweepIndex));
    end
    swept = model(fixture.payload_bytes, 400000, 400000, ...
        72, 45, stretchFault, Inf);
    assert(abs(swept.i2c.modeled_elapsed_time_us - ...
        (157.5 + stretchSweepUs(sweepIndex))) < 1e-12, ...
        'Stretch sweep elapsed time must equal clocked time plus stretch.');
    assert(swept.i2c.actual_clocked_bit_count == 63 && ...
        isequal(swept.i2c.clocked_sda_bits, clean.i2c.clocked_sda_bits), ...
        'Stretch sweep must leave pulse count and SDA cells unchanged.');
    assert(isequaln(swept.spi, clean.spi), ...
        'I2C stretch must leave the SPI result isolated and unchanged.');
end

%% Target NACK ownership, immediate stop, clean retry, and final NACK success
for nackIndex = 1:3
    nackFault = struct('mode', 'i2c-target-nack', ...
        'i2c_ack_index', nackIndex);
    refused = model(fixture.payload_bytes, 400000, 400000, ...
        72, 45, nackFault, Inf);
    assert(refused.i2c.target_nack_detected && ...
        refused.i2c.target_nack_index == nackIndex && ...
        refused.i2c.actual_clocked_bit_count == 9 .* nackIndex, ...
        'A target NACK must stop at its own ninth clock.');
    assert(refused.i2c.response_bits(end) == 1 && ...
        ~refused.i2c.transaction_complete && ...
        isempty(refused.i2c.wire_payload_bytes) && ...
        isempty(refused.i2c.committed_payload_bytes), ...
        'A target NACK must expose refusal and no returned or committed payload.');
    assert(refused.i2c.repeated_start_present == (nackIndex == 3), ...
        'Repeated START exists only when the address-read header is attempted.');
    assert(isequaln(refused.spi, clean.spi), ...
        'An I2C target NACK must not mutate the independent SPI transaction.');
end
registerNackFixture = p06_scenario('target-nack');
registerNack = model(registerNackFixture.payload_bytes, ...
    registerNackFixture.spi_clock_hz, registerNackFixture.i2c_clock_hz, ...
    registerNackFixture.i2c_address_7bit, ...
    registerNackFixture.register_address, registerNackFixture.fault, Inf);
assert(registerNack.i2c.actual_clocked_bit_count == 18 && ...
    isequal(registerNack.i2c.response_bits, [0 1]) && ...
    ~registerNack.i2c.repeated_start_present, ...
    'Register-byte NACK must prevent repeated START and data after 18 pulses.');
cleanRetry = model(fixture.payload_bytes, 400000, 400000, 72, 45);
assert(isequaln(cleanRetry, clean), ...
    'A clean retry after target NACK must exactly recover the baseline.');

%% Silent SPI corruption, protocol isolation, rollback, and recovery
spiFault = struct('mode', 'spi-bit-flip', ...
    'spi_payload_index', 2, 'spi_bit_index', 0);
corrupted = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, spiFault, Inf);
assert(corrupted.spi.received_payload_bytes(2) == 87 && ...
    ~corrupted.spi.wire_payload_byte_correct(2), ...
    'SPI bit-zero flip must change returned byte 56 hex from 86 to 87 decimal.');
assert(corrupted.spi.transaction_complete && ...
    ~corrupted.spi.payload_correct && ~corrupted.spi.error_detected && ...
    corrupted.metrics.spi_undetected_corruption_count == 1, ...
    'Generic SPI must complete while the one returned-bit fault is undetected.');
assert(isequaln(corrupted.i2c, clean.i2c), ...
    'A SPI return fault must not mutate the independent I2C transaction.');
rolledBack = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], []);
assert(isequaln(rolledBack, clean), ...
    'Removing fault and deadline inputs must roll back exactly to baseline.');

%% Deterministic deadline boundaries, stretch timeout, and recovery
atBoundary = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], clean.i2c.modeled_elapsed_time_us);
assert(atBoundary.spi.transaction_complete && ...
    atBoundary.i2c.transaction_complete && ...
    ~atBoundary.i2c.timed_out, ...
    'A deadline exactly at I2C elapsed time must accept both transactions.');
justBefore = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], clean.i2c.modeled_elapsed_time_us - 1e-6);
assert(justBefore.spi.transaction_complete && ...
    justBefore.i2c.timed_out && ~justBefore.i2c.transaction_complete && ...
    isempty(justBefore.i2c.committed_payload_bytes), ...
    'A deadline just before I2C completion must reject only its committed result.');
oneUlpBefore = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], clean.i2c.modeled_elapsed_time_us - ...
    eps(clean.i2c.modeled_elapsed_time_us));
assert(oneUlpBefore.spi.transaction_complete && ...
    oneUlpBefore.i2c.timed_out && ...
    isempty(oneUlpBefore.i2c.committed_payload_bytes), ...
    'A deadline one representable step before completion must be strict.');
zeroDeadline = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], 0);
assert(zeroDeadline.spi.timed_out && zeroDeadline.i2c.timed_out && ...
    isempty(zeroDeadline.spi.committed_payload_bytes) && ...
    isempty(zeroDeadline.i2c.committed_payload_bytes), ...
    'A zero deadline must reject both positive-duration committed payloads.');
timeoutFixture = p06_scenario('stretch-timeout');
stretchedTimeout = model(timeoutFixture.payload_bytes, ...
    timeoutFixture.spi_clock_hz, timeoutFixture.i2c_clock_hz, ...
    timeoutFixture.i2c_address_7bit, timeoutFixture.register_address, ...
    timeoutFixture.fault, timeoutFixture.transaction_timeout_us);
assert(stretchedTimeout.spi.transaction_complete && ...
    stretchedTimeout.i2c.timed_out && ...
    stretchedTimeout.i2c.modeled_elapsed_time_us == 457.5 && ...
    isempty(stretchedTimeout.i2c.committed_payload_bytes), ...
    'The 300 us stretch must miss 250 us only on the I2C result.');
timeoutRecovery = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], Inf);
assert(isequaln(timeoutRecovery, clean), ...
    'Infinite-deadline re-invocation must recover the exact clean result.');
% This finite pure calculation has no asynchronous wait or cancellation API.

%% Determinism, state isolation, shape, numeric, text, and optional compatibility
first = model(fixture.payload_bytes, 400000, 400000, 72, 45);
second = model(fixture.payload_bytes, 400000, 400000, 72, 45);
assert(isequaln(first, second), ...
    'Repeated calls must be deterministic and state-isolated.');
textFault = struct('mode', string('none'));
compatible = model(uint8([163; 86; 201; 30]), uint32(400000), ...
    uint32(400000), uint8(72), uint8(45), textFault, []);
assert(isrow(compatible.input.payload_bytes) && ...
    isa(compatible.input.payload_bytes, 'double') && ...
    isequal(compatible.input.payload_bytes, fixture.payload_bytes), ...
    'Column and integer inputs must normalize to the same double payload row.');
assert(isequaln(compatible, clean), ...
    'Supported numeric classes and scalar-string mode must preserve compatibility.');
explicitDefaults = model(fixture.payload_bytes, 400000, 400000, ...
    72, 45, [], []);
assert(isequaln(first, explicitDefaults), ...
    'Omitted and empty optional fault/deadline inputs must be compatible.');

%% Callback dependency lifetime across launcher cleanup and module switches
callbackModel = @model;
callbackScenario = @p06_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackFixture = callbackScenario('baseline');
callbackOut = callbackModel(callbackFixture.payload_bytes, ...
    callbackFixture.spi_clock_hz, callbackFixture.i2c_clock_hz, ...
    callbackFixture.i2c_address_7bit, ...
    callbackFixture.register_address);
assert(callbackOut.spi.clocked_bit_count == 40 && ...
    callbackOut.i2c.nominal_clocked_bit_count == 63, ...
    ['Callback-bound P06 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed input, fault schema, timing, and resource-bound rejection
assertReject(@() model(1, 400000, 400000, 72), 'P06:model:Arity');
assertReject(@() model({1}, 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model([1 2; 3 4], 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model([1 NaN], 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model([1 1i], 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model(1.5, 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model(-1, 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model(256, 400000, 400000, 72, 45), ...
    'P06:model:PayloadBytes');
assertReject(@() model(1, 0, 400000, 72, 45), 'P06:model:SPIClock');
assertReject(@() model(1, Inf, 400000, 72, 45), 'P06:model:SPIClock');
assertReject(@() model(1, 1e8 + 1, 400000, 72, 45), ...
    'P06:model:SPIClock');
assertReject(@() model(1, 400000, 0, 72, 45), 'P06:model:I2CClock');
assertReject(@() model(1, 400000, NaN, 72, 45), 'P06:model:I2CClock');
assertReject(@() model(1, 400000, 1e8 + 1, 72, 45), ...
    'P06:model:I2CClock');
assertReject(@() model(1, 400000, 400000, 7, 45), ...
    'P06:model:I2CAddress');
assertReject(@() model(1, 400000, 400000, 120, 45), ...
    'P06:model:I2CAddress');
assertReject(@() model(1, 400000, 400000, 72.5, 45), ...
    'P06:model:I2CAddress');
assertReject(@() model(1, 400000, 400000, 72, -1), ...
    'P06:model:RegisterAddress');
assertReject(@() model(1, 400000, 400000, 72, 128), ...
    'P06:model:RegisterAddress');
assertReject(@() model(1, 400000, 400000, 72, 45, [], -1), ...
    'P06:model:TransactionTimeout');
assertReject(@() model(1, 400000, 400000, 72, 45, [], NaN), ...
    'P06:model:TransactionTimeout');
assertReject(@() model(1, 400000, 400000, 72, 45, [], -Inf), ...
    'P06:model:TransactionTimeout');
assertReject(@() model(1, 400000, 400000, 72, 45, {'none'}, Inf), ...
    'P06:model:Fault');
assertReject(@() model(1, 400000, 400000, 72, 45, struct(), Inf), ...
    'P06:model:Fault');
extraFault = struct('mode', 'none', 'extra', 1);
assertReject(@() model(1, 400000, 400000, 72, 45, extraFault, Inf), ...
    'P06:model:Fault');
badMode = struct('mode', 'spi-nack');
assertReject(@() model(1, 400000, 400000, 72, 45, badMode, Inf), ...
    'P06:model:FaultMode');
activeNone = struct('mode', 'none', 'i2c_ack_index', 1);
assertReject(@() model(1, 400000, 400000, 72, 45, activeNone, Inf), ...
    'P06:model:FaultField');
missingAck = struct('mode', 'i2c-target-nack');
assertReject(@() model(1, 400000, 400000, 72, 45, missingAck, Inf), ...
    'P06:model:FaultField');
badAck = struct('mode', 'i2c-target-nack', 'i2c_ack_index', 4);
assertReject(@() model(1, 400000, 400000, 72, 45, badAck, Inf), ...
    'P06:model:I2CAckIndex');
missingSpiBit = struct('mode', 'spi-bit-flip', ...
    'spi_payload_index', 1);
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    missingSpiBit, Inf), 'P06:model:FaultField');
badSpiPayload = struct('mode', 'spi-bit-flip', ...
    'spi_payload_index', 2, 'spi_bit_index', 0);
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    badSpiPayload, Inf), 'P06:model:SPIPayloadIndex');
badSpiBit = struct('mode', 'spi-bit-flip', ...
    'spi_payload_index', 1, 'spi_bit_index', 8);
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    badSpiBit, Inf), 'P06:model:SPIBitIndex');
missingStretch = struct('mode', 'i2c-clock-stretch');
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    missingStretch, Inf), 'P06:model:FaultField');
badStretch = struct('mode', 'i2c-clock-stretch', 'i2c_stretch_us', 0);
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    badStretch, Inf), 'P06:model:ClockStretch');
hugeStretch = struct('mode', 'i2c-clock-stretch', ...
    'i2c_stretch_us', 1e6 + 1);
assertReject(@() model(1, 400000, 400000, 72, 45, ...
    hugeStretch, Inf), 'P06:model:ClockStretch');

tooManyPayloadBytes = zeros(1, 100001);
assertReject(@() model(tooManyPayloadBytes, 400000, 400000, 72, 45), ...
    'P06:model:ResourceBound');
clear tooManyPayloadBytes;
tooManyClockedCells = zeros(1, 94442);
assertReject(@() model(tooManyClockedCells, 400000, 400000, 72, 45), ...
    'P06:model:ResourceBound');
clear tooManyClockedCells;
assertReject(@() p06_scenario({'baseline'}), 'P06:scenario:Kind');
assertReject(@() p06_scenario('baseline', -1), ...
    'P06:scenario:PayloadCount');
assertReject(@() p06_scenario('spi-corruption', 1), ...
    'P06:scenario:PayloadCount');
assertReject(@() p06_scenario('unknown'), 'P06:scenario:Kind');

afterRejection = model(fixture.payload_bytes, 400000, 400000, 72, 45);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('P06 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
