function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P03.

%% No-event limit, periodic check cost, and accounting identities
quiet = model([], [], 4, 1, 0.1, 0.05, 0.2, 1);
assert(quiet.metrics.total_events == 0, 'No-event input must retain zero events.');
assert(quiet.metrics.poll_detected_count == 0 && ...
    quiet.metrics.poll_missed_count == 0, ...
    'No-event polling accounting must stay empty.');
assert(quiet.metrics.interrupt_captured_count == 0 && ...
    quiet.metrics.interrupt_dropped_count == 0, ...
    'No-event interrupt accounting must stay empty.');
assert(numel(quiet.poll.sample_times_ms) == 4, ...
    'A four-millisecond horizon and one-millisecond period require four polls.');
assert(abs(quiet.poll.cpu_busy_ms - 0.4) < 1e-12 && ...
    abs(quiet.poll.cpu_busy_fraction - 0.1) < 1e-12, ...
    'Polling CPU work must include each explicit check even with no events.');
assert(quiet.interrupt.cpu_busy_ms == 0, ...
    'The interrupt path must spend no handler work when no event arrives.');
assert(isnan(quiet.metrics.poll_worst_response_ms) && ...
    isnan(quiet.metrics.interrupt_worst_response_ms), ...
    'No serviced event must report response as N/A rather than zero latency.');
decimalHorizon = model([], [], 1, 0.1, 0, 0, 0, 1);
assert(numel(decimalHorizon.poll.sample_times_ms) == 10 && ...
    decimalHorizon.poll.sample_times_ms(end) < decimalHorizon.horizon_ms, ...
    'A decimal poll intended at the half-open horizon must not become an extra check.');

%% Half-open polling boundaries and independent response calculation
boundary = model([1 2.5], [0.5 0.5], 4, 1, 0, 0, 0, 2);
assert(isequal(boundary.poll.detected, [true false]), ...
    'Arrival exactly on a poll must detect; pulse end exactly on a poll must miss.');
assert(boundary.poll.detection_time_ms(1) == 1, ...
    'Boundary detection time must equal the actual poll instant.');
assert(boundary.poll.response_latency_ms(1) == 0, ...
    'Zero-cost boundary response must start at arrival.');
assert(boundary.metrics.poll_detected_count + boundary.metrics.poll_missed_count == ...
    boundary.metrics.total_events, 'Polling detected plus missed must conserve arrivals.');
allMissed = model([0.1 1.1], 0.1, 2, 1, 0, 0, 0.1, 2);
assert(all(allMissed.poll.missed) && ...
    isnan(allMissed.metrics.poll_worst_response_ms), ...
    'All-missed polling must report no response, not instantaneous response.');
assert(all(allMissed.interrupt.captured), ...
    'All-missed polling must remain isolated from interrupt edge capture.');

roundoffBoundary = model([0.8 0.91], [0.05 0.09], 1.2, 0.1, 0, 0, 0, 2);
assert(isequal(roundoffBoundary.poll.detected, [true false]), ...
    ['Accumulated poll-grid roundoff must preserve arrival-inclusive and ' ...
    'end-exclusive pulse boundaries.']);
assert(roundoffBoundary.poll.detection_time_ms(1) == 0.8 && ...
    roundoffBoundary.poll.response_latency_ms(1) == 0, ...
    'A poll snapped to an arrival must not report a pre-arrival detection or negative response.');

longPulse = model([0.1 1.1 2.1], 1, 4, 1, 0, 0, 0, 4);
assert(all(longPulse.poll.detected), ...
    'Nonblocking polls must detect every nonoverlapping pulse as wide as the period.');
assert(all(longPulse.poll.response_latency_ms >= 0 & ...
    longPulse.poll.response_latency_ms < longPulse.poll.period_ms), ...
    'Long-pulse polling response must remain in [0, poll period).');

stretchedLoop = model([0 1], [0.2 0.4], 3, 1, 0, 0, 1.5, 2);
assert(stretchedLoop.poll.detected(1) && stretchedLoop.poll.missed(2), ...
    'Handler work longer than the period must delay a poll and expose a later miss.');
assert(abs(stretchedLoop.poll.sample_times_ms(2) - 1.5) < 1e-12, ...
    'Next poll must be max(requested poll time, current work finish).');

%% Idle interrupt latency, FIFO order, and exact capacity release
fifo = model([1 1.1], [0.05 0.05], 3, 1, 0, 0.2, 0.3, 2);
assert(all(fifo.interrupt.captured), 'Two-slot FIFO must capture both close arrivals.');
assert(abs(fifo.interrupt.service_start_ms(1) - 1.2) < 1e-12, ...
    'Idle unmasked service must start at arrival plus interrupt latency.');
assert(fifo.interrupt.service_start_ms(2) >= fifo.interrupt.finish_ms(1), ...
    'FIFO service start must never precede the prior accepted finish.');
assert(abs(fifo.interrupt.response_latency_ms(2) - 0.6) < 1e-12, ...
    'Queued response must include prior finish and the next dispatch latency.');
assert(fifo.interrupt.max_outstanding == 2, ...
    'Outstanding capacity must include both in-service and queued work.');

exactRelease = model([1 1.5], 0.1, 3, 1, 0, 0, 0.5, 1);
assert(all(exactRelease.interrupt.captured), ...
    'A finish exactly at the next arrival must free the one-slot capacity.');
assert(exactRelease.interrupt.service_start_ms(2) == 1.5, ...
    'The newly freed slot must dispatch the next event at its arrival.');
decimalRelease = model([0.1 0.3], 0.01, 1, 1, 0, 0, 0.2, 1);
assert(all(decimalRelease.interrupt.captured) && ...
    decimalRelease.interrupt.service_start_ms(2) == 0.3, ...
    ['Decimal finish roundoff must not prevent mathematically exact ' ...
    'capacity release at the next arrival.']);

%% Masking, finite backlog, overrun, horizon timeout, rollback, and recovery
masked = model(1.5, 0.1, 4, 1, 0, 0.1, 0.2, 1, [1 3]);
assert(masked.interrupt.arrived_while_masked, ...
    'An arrival inside a mask window must be observable as masked.');
assert(abs(masked.interrupt.service_start_ms - 3) < 1e-12, ...
    'Dispatch candidate inside a mask must move to the mask end.');
assert(abs(masked.interrupt.response_latency_ms - 1.5) < 1e-12, ...
    'Masked service-start response must be computed from the original arrival.');
maskStartRoundoff = model(0.7, 0.05, 1.5, 1, 0, 0.1, 0.2, 1, [0.8 1]);
assert(maskStartRoundoff.interrupt.service_start_ms == 1, ...
    'A dispatch candidate rounded just below a mask start must remain masked.');
maskCrossing = model(1, 0.1, 4, 1, 0, 0, 2, 1, [1.5 2.5]);
assert(maskCrossing.interrupt.service_start_ms == 1 && ...
    maskCrossing.interrupt.finish_ms == 3, ...
    'A mask starting during active handler work must not abort or stretch that handler.');
adjacentMasks = model([1 2], 0.1, 4, 1, 0, 0, 0, 2, [1 2; 2 3]);
assert(all(adjacentMasks.interrupt.service_start_ms == [3 3]), ...
    'Adjacent half-open masks must defer a start at their shared boundary to the final end.');
decimalMasks = model(0.15, 0.01, 1, 1, 0, 0, 0, 1, ...
    [0.1 0.1 + 0.2; 0.3 0.5]);
assert(decimalMasks.interrupt.service_start_ms == 0.5, ...
    'Mathematically touching decimal mask windows must normalize and chain.');
maskHorizon = model(0.15, 0.01, 0.3, 0.3, 0, 0, 0, 1, ...
    [0.1 0.1 + 0.2]);
assert(maskHorizon.interrupt.mask_windows_ms(2) == 0.3 && ...
    maskHorizon.interrupt.service_start_ms == 0.3, ...
    'A decimal mask end mathematically at the horizon must normalize to that boundary.');

late = model(1.9, 0.05, 2, 0.5, 0, 0.05, 0.2, 1);
assert(late.interrupt.captured && ~late.interrupt.dropped_overrun, ...
    'A late accepted event must not be mislabeled as overrun.');
assert(late.interrupt.backlog_at_horizon == 1 && ...
    late.metrics.interrupt_completion_after_horizon_count == 1, ...
    'Handler completion after the horizon must be reported as backlog timeout.');
assert(abs(late.interrupt.cpu_busy_ms - 0.05) < 1e-12, ...
    'Modeled CPU work must be clipped at the observation horizon.');
latePoll = model(1.75, 0.2, 2, 0.25, 0.05, 0, 0.3, 1);
assert(latePoll.poll.detected && ...
    latePoll.metrics.poll_completion_after_horizon_count == 1, ...
    'A detected polling handler finishing after the horizon must report timeout backlog.');
horizonTouch = model(0.1, 0.05, 0.3, 0.3, 0, 0, 0.2, 1);
assert(horizonTouch.interrupt.backlog_at_horizon == 0 && ...
    horizonTouch.metrics.interrupt_completion_after_horizon_count == 0, ...
    'A handler finishing mathematically at the horizon must not become backlog from roundoff.');
pollHorizonTouch = model(0.1, 0.05, 0.3, 0.1, 0, 0, 0.2, 1);
assert(pollHorizonTouch.poll.detected && ...
    pollHorizonTouch.metrics.poll_completion_after_horizon_count == 0, ...
    'A polling handler finishing mathematically at the horizon must not become backlog.');

fixture = p03_scenario('mixed', 0.3);
baseline = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
    fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 3, zeros(0, 2));
broken = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
    fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 1, [6 10]);
recoveryIndex = find(fixture.event_times_ms == 11.5, 1, 'first');
assert(baseline.metrics.poll_detected_count == 6 && ...
    baseline.metrics.poll_missed_count == 4, ...
    'Deterministic baseline polling counts must match independent interval inspection.');
assert(baseline.metrics.interrupt_captured_count == 10 && ...
    baseline.metrics.interrupt_dropped_count == 0, ...
    'Unmasked three-slot baseline must capture every separated edge.');
assert(broken.metrics.interrupt_dropped_count == 5, ...
    'One-slot masked burst must expose five finite-capacity overruns.');
assert(broken.interrupt.max_outstanding <= broken.interrupt.queue_capacity, ...
    'Maximum outstanding work must never exceed configured interrupt capacity.');
assert(broken.interrupt.captured(3) && all(broken.interrupt.dropped_overrun(4:8)), ...
    'The first burst edge must be retained and the next five must overrun.');
assert(broken.interrupt.captured(recoveryIndex) && ...
    broken.interrupt.finish_ms(recoveryIndex) < fixture.horizon_ms, ...
    'A post-drain event must prove recovery after masked-burst overload.');
rolledBack = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
    fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 3, zeros(0, 2));
assert(isequaln(rolledBack, baseline), ...
    'Resetting mask and capacity must roll back the broken configuration.');

%% Two independent lever sweeps and conservation laws
pollPeriodSweepMs = [0.25 0.5 1 2];
detectedCounts = zeros(size(pollPeriodSweepMs));
interruptCounts = zeros(size(pollPeriodSweepMs));
for sweepIndex = 1:numel(pollPeriodSweepMs)
    swept = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
        fixture.horizon_ms, pollPeriodSweepMs(sweepIndex), 0.02, 0.05, ...
        0.2, 3, zeros(0, 2));
    detectedCounts(sweepIndex) = swept.metrics.poll_detected_count;
    interruptCounts(sweepIndex) = swept.metrics.interrupt_captured_count;
    assert(swept.metrics.poll_detected_count + swept.metrics.poll_missed_count == ...
        swept.metrics.total_events, 'Every poll sweep must conserve input events.');
end
assert(isequal(detectedCounts, [10 6 2 2]), ...
    'Poll-period sweep must retain its independently calculated detections.');
assert(all(interruptCounts == 10), ...
    'Changing poll period must leave interrupt capture unchanged.');

maskDurationSweepMs = [0 1 2 4];
capturedCounts = zeros(size(maskDurationSweepMs));
droppedCounts = zeros(size(maskDurationSweepMs));
pollCounts = zeros(size(maskDurationSweepMs));
for sweepIndex = 1:numel(maskDurationSweepMs)
    if maskDurationSweepMs(sweepIndex) == 0
        maskWindowsMs = zeros(0, 2);
    else
        maskWindowsMs = [6 6 + maskDurationSweepMs(sweepIndex)];
    end
    swept = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
        fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 3, maskWindowsMs);
    capturedCounts(sweepIndex) = swept.metrics.interrupt_captured_count;
    droppedCounts(sweepIndex) = swept.metrics.interrupt_dropped_count;
    pollCounts(sweepIndex) = swept.metrics.poll_detected_count;
    assert(swept.metrics.interrupt_captured_count + ...
        swept.metrics.interrupt_dropped_count == swept.metrics.total_events, ...
        'Every mask sweep must conserve captured plus dropped input events.');
end
assert(isequal(capturedCounts, [10 10 9 7]), ...
    'Mask sweep must retain the independently calculated capture counts.');
assert(isequal(droppedCounts, [0 0 1 3]), ...
    'Mask sweep must retain the complementary overrun counts.');
assert(all(pollCounts == 6), ...
    'Changing mask duration must leave polling unchanged.');
pulseNarrow = model(fixture.event_times_ms, 0.1, fixture.horizon_ms, ...
    0.5, 0.02, 0.05, 0.2, 3, zeros(0, 2));
pulseWide = model(fixture.event_times_ms, 0.5, fixture.horizon_ms, ...
    0.5, 0.02, 0.05, 0.2, 3, zeros(0, 2));
assert(isequal(pulseNarrow.interrupt.captured, pulseWide.interrupt.captured), ...
    'Changing transient pulse width must not mutate rising-edge interrupt capture.');

%% Determinism, state isolation, shape, numeric, and optional-mask compatibility
first = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
    fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 3);
second = model(fixture.event_times_ms, fixture.pulse_width_ms, ...
    fixture.horizon_ms, 0.5, 0.02, 0.05, 0.2, 3, []);
assert(isequaln(first, second), ...
    'Repeated calls and omitted versus empty masks must be deterministic and compatible.');
assert(all(first.poll.cpu_busy_fraction >= 0 & first.poll.cpu_busy_fraction <= 1) && ...
    all(first.interrupt.cpu_busy_fraction >= 0 & ...
    first.interrupt.cpu_busy_fraction <= 1), ...
    'Modeled CPU fractions must stay within [0, 1].');
columnInput = model([1; 2], [0.2; 0.2], 4, 1, 0.1, 0.1, 0.1, 2);
assert(isrow(columnInput.events.arrival_ms) && isrow(columnInput.events.width_ms), ...
    'Column-vector inputs must normalize to documented row-vector outputs.');
integerInput = model(uint8([1 3]), uint8(1), uint8(5), uint8(1), ...
    uint8(0), uint8(0), uint8(0), uint8(2));
assert(isa(integerInput.horizon_ms, 'double') && ...
    isa(integerInput.events.arrival_ms, 'double'), ...
    'Accepted integer inputs must normalize to double before timing arithmetic.');

%% Callback dependency lifetime across launcher cleanup and module switches
callbackModel = @model;
callbackScenario = @p03_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackFixture = callbackScenario('mixed', 0.3);
callbackOut = callbackModel(callbackFixture.event_times_ms, ...
    callbackFixture.pulse_width_ms, callbackFixture.horizon_ms, ...
    0.5, 0.02, 0.05, 0.2, 3, zeros(0, 2));
assert(callbackOut.metrics.poll_detected_count == 6 && ...
    callbackOut.metrics.interrupt_captured_count == 10, ...
    ['Callback-bound P03 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed-input, timing, capacity, and resource-bound rejection
assertReject(@() model([1], 0.1, 3, 1, 0, 0, 0), 'P03:model:Arity');
assertReject(@() model({1}, 0.1, 3, 1, 0, 0, 0, 1), ...
    'P03:model:EventTimes');
assertReject(@() model([1 2; 3 4], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventTimes');
assertReject(@() model([1 NaN], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventTimes');
assertReject(@() model([1 2i], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventTimes');
assertReject(@() model([1 1], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventOrder');
assertReject(@() model([2 1], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventOrder');
assertReject(@() model([1 2], [0.1 0.2 0.3], 5, 1, 0, 0, 0, 1), ...
    'P03:model:PulseWidth');
assertReject(@() model([1], 0, 5, 1, 0, 0, 0, 1), ...
    'P03:model:PulseWidth');
assertReject(@() model([], -1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:PulseWidth');
assertReject(@() model([-1], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventBounds');
assertReject(@() model([5], 0.1, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventBounds');
assertReject(@() model([4.9], 0.2, 5, 1, 0, 0, 0, 1), ...
    'P03:model:EventBounds');
assertReject(@() model([1 1.2], 0.3, 5, 1, 0, 0, 0, 1), ...
    'P03:model:PulseOverlap');
assertReject(@() model([1], 0.1, 0, 1, 0, 0, 0, 1), ...
    'P03:model:Horizon');
assertReject(@() model([1], 0.1, 5, 0, 0, 0, 0, 1), ...
    'P03:model:PollPeriod');
assertReject(@() model([1], 0.1, 5, 1, -1, 0, 0, 1), ...
    'P03:model:PollCheckCost');
assertReject(@() model([1], 0.1, 5, 1, 0, -1, 0, 1), ...
    'P03:model:InterruptLatency');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, -1, 1), ...
    'P03:model:HandlerCost');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 0), ...
    'P03:model:QueueCapacity');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1.5), ...
    'P03:model:QueueCapacity');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1, [1 2 3]), ...
    'P03:model:MaskWindows');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1, [-1 2]), ...
    'P03:model:MaskWindows');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1, [1 6]), ...
    'P03:model:MaskWindows');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1, [2 3; 1 1.5]), ...
    'P03:model:MaskOrder');
assertReject(@() model([1], 0.1, 5, 1, 0, 0, 0, 1, [1 2; 1.5 3]), ...
    'P03:model:MaskOrder');
assertReject(@() model([0.1], 0.1, 1, 1e-7, 0, 0, 0, 1), ...
    'P03:model:ResourceBound');
tooManyEvents = zeros(1, 1000001);
assertReject(@() model(tooManyEvents, 0.1, 2, 1, 0, 0, 0, 1), ...
    'P03:model:ResourceBound');
clear tooManyEvents;
assertReject(@() model([1], 0.1, 2, 1, realmax, realmax, realmax, 1), ...
    'P03:model:TimingResourceBound');
assertReject(@() model([1], realmin, 2, 1, 0, 0, 0, 1), ...
    'P03:model:TimingResourceBound');
assertReject(@() model([], [], 2, 1, realmin, 0, 0, 1), ...
    'P03:model:TimingResourceBound');
assertReject(@() model([1], 0.1, 2, 1, 0, realmin, 0, 1), ...
    'P03:model:TimingResourceBound');
assertReject(@() model([1], 0.1, 2, 1, 0, 0, realmin, 1), ...
    'P03:model:TimingResourceBound');
touchingDecimals = model([0.1 0.3], 0.2, 1, 0.1, 0, 0, 0, 2);
assert(touchingDecimals.events.end_ms(1) == ...
    touchingDecimals.events.arrival_ms(2), ...
    'Scale-aware comparison must normalize roundoff at mathematically touching pulses.');
assertReject(@() p03_scenario('unknown', 0.3), 'P03:scenario:Kind');
assertReject(@() p03_scenario('mixed', 0), 'P03:scenario:PulseWidth');
assertReject(@() p03_scenario('mixed', 0.6), 'P03:scenario:PulseWidth');

disp('P03 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
try
    callable();
catch caught
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection with identifier %s.', expectedIdentifier);
end
