function out = model(commandVoltageV, initialVoltageV, referenceVoltageV, ...
    dacBits, updateLatencyS, timeConstantS, slewRateVPerS, toleranceV, ...
    samplePeriodS, sampleCount, fault, commandDeadlineS)
%MODEL Quantize one DAC command and calculate its bounded settling trace.
%   The ideal unipolar DAC uses L=2^dacBits, LSB=referenceVoltageV/L,
%   code=round(request/LSB) clamped to [0,L-1], and V_code=code*LSB.
%   The active code changes after updateLatencyS when the command is
%   accepted. The analog output then follows a first-order response whose
%   magnitude of slope is capped by slewRateVPerS. A finite command
%   deadline classifies whether the update is accepted; it does not wait
%   for, cancel, or control hardware. The selected reference and bit depth
%   must retain a positive LSB in double precision.

if nargin < 10 || nargin > 12
    error('P08:model:Arity', ...
        ['Expected command/initial/reference voltages, DAC bits, update ' ...
        'latency, time constant, slew rate, tolerance, sample period/count, ' ...
        'and optional fault/deadline.']);
end
if nargin < 11 || isempty(fault)
    fault = defaultFault();
end
if nargin < 12 || isempty(commandDeadlineS)
    commandDeadlineS = Inf;
end

maxSamples = 10000;
if isnumeric(sampleCount) && isreal(sampleCount) && isscalar(sampleCount) && ...
        isfinite(sampleCount) && sampleCount > maxSamples
    error('P08:model:ResourceBound', ...
        'At most ten thousand response samples are allowed.');
end

referenceVoltageV = validateFiniteScalar(referenceVoltageV, ...
    'P08:model:ReferenceVoltage', 'referenceVoltageV');
if referenceVoltageV <= 0 || referenceVoltageV > 1000
    error('P08:model:ReferenceVoltage', ...
        'referenceVoltageV must lie in (0, 1000] V.');
end
dacBits = validateIntegerScalar(dacBits, 2, 24, ...
    'P08:model:DACBits', 'dacBits');
commandVoltageV = validateVoltage(commandVoltageV, referenceVoltageV, ...
    'P08:model:CommandVoltage', 'commandVoltageV');
initialVoltageV = validateVoltage(initialVoltageV, referenceVoltageV, ...
    'P08:model:InitialVoltage', 'initialVoltageV');
updateLatencyS = validateFiniteScalar(updateLatencyS, ...
    'P08:model:UpdateLatency', 'updateLatencyS');
if updateLatencyS < 0 || updateLatencyS > 1e6
    error('P08:model:UpdateLatency', ...
        'updateLatencyS must lie in [0, 1e6] s.');
end
timeConstantS = validateFiniteScalar(timeConstantS, ...
    'P08:model:TimeConstant', 'timeConstantS');
if timeConstantS <= 0 || timeConstantS > 1e6
    error('P08:model:TimeConstant', ...
        'timeConstantS must lie in (0, 1e6] s.');
end
slewRateVPerS = validateSlewRate(slewRateVPerS);
toleranceV = validateFiniteScalar(toleranceV, ...
    'P08:model:Tolerance', 'toleranceV');
if toleranceV <= 0 || toleranceV > referenceVoltageV
    error('P08:model:Tolerance', ...
        'toleranceV must lie in (0, referenceVoltageV] V.');
end
samplePeriodS = validateFiniteScalar(samplePeriodS, ...
    'P08:model:SamplePeriod', 'samplePeriodS');
if samplePeriodS <= 0 || samplePeriodS > 1e6
    error('P08:model:SamplePeriod', ...
        'samplePeriodS must lie in (0, 1e6] s.');
end
sampleCount = validateIntegerScalar(sampleCount, 2, maxSamples, ...
    'P08:model:SampleCount', 'sampleCount');
fault = validateFault(fault);
commandDeadlineS = validateDeadline(commandDeadlineS);

observationEndS = (sampleCount - 1) .* samplePeriodS;
if ~isfinite(observationEndS) || observationEndS > 1e6
    error('P08:model:TimingResourceBound', ...
        'The response observation horizon must not exceed 1e6 s.');
end

levelCount = 2 .^ dacBits;
maxCode = levelCount - 1;
lsbV = referenceVoltageV ./ levelCount;
if ~isfinite(lsbV) || lsbV <= 0
    error('P08:model:ReferenceResolution', ...
        ['referenceVoltageV is too small for dacBits to retain a positive ' ...
        'LSB in double precision.']);
end
[initialCode, quantizedInitialV, initialRawCode, initialSaturated] = ...
    quantizeVoltage(initialVoltageV, lsbV, maxCode);
[commandCode, quantizedCommandV, commandRawCode, commandSaturated] = ...
    quantizeVoltage(commandVoltageV, lsbV, maxCode);

timedOut = updateLatencyS > commandDeadlineS;
digitalCommandComplete = ~timedOut;
updateNotLatched = strcmp(fault.mode, 'update-not-latched');
outputUpdateApplied = digitalCommandComplete && ~updateNotLatched;
if digitalCommandComplete
    recordedCode = commandCode;
    recordedVoltageV = quantizedCommandV;
else
    recordedCode = zeros(1, 0);
    recordedVoltageV = zeros(1, 0);
end

timeS = (0:(sampleCount - 1)) .* samplePeriodS;
heldCode = initialCode .* ones(1, sampleCount);
heldTargetV = quantizedInitialV .* ones(1, sampleCount);
if outputUpdateApplied
    updateMask = timeS >= updateLatencyS;
    heldCode(updateMask) = commandCode;
    heldTargetV(updateMask) = quantizedCommandV;
else
    updateMask = false(1, sampleCount);
end

signedStepV = quantizedCommandV - quantizedInitialV;
stepMagnitudeV = abs(signedStepV);
stepDirection = sign(signedStepV);
naturalInitialSlopeVPerS = stepMagnitudeV ./ timeConstantS;
slewLimited = stepMagnitudeV > 0 && ...
    slewRateVPerS < naturalInitialSlopeVPerS;
if slewLimited
    slewDurationS = max(stepMagnitudeV ./ slewRateVPerS - ...
        timeConstantS, 0);
else
    slewDurationS = 0;
end

outputV = quantizedInitialV .* ones(1, sampleCount);
intendedErrorV = stepMagnitudeV .* ones(1, sampleCount);
if outputUpdateApplied && stepMagnitudeV > 0
    elapsedAfterUpdateS = timeS(updateMask) - updateLatencyS;
    remainingErrorV = hybridError(stepMagnitudeV, elapsedAfterUpdateS, ...
        timeConstantS, slewRateVPerS, slewLimited, slewDurationS);
    outputV(updateMask) = quantizedCommandV - ...
        stepDirection .* remainingErrorV;
    % Retain error from the analytical state. Re-subtracting two nearly
    % equal voltages can round a positive subnormal error to zero and report
    % sampled settling long before the declared tolerance is reached.
    intendedErrorV(updateMask) = remainingErrorV;
end

inTolerance = intendedErrorV <= toleranceV;
staysInTolerance = false(1, sampleCount);
allFutureSamplesInTolerance = true;
for sampleIndex = sampleCount:-1:1
    allFutureSamplesInTolerance = allFutureSamplesInTolerance && ...
        inTolerance(sampleIndex);
    staysInTolerance(sampleIndex) = allFutureSamplesInTolerance;
end
eligibleStay = staysInTolerance & timeS >= updateLatencyS & ...
    outputUpdateApplied;
firstStayIndex = find(eligibleStay, 1, 'first');
if isempty(firstStayIndex)
    sampledFirstStayTimeS = NaN;
    sampledSettlingAfterUpdateS = NaN;
else
    sampledFirstStayTimeS = timeS(firstStayIndex);
    sampledSettlingAfterUpdateS = sampledFirstStayTimeS - updateLatencyS;
end

if outputUpdateApplied
    analyticSettlingAfterUpdateS = settlingDuration(stepMagnitudeV, ...
        toleranceV, timeConstantS, slewRateVPerS, slewLimited, ...
        slewDurationS);
    analyticSettlingFromCommandS = updateLatencyS + ...
        analyticSettlingAfterUpdateS;
else
    analyticSettlingAfterUpdateS = Inf;
    analyticSettlingFromCommandS = Inf;
end
settledWithinObservation = ~isnan(sampledFirstStayTimeS);

out = struct();
out.input = struct( ...
    'command_voltage_v', commandVoltageV, ...
    'initial_voltage_v', initialVoltageV, ...
    'reference_voltage_v', referenceVoltageV, ...
    'dac_bits', dacBits, ...
    'update_latency_s', updateLatencyS, ...
    'time_constant_s', timeConstantS, ...
    'slew_rate_v_per_s', slewRateVPerS, ...
    'tolerance_v', toleranceV, ...
    'sample_period_s', samplePeriodS, ...
    'sample_count', sampleCount);
out.quantizer = struct( ...
    'level_count', levelCount, ...
    'max_code', maxCode, ...
    'lsb_v', lsbV, ...
    'initial_raw_code', initialRawCode, ...
    'initial_code', initialCode, ...
    'initial_voltage_v', quantizedInitialV, ...
    'initial_quantization_error_v', quantizedInitialV - initialVoltageV, ...
    'initial_saturated', initialSaturated, ...
    'command_raw_code', commandRawCode, ...
    'command_code', commandCode, ...
    'command_voltage_v', quantizedCommandV, ...
    'command_quantization_error_v', quantizedCommandV - commandVoltageV, ...
    'command_saturated', commandSaturated);
out.command = struct( ...
    'fault', fault, ...
    'deadline_s', commandDeadlineS, ...
    'timed_out', timedOut, ...
    'digital_complete', digitalCommandComplete, ...
    'output_update_applied', outputUpdateApplied, ...
    'recorded_code', recordedCode, ...
    'recorded_voltage_v', recordedVoltageV, ...
    'scheduled_update_time_s', updateLatencyS, ...
    'update_observed', any(updateMask));
out.response = struct( ...
    'time_s', timeS, ...
    'held_code', heldCode, ...
    'held_target_v', heldTargetV, ...
    'output_v', outputV, ...
    'intended_error_v', intendedErrorV, ...
    'in_tolerance', inTolerance, ...
    'stays_in_tolerance', staysInTolerance);
out.settling = struct( ...
    'step_magnitude_v', stepMagnitudeV, ...
    'natural_initial_slope_v_per_s', naturalInitialSlopeVPerS, ...
    'slew_limited', slewLimited, ...
    'slew_duration_s', slewDurationS, ...
    'analytic_after_update_s', analyticSettlingAfterUpdateS, ...
    'analytic_from_command_s', analyticSettlingFromCommandS, ...
    'sampled_first_stay_time_s', sampledFirstStayTimeS, ...
    'sampled_after_update_s', sampledSettlingAfterUpdateS, ...
    'settled_within_observation', settledWithinObservation, ...
    'final_error_v', intendedErrorV(end));
out.claim_boundary = [ ...
    'Deterministic ideal DAC quantization, latch, and synthetic first-order/' ...
    'slew response; not a MATLAB-runtime or hardware measurement.'];
end

function remainingErrorV = hybridError(stepMagnitudeV, elapsedS, ...
    timeConstantS, slewRateVPerS, slewLimited, slewDurationS)
if ~slewLimited
    remainingErrorV = stepMagnitudeV .* exp(-elapsedS ./ timeConstantS);
    return;
end
remainingErrorV = zeros(size(elapsedS));
linearMask = elapsedS <= slewDurationS;
remainingErrorV(linearMask) = stepMagnitudeV - ...
    slewRateVPerS .* elapsedS(linearMask);
exponentialMask = ~linearMask;
remainingErrorV(exponentialMask) = slewRateVPerS .* timeConstantS .* ...
    exp(-(elapsedS(exponentialMask) - slewDurationS) ./ timeConstantS);
remainingErrorV = max(remainingErrorV, 0);
end

function durationS = settlingDuration(stepMagnitudeV, toleranceV, ...
    timeConstantS, slewRateVPerS, slewLimited, slewDurationS)
if stepMagnitudeV <= toleranceV
    durationS = 0;
elseif ~slewLimited
    durationS = timeConstantS .* ...
        (log(stepMagnitudeV) - log(toleranceV));
elseif toleranceV >= slewRateVPerS .* timeConstantS
    durationS = (stepMagnitudeV - toleranceV) ./ slewRateVPerS;
else
    durationS = slewDurationS + timeConstantS .* ...
        (log(slewRateVPerS .* timeConstantS) - log(toleranceV));
end
end

function [code, quantizedV, rawCode, saturated] = ...
    quantizeVoltage(requestedV, lsbV, maxCode)
rawCode = round(requestedV ./ lsbV);
code = min(max(rawCode, 0), maxCode);
quantizedV = code .* lsbV;
saturated = rawCode ~= code;
end

function value = validateVoltage(value, referenceVoltageV, identifier, label)
value = validateFiniteScalar(value, identifier, label);
if value < 0 || value > referenceVoltageV
    error(identifier, '%s must lie in [0, referenceVoltageV].', label);
end
end

function value = validateFiniteScalar(value, identifier, label)
valid = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && isfinite(value);
if ~valid
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function value = validateIntegerScalar(value, lowerBound, upperBound, ...
    identifier, label)
value = validateFiniteScalar(value, identifier, label);
if value ~= round(value) || value < lowerBound || value > upperBound
    error(identifier, '%s must be an integer in [%d, %d].', ...
        label, lowerBound, upperBound);
end
end

function slewRateVPerS = validateSlewRate(slewRateVPerS)
validType = isnumeric(slewRateVPerS) && ~islogical(slewRateVPerS) && ...
    isreal(slewRateVPerS) && isscalar(slewRateVPerS);
validValue = validType && ((isfinite(slewRateVPerS) && ...
    slewRateVPerS > 0 && slewRateVPerS <= 1e12) || ...
    (isinf(slewRateVPerS) && slewRateVPerS > 0));
if ~validValue
    error('P08:model:SlewRate', ...
        'slewRateVPerS must be positive and finite up to 1e12, or positive Inf.');
end
slewRateVPerS = double(slewRateVPerS);
end

function deadlineS = validateDeadline(deadlineS)
validType = isnumeric(deadlineS) && ~islogical(deadlineS) && ...
    isreal(deadlineS) && isscalar(deadlineS);
validValue = validType && ((isfinite(deadlineS) && deadlineS >= 0) || ...
    (isinf(deadlineS) && deadlineS > 0));
if ~validValue
    error('P08:model:CommandDeadline', ...
        'commandDeadlineS must be nonnegative and finite, or positive Inf.');
end
deadlineS = double(deadlineS);
end

function fault = defaultFault()
fault = struct('mode', 'none');
end

function fault = validateFault(candidate)
if ~isstruct(candidate) || ~isscalar(candidate) || ...
        ~isfield(candidate, 'mode')
    error('P08:model:Fault', ...
        'fault must be a scalar struct with a mode field.');
end
if any(~ismember(fieldnames(candidate), {'mode'}))
    error('P08:model:Fault', 'fault contains an unsupported field.');
end
mode = candidate.mode;
if ~(ischar(mode) || (isstring(mode) && isscalar(mode)))
    error('P08:model:FaultMode', 'fault.mode must be scalar text.');
end
mode = lower(strtrim(char(mode)));
if ~any(strcmp(mode, {'none', 'update-not-latched'}))
    error('P08:model:FaultMode', ...
        'fault.mode must be none or update-not-latched.');
end
fault = struct('mode', mode);
end
