function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P08.

%% Exact baseline transfer, latch, response, and settling identities
fixture = p08_scenario('baseline');
clean = model(fixture.command_voltage_v, fixture.initial_voltage_v, ...
    fixture.reference_voltage_v, fixture.dac_bits, ...
    fixture.update_latency_s, fixture.time_constant_s, ...
    fixture.slew_rate_v_per_s, fixture.tolerance_v, ...
    fixture.sample_period_s, fixture.sample_count, fixture.fault, ...
    fixture.command_deadline_s);
assert(isequal(clean.response.time_s, (0:600) .* 5e-6), ...
    'Baseline trace must retain exact t_n=n*T_s sample instants.');
assert(clean.response.time_s(end) == 0.003, ...
    'Six hundred 5 us intervals must span exactly 3 ms.');
assert(clean.quantizer.level_count == 4096 && ...
    clean.quantizer.max_code == 4095, ...
    'Twelve DAC bits must define 4096 levels and maximum code 4095.');
assert(clean.quantizer.lsb_v == 3.3 ./ 4096, ...
    'The declared unipolar LSB must equal 3.3/4096 V.');
assert(clean.quantizer.initial_code == 621 && ...
    clean.quantizer.command_code == 3103, ...
    'Nearest-code quantization must retain baseline codes 621 and 3103.');
assert(clean.quantizer.initial_voltage_v == ...
    621 .* clean.quantizer.lsb_v && ...
    clean.quantizer.command_voltage_v == ...
    3103 .* clean.quantizer.lsb_v, ...
    'Baseline code voltages must equal code times LSB exactly.');
assert(abs(clean.quantizer.initial_quantization_error_v) < ...
    clean.quantizer.lsb_v ./ 2 && ...
    abs(clean.quantizer.command_quantization_error_v) < ...
    clean.quantizer.lsb_v ./ 2, ...
    'In-range nearest-code errors must remain within half an LSB.');
assert(clean.command.digital_complete && ...
    clean.command.output_update_applied && ...
    ~clean.command.timed_out && ...
    clean.command.recorded_code == 3103, ...
    'The infinite-deadline baseline must record and apply code 3103.');

beforeUpdate = clean.response.time_s < fixture.update_latency_s;
atAndAfterUpdate = clean.response.time_s >= fixture.update_latency_s;
assert(all(clean.response.held_code(beforeUpdate) == 621) && ...
    all(clean.response.held_code(atAndAfterUpdate) == 3103), ...
    'The active code must remain initial before update and then hold command.');
updateIndex = find(clean.response.time_s == fixture.update_latency_s, 1);
assert(~isempty(updateIndex) && ...
    clean.response.output_v(updateIndex) == ...
    clean.quantizer.initial_voltage_v, ...
    'The analog output must remain continuous at the ideal latch event.');
assert(clean.settling.step_magnitude_v == 1.999658203125 && ...
    abs(clean.settling.natural_initial_slope_v_per_s - ...
    7998.6328125) < 1e-10, ...
    'The quantized step and natural initial slope must be independent identities.');
assert(clean.settling.slew_limited && ...
    abs(clean.settling.slew_duration_s - ...
    249.91455078125e-6) < 1e-15, ...
    'The baseline must cross its large-signal slew threshold at the exact time.');
expectedSettlingAfterUpdateS = clean.settling.slew_duration_s + ...
    fixture.time_constant_s .* log((fixture.slew_rate_v_per_s .* ...
    fixture.time_constant_s) ./ fixture.tolerance_v);
assert(abs(clean.settling.analytic_after_update_s - ...
    expectedSettlingAfterUpdateS) < 1e-15, ...
    'The slew-to-exponential settling equation must match independently.');
assert(abs(clean.settling.analytic_from_command_s - ...
    1.501207097278273e-3) < 1e-15, ...
    'Command-to-settling time must add the exact 100 us latch latency.');
assert(abs(clean.settling.sampled_first_stay_time_s - 1.505e-3) < ...
    1e-15 && clean.settling.settled_within_observation, ...
    'The 5 us grid must first retain the settling boundary at 1.505 ms.');
sampledStayIndex = find(clean.response.stays_in_tolerance, 1, 'first');
assert(sampledStayIndex == find(clean.response.time_s == 1.505e-3, 1) && ...
    all(clean.response.in_tolerance(sampledStayIndex:end)), ...
    'Sampled settling must mean entry and stay, not one isolated band hit.');
assert(clean.settling.final_error_v < fixture.tolerance_v, ...
    'The baseline final error must be inside its inclusive tolerance.');

%% DAC code, rail, equal-code, and observation limiting cases
lowRail = model(0, 0, 3.3, 12, 0, 250e-6, Inf, ...
    0.01, 5e-6, 2);
assert(lowRail.quantizer.command_code == 0 && ...
    lowRail.quantizer.command_voltage_v == 0, ...
    'A zero-volt command must produce code zero at the low rail.');
assert(all(lowRail.response.output_v == 0) && ...
    lowRail.settling.analytic_after_update_s == 0, ...
    'A zero step must stay constant and settle at the update.');

halfScale = model(1.65, 0, 3.3, 12, 0, 250e-6, Inf, ...
    0.01, 5e-6, 2);
assert(halfScale.quantizer.command_code == 2048 && ...
    halfScale.quantizer.command_voltage_v == 1.65, ...
    'An exact half-scale command must map to half-scale code 2048.');

highRail = model(3.3, 0, 3.3, 12, 0, 250e-6, Inf, ...
    0.01, 5e-6, 2);
assert(highRail.quantizer.command_raw_code == 4096 && ...
    highRail.quantizer.command_code == 4095 && ...
    highRail.quantizer.command_saturated, ...
    'A full-scale command must clamp to the maximum code at the high rail.');
assert(highRail.quantizer.command_voltage_v == ...
    3.3 - highRail.quantizer.lsb_v, ...
    'The maximum code voltage must be one LSB below V_ref.');

sameCode = model(0.5001, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 100);
assert(sameCode.quantizer.initial_code == ...
    sameCode.quantizer.command_code && ...
    sameCode.settling.step_magnitude_v == 0, ...
    'Requests that quantize to one code must produce no analog step.');
assert(sameCode.settling.analytic_after_update_s == 0 && ...
    sameCode.settling.sampled_first_stay_time_s == 100e-6, ...
    'An equal-code command must settle at the latch event.');

wideTolerance = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 3.3, 5e-6, 100);
assert(wideTolerance.settling.analytic_after_update_s == 0 && ...
    wideTolerance.settling.sampled_first_stay_time_s == 100e-6, ...
    'A tolerance wider than the step must accept the exact update boundary.');

betweenSamples = model(2.5, 0.5, 3.3, 12, 102.5e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601);
firstActiveIndex = find(betweenSamples.response.held_code == ...
    betweenSamples.quantizer.command_code, 1);
assert(betweenSamples.response.time_s(firstActiveIndex) == 105e-6 && ...
    betweenSamples.command.scheduled_update_time_s == 102.5e-6, ...
    'A between-sample latch must retain analytical time and sampled observation separately.');

beyondHorizon = model(2.5, 0.5, 3.3, 12, 1, ...
    250e-6, 4000, 0.01, 5e-6, 10);
assert(beyondHorizon.command.digital_complete && ...
    beyondHorizon.command.output_update_applied && ...
    ~beyondHorizon.command.update_observed, ...
    'An accepted update beyond the trace horizon must be complete but unobserved.');
assert(all(beyondHorizon.response.output_v == ...
    beyondHorizon.quantizer.initial_voltage_v) && ...
    ~beyondHorizon.settling.settled_within_observation, ...
    'A short observation must not invent an update or sampled settling event.');

%% Pure first-order, exact slew handoff, and tolerance boundaries
pole = model(2.5, 2.25, 3.3, 12, 0, 250e-6, Inf, ...
    1e-6, 250e-6, 3);
poleDistanceV = pole.settling.step_magnitude_v;
assert(~pole.settling.slew_limited && ...
    abs(pole.response.output_v(2) - ...
    (pole.quantizer.command_voltage_v - poleDistanceV ./ exp(1))) < 1e-14, ...
    'After one time constant a pole-only step must complete about 63.2 percent.');

boundaryRateVPerS = clean.settling.step_magnitude_v ./ ...
    fixture.time_constant_s;
atSlewBoundary = model(2.5, 0.5, 3.3, 12, 0, ...
    fixture.time_constant_s, boundaryRateVPerS, fixture.tolerance_v, ...
    fixture.time_constant_s, 2);
assert(~atSlewBoundary.settling.slew_limited && ...
    abs(atSlewBoundary.response.intended_error_v(2) - ...
    clean.settling.step_magnitude_v ./ exp(1)) < 1e-14, ...
    'At S=D/tau the slew threshold must equal the pure exponential branch.');

handoffTimeS = clean.settling.slew_duration_s;
atHandoff = model(2.5, 0.5, 3.3, 12, 0, ...
    fixture.time_constant_s, fixture.slew_rate_v_per_s, ...
    fixture.tolerance_v, handoffTimeS, 2);
assert(abs(atHandoff.response.intended_error_v(end) - ...
    fixture.slew_rate_v_per_s .* fixture.time_constant_s) < 1e-14, ...
    'The slew-to-exponential response must be continuous at the handoff.');
justAfterHandoff = model(2.5, 0.5, 3.3, 12, 0, ...
    fixture.time_constant_s, fixture.slew_rate_v_per_s, ...
    fixture.tolerance_v, handoffTimeS + eps(handoffTimeS), 2);
assert(abs(justAfterHandoff.response.output_v(end) - ...
    atHandoff.response.output_v(end)) < 1e-10, ...
    'One floating-point step after handoff must not create a voltage jump.');

atSettlingBoundary = model(2.5, 0.5, 3.3, 12, 0, ...
    fixture.time_constant_s, fixture.slew_rate_v_per_s, ...
    fixture.tolerance_v, clean.settling.analytic_after_update_s, 2);
assert(atSettlingBoundary.response.intended_error_v(end) <= ...
    fixture.tolerance_v .* (1 + 1e-12), ...
    'The analytic settling boundary must enter the inclusive tolerance.');
justBeforeSettling = model(2.5, 0.5, 3.3, 12, 0, ...
    fixture.time_constant_s, fixture.slew_rate_v_per_s, ...
    fixture.tolerance_v, clean.settling.analytic_after_update_s - 1e-12, 2);
assert(justBeforeSettling.response.intended_error_v(end) > ...
    fixture.tolerance_v, ...
    'A representably earlier response time must remain outside tolerance.');

subnormalToleranceV = eps(0);
subnormalPole = model(2.5, 2.25, 3.3, 12, 0, 250e-6, Inf, ...
    subnormalToleranceV, 250e-6, 3);
expectedSubnormalPoleS = subnormalPole.input.time_constant_s .* ...
    (log(subnormalPole.settling.step_magnitude_v) - ...
    log(subnormalToleranceV));
assert(isfinite(subnormalPole.settling.analytic_after_update_s) && ...
    subnormalPole.settling.analytic_after_update_s == ...
    expectedSubnormalPoleS, ...
    ['A positive subnormal tolerance must retain a finite pole settling ' ...
    'calculation without overflowing an intermediate ratio.']);
subnormalSlew = model(2.5, 0.5, 3.3, 12, 0, 250e-6, 4000, ...
    subnormalToleranceV, 250e-6, 3);
expectedSubnormalSlewS = subnormalSlew.settling.slew_duration_s + ...
    subnormalSlew.input.time_constant_s .* ...
    (log(subnormalSlew.input.slew_rate_v_per_s .* ...
    subnormalSlew.input.time_constant_s) - log(subnormalToleranceV));
assert(isfinite(subnormalSlew.settling.analytic_after_update_s) && ...
    subnormalSlew.settling.analytic_after_update_s == ...
    expectedSubnormalSlewS, ...
    ['A positive subnormal tolerance must retain a finite hybrid settling ' ...
    'calculation without overflowing an intermediate ratio.']);

subnormalSamplePeriodS = 1e-3;
subnormalSampled = model(2.5, 2.25, 3.3, 12, 0, 250e-6, Inf, ...
    subnormalToleranceV, subnormalSamplePeriodS, 201);
expectedSubnormalSampleTimeS = ceil( ...
    subnormalSampled.settling.analytic_after_update_s ./ ...
    subnormalSamplePeriodS) .* subnormalSamplePeriodS;
subnormalStayIndex = find( ...
    subnormalSampled.response.stays_in_tolerance, 1, 'first');
assert(subnormalSampled.settling.settled_within_observation && ...
    abs(subnormalSampled.settling.sampled_first_stay_time_s - ...
    expectedSubnormalSampleTimeS) <= eps(expectedSubnormalSampleTimeS) && ...
    subnormalSampled.settling.sampled_first_stay_time_s >= ...
    subnormalSampled.settling.analytic_after_update_s, ...
    ['Subnormal sampled settling must use the remaining-error state, not ' ...
    'cancellation-prone subtraction of rounded output voltages.']);
assert(subnormalStayIndex > 1 && ...
    subnormalSampled.response.intended_error_v( ...
    subnormalStayIndex - 1) > subnormalToleranceV && ...
    subnormalSampled.response.intended_error_v(subnormalStayIndex) <= ...
    subnormalToleranceV, ...
    'The retained grid must cross the subnormal tolerance at its first stay.');

%% Time-constant and slew-rate sweeps retain independent inputs
timeConstantSweepS = [100 250 500 1000 2000] .* 1e-6;
previousSettlingS = -Inf;
for sweepIndex = 1:numel(timeConstantSweepS)
    swept = model(2.5, 0.5, 3.3, 12, 100e-6, ...
        timeConstantSweepS(sweepIndex), 4000, 0.01, 5e-6, 601);
    assert(swept.quantizer.command_code == 3103 && ...
        swept.command.scheduled_update_time_s == 100e-6 && ...
        swept.input.slew_rate_v_per_s == 4000 && ...
        swept.input.tolerance_v == 0.01, ...
        'Time-constant sweep must isolate its pole lever.');
    assert(swept.settling.analytic_after_update_s > previousSettlingS, ...
        'Increasing time constant must lengthen this fixture settling time.');
    previousSettlingS = swept.settling.analytic_after_update_s;
end

slewRateSweepVPerS = [Inf 8000 4000 2000 1000];
previousSettlingS = -Inf;
for sweepIndex = 1:numel(slewRateSweepVPerS)
    swept = model(2.5, 0.5, 3.3, 12, 100e-6, 250e-6, ...
        slewRateSweepVPerS(sweepIndex), 0.01, 5e-6, 601);
    assert(swept.quantizer.command_code == 3103 && ...
        swept.command.scheduled_update_time_s == 100e-6 && ...
        swept.input.time_constant_s == 250e-6 && ...
        swept.input.tolerance_v == 0.01, ...
        'Slew-rate sweep must isolate its large-signal lever.');
    assert(swept.settling.analytic_after_update_s >= previousSettlingS, ...
        'Lowering the ordered slew rate must not shorten settling time.');
    previousSettlingS = swept.settling.analytic_after_update_s;
end

%% Update-not-latched fault, deadline, rollback, and clean recovery
brokenFixture = p08_scenario('update-not-latched');
broken = model(brokenFixture.command_voltage_v, ...
    brokenFixture.initial_voltage_v, brokenFixture.reference_voltage_v, ...
    brokenFixture.dac_bits, brokenFixture.update_latency_s, ...
    brokenFixture.time_constant_s, brokenFixture.slew_rate_v_per_s, ...
    brokenFixture.tolerance_v, brokenFixture.sample_period_s, ...
    brokenFixture.sample_count, brokenFixture.fault, Inf);
assert(broken.command.digital_complete && ...
    broken.command.recorded_code == 3103 && ...
    ~broken.command.output_update_applied, ...
    'The register command completes while the update not latched fault blocks output.');
assert(all(broken.response.held_code == 621) && ...
    all(broken.response.output_v == ...
    broken.quantizer.initial_voltage_v) && ...
    isinf(broken.settling.analytic_after_update_s), ...
    'Digital command can complete without analog movement or settling.');

rolledBack = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], []);
assert(isequaln(rolledBack, clean), ...
    'Removing fault and deadline inputs must roll back exactly to baseline.');

exactDeadline = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], 100e-6);
assert(exactDeadline.command.digital_complete && ...
    exactDeadline.command.output_update_applied && ...
    ~exactDeadline.command.timed_out && ...
    exactDeadline.command.recorded_code == 3103, ...
    'A deadline exactly at update latency must accept the command.');

justShortDeadlineS = 100e-6 - eps(100e-6);
justShort = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], justShortDeadlineS);
assert(justShort.command.timed_out && ...
    ~justShort.command.digital_complete && ...
    isempty(justShort.command.recorded_code), ...
    'A deadline one representable step before update must reject strictly.');
assert(all(justShort.response.held_code == 621) && ...
    all(justShort.response.output_v == ...
    justShort.quantizer.initial_voltage_v), ...
    'A timed-out command must not move the active code or analog output.');

zeroDeadline = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], 0);
assert(zeroDeadline.command.timed_out && ...
    isempty(zeroDeadline.command.recorded_voltage_v), ...
    'A zero deadline must reject a positive-latency command result.');

retryAfterTimeout = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], Inf);
assert(isequaln(retryAfterTimeout, clean), ...
    'A clean retry after timeout must recover the exact baseline.');
% This finite pure calculation has no external operation to cancel.

%% Determinism, compatibility, state isolation, and callback lifetime
first = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601);
second = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601);
assert(isequaln(first, second), ...
    'Repeated calls must be deterministic and state-isolated.');

integerInputs = model(uint8(2), uint8(1), uint8(4), uint8(12), ...
    uint8(0), uint8(1), uint8(10), uint8(1), uint8(1), ...
    uint8(3), struct('mode', string('none')), []);
scalarNumericExpected = model(2, 1, 4, 12, 0, 1, 10, 1, 1, 3);
assert(isequaln(integerInputs, scalarNumericExpected), ...
    'Supported integer inputs and scalar numeric compatibility must normalize.');
explicitDefaults = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], []);
assert(isequaln(first, explicitDefaults), ...
    'Omitted and empty optional fault/deadline inputs must be compatible.');

callbackModel = @model;
callbackScenario = @p08_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.command_voltage_v, ...
    callbackInput.initial_voltage_v, callbackInput.reference_voltage_v, ...
    callbackInput.dac_bits, callbackInput.update_latency_s, ...
    callbackInput.time_constant_s, callbackInput.slew_rate_v_per_s, ...
    callbackInput.tolerance_v, callbackInput.sample_period_s, ...
    callbackInput.sample_count);
assert(callbackOut.quantizer.command_code == 3103 && ...
    callbackOut.settling.slew_limited, ...
    ['Callback-bound P08 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed input, fault schema, timing, and resource-bound rejection
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6), 'P08:model:Arity');
assertReject(@() model('2.5', 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(true, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(NaN, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(1i, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(-1, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(3.4, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:CommandVoltage');
assertReject(@() model(2.5, '0.5', 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:InitialVoltage');
assertReject(@() model(2.5, 3.4, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:InitialVoltage');
assertReject(@() model(2.5, 0.5, 0, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:ReferenceVoltage');
assertReject(@() model(2.5, 0.5, 1001, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:ReferenceVoltage');
assertReject(@() model(0, 0, eps(0), 12, 0, ...
    1, Inf, eps(0), 1, 2), 'P08:model:ReferenceResolution');
assertReject(@() model(2.5, 0.5, 3.3, 1, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:DACBits');
assertReject(@() model(2.5, 0.5, 3.3, 12.5, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:DACBits');
assertReject(@() model(2.5, 0.5, 3.3, 25, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:DACBits');
assertReject(@() model(2.5, 0.5, 3.3, 12, -1, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:UpdateLatency');
assertReject(@() model(2.5, 0.5, 3.3, 12, NaN, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:UpdateLatency');
assertReject(@() model(2.5, 0.5, 3.3, 12, 1e6 + 1, ...
    250e-6, 4000, 0.01, 5e-6, 601), 'P08:model:UpdateLatency');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    0, 4000, 0.01, 5e-6, 601), 'P08:model:TimeConstant');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    Inf, 4000, 0.01, 5e-6, 601), 'P08:model:TimeConstant');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 0, 0.01, 5e-6, 601), 'P08:model:SlewRate');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, NaN, 0.01, 5e-6, 601), 'P08:model:SlewRate');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, -Inf, 0.01, 5e-6, 601), 'P08:model:SlewRate');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 1e12 + 1, 0.01, 5e-6, 601), 'P08:model:SlewRate');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0, 5e-6, 601), 'P08:model:Tolerance');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 3.4, 5e-6, 601), 'P08:model:Tolerance');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 0, 601), 'P08:model:SamplePeriod');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, Inf, 601), 'P08:model:SamplePeriod');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 1), 'P08:model:SampleCount');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 2.5), 'P08:model:SampleCount');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 10001), 'P08:model:ResourceBound');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 1e6, 3), 'P08:model:TimingResourceBound');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, {'none'}, Inf), ...
    'P08:model:Fault');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, struct(), Inf), ...
    'P08:model:Fault');
extraFault = struct('mode', 'none', 'extra', 1);
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, extraFault, Inf), ...
    'P08:model:Fault');
badMode = struct('mode', 'amplifier-magic');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, badMode, Inf), ...
    'P08:model:FaultMode');
badModeType = struct('mode', {'none', 'update-not-latched'});
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, badModeType, Inf), ...
    'P08:model:Fault');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], -1), ...
    'P08:model:CommandDeadline');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], NaN), ...
    'P08:model:CommandDeadline');
assertReject(@() model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601, [], -Inf), ...
    'P08:model:CommandDeadline');

largestAccepted = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 1e-6, 10000);
assert(numel(largestAccepted.response.time_s) == 10000, ...
    'The accepted upper bound must produce exactly 10000 bounded samples.');
assertReject(@() p08_scenario({'baseline'}), 'P08:scenario:Kind');
assertReject(@() p08_scenario('baseline', 1), ...
    'P08:scenario:SampleCount');
assertReject(@() p08_scenario('baseline', 10001), ...
    'P08:scenario:SampleCount');
assertReject(@() p08_scenario('unknown'), 'P08:scenario:Kind');

afterRejection = model(2.5, 0.5, 3.3, 12, 100e-6, ...
    250e-6, 4000, 0.01, 5e-6, 601);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('No asynchronous wait or cancellation API exists in this pure model.');
disp('P08 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
