function run_checks()
%RUN_CHECKS Independent numerical and contract checks for P14.
modelFcn = @model;
scenarioFcn = @p14_scenario;
runFixture = @(input) modelFcn(input.source_samples, ...
    input.producer_period_us, input.consumer_period_us, ...
    input.consumer_quota_samples, input.consumer_start_us, ...
    input.capacity_samples, input.overrun_policy, ...
    input.drain_timeout_us, input.timeout_action);

%% Deterministic baseline and independent ring recurrence
fixture = scenarioFcn('baseline');
clean = runFixture(fixture);
repeat = runFixture(fixture);
assert(isequaln(clean, repeat), ...
    'The same P14 input must return the same complete result.');

sampleCount = numel(fixture.source_samples);
referenceOccupancy = zeros(1, sampleCount);
referenceAgeUs = zeros(1, sampleCount);
occupancy = 0;
for sourceId = 1:sampleCount
    readyUs = (sourceId - 1) .* fixture.producer_period_us;
    if readyUs > 0 && mod(readyUs, fixture.consumer_period_us) == 0
        occupancy = max(0, occupancy - ...
            fixture.consumer_quota_samples);
    end
    occupancy = occupancy + 1;
    referenceOccupancy(sourceId) = occupancy;
    nextServiceUs = fixture.consumer_start_us + ...
        ceil(max(0, readyUs - fixture.consumer_start_us) ./ ...
        fixture.consumer_period_us) .* fixture.consumer_period_us;
    if nextServiceUs < readyUs || ...
            (nextServiceUs == readyUs && readyUs == 0)
        nextServiceUs = nextServiceUs + fixture.consumer_period_us;
    end
    if nextServiceUs == readyUs
        nextServiceUs = nextServiceUs + fixture.consumer_period_us;
    end
    referenceAgeUs(sourceId) = nextServiceUs - readyUs;
end
assert(isequal(referenceOccupancy, repmat([1 2 3 4], 1, 8)) && ...
    isequal(clean.producer.occupancy_after, referenceOccupancy), ...
    'Baseline occupancy recurrence changed.');
assert(clean.metrics.producer_rate_samples_per_s == 20000 && ...
    clean.metrics.consumer_capacity_samples_per_s == 20000 && ...
    clean.metrics.offered_load_ratio == 1 && ...
    clean.metrics.finite_trace_required_capacity_samples == 4 && ...
    clean.metrics.peak_occupancy_samples == 4, ...
    'Independent baseline rate or capacity arithmetic changed.');
assert(clean.metrics.full_write_encounter_count == 0 && ...
    clean.metrics.data_loss_count == 0 && ...
    clean.metrics.source_conservation_error_samples == 0 && ...
    clean.metrics.occupancy_bound_respected && ...
    clean.metrics.fifo_order_preserved, ...
    'Safe baseline storage, FIFO, or conservation changed.');
assert(isequal(clean.consumer.consumed_source_id, 1:32) && ...
    isequal(clean.consumer.consumed_samples, fixture.source_samples) && ...
    isequal(clean.consumer.age_us, repmat([200 150 100 50], 1, 8)) && ...
    min(clean.consumer.age_us) == 50 && ...
    mean(clean.consumer.age_us) == 125 && ...
    max(clean.consumer.age_us) == 200 && ...
    clean.observation.last_producer_decision_us == 1550 && ...
    clean.observation.campaign_completion_us == 1600 && ...
    clean.ring.final_occupancy_samples == 0, ...
    'Baseline sequence identity, residence, or drain changed.');

%% Sweep 1: usable capacity only
capacitySweepSamples = [1 2 3 4 6 8];
capacityLost = zeros(size(capacitySweepSamples));
capacityPeak = zeros(size(capacitySweepSamples));
capacityConsumed = zeros(size(capacitySweepSamples));
for sweepIndex = 1:numel(capacitySweepSamples)
    input = fixture;
    input.capacity_samples = capacitySweepSamples(sweepIndex);
    swept = runFixture(input);
    capacityLost(sweepIndex) = swept.metrics.data_loss_count;
    capacityPeak(sweepIndex) = swept.metrics.peak_occupancy_samples;
    capacityConsumed(sweepIndex) = swept.metrics.consumed_count;
    assert(swept.input.producer_period_us == ...
        clean.input.producer_period_us && ...
        swept.input.consumer_period_us == ...
        clean.input.consumer_period_us && ...
        swept.input.consumer_quota_samples == ...
        clean.input.consumer_quota_samples && ...
        swept.metrics.offered_load_ratio == 1 && ...
        swept.metrics.source_conservation_error_samples == 0, ...
        'Capacity sweep must isolate capacity and conserve source IDs.');
end
assert(isequal(capacityLost, [24 16 8 0 0 0]) && ...
    isequal(capacityPeak, [1 2 3 4 4 4]) && ...
    isequal(capacityConsumed, [8 16 24 32 32 32]), ...
    'Capacity sweep reference vectors changed.');

%% Sweep 2: reset, then consumer service quota only
quotaSweepSamples = [1 2 3 4 5 8];
quotaLost = zeros(size(quotaSweepSamples));
quotaPeak = zeros(size(quotaSweepSamples));
quotaRequired = zeros(size(quotaSweepSamples));
quotaDrainUs = zeros(size(quotaSweepSamples));
quotaLoad = zeros(size(quotaSweepSamples));
for sweepIndex = 1:numel(quotaSweepSamples)
    input = fixture;
    input.consumer_quota_samples = quotaSweepSamples(sweepIndex);
    swept = runFixture(input);
    quotaLost(sweepIndex) = swept.metrics.data_loss_count;
    quotaPeak(sweepIndex) = swept.metrics.peak_occupancy_samples;
    quotaRequired(sweepIndex) = ...
        swept.metrics.finite_trace_required_capacity_samples;
    quotaDrainUs(sweepIndex) = ...
        swept.observation.campaign_completion_us;
    quotaLoad(sweepIndex) = swept.metrics.offered_load_ratio;
    assert(swept.input.capacity_samples == clean.input.capacity_samples && ...
        swept.input.producer_period_us == ...
        clean.input.producer_period_us && ...
        swept.input.consumer_period_us == ...
        clean.input.consumer_period_us && ...
        strcmp(swept.input.overrun_policy, ...
        clean.input.overrun_policy) && ...
        swept.metrics.source_conservation_error_samples == 0, ...
        'Quota sweep must isolate service quota and conserve source IDs.');
end
assert(isequal(quotaLost, [17 10 3 0 0 0]) && ...
    isequal(quotaPeak, [8 8 8 4 4 4]) && ...
    isequal(quotaRequired, [25 18 11 4 4 4]) && ...
    isequal(quotaDrainUs, [3000 2200 2000 1600 1600 1600]) && ...
    max(abs(quotaLoad - [4 2 4/3 1 0.8 0.5])) < 1e-12, ...
    'Consumer-quota sweep reference vectors changed.');

%% Broken bounded-occupancy criterion and explicit full policies
broken = runFixture(scenarioFcn('overwrite-oldest'));
expectedConsumed = [1 5 9 13 17 21 25 29 30 31 32];
expectedOverwritten = ...
    [2 3 4 6 7 8 10 11 12 14 15 16 18 19 20 22 23 24 26 27 28];
assert(broken.metrics.occupancy_bound_respected && ...
    broken.metrics.accepted_write_count == 32 && ...
    broken.metrics.dropped_newest_count == 0 && ...
    broken.metrics.overwritten_oldest_count == 21 && ...
    broken.metrics.data_loss_count == 21 && ...
    broken.metrics.full_write_encounter_count == 21, ...
    'Overwrite-oldest must expose loss despite bounded accepted writes.');
assert(isequal(broken.consumer.consumed_source_id, expectedConsumed) && ...
    isequal(find(broken.producer.overwritten_oldest), ...
    expectedOverwritten) && ...
    broken.metrics.source_conservation_error_samples == 0, ...
    'Overwrite-oldest survivor identities or conservation changed.');

dropInput = scenarioFcn('overwrite-oldest');
dropInput.overrun_policy = 'drop-newest';
dropped = runFixture(dropInput);
assert(dropped.metrics.dropped_newest_count == 21 && ...
    dropped.metrics.overwritten_oldest_count == 0 && ...
    isequal(dropped.consumer.consumed_source_id, ...
    [1 2 3 4 5 9 13 17 21 25 29]) && ...
    dropped.metrics.source_conservation_error_samples == 0, ...
    'Drop-newest must preserve the older queued survivors.');

backpressured = runFixture(scenarioFcn('backpressure'));
assert(backpressured.metrics.data_loss_count == 0 && ...
    isequal(backpressured.consumer.consumed_source_id, 1:32) && ...
    backpressured.metrics.full_write_encounter_count == 27 && ...
    backpressured.metrics.producer_stall_event_count == 27 && ...
    backpressured.metrics.total_producer_stall_us == 4050 && ...
    backpressured.observation.last_producer_decision_us == 5600 && ...
    backpressured.observation.campaign_completion_us == 6400 && ...
    backpressured.metrics.source_conservation_error_samples == 0, ...
    'Throttleable backpressure must trade producer timing for zero loss.');

%% Drain timeout equality, continuation, cancellation, rollback, recovery
equalityInput = fixture;
equalityInput.drain_timeout_us = 50;
equalityInput.timeout_action = 'cancel-consumer';
equality = runFixture(equalityInput);
assert(~equality.observation.wait_timed_out && ...
    ~equality.observation.consumer_cancelled && ...
    equality.observation.campaign_complete && ...
    equality.observation.campaign_completion_us == 1600, ...
    'A consumer event exactly at the drain deadline must pass.');

continued = runFixture(scenarioFcn('timeout-continue'));
assert(continued.observation.wait_timed_out && ...
    ~continued.observation.consumer_cancelled && ...
    continued.observation.pending_count_at_timeout == 4 && ...
    continued.observation.campaign_complete && ...
    continued.observation.campaign_completion_us == 1600 && ...
    continued.metrics.consumed_count == 32, ...
    'Continue-waiting must retain the eventual drain after timeout.');

cancelled = runFixture(scenarioFcn('timeout-cancel'));
assert(cancelled.observation.wait_timed_out && ...
    cancelled.observation.consumer_cancelled && ...
    ~cancelled.observation.campaign_complete && ...
    isnan(cancelled.observation.campaign_completion_us) && ...
    cancelled.observation.reference_campaign_completion_us == 1600 && ...
    cancelled.metrics.consumed_count == 28 && ...
    cancelled.metrics.pending_count == 4 && ...
    cancelled.metrics.data_loss_count == 0 && ...
    isequal(cancelled.ring.pending_source_id, 29:32) && ...
    cancelled.metrics.source_conservation_error_samples == 0, ...
    'Cancellation must retain four pending records without calling them loss.');

rollback = runFixture(fixture);
afterCancellation = runFixture(fixture);
assert(isequaln(rollback, clean) && isequaln(afterCancellation, clean), ...
    'Pure clean input must provide exact computational rollback and recovery.');

%% Limiting cases, full/empty pointer ambiguity, and compatibility
capacityOne = modelFcn(1:4, 50, 50, 1, 50, 1, ...
    'drop-newest', Inf, 'continue-waiting');
assert(capacityOne.metrics.data_loss_count == 0 && ...
    capacityOne.metrics.peak_occupancy_samples == 1 && ...
    isequal(capacityOne.consumer.consumed_source_id, 1:4) && ...
    capacityOne.observation.campaign_completion_us == 200 && ...
    capacityOne.metrics.pointer_equality_ambiguous, ...
    'Consumer-before-producer ties must make capacity one safe and explicit.');

fractionalTie = modelFcn(1:7, 0.1, 0.1, 1, 0.2, 2, ...
    'drop-newest', Inf, 'continue-waiting');
expectedFractionalReadyUs = (0:6) .* 0.1;
assert(isequal(fractionalTie.producer.ready_us, ...
    expectedFractionalReadyUs) && ...
    isequal(fractionalTie.producer.decision_us, ...
    expectedFractionalReadyUs) && ...
    isequal(fractionalTie.producer.occupancy_after, ...
    [1 2 2 2 2 2 2]) && ...
    fractionalTie.metrics.finite_trace_required_capacity_samples == 2 && ...
    fractionalTie.metrics.peak_occupancy_samples == 2 && ...
    fractionalTie.metrics.full_write_encounter_count == 0 && ...
    fractionalTie.metrics.data_loss_count == 0 && ...
    isequal(fractionalTie.consumer.consumed_source_id, 1:7) && ...
    abs(fractionalTie.observation.campaign_completion_us - 0.8) <= ...
    4 .* eps(0.8), ...
    ['Fractional commensurate schedules must preserve anchored ' ...
    'consumer-before-producer ties without recurrence drift.']);

exactFull = modelFcn(1:4, 10, 1000, 4, 1000, 4, ...
    'drop-newest', Inf, 'continue-waiting');
assert(exactFull.metrics.peak_occupancy_samples == 4 && ...
    exactFull.metrics.full_write_encounter_count == 0 && ...
    exactFull.metrics.data_loss_count == 0 && ...
    exactFull.metrics.full_pointer_equality_count > 0 && ...
    exactFull.observation.campaign_completion_us == 1000, ...
    'Exactly filling all C slots is full but is not yet overrun.');

oneTooMany = modelFcn(1:5, 10, 1000, 5, 1000, 4, ...
    'drop-newest', Inf, 'continue-waiting');
assert(oneTooMany.metrics.full_write_encounter_count == 1 && ...
    oneTooMany.metrics.dropped_newest_count == 1 && ...
    isequal(oneTooMany.consumer.consumed_source_id, 1:4), ...
    'The first write attempted while full must invoke the declared policy.');

wholeCampaignCapacity = modelFcn(1:8, 10, 1000, 8, 1000, 8, ...
    'drop-newest', Inf, 'continue-waiting');
assert(wholeCampaignCapacity.metrics.data_loss_count == 0 && ...
    wholeCampaignCapacity.metrics.peak_occupancy_samples == 8 && ...
    isequal(wholeCampaignCapacity.consumer.consumed_source_id, 1:8), ...
    'Capacity equal to the finite campaign must retain delayed records.');

duplicateValues = modelFcn([7 7 7 7], 50, 50, 1, 50, 1, ...
    'drop-newest', Inf, 'continue-waiting');
assert(isequal(duplicateValues.consumer.consumed_source_id, 1:4) && ...
    isequal(duplicateValues.consumer.consumed_samples, [7 7 7 7]), ...
    'Duplicate values must not collapse independent source identities.');

compatible = modelFcn(uint16(fixture.source_samples'), uint8(50), ...
    uint16(200), uint8(4), uint16(200), uint8(8), ...
    string('drop-newest'), [], string('continue-waiting'));
assert(isequaln(compatible, clean), ...
    'Column/integer/string/empty compatibility must normalize exactly.');
emptyDefaults = modelFcn(fixture.source_samples, 50, 200, 4, 200, 8, ...
    [], [], []);
assert(isequaln(emptyDefaults, clean), ...
    'Empty policy, timeout, and action must recover baseline defaults.');
safeInteger = modelFcn(uint64([0 flintmax]), 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting');
assert(isequal(safeInteger.consumer.consumed_samples, [0 flintmax]), ...
    'Integer source values through flintmax must retain exact identity.');
stringScenario = scenarioFcn(string('baseline'));
assert(isequaln(stringScenario, fixture), ...
    'Scalar-string and character scenario names must agree.');
fixedOverride = scenarioFcn('overwrite-oldest', 64, 8, 100, 300, 10);
assert(isequaln(fixedOverride, scenarioFcn('overwrite-oldest')), ...
    'Named fixed diagnostics must replace every editable override.');

%% Callback lifetime and module isolation
callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
clear model;
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.source_samples, ...
    callbackInput.producer_period_us, callbackInput.consumer_period_us, ...
    callbackInput.consumer_quota_samples, callbackInput.consumer_start_us, ...
    callbackInput.capacity_samples, callbackInput.overrun_policy, ...
    callbackInput.drain_timeout_us, callbackInput.timeout_action);
assert(isequaln(callbackOut, clean), ...
    ['Callback-bound P14 dependencies must survive module path cleanup ' ...
    'and a conflicting generic model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn(1, 50, 200, 4, 200, 8, ...
    'drop-newest', Inf), 'P14:model:Arity');
assertReject(@() modelFcn([], 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SourceSamples');
assertReject(@() modelFcn(true, 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SourceSamples');
assertReject(@() modelFcn(1 + 1i, 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SourceSamples');
assertReject(@() modelFcn(NaN, 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SourceSamples');
assertReject(@() modelFcn(ones(2), 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SourceSamples');
assertReject(@() modelFcn(uint64(flintmax) + uint64(1), ...
    50, 200, 4, 200, 8, 'drop-newest', Inf, ...
    'continue-waiting'), 'P14:model:SourcePrecision');

assertReject(@() modelFcn(1, 0, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:ProducerPeriod');
assertReject(@() modelFcn(1, 50, Inf, 4, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:ConsumerPeriod');
assertReject(@() modelFcn(1, 50, 200, 0, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:ConsumerQuota');
assertReject(@() modelFcn(1, 50, 200, 1.5, 200, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:ConsumerQuota');
assertReject(@() modelFcn(1, 50, 200, 4, -1, 8, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:ConsumerStart');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 0, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:Capacity');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 1.5, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:Capacity');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 8, ...
    'block', Inf, 'continue-waiting'), 'P14:model:Policy');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 8, ...
    {'drop-newest'}, Inf, 'continue-waiting'), 'P14:model:Policy');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 8, ...
    'drop-newest', -1, 'continue-waiting'), ...
    'P14:model:DrainTimeout');
assertReject(@() modelFcn(1, 50, 200, 4, 200, 8, ...
    'drop-newest', Inf, 'flush-ring'), ...
    'P14:model:TimeoutAction');

largest = modelFcn(1:10000, 1, 1, 1, 1, 1, ...
    'drop-newest', Inf, 'continue-waiting');
assert(largest.metrics.sample_count == 10000 && ...
    largest.metrics.data_loss_count == 0 && ...
    largest.metrics.source_conservation_error_samples == 0, ...
    'The accepted 10,000-record event boundary must execute.');
assertReject(@() modelFcn(zeros(1, 10001), 1, 1, 1, 1, 1, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:SampleResourceBound');
largestCapacity = modelFcn(1, 1, 1, 1, 1, 100000, ...
    'drop-newest', Inf, 'continue-waiting');
assert(largestCapacity.metrics.capacity_samples == 100000 && ...
    largestCapacity.metrics.data_loss_count == 0, ...
    'The accepted capacity resource boundary must execute.');
assertReject(@() modelFcn(1, 1, 1, 1, 1, 100001, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:CapacityResourceBound');
assertReject(@() modelFcn([1 2], 1e12, 1, 1, 0, 2, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:TimelineResourceBound');
assertReject(@() modelFcn(1, 1, 1e-6, 1, 1e12 - 10, 1, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:TimingPrecision');
assertReject(@() modelFcn(1:3, realmin, 1, 1, 1, 1, ...
    'backpressure', Inf, 'continue-waiting'), ...
    'P14:model:TimingPrecision');
assertReject(@() modelFcn(1:2, 50, 1000, 2, 1000, 2, ...
    'drop-newest', realmin, 'continue-waiting'), ...
    'P14:model:TimingPrecision');
assertReject(@() modelFcn(1, realmin, 1, 1, 1, 1, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:TimingPrecision');
assertReject(@() modelFcn(1, 1e-300, 1e7, 1, 0, 1, ...
    'drop-newest', Inf, 'continue-waiting'), ...
    'P14:model:TimingPrecision');

assertReject(@() scenarioFcn({'baseline'}), 'P14:scenario:Name');
assertReject(@() scenarioFcn('unknown'), 'P14:scenario:Name');
assertReject(@() scenarioFcn('baseline', 0), ...
    'P14:scenario:CapacitySamples');
assertReject(@() scenarioFcn('baseline', 8, 1.5), ...
    'P14:scenario:ConsumerQuotaSamples');
assertReject(@() scenarioFcn('baseline', 8, 4, 0), ...
    'P14:scenario:ProducerPeriod');
assertReject(@() scenarioFcn('baseline', 8, 4, 0.5), ...
    'P14:scenario:ProducerPeriod');
assertReject(@() scenarioFcn('baseline', 8, 4, 50, Inf), ...
    'P14:scenario:ConsumerPeriod');
assertReject(@() scenarioFcn('baseline', 8, 4, 50, 200, -1), ...
    'P14:scenario:DrainTimeout');
assertReject(@() scenarioFcn('baseline', 8, 4, 50, 200, 0.5), ...
    'P14:scenario:DrainTimeout');
assertReject(@() scenarioFcn('baseline', 8, 4, 50, 200, Inf, 1), ...
    'P14:scenario:Arity');

afterMalformed = runFixture(fixture);
assert(isequaln(afterMalformed, clean), ...
    'A malformed or rejected call must not contaminate clean recovery.');

disp(['P14 source IDs conserve consumed, pending, drop-newest, and ' ...
    'overwrite-oldest outcomes independently of sample values.']);
disp(['Backpressure is modeled only for a throttleable producer; ' ...
    'consumer cancellation retains pending ring state.']);
disp(['Checks are deterministic calculations, not MATLAB-runtime ' ...
    'evidence unless this file is executed on a named MATLAB runtime.']);
disp('P14 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
