function run_checks
%RUN_CHECKS Verify P09 scheduler semantics, boundaries, and recovery.

modelFcn = @model;
scenarioFcn = @p09_scenario;
fixture = scenarioFcn('baseline');
clean = modelFcn(fixture.period_ms, fixture.execution_ms, ...
    fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
    fixture.tick_ms, fixture.horizon_ms, fixture.deadline_action);

%% Deterministic baseline, exact timeline, and conservation
repeat = modelFcn(fixture.period_ms, fixture.execution_ms, ...
    fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
    fixture.tick_ms, fixture.horizon_ms, fixture.deadline_action);
assert(isequaln(clean, repeat), ...
    'Repeated baseline calls must be deterministic and state-isolated.');
expectedOwner = [ ...
    1 2 2 3 3 1 3 3 3 0 1 2 2 0 0 1 0 0 0 0 ...
    1 2 2 3 3 1 3 3 3 0 1 2 2 0 0 1 0 0 0 0];
assert(isequal(clean.schedule.owner_task_id, expectedOwner), ...
    'Baseline owner intervals must retain the exact dispatch sequence.');
assert(isequal(clean.metrics.release_count_by_task, [8 4 2]), ...
    'The half-open 40 ms horizon must release [8 4 2] jobs.');
assert(isequal(clean.metrics.completion_count_by_task, [8 4 2]), ...
    'Every baseline job must complete within the observation.');
assert(isequal(clean.metrics.service_time_ms_by_task, [8 8 10]), ...
    'Baseline service must retain [8 8 10] ms by task.');
assert(isequal(clean.metrics.worst_response_ms_by_task, [1 3 9]), ...
    'Baseline worst responses must be [1 3 9] ms.');
assert(isequal(clean.metrics.deadline_miss_count_by_task, [0 0 0]), ...
    'The baseline must have no deadline timeouts.');
assert(clean.metrics.preemption_count == 2 && ...
    sum(clean.jobs.preemption_count(clean.jobs.task_id == 3)) == 2, ...
    'The logger must be preempted by control exactly twice.');
assert(abs(clean.metrics.nominal_utilization - 0.65) < 1e-14, ...
    'Nominal utilization must equal 1/5 + 2/10 + 5/20.');
assert(clean.metrics.busy_time_ms == 26 && ...
    clean.metrics.idle_time_ms == 14 && ...
    clean.metrics.busy_time_ms + clean.metrics.idle_time_ms == 40, ...
    'Busy and idle time must conserve the 40 ms horizon.');
assert(abs(clean.metrics.busy_fraction - 0.65) < 1e-14 && ...
    abs(clean.metrics.idle_fraction - 0.35) < 1e-14, ...
    'Busy and idle fractions must match retained service.');
assert(clean.metrics.demand_conservation_error_ms == 0 && ...
    clean.metrics.released_demand_ms == ...
    clean.metrics.served_work_ms, ...
    'Released, served, remaining, and canceled demand must conserve work.');
assert(isequal(clean.metrics.release_count_by_task, ...
    clean.metrics.completion_count_by_task + ...
    clean.metrics.unfinished_count_by_task + ...
    clean.metrics.deadline_cancel_count_by_task), ...
    'Every released baseline job must have one terminal or pending state.');
assert(clean.metrics.max_ready_jobs >= 1 && ...
    clean.metrics.max_ready_jobs <= sum(clean.metrics.release_count_by_task), ...
    'Ready depth must remain within the bounded released-job population.');
assert(all(ismember(unique(clean.schedule.owner_task_id), 0:3)), ...
    'Every owner interval must be idle or one declared task.');
busyMask = clean.schedule.owner_task_id > 0;
assert(all(clean.schedule.selected_priority(busyMask) == ...
    clean.input.priority(clean.schedule.owner_task_id(busyMask))), ...
    'Selected priority must belong to the recorded CPU owner.');

%% Independent fixed-priority response calculation
independentResponseMs = responseTimeRecurrence( ...
    fixture.period_ms, fixture.execution_ms, fixture.priority);
assert(isequal(independentResponseMs, [1 3 9]), ...
    ['Independent higher-priority interference recurrence must produce ' ...
    '[1 3 9] ms.']);
assert(isequal(independentResponseMs, ...
    clean.metrics.worst_response_ms_by_task), ...
    'Observed synchronous baseline responses must match the recurrence.');

%% Release, preemption, resume, completion, and deterministic ties
loggerFirstJob = find(clean.jobs.task_id == 3 & ...
    clean.jobs.sequence == 1, 1);
assert(clean.jobs.start_ms(loggerFirstJob) == 3 && ...
    clean.jobs.completion_ms(loggerFirstJob) == 9 && ...
    clean.jobs.response_ms(loggerFirstJob) == 9, ...
    'The first logger job must run, be preempted, resume, and finish at 9 ms.');
assert(clean.schedule.owner_task_id(6) == 1 && ...
    clean.schedule.owner_task_id(7) == 3, ...
    'Control must preempt logger at 5 ms and logger must resume at 6 ms.');
equalPriority = modelFcn([10 10], [2 1], [10 10], [1 1], ...
    [0 0], 1, 3);
assert(isequal(equalPriority.schedule.owner_task_id, [1 1 2]), ...
    ['Equal-priority simultaneous jobs must use task ID, and the older ' ...
    'job must remain FIFO without time slicing.']);
assert(isequal(equalPriority.jobs.response_ms, [2 3]), ...
    'Equal-priority tie-breaking must retain exact response times.');

%% Zero-work, phase, horizon, and exact-deadline limiting cases
zeroWork = modelFcn(5, 0, 5, 1, 0, 1, 10);
assert(isequal(zeroWork.metrics.release_count_by_task, 2) && ...
    isequal(zeroWork.metrics.completion_count_by_task, 2) && ...
    all(zeroWork.jobs.response_ms == 0), ...
    'A zero-WCET job must complete exactly at each release.');
assert(all(zeroWork.schedule.owner_task_id == 0) && ...
    zeroWork.metrics.busy_time_ms == 0 && ...
    zeroWork.metrics.idle_time_ms == 10, ...
    'Zero-WCET releases must not consume a CPU interval.');
atHorizonPhase = modelFcn(5, 1, 5, 1, 10, 1, 10);
assert(isempty(atHorizonPhase.jobs.id) && ...
    atHorizonPhase.metrics.release_count_by_task == 0, ...
    'A phase exactly at the half-open horizon must not release a job.');
exactDeadline = modelFcn(5, 5, 5, 1, 0, 1, 5);
assert(exactDeadline.jobs.completion_ms(1) == 5 && ...
    ~exactDeadline.jobs.deadline_missed(1), ...
    'Completion exactly at the final deadline boundary must be on time.');

%% Timeout, continue-late, cancellation, and beyond-horizon classification
continuesLate = modelFcn(5, 6, 5, 1, 0, 1, 7, 'continue-late');
assert(continuesLate.jobs.deadline_missed(1) && ...
    continuesLate.jobs.miss_time_ms(1) == 5 && ...
    continuesLate.jobs.completion_ms(1) == 6, ...
    'One remaining tick at 5 ms must time out once and complete late at 6 ms.');
assert(~continuesLate.jobs.cancelled_at_deadline(1) && ...
    continuesLate.jobs.service_ms(1) == 6, ...
    'Continue-late policy must serve, not cancel, the expired remainder.');
assert(~continuesLate.jobs.deadline_missed(2) && ...
    continuesLate.jobs.unfinished_at_horizon(2) && ...
    continuesLate.jobs.absolute_deadline_ms(2) == 10, ...
    'A deadline beyond the horizon must remain unobserved, not missed.');
cancelsLate = modelFcn(5, 6, 5, 1, 0, 1, 7, ...
    'cancel-at-deadline');
assert(cancelsLate.jobs.deadline_missed(1) && ...
    cancelsLate.jobs.cancelled_at_deadline(1) && ...
    cancelsLate.jobs.cancellation_time_ms(1) == 5, ...
    'Cancel-at-deadline must remove the expired job before dispatch at 5 ms.');
assert(cancelsLate.jobs.service_ms(1) == 5 && ...
    cancelsLate.jobs.cancelled_work_ms(1) == 1 && ...
    isnan(cancelsLate.jobs.completion_ms(1)), ...
    'Deadline cancellation must retain five served and one canceled tick.');
assert(cancelsLate.schedule.owner_job_id(6) == 2 && ...
    ~cancelsLate.jobs.deadline_missed(2), ...
    'The replacement job must dispatch after cancellation without an invented miss.');
assert(cancelsLate.metrics.released_demand_ms == ...
    cancelsLate.metrics.served_work_ms + ...
    cancelsLate.metrics.cancelled_work_ms + ...
    cancelsLate.metrics.remaining_work_ms, ...
    'Cancellation must preserve released-demand accounting.');
explicitContinue = modelFcn(5, 6, 5, 1, 0, 1, 7, ...
    'continue-late');
defaultContinue = modelFcn(5, 6, 5, 1, 0, 1, 7, []);
assert(isequaln(explicitContinue, defaultContinue), ...
    'Empty deadline action must be compatible with continue-late default.');

%% Overlapping releases remain separate FIFO jobs
backlog = modelFcn(2, 3, 2, 1, 0, 1, 7, 'continue-late');
assert(isequal(backlog.jobs.id, 1:4) && ...
    isequal(backlog.jobs.release_ms, [0 2 4 6]) && ...
    isequal(backlog.jobs.absolute_deadline_ms, [2 4 6 8]), ...
    'Overlapping releases must retain four distinct jobs and deadlines.');
assert(isequal(backlog.jobs.completion_ms(1:2), [3 6]) && ...
    all(isnan(backlog.jobs.completion_ms(3:4))), ...
    'Backlogged jobs must remain FIFO rather than overwrite unfinished work.');
assert(isequal(backlog.jobs.deadline_missed, ...
    [true true true false]), ...
    'Each expired backlogged job must be counted once at its own deadline.');
assert(isequal(backlog.metrics.deadline_miss_count_by_task, 3) && ...
    backlog.metrics.unfinished_count_by_task == 2, ...
    'Backlog metrics must separate observed misses from unfinished jobs.');

%% Two isolated sweeps
prioritySweep = [3 2 1; 2 3 1; 3 1 2];
expectedPriorityResponses = [1 3 9; 3 2 9; 1 9 7];
for sweepIndex = 1:size(prioritySweep, 1)
    swept = modelFcn(fixture.period_ms, fixture.execution_ms, ...
        fixture.relative_deadline_ms, prioritySweep(sweepIndex, :), ...
        fixture.phase_ms, fixture.tick_ms, fixture.horizon_ms, ...
        fixture.deadline_action);
    assert(isequal(swept.metrics.worst_response_ms_by_task, ...
        expectedPriorityResponses(sweepIndex, :)), ...
        'Priority sweep must retain its independent response vector.');
    assert(isequal(swept.input.execution_ms, clean.input.execution_ms) && ...
        isequal(swept.input.period_ms, clean.input.period_ms) && ...
        isequal(swept.input.relative_deadline_ms, ...
        clean.input.relative_deadline_ms) && ...
        isequal(swept.metrics.release_count_by_task, ...
        clean.metrics.release_count_by_task) && ...
        swept.metrics.nominal_utilization == ...
        clean.metrics.nominal_utilization, ...
        'Priority sweep must isolate priority from timing and demand.');
    assert(~any(swept.metrics.deadline_miss_count_by_task), ...
        'Every declared safe priority sweep case must meet deadlines.');
end

loggerExecutionSweepMs = [2 5 8];
expectedLoggerResponsesMs = [5 9 15];
expectedUtilization = [0.50 0.65 0.80];
for sweepIndex = 1:numel(loggerExecutionSweepMs)
    execution = fixture.execution_ms;
    execution(3) = loggerExecutionSweepMs(sweepIndex);
    swept = modelFcn(fixture.period_ms, execution, ...
        fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
        fixture.tick_ms, fixture.horizon_ms, fixture.deadline_action);
    assert(swept.metrics.worst_response_ms_by_task(3) == ...
        expectedLoggerResponsesMs(sweepIndex) && ...
        abs(swept.metrics.nominal_utilization - ...
        expectedUtilization(sweepIndex)) < 1e-14, ...
        'Logger WCET sweep must retain response and utilization references.');
    assert(isequal(swept.input.priority, clean.input.priority) && ...
        isequal(swept.input.period_ms, clean.input.period_ms) && ...
        isequal(swept.input.relative_deadline_ms, ...
        clean.input.relative_deadline_ms) && ...
        isequal(swept.metrics.release_count_by_task, ...
        clean.metrics.release_count_by_task), ...
        'Logger WCET sweep must isolate execution demand from scheduling inputs.');
    assert(isequal(swept.metrics.worst_response_ms_by_task(1:2), [1 3]), ...
        'Lower-priority logger demand must not delay ready higher-priority jobs.');
end

%% Broken priority map, rollback, and clean recovery
brokenFixture = scenarioFcn('priority-misassigned');
broken = modelFcn(brokenFixture.period_ms, brokenFixture.execution_ms, ...
    brokenFixture.relative_deadline_ms, brokenFixture.priority, ...
    brokenFixture.phase_ms, brokenFixture.tick_ms, ...
    brokenFixture.horizon_ms, brokenFixture.deadline_action);
assert(broken.metrics.nominal_utilization == ...
    clean.metrics.nominal_utilization && ...
    isequal(broken.metrics.release_count_by_task, ...
    clean.metrics.release_count_by_task), ...
    'Broken priority map must not change utilization or releases.');
assert(isequal(broken.metrics.worst_response_ms_by_task, [6 9 5]), ...
    'Logger promotion must move worst responses to [6 9 5] ms.');
assert(isequal(broken.metrics.deadline_miss_count_by_task, [2 0 0]), ...
    ['Utilization below one with a bad priority assignment must expose ' ...
    'two control deadline misses.']);
rolledBack = modelFcn(fixture.period_ms, fixture.execution_ms, ...
    fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
    fixture.tick_ms, fixture.horizon_ms, fixture.deadline_action);
assert(isequaln(rolledBack, clean), ...
    'Restoring priorities must roll back exactly to the clean baseline.');
recoveredAfterCancellation = modelFcn(fixture.period_ms, ...
    fixture.execution_ms, fixture.relative_deadline_ms, fixture.priority, ...
    fixture.phase_ms, fixture.tick_ms, fixture.horizon_ms, ...
    'continue-late');
assert(isequaln(recoveredAfterCancellation, clean), ...
    'A clean retry after deadline cancellation must recover exactly.');

%% Numeric shape compatibility and callback lifetime after path cleanup
columnCompatible = modelFcn(uint8(fixture.period_ms.'), ...
    uint8(fixture.execution_ms.'), ...
    uint8(fixture.relative_deadline_ms.'), ...
    int8(fixture.priority.'), uint8(fixture.phase_ms.'), uint8(1), ...
    uint8(40), string('continue-late'));
assert(isequaln(columnCompatible, clean), ...
    'Integer-class column vectors and scalar strings must normalize compatibly.');
explicitDefaults = modelFcn(fixture.period_ms, fixture.execution_ms, ...
    fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
    fixture.tick_ms, fixture.horizon_ms, []);
assert(isequaln(explicitDefaults, clean), ...
    'Omitted and empty deadline-action inputs must be compatible.');

callbackModel = @model;
callbackScenario = @p09_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.period_ms, ...
    callbackInput.execution_ms, callbackInput.relative_deadline_ms, ...
    callbackInput.priority, callbackInput.phase_ms, callbackInput.tick_ms, ...
    callbackInput.horizon_ms, callbackInput.deadline_action);
assert(isequal(callbackOut.metrics.worst_response_ms_by_task, [1 3 9]), ...
    ['Callback-bound P09 dependencies must survive module path cleanup ' ...
    'and a conflicting P01 model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn([5 10], [1 2], [5 10], [2 1], ...
    [0 0], 1), 'P09:model:Arity');
assertReject(@() modelFcn('5', 1, 5, 1, 0, 1, 10), ...
    'P09:model:Period');
assertReject(@() modelFcn(true, 1, 5, 1, 0, 1, 10), ...
    'P09:model:Period');
assertReject(@() modelFcn(NaN, 1, 5, 1, 0, 1, 10), ...
    'P09:model:Period');
assertReject(@() modelFcn(1i, 1, 5, 1, 0, 1, 10), ...
    'P09:model:Period');
assertReject(@() modelFcn(0, 1, 5, 1, 0, 1, 10), ...
    'P09:model:Period');
assertReject(@() modelFcn(5, -1, 5, 1, 0, 1, 10), ...
    'P09:model:Execution');
assertReject(@() modelFcn(5, [1 2; 3 4], 5, 1, 0, 1, 10), ...
    'P09:model:Execution');
assertReject(@() modelFcn(5, 1, 0, 1, 0, 1, 10), ...
    'P09:model:Deadline');
assertReject(@() modelFcn(5, 1, 5, 1.5, 0, 1, 10), ...
    'P09:model:Priority');
assertReject(@() modelFcn(5, 1, 5, 1, -1, 1, 10), ...
    'P09:model:Phase');
assertReject(@() modelFcn([5 10], 1, [5 10], [2 1], ...
    [0 0], 1, 10), 'P09:model:VectorLength');
assertReject(@() modelFcn(5, 1, 5, 1, 0, 0, 10), ...
    'P09:model:Tick');
assertReject(@() modelFcn(5, 1, 5, 1, 0, 1, 0), ...
    'P09:model:Horizon');
assertReject(@() modelFcn(5, 1.5, 5, 1, 0, 1, 10), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(eps(1), 0, 1, 1, 0, 1, 10), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(5, eps(1), 5, 1, 0, 1, 10), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(5, 1, eps(1), 1, 0, 1, 10), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(5, 1, 5, 1, eps(1), 1, 10), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(5, 1, 5, 1, 0, 1, eps(1)), ...
    'P09:model:GridAlignment');
assertReject(@() modelFcn(5, 1, 5, 1, 0, 1, 10, {'continue-late'}), ...
    'P09:model:DeadlineAction');
assertReject(@() modelFcn(5, 1, 5, 1, 0, 1, 10, 'drop-magic'), ...
    'P09:model:DeadlineAction');
assertReject(@() modelFcn(ones(1, 17), zeros(1, 17), ...
    ones(1, 17), 17:-1:1, zeros(1, 17), 1, 10), ...
    'P09:model:ResourceBound');
assertReject(@() modelFcn(1, 0, 1, 1, 0, 1, 100001), ...
    'P09:model:TimingResourceBound');
assertReject(@() modelFcn(1, 1e9 + 1, 1, 1, 0, 1, 10), ...
    'P09:model:TimingResourceBound');
assertReject(@() modelFcn(1, 0, 1, 1, 0, 1, 10001), ...
    'P09:model:JobResourceBound');

largestAccepted = modelFcn(1, 0, 1, 1, 0, 1, 10000);
assert(numel(largestAccepted.jobs.id) == 10000 && ...
    largestAccepted.metrics.release_count_by_task == 10000, ...
    'The accepted job resource bound must retain exactly 10000 releases.');
largestScenario = scenarioFcn('baseline', 28570);
largestScenarioOut = modelFcn(largestScenario.period_ms, ...
    largestScenario.execution_ms, ...
    largestScenario.relative_deadline_ms, largestScenario.priority, ...
    largestScenario.phase_ms, largestScenario.tick_ms, ...
    largestScenario.horizon_ms, largestScenario.deadline_action);
assert(numel(largestScenarioOut.jobs.id) == 10000 && ...
    sum(largestScenarioOut.metrics.release_count_by_task) == 10000, ...
    ['The largest accepted scenario horizon must remain runnable at the ' ...
    'model job ceiling.']);
assertReject(@() scenarioFcn('baseline', 28571), ...
    'P09:scenario:JobResourceBound');
assertReject(@() scenarioFcn({'baseline'}), 'P09:scenario:Kind');
assertReject(@() scenarioFcn('baseline', 0), 'P09:scenario:Horizon');
assertReject(@() scenarioFcn('baseline', 100001), ...
    'P09:scenario:Horizon');
assertReject(@() scenarioFcn('unknown'), 'P09:scenario:Kind');

afterRejection = modelFcn(fixture.period_ms, fixture.execution_ms, ...
    fixture.relative_deadline_ms, fixture.priority, fixture.phase_ms, ...
    fixture.tick_ms, fixture.horizon_ms, fixture.deadline_action);
assert(isequaln(afterRejection, clean), ...
    'A malformed call must not contaminate the next valid calculation.');

disp('Deadline cancellation is a synchronous calculation policy, not an asynchronous RTOS cancellation API or physical rollback.');
disp('P09 checks passed.');
end

function responseMs = responseTimeRecurrence(periodMs, executionMs, priority)
% Independent recurrence for the declared independent preemptive task set.
taskCount = numel(periodMs);
responseMs = zeros(1, taskCount);
for taskId = 1:taskCount
    candidate = executionMs(taskId);
    for boundedIteration = 1:100
        higher = priority > priority(taskId);
        nextCandidate = executionMs(taskId) + sum( ...
            ceil(candidate ./ periodMs(higher)) .* executionMs(higher));
        if nextCandidate == candidate
            break;
        end
        candidate = nextCandidate;
    end
    responseMs(taskId) = candidate;
end
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
