function out = model(sampleValue, sampleTimeUs, decimationFactor, ...
    fastCostUs, slowCostUs, outputTimeoutUs, timeoutAction, ...
    executionOrder, varargin)
%MODEL Execute a bounded deterministic two-rate processing graph.
%   A fast two-sample filter runs for every timestamped input. A slow frame
%   node runs once per decimationFactor inputs on its own serial worker.
%   This pure calculation owns no figures, UI, timers, hardware APIs, or
%   persistent state.

if nargin ~= 8
    error('P16:model:Arity', 'model requires exactly eight inputs.');
end

maxSampleCount = 4096;
maxDecimationFactor = 1024;
maxSampleMagnitude = 1e9;
maxInputTimestampUs = 1e12;
maxExecutionCostUs = 1e9;
maxTimelineUs = 2e12;

sampleValue = validateSampleVector(sampleValue, maxSampleCount, ...
    maxSampleMagnitude);
sampleTimeUs = validateSampleTime(sampleTimeUs, maxSampleCount, ...
    maxInputTimestampUs);
if numel(sampleValue) ~= numel(sampleTimeUs)
    error('P16:model:SampleLength', ...
        'sampleValue and sampleTimeUs must have the same length.');
end
sampleCount = numel(sampleValue);
samplePeriodUs = sampleTimeUs(2) - sampleTimeUs(1);
if any(diff(sampleTimeUs) ~= samplePeriodUs)
    error('P16:model:SampleTimeUniform', ...
        'sampleTimeUs must lie on one exact uniform microsecond grid.');
end

decimationFactor = validateExactIntegerScalar(decimationFactor, ...
    'DecimationFactor', 1, maxDecimationFactor);
if decimationFactor > sampleCount
    error('P16:model:DecimationResourceBound', ...
        'decimationFactor must not exceed the accepted sample count.');
end
if rem(sampleCount, decimationFactor) ~= 0
    error('P16:model:FramePartition', ...
        'sample count must be an exact multiple of decimationFactor.');
end
fastCostUs = validateExactIntegerScalar(fastCostUs, 'FastCost', ...
    0, maxExecutionCostUs);
slowCostUs = validateExactIntegerScalar(slowCostUs, 'SlowCost', ...
    0, maxExecutionCostUs);
outputTimeoutUs = validateTimeout(outputTimeoutUs, maxExecutionCostUs);
timeoutAction = validateChoice(timeoutAction, 'TimeoutAction', ...
    {'continue-processing', 'cancel-frame'}, 'continue-processing');
executionOrder = validateChoice(executionOrder, 'ExecutionOrder', ...
    {'producer-first', 'consumer-first'}, 'producer-first');
slowPeriodUs = decimationFactor .* samplePeriodUs;
if ~isfinite(slowPeriodUs) || slowPeriodUs > maxTimelineUs
    error('P16:model:TimelineResourceBound', ...
        'Derived slow-node period exceeds the timeline bound.');
end

% The source releases from the supplied origin/index grid. The recurrence
% below is only worker availability, never repeated release-time addition.
fastStartUs = zeros(1, sampleCount);
fastFinishUs = zeros(1, sampleCount);
filteredValue = zeros(1, sampleCount);
fastAvailableUs = sampleTimeUs(1);
for sampleIndex = 1:sampleCount
    fastStartUs(sampleIndex) = max(sampleTimeUs(sampleIndex), ...
        fastAvailableUs);
    fastFinishUs(sampleIndex) = addBoundedTime( ...
        fastStartUs(sampleIndex), fastCostUs, maxTimelineUs);
    fastAvailableUs = fastFinishUs(sampleIndex);
    if sampleIndex == 1
        filteredValue(sampleIndex) = sampleValue(sampleIndex);
    else
        filteredValue(sampleIndex) = ...
            (sampleValue(sampleIndex - 1) + sampleValue(sampleIndex)) ./ 2;
    end
end
if any(~isfinite(filteredValue)) || ...
        any(abs(filteredValue) > maxSampleMagnitude)
    error('P16:model:FilteredValueResourceBound', ...
        'Derived fast-stage values exceed the finite value bound.');
end

frameCount = sampleCount ./ decimationFactor;
expectedFirstIndex = zeros(1, frameCount);
expectedLastIndex = zeros(1, frameCount);
consumedFirstIndex = zeros(1, frameCount);
consumedLastIndex = zeros(1, frameCount);
frameReleaseUs = zeros(1, frameCount);
frameReadyUs = nan(1, frameCount);
expectedTimestampUs = zeros(1, frameCount);
consumedTimestampUs = zeros(1, frameCount);
timestampErrorUs = zeros(1, frameCount);
dataValid = true(1, frameCount);
computedValue = nan(1, frameCount);
visibleFastCountAtDispatch = zeros(1, frameCount);
visibilityLagSamples = zeros(1, frameCount);
outstandingDepthAtReady = zeros(1, frameCount);
slowStartUs = nan(1, frameCount);
scheduledFinishUs = nan(1, frameCount);
deadlineUs = inf(1, frameCount);
deadlineSlackUs = nan(1, frameCount);
timedOut = false(1, frameCount);
cancelled = false(1, frameCount);
slowStopUs = nan(1, frameCount);
completionUs = nan(1, frameCount);
emitted = false(1, frameCount);
outputValue = nan(1, frameCount);
outputLatencyUs = nan(1, frameCount);

slowAvailableUs = sampleTimeUs(1);
producerFirst = strcmp(executionOrder, 'producer-first');
for frameIndex = 1:frameCount
    firstIndex = (frameIndex - 1) .* decimationFactor + 1;
    lastIndex = frameIndex .* decimationFactor;
    expectedFirstIndex(frameIndex) = firstIndex - 1;
    expectedLastIndex(frameIndex) = lastIndex - 1;
    frameReleaseUs(frameIndex) = sampleTimeUs(lastIndex);
    expectedTimestampUs(frameIndex) = ...
        sum(sampleTimeUs(firstIndex:lastIndex)) ./ decimationFactor;

    if producerFirst
        consumedFirstIndex(frameIndex) = firstIndex - 1;
        consumedLastIndex(frameIndex) = lastIndex - 1;
        consumedTimestampUs(frameIndex) = ...
            expectedTimestampUs(frameIndex);
        computedValue(frameIndex) = ...
            sum(filteredValue(firstIndex:lastIndex)) ./ decimationFactor;
        frameReadyUs(frameIndex) = max(frameReleaseUs(frameIndex), ...
            fastFinishUs(lastIndex));
        visibleFastCountAtDispatch(frameIndex) = lastIndex;
    else
        % The consumer fires at the activation before the current fast
        % result is published. Consume the newest complete D-value window
        % visible strictly before that activation; an overloaded fast worker
        % can therefore lag by more than one sample.
        latestVisibleIndex = find( ...
            fastFinishUs < frameReleaseUs(frameIndex), 1, 'last');
        if isempty(latestVisibleIndex)
            latestVisibleIndex = 0;
        end
        visibleFastCountAtDispatch(frameIndex) = latestVisibleIndex;
        visibilityLagSamples(frameIndex) = lastIndex - latestVisibleIndex;
        consumedFirstIndex(frameIndex) = ...
            latestVisibleIndex - decimationFactor;
        consumedLastIndex(frameIndex) = latestVisibleIndex - 1;
        consumedTimestampUs(frameIndex) = sampleTimeUs(1) + ...
            ((consumedFirstIndex(frameIndex) + ...
            consumedLastIndex(frameIndex)) ./ 2) .* samplePeriodUs;
        if latestVisibleIndex < decimationFactor
            dataValid(frameIndex) = false;
        else
            computedValue(frameIndex) = sum( ...
                filteredValue(latestVisibleIndex - decimationFactor + 1: ...
                latestVisibleIndex)) ./ ...
                decimationFactor;
            frameReadyUs(frameIndex) = frameReleaseUs(frameIndex);
        end
    end
    timestampErrorUs(frameIndex) = ...
        consumedTimestampUs(frameIndex) - expectedTimestampUs(frameIndex);

    if isfinite(outputTimeoutUs)
        deadlineUs(frameIndex) = addBoundedTime( ...
            frameReleaseUs(frameIndex), outputTimeoutUs, maxTimelineUs);
    end
    if ~dataValid(frameIndex)
        % Underflow is rejected at dispatch. Without a complete input window
        % there is no slow job to queue, start, complete, time out, or cancel.
        continue;
    end

    if frameIndex == 1
        outstandingDepthAtReady(frameIndex) = 1;
    else
        outstandingDepthAtReady(frameIndex) = 1 + ...
            sum(slowStopUs(1:frameIndex - 1) > frameReadyUs(frameIndex));
    end
    slowStartUs(frameIndex) = max(frameReadyUs(frameIndex), ...
        slowAvailableUs);
    scheduledFinishUs(frameIndex) = addBoundedTime( ...
        slowStartUs(frameIndex), slowCostUs, maxTimelineUs);
    deadlineSlackUs(frameIndex) = deadlineUs(frameIndex) - ...
        scheduledFinishUs(frameIndex);
    % Completion at exact equality is visible before timeout handling.
    timedOut(frameIndex) = ...
        scheduledFinishUs(frameIndex) > deadlineUs(frameIndex);
    cancelled(frameIndex) = timedOut(frameIndex) && ...
        strcmp(timeoutAction, 'cancel-frame');
    if cancelled(frameIndex)
        slowStopUs(frameIndex) = max(slowStartUs(frameIndex), ...
            deadlineUs(frameIndex));
    else
        slowStopUs(frameIndex) = scheduledFinishUs(frameIndex);
        completionUs(frameIndex) = scheduledFinishUs(frameIndex);
    end
    slowAvailableUs = slowStopUs(frameIndex);
    emitted(frameIndex) = dataValid(frameIndex) && ...
        ~cancelled(frameIndex);
    if emitted(frameIndex)
        outputValue(frameIndex) = computedValue(frameIndex);
        outputLatencyUs(frameIndex) = completionUs(frameIndex) - ...
            frameReleaseUs(frameIndex);
    end
end

out.input = struct( ...
    'sample_value', sampleValue, ...
    'sample_time_us', sampleTimeUs, ...
    'decimation_factor', decimationFactor, ...
    'fast_cost_us', fastCostUs, ...
    'slow_cost_us', slowCostUs, ...
    'output_timeout_us', outputTimeoutUs, ...
    'timeout_action', timeoutAction, ...
    'execution_order', executionOrder);
out.fast = struct( ...
    'start_us', fastStartUs, ...
    'finish_us', fastFinishUs, ...
    'filtered_value', filteredValue);
out.frame = struct( ...
    'expected_first_sample_index', expectedFirstIndex, ...
    'expected_last_sample_index', expectedLastIndex, ...
    'consumed_first_sample_index', consumedFirstIndex, ...
    'consumed_last_sample_index', consumedLastIndex, ...
    'release_us', frameReleaseUs, ...
    'ready_us', frameReadyUs, ...
    'expected_timestamp_us', expectedTimestampUs, ...
    'consumed_timestamp_us', consumedTimestampUs, ...
    'timestamp_error_us', timestampErrorUs, ...
    'data_valid', dataValid, ...
    'computed_value', computedValue, ...
    'visible_fast_count_at_dispatch', visibleFastCountAtDispatch, ...
    'visibility_lag_samples', visibilityLagSamples, ...
    'outstanding_depth_at_ready', outstandingDepthAtReady, ...
    'slow_start_us', slowStartUs, ...
    'scheduled_finish_us', scheduledFinishUs, ...
    'deadline_us', deadlineUs, ...
    'deadline_slack_us', deadlineSlackUs, ...
    'timed_out', timedOut, ...
    'cancelled', cancelled, ...
    'slow_stop_us', slowStopUs, ...
    'completion_us', completionUs, ...
    'emitted', emitted, ...
    'output_value', outputValue, ...
    'output_latency_us', outputLatencyUs);
out.metrics = struct( ...
    'sample_count', sampleCount, ...
    'frame_count', frameCount, ...
    'emitted_count', sum(emitted), ...
    'dropped_count', sum(~emitted), ...
    'timeout_count', sum(timedOut), ...
    'cancelled_count', sum(cancelled), ...
    'underflow_count', sum(~dataValid), ...
    'sample_period_us', samplePeriodUs, ...
    'slow_period_us', slowPeriodUs, ...
    'input_rate_hz', 1e6 ./ samplePeriodUs, ...
    'nominal_output_rate_hz', 1e6 ./ slowPeriodUs, ...
    'fast_utilization_ratio', fastCostUs ./ samplePeriodUs, ...
    'slow_utilization_ratio', slowCostUs ./ slowPeriodUs, ...
    'maximum_outstanding_depth', max(outstandingDepthAtReady), ...
    'maximum_scheduled_latency_us', ...
    maximumOrNaN(scheduledFinishUs - frameReleaseUs), ...
    'maximum_output_latency_us', maximumOrNaN(outputLatencyUs), ...
    'minimum_deadline_slack_us', minimumOrNaN(deadlineSlackUs), ...
    'maximum_absolute_timestamp_error_us', ...
    max(abs(timestampErrorUs)), ...
    'maximum_visibility_lag_samples', max(visibilityLagSamples), ...
    'ordering_consistent', producerFirst);
out.semantics = struct( ...
    'fast_filter_rule', ...
    'y[0] = x[0]; y[n] = (x[n-1] + x[n]) / 2', ...
    'rate_rule', ...
    'slow period = decimation factor * sample period', ...
    'frame_rule', ...
    ['an underflow is rejected before slow-worker admission; a valid ' ...
    'frame consumes exactly D consecutive fast-stage values'], ...
    'utilization_rule', ...
    'slow utilization = slow cost / (D * sample period)', ...
    'outstanding_depth_rule', ...
    ['outstanding depth includes the arriving frame plus every prior ' ...
    'frame still waiting or in service at readiness'], ...
    'same_time_rule', ...
    ['producer-first publishes a zero-cost fast result before slow ' ...
    'dispatch at the same timestamp'], ...
    'timeout_rule', ...
    ['scheduled completion strictly after release plus timeout is late; ' ...
    'completion at equality emits first'], ...
    'cancellation_rule', ...
    ['cancel-frame stops the simulated slow job at its deadline or drops ' ...
    'it immediately if already stale; data membership and computed ' ...
    'values remain unchanged while future worker availability follows stop'], ...
    'recovery_rule', ...
    'recovery is a clean stateless rerun from explicit inputs');
out.claim_boundary = [ ...
    'Deterministic simulated graph arithmetic only; not MATLAB-runtime, ' ...
    'rendered-UI, real task concurrency, interrupt, DMA, processor, ' ...
    'bench, HIL, field, RT1/RT2, Unreal, signing, deployment, staging, ' ...
    'or production evidence.'];
end

function values = validateSampleVector(values, maximumCount, maximumMagnitude)
validShape = isnumeric(values) && ~islogical(values) && isreal(values) && ...
    isvector(values) && ~isempty(values);
if ~validShape
    error('P16:model:SampleValue', ...
        'sampleValue must be a nonempty finite real numeric vector.');
end
if numel(values) < 2
    error('P16:model:SampleCount', ...
        'At least two samples are required to establish a source period.');
end
if numel(values) > maximumCount
    error('P16:model:SampleResourceBound', ...
        'sampleValue exceeds the 4096-sample resource bound.');
end
if any(~isfinite(values(:)))
    error('P16:model:SampleValue', ...
        'sampleValue must be a nonempty finite real numeric vector.');
end
values = double(values(:)');
if any(abs(values) > maximumMagnitude)
    error('P16:model:SampleValueResourceBound', ...
        'sampleValue magnitude must not exceed 1e9 engineering units.');
end
end

function values = validateSampleTime(values, maximumCount, maximumTimeUs)
validShape = isnumeric(values) && ~islogical(values) && isreal(values) && ...
    isvector(values) && ~isempty(values);
if ~validShape
    error('P16:model:SampleTime', ...
        'sampleTimeUs must be a nonempty finite real numeric vector.');
end
if numel(values) > maximumCount
    error('P16:model:SampleTimeResourceBound', ...
        'sampleTimeUs exceeds the 4096-sample resource bound.');
end
if any(~isfinite(values(:)))
    error('P16:model:SampleTime', ...
        'sampleTimeUs must be a nonempty finite real numeric vector.');
end
if isa(values, 'uint64') && any(values(:) > uint64(flintmax))
    error('P16:model:SampleTimePrecision', ...
        'uint64 sample timestamps above flintmax cannot normalize exactly.');
end
if isa(values, 'int64') && ...
        (any(values(:) > int64(flintmax)) || ...
        any(values(:) < -int64(flintmax)))
    error('P16:model:SampleTimePrecision', ...
        'int64 sample timestamps must lie within +/-flintmax.');
end
values = double(values(:)');
if numel(values) < 2
    error('P16:model:SampleCount', ...
        'At least two timestamps are required to establish a source period.');
end
if any(values < 0) || any(values > maximumTimeUs)
    error('P16:model:SampleTimeResourceBound', ...
        'sampleTimeUs must lie from 0 through 1e12 us.');
end
if any(values ~= fix(values))
    error('P16:model:SampleTime', ...
        'sampleTimeUs must use exact integer microseconds.');
end
if any(diff(values) <= 0)
    error('P16:model:SampleTimeOrder', ...
        'sampleTimeUs must be unique and strictly increasing.');
end
end

function value = validateExactIntegerScalar(value, label, minimum, maximum)
valid = isnumeric(value) && ~islogical(value) && isreal(value) && ...
    isscalar(value) && isfinite(value);
if ~valid
    error(['P16:model:' label], ...
        '%s must be a finite real numeric scalar.', label);
end
if isa(value, 'uint64') && value > uint64(flintmax)
    error(['P16:model:' label 'Precision'], ...
        '%s exceeds exact double integer precision.', label);
end
if isa(value, 'int64') && ...
        (value > int64(flintmax) || value < -int64(flintmax))
    error(['P16:model:' label 'Precision'], ...
        '%s exceeds exact double integer precision.', label);
end
value = double(value);
if value < minimum || value > maximum || value ~= fix(value)
    error(['P16:model:' label], ...
        '%s must be an exact integer from %g through %g.', ...
        label, minimum, maximum);
end
end

function timeoutUs = validateTimeout(timeoutUs, maximumTimeoutUs)
if isempty(timeoutUs)
    timeoutUs = Inf;
end
valid = isnumeric(timeoutUs) && ~islogical(timeoutUs) && ...
    isreal(timeoutUs) && isscalar(timeoutUs) && ~isnan(timeoutUs) && ...
    timeoutUs >= 0;
if ~valid
    error('P16:model:OutputTimeout', ...
        'outputTimeoutUs must be a nonnegative integer or Inf.');
end
if isa(timeoutUs, 'uint64') && timeoutUs > uint64(flintmax)
    error('P16:model:OutputTimeoutPrecision', ...
        'uint64 outputTimeoutUs above flintmax cannot normalize exactly.');
end
timeoutUs = double(timeoutUs);
if isfinite(timeoutUs) && ...
        (timeoutUs > maximumTimeoutUs || timeoutUs ~= fix(timeoutUs))
    error('P16:model:OutputTimeoutResourceBound', ...
        'Finite outputTimeoutUs must be an integer from 0 through 1e9 us.');
end
end

function choice = validateChoice(choice, label, choices, defaultChoice)
if isempty(choice)
    choice = defaultChoice;
end
if ~(ischar(choice) || (isstring(choice) && isscalar(choice)))
    error(['P16:model:' label], ...
        '%s must be a character vector or scalar string.', label);
end
choice = lower(strtrim(char(choice)));
if ~any(strcmp(choice, choices))
    error(['P16:model:' label], ...
        '%s is not a supported value.', label);
end
end

function laterUs = addBoundedTime(currentUs, deltaUs, maximumTimeUs)
laterUs = currentUs + deltaUs;
if ~isfinite(laterUs) || laterUs > maximumTimeUs
    error('P16:model:TimelineResourceBound', ...
        'A derived graph timestamp exceeds the 2e12-us bound.');
end
if deltaUs > 0 && laterUs == currentUs
    error('P16:model:TimelinePrecision', ...
        'A positive execution or timeout interval collapsed at precision.');
end
end

function value = maximumOrNaN(values)
finiteValues = values(~isnan(values));
if isempty(finiteValues)
    value = NaN;
else
    value = max(finiteValues);
end
end

function value = minimumOrNaN(values)
finiteValues = values(~isnan(values));
if isempty(finiteValues)
    value = NaN;
else
    value = min(finiteValues);
end
end
