function run_checks()
%RUN_CHECKS Verify deterministic P16 graph and failure-mode invariants.
%   These are pure numerical checks. They do not wait in real time or claim
%   MATLAB-runtime, rendered-UI, scheduler, processor, or physical evidence
%   unless this file is separately executed and retained on a named system.

modelFcn = @model;
scenarioFcn = @p16_scenario;
runFixture = @(input) modelFcn(input.sample_value, ...
    input.sample_time_us, input.decimation_factor, ...
    input.fast_cost_us, input.slow_cost_us, ...
    input.output_timeout_us, input.timeout_action, ...
    input.execution_order);

%% Deterministic baseline and independent graph equations
fixture = scenarioFcn('baseline');
baseline = runFixture(fixture);
baselineRepeat = runFixture(fixture);
assert(isequaln(baseline, baselineRepeat), ...
    'Deterministic baseline must repeat exactly.');

independentFiltered = zeros(size(fixture.sample_value));
independentFiltered(1) = fixture.sample_value(1);
for sampleIndex = 2:numel(fixture.sample_value)
    independentFiltered(sampleIndex) = ...
        (fixture.sample_value(sampleIndex - 1) + ...
        fixture.sample_value(sampleIndex)) ./ 2;
end
independentFrame = zeros(1, 8);
for frameIndex = 1:8
    firstIndex = (frameIndex - 1) .* 4 + 1;
    lastIndex = frameIndex .* 4;
    independentFrame(frameIndex) = ...
        sum(independentFiltered(firstIndex:lastIndex)) ./ 4;
end
expectedFiltered = [0 0.5 1.5:1:30.5];
expectedFrame = [1.125 5 9 13 17 21 25 29];
assert(isequal(independentFiltered, expectedFiltered) && ...
    isequal(baseline.fast.filtered_value, independentFiltered), ...
    'Fast two-sample filter must match independent arithmetic.');
assert(isequal(independentFrame, expectedFrame) && ...
    isequal(baseline.frame.computed_value, independentFrame) && ...
    isequal(baseline.frame.output_value, independentFrame), ...
    'Slow frame values must match independent complete-window means.');
assert(isequal(baseline.frame.expected_first_sample_index, ...
    [0 4 8 12 16 20 24 28]) && ...
    isequal(baseline.frame.expected_last_sample_index, ...
    [3 7 11 15 19 23 27 31]) && ...
    isequal(baseline.frame.release_us, 3000:4000:31000) && ...
    isequal(baseline.frame.ready_us, 3100:4000:31100) && ...
    isequal(baseline.frame.slow_start_us, 3100:4000:31100) && ...
    isequal(baseline.frame.completion_us, 4300:4000:32300), ...
    'Baseline release, readiness, start, or completion recurrence changed.');
assert(isequal(baseline.frame.output_latency_us, 1300 .* ones(1, 8)) && ...
    isequal(baseline.frame.deadline_slack_us, 700 .* ones(1, 8)) && ...
    all(baseline.frame.data_valid) && all(baseline.frame.emitted) && ...
    ~any(baseline.frame.timed_out) && ...
    baseline.metrics.maximum_outstanding_depth == 1 && ...
    baseline.metrics.nominal_output_rate_hz == 250 && ...
    baseline.metrics.slow_utilization_ratio == 0.3, ...
    'Baseline latency, slack, validity, rate, or demand changed.');
assert(baseline.metrics.frame_count .* fixture.decimation_factor == ...
    baseline.metrics.sample_count, ...
    'Complete frames must conserve the accepted sample count.');
assert(isequal(baseline.frame.expected_timestamp_us, ...
    1500:4000:29500) && ...
    isequal(baseline.frame.consumed_timestamp_us, ...
    baseline.frame.expected_timestamp_us), ...
    'Producer-first baseline must preserve each aligned frame timestamp.');
assert(all(abs(baseline.frame.output_value) <= ...
    max(abs(fixture.sample_value))), ...
    'Averages must remain inside the bounded source-value envelope.');

%% Sweep 1: decimation factor only
decimationSweep = [1 2 4 8];
expectedFrameCount = [32 16 8 4];
expectedOutputRateHz = [1000 500 250 125];
expectedUtilization = [1.2 0.6 0.3 0.15];
expectedTimeoutCount = [28 0 0 0];
expectedMaximumLatencyUs = [7500 1300 1300 1300];
expectedMaximumOutstanding = [7 1 1 1];
for sweepIndex = 1:numel(decimationSweep)
    sweptInput = fixture;
    sweptInput.decimation_factor = decimationSweep(sweepIndex);
    swept = runFixture(sweptInput);
    assert(swept.metrics.frame_count == expectedFrameCount(sweepIndex) && ...
        swept.metrics.nominal_output_rate_hz == ...
        expectedOutputRateHz(sweepIndex) && ...
        abs(swept.metrics.slow_utilization_ratio - ...
        expectedUtilization(sweepIndex)) < 1e-12 && ...
        swept.metrics.timeout_count == ...
        expectedTimeoutCount(sweepIndex) && ...
        swept.metrics.maximum_output_latency_us == ...
        expectedMaximumLatencyUs(sweepIndex) && ...
        swept.metrics.maximum_outstanding_depth == ...
        expectedMaximumOutstanding(sweepIndex), ...
        'Decimation-factor sweep reference result changed.');
    assert(swept.input.fast_cost_us == fixture.fast_cost_us && ...
        swept.input.slow_cost_us == fixture.slow_cost_us && ...
        swept.input.output_timeout_us == fixture.output_timeout_us && ...
        strcmp(swept.input.timeout_action, fixture.timeout_action) && ...
        strcmp(swept.input.execution_order, fixture.execution_order), ...
        'Decimation sweep must isolate the graph rate relation.');
end

%% Sweep 2: reset, then slow-node execution cost only
slowCostSweepUs = [200 800 1200 1800 4200];
expectedCostUtilization = [0.05 0.2 0.3 0.45 1.05];
expectedCostLatencyUs = [300 900 1300 1900 5700];
expectedCostSlackUs = [1700 1100 700 100 -3700];
expectedCostTimeouts = [0 0 0 0 8];
expectedCostOutstanding = [1 1 1 1 2];
for sweepIndex = 1:numel(slowCostSweepUs)
    sweptInput = fixture;
    sweptInput.slow_cost_us = slowCostSweepUs(sweepIndex);
    swept = runFixture(sweptInput);
    assert(abs(swept.metrics.slow_utilization_ratio - ...
        expectedCostUtilization(sweepIndex)) < 1e-12 && ...
        swept.metrics.maximum_output_latency_us == ...
        expectedCostLatencyUs(sweepIndex) && ...
        swept.metrics.minimum_deadline_slack_us == ...
        expectedCostSlackUs(sweepIndex) && ...
        swept.metrics.timeout_count == expectedCostTimeouts(sweepIndex) && ...
        swept.metrics.maximum_outstanding_depth == ...
        expectedCostOutstanding(sweepIndex), ...
        'Slow-node execution-cost sweep reference result changed.');
    assert(swept.input.decimation_factor == fixture.decimation_factor && ...
        swept.input.fast_cost_us == fixture.fast_cost_us && ...
        swept.input.output_timeout_us == fixture.output_timeout_us && ...
        strcmp(swept.input.timeout_action, fixture.timeout_action) && ...
        strcmp(swept.input.execution_order, fixture.execution_order), ...
        'Slow-cost sweep must reset and isolate frame execution work.');
end

%% Limiting cases and exact same-timestamp ordering
unityRate = runFixture(scenarioFcn('unity-rate'));
assert(unityRate.metrics.frame_count == 32 && ...
    unityRate.metrics.nominal_output_rate_hz == 1000 && ...
    unityRate.metrics.slow_utilization_ratio == 0.8 && ...
    unityRate.metrics.maximum_output_latency_us == 900 && ...
    unityRate.metrics.timeout_count == 0 && ...
    isequal(unityRate.frame.output_value, ...
    unityRate.fast.filtered_value), ...
    'Unity-rate limit must emit every fast result without backlog.');

zeroCost = runFixture(scenarioFcn('zero-cost'));
assert(all(zeroCost.fast.start_us == zeroCost.input.sample_time_us) && ...
    all(zeroCost.fast.finish_us == zeroCost.input.sample_time_us) && ...
    all(zeroCost.frame.slow_start_us == zeroCost.frame.release_us) && ...
    all(zeroCost.frame.completion_us == zeroCost.frame.release_us) && ...
    all(zeroCost.frame.output_latency_us == 0) && ...
    ~any(zeroCost.frame.timed_out) && ...
    zeroCost.metrics.emitted_count == 8, ...
    ['Producer-first same-timestamp publication and exact timeout ' ...
    'equality must emit before timeout handling.']);

singleFrameInput = fixture;
singleFrameInput.decimation_factor = 32;
singleFrame = runFixture(singleFrameInput);
assert(singleFrame.metrics.frame_count == 1 && ...
    singleFrame.metrics.nominal_output_rate_hz == 31.25 && ...
    singleFrame.frame.output_value == ...
    sum(independentFiltered) ./ 32, ...
    'Maximum whole-fixture frame must conserve every filtered value.');

%% Broken consumer-first order and correct comparator
broken = runFixture(scenarioFcn('broken-consumer-first'));
assert(~broken.metrics.ordering_consistent && ...
    broken.metrics.underflow_count == 1 && ...
    broken.metrics.dropped_count == 1 && ...
    ~broken.frame.data_valid(1) && ...
    all(broken.frame.data_valid(2:end)) && ...
    isequaln(broken.frame.output_value, ...
    [NaN 4 8 12 16 20 24 28]) && ...
    isequal(broken.frame.timestamp_error_us, -1000 .* ones(1, 8)) && ...
    isequal(broken.frame.consumed_last_sample_index, ...
    baseline.frame.expected_last_sample_index - 1), ...
    'Broken consumer-first underflow or stale-value symptom changed.');
assert(baseline.metrics.ordering_consistent && ...
    baseline.metrics.underflow_count == 0 && ...
    all(baseline.frame.timestamp_error_us == 0) && ...
    all(baseline.frame.data_valid), ...
    'Producer-first comparator must retain current frame identity.');

underflowIsolationInput = scenarioFcn('baseline', ...
    1, 100, 1200, 2000, 'continue-processing', 'consumer-first');
underflowIsolation = runFixture(underflowIsolationInput);
assert(~underflowIsolation.frame.data_valid(1) && ...
    underflowIsolation.frame.outstanding_depth_at_ready(1) == 0 && ...
    isnan(underflowIsolation.frame.ready_us(1)) && ...
    isnan(underflowIsolation.frame.slow_start_us(1)) && ...
    isnan(underflowIsolation.frame.scheduled_finish_us(1)) && ...
    isnan(underflowIsolation.frame.slow_stop_us(1)) && ...
    isnan(underflowIsolation.frame.completion_us(1)) && ...
    ~underflowIsolation.frame.timed_out(1) && ...
    ~underflowIsolation.frame.cancelled(1), ...
    ['An underflow must be rejected before slow-worker admission, not ' ...
    'consume phantom service or enter timeout handling.']);
assert(underflowIsolation.frame.slow_start_us(2) == 1000 && ...
    underflowIsolation.frame.completion_us(2) == 2200 && ...
    underflowIsolation.metrics.timeout_count == 26 && ...
    underflowIsolation.metrics.maximum_output_latency_us == 7200 && ...
    underflowIsolation.metrics.maximum_outstanding_depth == 6, ...
    ['Rejecting the invalid D=1 firing must leave worker availability ' ...
    'unchanged for the first valid frame and its successors.']);

fastOverloadedInput = scenarioFcn('broken-consumer-first');
fastOverloadedInput.fast_cost_us = 2000;
fastOverloaded = runFixture(fastOverloadedInput);
assert(isequal(fastOverloaded.frame.visible_fast_count_at_dispatch, ...
    [1 3 5 7 9 11 13 15]) && ...
    fastOverloaded.metrics.underflow_count == 2 && ...
    isequaln(fastOverloaded.frame.output_value, ...
    [NaN NaN 2 4 6 8 10 12]) && ...
    isequal(fastOverloaded.frame.timestamp_error_us, ...
    [-3000 -5000 -7000 -9000 -11000 -13000 -15000 -17000]) && ...
    isequal(fastOverloaded.frame.visibility_lag_samples, ...
    [3 5 7 9 11 13 15 17]), ...
    ['Consumer-first visibility must follow completed fast work, not ' ...
    'assume a fixed one-sample lag when the fast worker is overloaded.']);

%% Timeout equality, strict lateness, continuation, and cancellation
equalityInput = fixture;
equalityInput.slow_cost_us = 1900;
equalityInput.timeout_action = 'cancel-frame';
equality = runFixture(equalityInput);
oneLateInput = equalityInput;
oneLateInput.slow_cost_us = 1901;
oneLate = runFixture(oneLateInput);
assert(~any(equality.frame.timed_out) && ...
    ~any(equality.frame.cancelled) && ...
    all(equality.frame.emitted) && ...
    all(equality.frame.output_latency_us == 2000), ...
    'Completion at exact timeout equality must emit first.');
assert(all(oneLate.frame.timed_out) && ...
    all(oneLate.frame.cancelled) && ...
    ~any(oneLate.frame.emitted) && ...
    all(oneLate.frame.slow_stop_us == oneLate.frame.deadline_us), ...
    'A one-microsecond-late frame must be cancelled at its deadline.');

continued = runFixture(scenarioFcn('timeout-continue'));
cancelled = runFixture(scenarioFcn('timeout-cancel'));
assert(continued.metrics.timeout_count == 28 && ...
    continued.metrics.cancelled_count == 0 && ...
    continued.metrics.emitted_count == 32 && ...
    continued.metrics.maximum_outstanding_depth == 7, ...
    'Continue-processing must retain late outputs and visible backlog.');
assert(cancelled.metrics.timeout_count == 28 && ...
    cancelled.metrics.cancelled_count == 28 && ...
    cancelled.metrics.emitted_count == 4 && ...
    cancelled.metrics.maximum_outstanding_depth == 2 && ...
    all(isnan(cancelled.frame.completion_us(5:end))) && ...
    all(isnan(cancelled.frame.output_value(5:end))), ...
    'Cancel-frame must remove late outputs and bound future backlog.');
assert(isequal(continued.input.sample_value, ...
    cancelled.input.sample_value) && ...
    isequal(continued.fast.filtered_value, ...
    cancelled.fast.filtered_value) && ...
    isequaln(continued.frame.computed_value, ...
    cancelled.frame.computed_value), ...
    'Cancellation must not rewrite source or computed frame values.');

rollback = runFixture(fixture);
recovered = runFixture(scenarioFcn('baseline'));
assert(isequaln(rollback, baseline) && isequaln(recovered, baseline), ...
    ['Rollback and recovery are clean stateless reruns, not mutation ' ...
    'of processor, task, DMA, or plant state.']);

%% Compatibility, empty defaults, and fixed diagnostic reset
compatible = modelFcn(uint32(fixture.sample_value'), ...
    uint32(fixture.sample_time_us'), uint8(fixture.decimation_factor), ...
    uint16(fixture.fast_cost_us), uint16(fixture.slow_cost_us), ...
    uint16(fixture.output_timeout_us), ...
    string('continue-processing'), string('producer-first'));
assert(isequaln(compatible, baseline), ...
    'Column/integer/string compatibility must normalize exactly.');

noTimeoutInput = fixture;
noTimeoutInput.output_timeout_us = Inf;
noTimeout = runFixture(noTimeoutInput);
emptyDefaults = modelFcn(fixture.sample_value, fixture.sample_time_us, ...
    fixture.decimation_factor, fixture.fast_cost_us, ...
    fixture.slow_cost_us, [], [], []);
assert(isequaln(emptyDefaults, noTimeout), ...
    'Empty timeout, action, and order must recover documented defaults.');

stringScenario = scenarioFcn(string('baseline'));
assert(isequaln(stringScenario, fixture), ...
    'Scalar-string and character scenario names must agree.');
fixedOverride = scenarioFcn('broken-consumer-first', ...
    8, 900, 5000, 9000, 'cancel-frame', 'producer-first');
assert(isequaln(fixedOverride, ...
    scenarioFcn('broken-consumer-first')), ...
    'Named diagnostics must replace every editable override.');

%% Callback lifetime and module isolation
callbackModel = modelFcn;
callbackScenario = scenarioFcn;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
clear model;
callbackInput = callbackScenario('baseline');
callbackOut = callbackModel(callbackInput.sample_value, ...
    callbackInput.sample_time_us, callbackInput.decimation_factor, ...
    callbackInput.fast_cost_us, callbackInput.slow_cost_us, ...
    callbackInput.output_timeout_us, callbackInput.timeout_action, ...
    callbackInput.execution_order);
assert(isequaln(callbackOut, baseline), ...
    ['Callback-bound P16 dependencies must survive module path cleanup ' ...
    'and a conflicting generic model path.']);
clear searchPathCleanup;

%% Malformed input and resource-bound rejection
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, Inf, ...
    'continue-processing'), 'P16:model:Arity');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first', 'extra'), ...
    'P16:model:Arity');
assertReject(@() modelFcn([], 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleValue');
assertReject(@() modelFcn(true, 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleValue');
assertReject(@() modelFcn([0 1i], 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleValue');
assertReject(@() modelFcn([0 NaN], 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleValue');
assertReject(@() modelFcn(ones(2), 0:3, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleValue');
assertReject(@() modelFcn(1, 0, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleCount');
assertReject(@() modelFcn([0 1e9 + 1], 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleValueResourceBound');

assertReject(@() modelFcn(0:1, [], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:1, true, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:1, [0 1i], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:1, [0 NaN], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:3, ones(2), 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:1, [-1 0], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleTimeResourceBound');
assertReject(@() modelFcn(0:1, [0 0.5], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleTime');
assertReject(@() modelFcn(0:1, [0 0], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleTimeOrder');
assertReject(@() modelFcn(0:2, [0 1 3], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleTimeUniform');
assertReject(@() modelFcn(0:2, 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SampleLength');
assertReject(@() modelFcn(0:1, ...
    [uint64(0) uint64(flintmax) + uint64(1)], 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleTimePrecision');

assertReject(@() modelFcn(0:3, 0:3, true, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:DecimationFactor');
assertReject(@() modelFcn(0:3, 0:3, 1.5, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:DecimationFactor');
assertReject(@() modelFcn(0:3, 0:3, 0, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:DecimationFactor');
assertReject(@() modelFcn(0:3, 0:3, 5, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:DecimationResourceBound');
assertReject(@() modelFcn(0:5, 0:5, 4, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:FramePartition');

assertReject(@() modelFcn(0:1, 0:1, 1, -1, 0, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:FastCost');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 1.5, Inf, ...
    'continue-processing', 'producer-first'), 'P16:model:SlowCost');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, -1, ...
    'continue-processing', 'producer-first'), 'P16:model:OutputTimeout');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, 0.5, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:OutputTimeoutResourceBound');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, 1e9 + 1, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:OutputTimeoutResourceBound');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, Inf, ...
    'drop-all', 'producer-first'), 'P16:model:TimeoutAction');
assertReject(@() modelFcn(0:1, 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'parallel'), 'P16:model:ExecutionOrder');

largestInput = zeros(1, 4096);
largestTimeUs = 0:4095;
largestAccepted = modelFcn(largestInput, largestTimeUs, 1, ...
    0, 0, Inf, 'continue-processing', 'producer-first');
assert(largestAccepted.metrics.sample_count == 4096 && ...
    largestAccepted.metrics.frame_count == 4096 && ...
    largestAccepted.metrics.emitted_count == 4096, ...
    'The accepted 4096-sample resource boundary must execute.');
assertReject(@() modelFcn(zeros(1, 4097), 0:4096, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleResourceBound');
assertReject(@() modelFcn(zeros(1, 1000000), 0:1, 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleResourceBound');
assertReject(@() modelFcn(0:1, zeros(1, 1000000), 1, 0, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:SampleTimeResourceBound');
assertReject(@() modelFcn(zeros(1, 4096), 0:4095, 1, 1e9, 0, Inf, ...
    'continue-processing', 'producer-first'), ...
    'P16:model:TimelineResourceBound');

assertReject(@() scenarioFcn({'baseline'}), 'P16:scenario:Name');
assertReject(@() scenarioFcn('unknown'), 'P16:scenario:Name');
assertReject(@() scenarioFcn('baseline', 3), ...
    'P16:scenario:FramePartition');
assertReject(@() scenarioFcn('baseline', 4, -1), ...
    'P16:scenario:FastCost');
assertReject(@() scenarioFcn('baseline', 4, 100, 10001), ...
    'P16:scenario:SlowCost');
assertReject(@() scenarioFcn('baseline', 4, 100, 1200, -1), ...
    'P16:scenario:OutputTimeout');
assertReject(@() scenarioFcn('baseline', 4, 100, 1200, 2000, ...
    'drop-all'), 'P16:scenario:TimeoutAction');
assertReject(@() scenarioFcn('baseline', 4, 100, 1200, 2000, ...
    'continue-processing', 'parallel'), 'P16:scenario:ExecutionOrder');
assertReject(@() scenarioFcn('baseline', 4, 100, 1200, 2000, ...
    'continue-processing', 'producer-first', 1), ...
    'P16:scenario:Arity');

afterMalformed = runFixture(fixture);
assert(isequaln(afterMalformed, baseline), ...
    'Malformed or rejected calls must not contaminate clean recovery.');

disp(['P16 checks preserve exact sample/frame membership, transparent ' ...
    'filter arithmetic, index-derived releases, rate/work utilization, ' ...
    'topological visibility, and strict timeout equality.']);
disp(['Cancellation removes late simulated outputs but cannot modify ' ...
    'source or computed values; recovery is a stateless model rerun.']);
disp(['Checks are deterministic calculations, not MATLAB-runtime, ' ...
    'rendered-UI, real concurrency, processor, DMA, bench, HIL, field, ' ...
    'RT1/RT2, Unreal, signing, deployment, staging, or production ' ...
    'evidence unless executed and retained on named systems.']);
disp('P16 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
