function out = model(startTimeUs, trueIntervalUs, tickPeriodUs, timerPhaseUs, counterBits)
%MODEL Quantize paired event captures with a finite free-running timer.
%   The timer's unwrapped tick at time t is
%       k(t) = floor((t + timerPhaseUs) / tickPeriodUs).
%   Hardware-visible captures are c(t) = mod(k(t), 2^counterBits).
%   Modular subtraction recovers an elapsed tick count only while the
%   unwrapped captured delta is strictly less than one counter modulus.
%
%   Inputs and time-valued outputs use microseconds. This deterministic
%   arithmetic model is not a clock-accuracy, input-latency, or hardware
%   measurement model.

if nargin ~= 5
    error('P04:model:Arity', ...
        ['Expected startTimeUs, trueIntervalUs, tickPeriodUs, ' ...
        'timerPhaseUs, and counterBits.']);
end

maxMeasurements = 1000000;
measurementCount = numel(startTimeUs);
if measurementCount > maxMeasurements
    error('P04:model:ResourceBound', ...
        'At most one million paired captures are allowed.');
end

startTimeUs = validateVector(startTimeUs, 'P04:model:StartTime', ...
    'startTimeUs');
intervalCount = numel(trueIntervalUs);
if intervalCount > maxMeasurements
    error('P04:model:ResourceBound', ...
        'At most one million true intervals are allowed.');
end
trueIntervalUs = validateVector(trueIntervalUs, ...
    'P04:model:TrueInterval', 'trueIntervalUs');

if measurementCount == 0
    if ~isempty(trueIntervalUs)
        error('P04:model:LengthMismatch', ...
            'Empty start times require empty true intervals.');
    end
elseif isscalar(trueIntervalUs)
    trueIntervalUs = repmat(trueIntervalUs, 1, measurementCount);
elseif numel(trueIntervalUs) ~= measurementCount
    error('P04:model:LengthMismatch', ...
        'trueIntervalUs must be scalar or match the start-time length.');
end

tickPeriodUs = validateScalar(tickPeriodUs, 'P04:model:TickPeriod', ...
    'tickPeriodUs');
timerPhaseUs = validateScalar(timerPhaseUs, 'P04:model:TimerPhase', ...
    'timerPhaseUs');
counterBits = validateScalar(counterBits, 'P04:model:CounterBits', ...
    'counterBits');

if any(startTimeUs < 0)
    error('P04:model:StartBounds', ...
        'startTimeUs values must be nonnegative.');
end
if any(trueIntervalUs < 0)
    error('P04:model:IntervalBounds', ...
        'trueIntervalUs values must be nonnegative.');
end
if tickPeriodUs <= 0
    error('P04:model:TickPeriod', ...
        'tickPeriodUs must be strictly positive.');
end
if timerPhaseUs < 0 || timerPhaseUs >= tickPeriodUs
    error('P04:model:TimerPhase', ...
        'timerPhaseUs must lie in [0, tickPeriodUs).');
end
if counterBits < 1 || counterBits > 32 || counterBits ~= floor(counterBits)
    error('P04:model:CounterBits', ...
        'counterBits must be an integer from 1 through 32.');
end

counterModulus = 2 ^ counterBits;
wrapPeriodUs = counterModulus * tickPeriodUs;
if ~isfinite(wrapPeriodUs)
    error('P04:model:TimingResourceBound', ...
        'The configured timer wrap period must remain finite.');
end

endTimeUs = startTimeUs + trueIntervalUs;
if any(~isfinite(endTimeUs)) || ...
        any(trueIntervalUs > 0 & endTimeUs <= startTimeUs)
    error('P04:model:TimingResourceBound', ...
        'Every positive interval must produce a finite, later stop time.');
end

shiftedStartUs = startTimeUs + timerPhaseUs;
shiftedEndUs = endTimeUs + timerPhaseUs;
scaledStartTick = shiftedStartUs ./ tickPeriodUs;
scaledEndTick = shiftedEndUs ./ tickPeriodUs;
maxFullTick = 1e12;
if any(~isfinite(shiftedStartUs)) || any(~isfinite(shiftedEndUs)) || ...
        any(~isfinite(scaledStartTick)) || any(~isfinite(scaledEndTick)) || ...
        any(scaledStartTick > maxFullTick) || any(scaledEndTick > maxFullTick)
    error('P04:model:TimingResourceBound', ...
        'Derived absolute tick indices exceed the transparent model bound.');
end

pairScaledMagnitude = max(ones(size(scaledStartTick)), ...
    max(abs(scaledStartTick), abs(scaledEndTick)));
comparisonToleranceTicks = 8 .* eps(pairScaledMagnitude);
startFullTick = quantizedTick(scaledStartTick, comparisonToleranceTicks);
endFullTick = quantizedTick(scaledEndTick, comparisonToleranceTicks);
fullElapsedTicks = endFullTick - startFullTick;
if any(fullElapsedTicks < 0)
    error('P04:model:TimingResourceBound', ...
        'Derived stop captures must not precede start captures.');
end

startCount = mod(startFullTick, counterModulus);
endCount = mod(endFullTick, counterModulus);
modularElapsedTicks = mod(endCount - startCount, counterModulus);
naiveElapsedTicks = endCount - startCount;
wrapCount = floor(endFullTick ./ counterModulus) - ...
    floor(startFullTick ./ counterModulus);

measurementValid = fullElapsedTicks < counterModulus;
measurementRangeAmbiguous = ~measurementValid;
modularAliasUs = modularElapsedTicks .* tickPeriodUs;
measuredIntervalUs = modularAliasUs;
measuredIntervalUs(measurementRangeAmbiguous) = NaN;
measurementErrorUs = measuredIntervalUs - trueIntervalUs;

startTimestampUs = startFullTick .* tickPeriodUs - timerPhaseUs;
endTimestampUs = endFullTick .* tickPeriodUs - timerPhaseUs;
startQuantizationErrorUs = startTimestampUs - startTimeUs;
endQuantizationErrorUs = endTimestampUs - endTimeUs;
naiveIntervalUs = naiveElapsedTicks .* tickPeriodUs;

validErrorsUs = measurementErrorUs(measurementValid);
if isempty(validErrorsUs)
    worstAbsErrorUs = NaN;
    meanErrorUs = NaN;
    measuredLevelCount = 0;
else
    worstAbsErrorUs = max(abs(validErrorsUs));
    meanErrorUs = mean(validErrorsUs);
    measuredLevelCount = numel(unique(measuredIntervalUs(measurementValid)));
end

out = struct();
out.input = struct( ...
    'start_time_us', startTimeUs, ...
    'end_time_us', endTimeUs, ...
    'true_interval_us', trueIntervalUs, ...
    'count', measurementCount);
out.timer = struct( ...
    'tick_period_us', tickPeriodUs, ...
    'timer_phase_us', timerPhaseUs, ...
    'counter_bits', counterBits, ...
    'counter_modulus', counterModulus, ...
    'wrap_period_us', wrapPeriodUs, ...
    'normalization_tolerance_ticks', comparisonToleranceTicks, ...
    'normalization_tolerance_us', ...
        comparisonToleranceTicks .* tickPeriodUs);
out.capture = struct( ...
    'start_full_tick', startFullTick, ...
    'end_full_tick', endFullTick, ...
    'start_count', startCount, ...
    'end_count', endCount, ...
    'start_timestamp_us', startTimestampUs, ...
    'end_timestamp_us', endTimestampUs, ...
    'start_quantization_error_us', startQuantizationErrorUs, ...
    'end_quantization_error_us', endQuantizationErrorUs, ...
    'wrap_count', wrapCount, ...
    'crossed_wrap', wrapCount > 0);
out.measurement = struct( ...
    'full_elapsed_ticks', fullElapsedTicks, ...
    'modular_elapsed_ticks', modularElapsedTicks, ...
    'interval_us', measuredIntervalUs, ...
    'error_us', measurementErrorUs, ...
    'valid', measurementValid, ...
    'range_ambiguous', measurementRangeAmbiguous);
out.diagnostic = struct( ...
    'modular_alias_us', modularAliasUs, ...
    'naive_elapsed_ticks', naiveElapsedTicks, ...
    'naive_interval_us', naiveIntervalUs, ...
    'naive_negative', naiveElapsedTicks < 0);
out.metrics = struct( ...
    'total_count', measurementCount, ...
    'valid_count', sum(measurementValid), ...
    'range_ambiguity_count', sum(measurementRangeAmbiguous), ...
    'wrap_crossing_count', sum(wrapCount > 0), ...
    'naive_negative_count', sum(naiveElapsedTicks < 0), ...
    'worst_abs_error_us', worstAbsErrorUs, ...
    'mean_error_us', meanErrorUs, ...
    'measured_level_count', measuredLevelCount, ...
    'strict_error_bound_us', tickPeriodUs);
out.claim_boundary = [ ...
    'Deterministic synthetic timer captures; not a hardware measurement.'];
end

function values = validateVector(values, identifier, label)
validType = isnumeric(values) && isreal(values) && ...
    (isvector(values) || isempty(values));
if ~validType
    error(identifier, '%s must be a real numeric vector.', label);
end
values = reshape(double(values), 1, []);
if any(~isfinite(values))
    error(identifier, '%s values must be finite.', label);
end
end

function value = validateScalar(value, identifier, label)
validValue = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
if ~validValue
    error(identifier, '%s must be a finite real numeric scalar.', label);
end
value = double(value);
end

function tick = quantizedTick(scaledTick, comparisonToleranceTicks)
% Share tolerance within each pair without coupling unrelated capture records.
nearestTick = round(scaledTick);
snapToBoundary = abs(scaledTick - nearestTick) <= comparisonToleranceTicks;
scaledTick(snapToBoundary) = nearestTick(snapToBoundary);
tick = floor(scaledTick);
end
