function run_checks
%RUN_CHECKS Independent deterministic and limiting-case checks for P04.

%% Empty, zero, exact-tick, and sub-tick limiting cases
quiet = model([], [], 10, 0, 8);
assert(quiet.metrics.total_count == 0 && quiet.metrics.valid_count == 0, ...
    'Empty input must retain zero paired captures.');
assert(isnan(quiet.metrics.worst_abs_error_us) && ...
    quiet.metrics.measured_level_count == 0, ...
    'Empty input must report error as N/A rather than zero precision.');

zeroInterval = model([0 9], 0, 10, 0, 8);
assert(all(zeroInterval.measurement.interval_us == 0), ...
    'A zero-length interval must capture zero elapsed ticks.');
assert(all(zeroInterval.measurement.valid), ...
    'Zero elapsed ticks are valid when no full modulus is hidden.');

exactTicks = model([0 3 7 19], 20, 10, 6, 8);
assert(all(exactTicks.measurement.full_elapsed_ticks == 2), ...
    'An exact two-tick interval must remain two ticks at every start phase.');
assert(all(exactTicks.measurement.error_us == 0), ...
    'An integer-tick true interval must have zero interval error.');

subTick = model([0 9], [1 1], 10, 0, 8);
assert(isequal(subTick.measurement.full_elapsed_ticks, [0 1]), ...
    'A positive sub-tick interval may capture zero or one tick by phase.');
assert(isequal(subTick.measurement.interval_us, [0 10]), ...
    'Sub-tick measurements must expose the complete-tick staircase.');
assert(all(abs(subTick.measurement.error_us) < 10), ...
    'Sub-tick interval error must remain strictly inside one tick.');

%% Decimal boundaries and endpoint-error identities
decimalBoundary = model([0.2 0.3], 0.1, 0.1, 0, 8);
assert(isequal(decimalBoundary.measurement.full_elapsed_ticks, [1 1]), ...
    'Mathematically exact decimal tick boundaries must normalize before floor.');
assert(all(abs(decimalBoundary.measurement.interval_us - 0.1) < 1e-14), ...
    'Normalized decimal boundaries must retain one-tick measurements.');
distinguishablyBelow = model(0, 0.3 - 1e-12, 0.1, 0, 8);
assert(distinguishablyBelow.measurement.full_elapsed_ticks == 2, ...
    'A value distinguishably below a boundary must not snap up to three ticks.');
powerBoundary = 2 ^ 39;
sharedTolerance = model(powerBoundary - 1 - 9 * 2 ^ -14, ...
    2 - 2 ^ -14, 1, 0, 32);
assert(sharedTolerance.measurement.full_elapsed_ticks == 2, ...
    'Paired endpoints across an exponent boundary must share one tick tolerance.');
assert(abs(sharedTolerance.measurement.error_us) < 1, ...
    'Scale-aware normalization must preserve the strict one-tick error bound.');
sharedEndpointErrorsUs = [ ...
    sharedTolerance.capture.start_quantization_error_us ...
    sharedTolerance.capture.end_quantization_error_us];
assert(all(sharedEndpointErrorsUs <= ...
    sharedTolerance.timer.normalization_tolerance_us) && ...
    all(sharedEndpointErrorsUs > -sharedTolerance.timer.tick_period_us), ...
    'Endpoint error must honor the retained normalization-tolerance bound.');

identityCase = model([1.1 2.7 9.9], [7.3 11.2 0.2], 2, 0.4, 8);
endpointDifferenceUs = identityCase.capture.end_quantization_error_us - ...
    identityCase.capture.start_quantization_error_us;
assert(all(abs(identityCase.measurement.error_us - endpointDifferenceUs) < 1e-12), ...
    'Interval error must equal stop endpoint error minus start endpoint error.');
assert(all(identityCase.capture.start_quantization_error_us <= 1e-12) && ...
    all(identityCase.capture.start_quantization_error_us > -2 - 1e-12), ...
    'Ordinary-scale start errors must lie from almost minus q through zero.');
assert(all(identityCase.capture.end_quantization_error_us <= 1e-12) && ...
    all(identityCase.capture.end_quantization_error_us > -2 - 1e-12), ...
    'Ordinary-scale stop errors must lie from almost minus q through zero.');
assert(all(abs(identityCase.measurement.error_us) < 2 + 1e-12), ...
    'Every valid interval must retain the strict one-tick error bound.');

isolatedNearBoundary = model(0, 0.9995, 1, 0, 32);
batchedNearBoundary = model([0 1e12 - 2], [0.9995 1], 1, 0, 32);
assert(batchedNearBoundary.measurement.full_elapsed_ticks(1) == ...
    isolatedNearBoundary.measurement.full_elapsed_ticks && ...
    batchedNearBoundary.measurement.error_us(1) == ...
    isolatedNearBoundary.measurement.error_us, ...
    'An unrelated far-future capture must not change an earlier quantization.');
assert(batchedNearBoundary.timer.normalization_tolerance_ticks(1) == ...
    isolatedNearBoundary.timer.normalization_tolerance_ticks, ...
    'Boundary normalization tolerance must remain isolated per capture pair.');

%% Deterministic baseline and two independent lever sweeps
fixture = p04_scenario('baseline', 37);
baseline = model(fixture.start_time_us, fixture.true_interval_us, 10, 0, 8);
expectedTicks = [3 4 4 3 4 4 3 4 4 4 3 4];
expectedErrorsUs = [-7 3 3 -7 3 3 -7 3 3 3 -7 3];
assert(isequal(baseline.measurement.full_elapsed_ticks, expectedTicks), ...
    'Baseline completed-tick deltas must match independent floor arithmetic.');
assert(isequal(baseline.measurement.error_us, expectedErrorsUs), ...
    'Baseline interval errors must retain the expected signed staircase.');
assert(baseline.metrics.measured_level_count == 2 && ...
    baseline.metrics.worst_abs_error_us == 7, ...
    'Baseline metrics must report two levels and seven-microsecond worst error.');
assert(baseline.metrics.valid_count + ...
    baseline.metrics.range_ambiguity_count == ...
    baseline.metrics.total_count, ...
    'Valid plus range-ambiguous measurements must conserve every capture pair.');

tickPeriodSweepUs = [1 2 5 10 20];
worstErrorsUs = zeros(size(tickPeriodSweepUs));
startTimesDuringTickSweep = cell(size(tickPeriodSweepUs));
for sweepIndex = 1:numel(tickPeriodSweepUs)
    swept = model(fixture.start_time_us, fixture.true_interval_us, ...
        tickPeriodSweepUs(sweepIndex), 0, 8);
    worstErrorsUs(sweepIndex) = swept.metrics.worst_abs_error_us;
    startTimesDuringTickSweep{sweepIndex} = swept.input.start_time_us;
    assert(all(swept.measurement.valid), ...
        'Every tick-period sweep fixture must remain range-valid.');
end
assert(isequal(worstErrorsUs, [0 1 3 7 17]), ...
    'Tick-period sweep must retain independently calculated worst errors.');
assert(all(cellfun(@(values) isequal(values, fixture.start_time_us), ...
    startTimesDuringTickSweep)), ...
    'Tick-period lever must not mutate the event-time fixture.');

phaseSweepUs = 0:1:9;
phaseMeasurementsUs = zeros(size(phaseSweepUs));
for sweepIndex = 1:numel(phaseSweepUs)
    swept = model(100, 37, 10, phaseSweepUs(sweepIndex), 8);
    phaseMeasurementsUs(sweepIndex) = swept.measurement.interval_us;
    assert(swept.timer.tick_period_us == 10 && ...
        swept.timer.counter_bits == 8, ...
        'Timer-phase lever must not mutate tick period or counter width.');
end
assert(isequal(phaseMeasurementsUs, [30 30 30 40 40 40 40 40 40 40]), ...
    'Timer-phase sweep must retain its independently calculated transition.');

widerCounter = model(fixture.start_time_us, fixture.true_interval_us, 10, 0, 16);
assert(isequal(widerCounter.measurement.interval_us, ...
    baseline.measurement.interval_us), ...
    'More counter bits must extend range without changing tick resolution.');
assert(widerCounter.timer.wrap_period_us > baseline.timer.wrap_period_us, ...
    'More counter bits must increase the wrap period.');

%% Rollover failure, range ambiguity, rollback, and recovery
wrapFixture = p04_scenario('wrap-recovery', 37);
wrapped = model(wrapFixture.start_time_us, wrapFixture.true_interval_us, ...
    10, 0, 8);
assert(isequal(wrapped.capture.crossed_wrap, [true false]), ...
    'The first pair must cross one wrap and the second prove recovery.');
assert(isequal(wrapped.measurement.interval_us, [30 30]), ...
    'Modular subtraction must recover both range-valid measurements.');
assert(isequal(wrapped.diagnostic.naive_interval_us, [-2530 30]), ...
    'Naive signed rollover subtraction must expose one negative interval.');
assert(wrapped.diagnostic.naive_negative(1) && ...
    ~wrapped.diagnostic.naive_negative(2), ...
    'A later non-wrapping pair must prove recovery after the broken view.');
assert(wrapped.metrics.naive_negative_count == 1 && ...
    wrapped.metrics.wrap_crossing_count == 1, ...
    'Broken-case metrics must isolate one naive failure and one safe wrap.');

rangeRecovery = model([0 3000], [2560 100], 10, 0, 8);
assert(rangeRecovery.measurement.range_ambiguous(1) && ...
    isnan(rangeRecovery.measurement.interval_us(1)), ...
    'Exactly one full counter cycle must report range ambiguity, not zero.');
assert(rangeRecovery.diagnostic.modular_alias_us(1) == 0, ...
    'The full-wrap zero residue must remain visible only as a diagnostic alias.');
assert(rangeRecovery.measurement.valid(2) && ...
    rangeRecovery.measurement.interval_us(2) == 100, ...
    'A later short pair must prove range recovery and state isolation.');
assert(rangeRecovery.metrics.range_ambiguity_count == 1 && ...
    rangeRecovery.metrics.valid_count == 1, ...
    'Range/recovery metrics must conserve one ambiguous and one valid pair.');
phaseRangeLimit = model(0.9, 3.9, 1, 0, 2);
assert(phaseRangeLimit.input.true_interval_us < ...
    phaseRangeLimit.timer.wrap_period_us && ...
    phaseRangeLimit.measurement.range_ambiguous, ...
    ['A duration merely below M*q is not phase-independently safe; ' ...
    'captured tick advance must stay below M.']);
multiWrap = model(0, 6000, 10, 0, 8);
assert(multiWrap.measurement.range_ambiguous && ...
    isnan(multiWrap.measurement.error_us), ...
    'A multi-wrap interval must stay ambiguous rather than become quantization error.');
widenedRecovery = model(0, 2560, 10, 0, 9);
assert(widenedRecovery.measurement.valid && ...
    widenedRecovery.measurement.interval_us == 2560, ...
    'Widening the counter must recover the formerly full-wrap interval.');

rolledBack = model(fixture.start_time_us, fixture.true_interval_us, 10, 0, 8);
assert(isequaln(rolledBack, baseline), ...
    'Resetting inputs must roll back the broken configuration exactly.');
% This synchronous pure calculation has no asynchronous cancellation input.

%% Determinism, state isolation, shape, and numeric compatibility
first = model(fixture.start_time_us, fixture.true_interval_us, 10, 0, 8);
second = model(fixture.start_time_us, fixture.true_interval_us, 10, 0, 8);
assert(isequaln(first, second), ...
    'Repeated calls must be deterministic and state-isolated.');
columnInput = model([0; 9], [1; 1], 10, 0, 8);
assert(isrow(columnInput.input.start_time_us) && ...
    isrow(columnInput.input.true_interval_us), ...
    'Column-vector inputs must normalize to documented row-vector outputs.');
integerInput = model(uint16([10 20]), uint8(10), uint8(5), ...
    uint8(0), uint8(8));
assert(isa(integerInput.input.start_time_us, 'double') && ...
    isa(integerInput.measurement.interval_us, 'double'), ...
    'Accepted integer inputs must normalize to double before timing arithmetic.');
scalarExpansion = model([0 10 20], 5, 10, 0, 8);
assert(isequal(scalarExpansion.input.true_interval_us, [5 5 5]), ...
    'A scalar true interval must expand compatibly across capture pairs.');

%% Callback dependency lifetime across launcher cleanup and module switches
callbackModel = @model;
callbackScenario = @p04_scenario;
moduleFolder = fileparts(mfilename('fullpath'));
modulesFolder = fileparts(moduleFolder);
p01Folder = fullfile(modulesFolder, ...
    '01-see-a-periodic-scheduler-miss-a-deadline');
originalSearchPath = path;
searchPathCleanup = onCleanup(@() path(originalSearchPath));
rmpath(moduleFolder);
addpath(p01Folder, '-begin');
callbackFixture = callbackScenario('baseline', 37);
callbackOut = callbackModel(callbackFixture.start_time_us, ...
    callbackFixture.true_interval_us, 10, 0, 8);
assert(callbackOut.metrics.worst_abs_error_us == 7 && ...
    callbackOut.timer.counter_bits == 8, ...
    ['Callback-bound P04 dependencies must survive module path cleanup ' ...
    'and a conflicting model path.']);
clear searchPathCleanup;

%% Malformed-input, timing, counter, and resource-bound rejection
assertReject(@() model(0, 1, 1, 0), 'P04:model:Arity');
assertReject(@() model({0}, 1, 1, 0, 8), 'P04:model:StartTime');
assertReject(@() model([0 1; 2 3], 1, 1, 0, 8), ...
    'P04:model:StartTime');
assertReject(@() model([0 NaN], 1, 1, 0, 8), 'P04:model:StartTime');
assertReject(@() model([0 1i], 1, 1, 0, 8), 'P04:model:StartTime');
assertReject(@() model(-1, 1, 1, 0, 8), 'P04:model:StartBounds');
assertReject(@() model(0, {1}, 1, 0, 8), 'P04:model:TrueInterval');
assertReject(@() model([0 1], [1 2 3], 1, 0, 8), ...
    'P04:model:LengthMismatch');
assertReject(@() model(0, -1, 1, 0, 8), 'P04:model:IntervalBounds');
assertReject(@() model(0, NaN, 1, 0, 8), 'P04:model:TrueInterval');
assertReject(@() model(0, 1i, 1, 0, 8), 'P04:model:TrueInterval');
assertReject(@() model(0, 1, 0, 0, 8), 'P04:model:TickPeriod');
assertReject(@() model(0, 1, Inf, 0, 8), 'P04:model:TickPeriod');
assertReject(@() model(0, 1, 1, -1, 8), 'P04:model:TimerPhase');
assertReject(@() model(0, 1, 10, 10, 8), 'P04:model:TimerPhase');
assertReject(@() model(0, 1, 1, NaN, 8), 'P04:model:TimerPhase');
assertReject(@() model(0, 1, 1, 0, 0), 'P04:model:CounterBits');
assertReject(@() model(0, 1, 1, 0, 1.5), 'P04:model:CounterBits');
assertReject(@() model(0, 1, 1, 0, 33), 'P04:model:CounterBits');
tooManyMeasurements = zeros(1, 1000001);
assertReject(@() model(tooManyMeasurements, 1, 1, 0, 8), ...
    'P04:model:ResourceBound');
clear tooManyMeasurements;
tooManyIntervals = zeros(1, 1000001);
assertReject(@() model(0, tooManyIntervals, 1, 0, 8), ...
    'P04:model:ResourceBound');
clear tooManyIntervals;
assertReject(@() model(1, realmin, 1, 0, 8), ...
    'P04:model:TimingResourceBound');
assertReject(@() model(realmax, 1, 1, 0, 8), ...
    'P04:model:TimingResourceBound');
assertReject(@() model(1, 1, realmin, 0, 8), ...
    'P04:model:TimingResourceBound');
assertReject(@() model([], [], realmax, 0, 32), ...
    'P04:model:TimingResourceBound');
assertReject(@() p04_scenario('unknown', 37), 'P04:scenario:Kind');
assertReject(@() p04_scenario('baseline', -1), ...
    'P04:scenario:TrueInterval');
assertReject(@() p04_scenario('baseline', 10001), ...
    'P04:scenario:TrueInterval');

disp('P04 checks passed.');
end

function assertReject(callable, expectedIdentifier)
didReject = false;
receivedIdentifier = '<none>';
try
    callable();
catch caught
    receivedIdentifier = caught.identifier;
    didReject = strcmp(caught.identifier, expectedIdentifier);
end
assert(didReject, 'Expected rejection %s but received %s.', ...
    expectedIdentifier, receivedIdentifier);
end
